package preInsertions;

import DBManager.DirectorsDBM;
import Conn.Connection;
import entities.Countries;
import entities.Directors;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertDirectors3
{

    DirectorsDBM directorsDBM = new DirectorsDBM();
    List<Directors> list = new ArrayList<>();
    Countries c = new Countries();

    public void insert() {

        c.setCountry_id(80);
        Directors dir1000 = new Directors("integer neque", c, "curabitur euismod turpis consectetuer convallis");
        list.add(dir1000);
        c.setCountry_id(39);
        Directors dir1001 = new Directors("tristique tempor magna", c, "lectus pellentesque accumsan porta pharetra");
        list.add(dir1001);
        c.setCountry_id(134);
        Directors dir1002 = new Directors("proin varius dignissim vestibulum", c, "velit etiam etiam congue rutrum");
        list.add(dir1002);
        c.setCountry_id(90);
        Directors dir1003 = new Directors("vivamus senectus senectus", c, "facilisi metus hymenaeos tellus hymenaeos");
        list.add(dir1003);
        c.setCountry_id(15);
        Directors dir1004 = new Directors("netus iaculis fames", c, "tumst justo nulla mattis semper");
        list.add(dir1004);
        c.setCountry_id(77);
        Directors dir1005 = new Directors("facilisi conubia", c, "consectetuer placerat risus tempor convallis");
        list.add(dir1005);
        c.setCountry_id(147);
        Directors dir1006 = new Directors("aliquet scelerisque", c, "litora tristique etiam aliquam eleifend");
        list.add(dir1006);
        c.setCountry_id(20);
        Directors dir1007 = new Directors("ornare donec porta", c, "laoreet neque maecenas torquent commodo");
        list.add(dir1007);
        c.setCountry_id(34);
        Directors dir1008 = new Directors("class mollis porta", c, "morbi venenatis porttitor praesent curabitur");
        list.add(dir1008);
        c.setCountry_id(104);
        Directors dir1009 = new Directors("pretium elementum", c, "vehicula pretium maecenas ultricies taciti");
        list.add(dir1009);
        c.setCountry_id(55);
        Directors dir1010 = new Directors("nullam litora", c, "ultricies donec platea augue mauris");
        list.add(dir1010);
        c.setCountry_id(128);
        Directors dir1011 = new Directors("facilisi libero porta", c, "pharetra tempus proin aenean venenatis");
        list.add(dir1011);
        c.setCountry_id(73);
        Directors dir1012 = new Directors("nulla bulum", c, "libero sollicitudin fames senectus lobortis");
        list.add(dir1012);
        c.setCountry_id(23);
        Directors dir1013 = new Directors("curabitur phasellus nullam", c, "nostra hymenaeos vivamus torquent lacus");
        list.add(dir1013);
        c.setCountry_id(19);
        Directors dir1014 = new Directors("aptent sapien suspendisse", c, "class augue morbi lacinia conubia");
        list.add(dir1014);
        c.setCountry_id(43);
        Directors dir1015 = new Directors("justo nulla feugiat senectus", c, "sodales tempor malesuada nonummy iaculis");
        list.add(dir1015);
        c.setCountry_id(28);
        Directors dir1016 = new Directors("laoreet vivamus", c, "eleifend fermentum molestie pulvinar inceptos");
        list.add(dir1016);
        c.setCountry_id(11);
        Directors dir1017 = new Directors("eleifend sociosqu aptent viverra", c, "nostra imperdiet consequat scelerisque vivamus");
        list.add(dir1017);
        c.setCountry_id(146);
        Directors dir1018 = new Directors("ipsum semper", c, "facilisis tumst facilisisnunc nonummy taciti");
        list.add(dir1018);
        c.setCountry_id(59);
        Directors dir1019 = new Directors("mauris morbi commodo facilisi", c, "suspendisse mollis class class varius");
        list.add(dir1019);
        c.setCountry_id(76);
        Directors dir1020 = new Directors("etiam tincidunt suspendisse", c, "senectus neque luctus elementum fames");
        list.add(dir1020);
        c.setCountry_id(8);
        Directors dir1021 = new Directors("mattis magna laoreet", c, "dictumst lobortis felis facilisisnunc tincidunt");
        list.add(dir1021);
        c.setCountry_id(12);
        Directors dir1022 = new Directors("proin fringilla venenatis", c, "dictumst vehicula velit inceptos cursus");
        list.add(dir1022);
        c.setCountry_id(112);
        Directors dir1023 = new Directors("tempor curabitur sodales", c, "sollicitudin lacinia lacinia convallis proin");
        list.add(dir1023);
        c.setCountry_id(3);
        Directors dir1024 = new Directors("donec senectus vitae", c, "fusce integer porttitor elementum volutpat");
        list.add(dir1024);
        c.setCountry_id(77);
        Directors dir1025 = new Directors("vitae mollis", c, "curabitur cubilia vitae bulum sodales");
        list.add(dir1025);
        c.setCountry_id(24);
        Directors dir1026 = new Directors("iaculis maecenas molestie", c, "sociosqu hendrerit aenean tempus facilisis");
        list.add(dir1026);
        c.setCountry_id(122);
        Directors dir1027 = new Directors("suspendisse tortor", c, "cubilia lobortis molestie pretium luctus");
        list.add(dir1027);
        c.setCountry_id(107);
        Directors dir1028 = new Directors("lorem rutrum ullamcorper donec", c, "dictumst dolor ultrices vivamus augue");
        list.add(dir1028);
        c.setCountry_id(103);
        Directors dir1029 = new Directors("fames pulvinar adipiscing vivamus", c, "lorem fames nulla congue purus");
        list.add(dir1029);
        c.setCountry_id(37);
        Directors dir1030 = new Directors("iaculis dolor lacus", c, "sodales facilisi mollis viverra habitant");
        list.add(dir1030);
        c.setCountry_id(138);
        Directors dir1031 = new Directors("curabitur tortor malesuada lobortis", c, "hendrerit vivamus tristique rutrum facilisisnunc");
        list.add(dir1031);
        c.setCountry_id(93);
        Directors dir1032 = new Directors("rutrum feugiat class torquent", c, "praesent volutpat morbi hymenaeos nonummy");
        list.add(dir1032);
        c.setCountry_id(38);
        Directors dir1033 = new Directors("dictumst aliquet magna dictum", c, "lorem accumsan iaculis ipsum pellentesque");
        list.add(dir1033);
        c.setCountry_id(60);
        Directors dir1034 = new Directors("fringilla vesti", c, "auctor venenatis tincidunt venenatis netus");
        list.add(dir1034);
        c.setCountry_id(68);
        Directors dir1035 = new Directors("pulvinar dictumst nonummy vehicula", c, "convallis elementum suspendisse purus proin");
        list.add(dir1035);
        c.setCountry_id(68);
        Directors dir1036 = new Directors("ullamcorper viverra dictum", c, "tincidunt ullamcorper integer taciti fusce");
        list.add(dir1036);
        c.setCountry_id(148);
        Directors dir1037 = new Directors("lacinia pharetra", c, "primis aliquet adipiscing conubia sociosqu");
        list.add(dir1037);
        c.setCountry_id(119);
        Directors dir1038 = new Directors("platea wisiaenean sodales", c, "bulum lobortis viverra facilisis fames");
        list.add(dir1038);
        c.setCountry_id(9);
        Directors dir1039 = new Directors("facilisi purus porttitor", c, "risus facilisisnunc primis vesti lectus");
        list.add(dir1039);
        c.setCountry_id(3);
        Directors dir1040 = new Directors("vitae curabitur", c, "pulvinar ipsum lectus ullamcorper neque");
        list.add(dir1040);
        c.setCountry_id(86);
        Directors dir1041 = new Directors("sapien lacinia", c, "lacinia sodales lorem accumsan viverra");
        list.add(dir1041);
        c.setCountry_id(65);
        Directors dir1042 = new Directors("praesent conubia class aenean", c, "quisque volutpat tempor senectus cubilia");
        list.add(dir1042);
        c.setCountry_id(37);
        Directors dir1043 = new Directors("facilisis feugiat nostra", c, "sollicitudin praesent cursus adipiscing curae");
        list.add(dir1043);
        c.setCountry_id(11);
        Directors dir1044 = new Directors("fames cubilia", c, "faucibus ullamcorper viverra phasellus facilisisnunc");
        list.add(dir1044);
        c.setCountry_id(108);
        Directors dir1045 = new Directors("tristique consequat aptent pretium", c, "malesuada aenean dignissim ultrices aliquet");
        list.add(dir1045);
        c.setCountry_id(39);
        Directors dir1046 = new Directors("habitasse scelerisque vesti", c, "nullam morbi lacus accumsan pellentesque");
        list.add(dir1046);
        c.setCountry_id(27);
        Directors dir1047 = new Directors("aliquam iaculis laoreet lobortis", c, "ipsum wisiaenean vivamus consequat semper");
        list.add(dir1047);
        c.setCountry_id(91);
        Directors dir1048 = new Directors("inceptos habitasse habitant libero", c, "vesti malesuada integer hendrerit conubia");
        list.add(dir1048);
        c.setCountry_id(77);
        Directors dir1049 = new Directors("eleifend varius pulvinar", c, "molestie venenatis class mauris fusce");
        list.add(dir1049);
        c.setCountry_id(141);
        Directors dir1050 = new Directors("tempus lorem", c, "cubilia bulum curae mauris tempus");
        list.add(dir1050);
        c.setCountry_id(93);
        Directors dir1051 = new Directors("lobortis volutpat auctor praesent", c, "venenatis molestie integer fermentum tempus");
        list.add(dir1051);
        c.setCountry_id(106);
        Directors dir1052 = new Directors("curae wisiaenean lectus lobortis", c, "auctor sagittis placerat conubia ornare");
        list.add(dir1052);
        c.setCountry_id(64);
        Directors dir1053 = new Directors("tempus elementum maecenas bibendum", c, "mattis lobortis dolor taciti eleifend");
        list.add(dir1053);
        c.setCountry_id(116);
        Directors dir1054 = new Directors("conubia neque", c, "venenatis convallis tristique viverra conubia");
        list.add(dir1054);
        c.setCountry_id(111);
        Directors dir1055 = new Directors("tumst cursus", c, "etiam vestibulum consectetuer hendrerit nulla");
        list.add(dir1055);
        c.setCountry_id(48);
        Directors dir1056 = new Directors("varius dictumst molestie", c, "justo venenatis semper nulla inceptos");
        list.add(dir1056);
        c.setCountry_id(52);
        Directors dir1057 = new Directors("donec porta habitasse", c, "justo vehicula felis curabitur netus");
        list.add(dir1057);
        c.setCountry_id(94);
        Directors dir1058 = new Directors("quisque facilisi vestibulum", c, "malesuada sapien egestas tristique vestibulum");
        list.add(dir1058);
        c.setCountry_id(56);
        Directors dir1059 = new Directors("consequat eleifend aliquet", c, "vivamus varius adipiscing lobortis sagittis");
        list.add(dir1059);
        c.setCountry_id(133);
        Directors dir1060 = new Directors("congue inceptos placerat", c, "curae laoreet bibendum congue egestas");
        list.add(dir1060);
        c.setCountry_id(126);
        Directors dir1061 = new Directors("wisiaenean tellus", c, "cursus purus bibendum augue augue");
        list.add(dir1061);
        c.setCountry_id(123);
        Directors dir1062 = new Directors("lacinia pellentesque", c, "proin neque hendrerit augue sagittis");
        list.add(dir1062);
        c.setCountry_id(36);
        Directors dir1063 = new Directors("tempor elementum commodo auctor", c, "sollicitudin mattis porta platea facilisi");
        list.add(dir1063);
        c.setCountry_id(110);
        Directors dir1064 = new Directors("morbi lacus", c, "proin iaculis platea convallis risus");
        list.add(dir1064);
        c.setCountry_id(30);
        Directors dir1065 = new Directors("inceptos platea", c, "sapien scelerisque habitasse ligula fusce");
        list.add(dir1065);
        c.setCountry_id(111);
        Directors dir1066 = new Directors("neque dictum", c, "volutpat tincidunt iaculis convallis dictumst");
        list.add(dir1066);
        c.setCountry_id(25);
        Directors dir1067 = new Directors("praesent class maecenas", c, "pulvinar facilisisnunc dolor velit sollicitudin");
        list.add(dir1067);
        c.setCountry_id(18);
        Directors dir1068 = new Directors("maecenas aliquet fusce tellus", c, "cubilia felis phasellus interdum maecenas");
        list.add(dir1068);
        c.setCountry_id(116);
        Directors dir1069 = new Directors("donec dolor ultricies hymenaeos", c, "commodo sapien cursus libero consectetuer");
        list.add(dir1069);
        c.setCountry_id(20);
        Directors dir1070 = new Directors("ultricies velit", c, "placerat ligula inceptos accumsan ipsum");
        list.add(dir1070);
        c.setCountry_id(107);
        Directors dir1071 = new Directors("dictum justo taciti", c, "nullam cursus metus fames senectus");
        list.add(dir1071);
        c.setCountry_id(150);
        Directors dir1072 = new Directors("tempus sodales", c, "lacus praesent senectus metus cubilia");
        list.add(dir1072);
        c.setCountry_id(79);
        Directors dir1073 = new Directors("mattis aliquet varius", c, "euismod mattis lacinia torquent vitae");
        list.add(dir1073);
        c.setCountry_id(136);
        Directors dir1074 = new Directors("lacinia conubia nonummy", c, "fermentum ipsum augue senectus lacus");
        list.add(dir1074);
        c.setCountry_id(60);
        Directors dir1075 = new Directors("sapien adipiscing habitasse venenatis", c, "vivamus inceptos varius vitae pretium");
        list.add(dir1075);
        c.setCountry_id(43);
        Directors dir1076 = new Directors("nullam litora senectus sagittis", c, "volutpat tellus inceptos viverra facilisi");
        list.add(dir1076);
        c.setCountry_id(2);
        Directors dir1077 = new Directors("vivamus mollis", c, "facilisi hymenaeos nullam primis ultricies");
        list.add(dir1077);
        c.setCountry_id(79);
        Directors dir1078 = new Directors("posuere integer molestie posuere", c, "lorem nullam primis cubilia litora");
        list.add(dir1078);
        c.setCountry_id(130);
        Directors dir1079 = new Directors("varius phasellus", c, "consectetuer tempor vesti dictum commodo");
        list.add(dir1079);
        c.setCountry_id(22);
        Directors dir1080 = new Directors("justo conubia aenean", c, "aliquam sodales purus molestie phasellus");
        list.add(dir1080);
        c.setCountry_id(20);
        Directors dir1081 = new Directors("ullamcorper scelerisque neque curabitur", c, "aptent auctor malesuada placerat habitant");
        list.add(dir1081);
        c.setCountry_id(23);
        Directors dir1082 = new Directors("class turpis porttitor purus", c, "maecenas tempus facilisis habitant dictumst");
        list.add(dir1082);
        c.setCountry_id(54);
        Directors dir1083 = new Directors("conubia venenatis sodales eleifend", c, "cubilia quisque lacus dolor ullamcorper");
        list.add(dir1083);
        c.setCountry_id(31);
        Directors dir1084 = new Directors("hymenaeos sapien feugiat scelerisque", c, "phasellus aenean placerat primis maecenas");
        list.add(dir1084);
        c.setCountry_id(104);
        Directors dir1085 = new Directors("dignissim volutpat", c, "augue dignissim quisque primis tristique");
        list.add(dir1085);
        c.setCountry_id(12);
        Directors dir1086 = new Directors("conubia mattis", c, "adipiscing sociosqu vehicula dictumst vitae");
        list.add(dir1086);
        c.setCountry_id(52);
        Directors dir1087 = new Directors("commodo nostra taciti ultricies", c, "commodo lacus vivamus bulum faucibus");
        list.add(dir1087);
        c.setCountry_id(1);
        Directors dir1088 = new Directors("vesti phasellus mattis habitasse", c, "cubilia fermentum tempor fames euismod");
        list.add(dir1088);
        c.setCountry_id(40);
        Directors dir1089 = new Directors("ultrices porttitor", c, "nullam phasellus aenean nostra bibendum");
        list.add(dir1089);
        c.setCountry_id(38);
        Directors dir1090 = new Directors("facilisisnunc porttitor conubia curae", c, "hymenaeos aliquet accumsan hymenaeos habitant");
        list.add(dir1090);
        c.setCountry_id(22);
        Directors dir1091 = new Directors("ligula conubia", c, "felis iaculis mollis porttitor facilisisnunc");
        list.add(dir1091);
        c.setCountry_id(21);
        Directors dir1092 = new Directors("netus lacinia", c, "fringilla class lorem dignissim viverra");
        list.add(dir1092);
        c.setCountry_id(36);
        Directors dir1093 = new Directors("pulvinar dignissim maecenas", c, "lobortis semper fusce congue ullamcorper");
        list.add(dir1093);
        c.setCountry_id(138);
        Directors dir1094 = new Directors("vivamus rutrum viverra", c, "euismod tempus semper tempor tincidunt");
        list.add(dir1094);
        c.setCountry_id(103);
        Directors dir1095 = new Directors("justo dignissim aliquam hendrerit", c, "augue fringilla lacinia sapien tumst");
        list.add(dir1095);
        c.setCountry_id(0);
        Directors dir1096 = new Directors("viverra posuere habitant iaculis", c, "rutrum donec laoreet cubilia senectus");
        list.add(dir1096);
        c.setCountry_id(83);
        Directors dir1097 = new Directors("tincidunt bibendum molestie proin", c, "interdum euismod primis auctor dolor");
        list.add(dir1097);
        c.setCountry_id(24);
        Directors dir1098 = new Directors("malesuada nulla pulvinar", c, "habitasse mauris taciti sollicitudin suspendisse");
        list.add(dir1098);
        c.setCountry_id(69);
        Directors dir1099 = new Directors("ultrices congue lectus sapien", c, "phasellus commodo inceptos elementum euismod");
        list.add(dir1099);
        c.setCountry_id(89);
        Directors dir1100 = new Directors("iaculis lorem tempor", c, "hymenaeos dignissim ligula fermentum turpis");
        list.add(dir1100);
        c.setCountry_id(94);
        Directors dir1101 = new Directors("torquent fringilla tortor suspendisse", c, "conubia varius tristique primis viverra");
        list.add(dir1101);
        c.setCountry_id(64);
        Directors dir1102 = new Directors("pellentesque taciti lacus torquent", c, "tempus consequat magna neque vesti");
        list.add(dir1102);
        c.setCountry_id(32);
        Directors dir1103 = new Directors("viverra accumsan", c, "euismod tortor vesti conubia vitae");
        list.add(dir1103);
        c.setCountry_id(40);
        Directors dir1104 = new Directors("scelerisque class elementum", c, "pretium bulum conubia porttitor consequat");
        list.add(dir1104);
        c.setCountry_id(32);
        Directors dir1105 = new Directors("pellentesque consectetuer", c, "donec fames placerat phasellus lectus");
        list.add(dir1105);
        c.setCountry_id(83);
        Directors dir1106 = new Directors("fringilla viverra class", c, "class donec vesti lectus varius");
        list.add(dir1106);
        c.setCountry_id(100);
        Directors dir1107 = new Directors("auctor posuere ultricies", c, "consequat justo pharetra augue taciti");
        list.add(dir1107);
        c.setCountry_id(30);
        Directors dir1108 = new Directors("aptent donec", c, "velit adipiscing nullam bibendum sagittis");
        list.add(dir1108);
        c.setCountry_id(19);
        Directors dir1109 = new Directors("inceptos sodales luctus aliquam", c, "interdum hendrerit rutrum class sodales");
        list.add(dir1109);
        c.setCountry_id(113);
        Directors dir1110 = new Directors("velit auctor viverra libero", c, "nulla adipiscing torquent vesti volutpat");
        list.add(dir1110);
        c.setCountry_id(121);
        Directors dir1111 = new Directors("lorem taciti aptent", c, "lacus risus curabitur habitant nulla");
        list.add(dir1111);
        c.setCountry_id(49);
        Directors dir1112 = new Directors("dignissim semper integer fringilla", c, "volutpat malesuada placerat etiam tempus");
        list.add(dir1112);
        c.setCountry_id(71);
        Directors dir1113 = new Directors("sodales consectetuer vitae phasellus", c, "congue velit eleifend justo aliquet");
        list.add(dir1113);
        c.setCountry_id(70);
        Directors dir1114 = new Directors("senectus luctus", c, "ultrices nulla elementum habitasse posuere");
        list.add(dir1114);
        c.setCountry_id(31);
        Directors dir1115 = new Directors("feugiat pretium purus", c, "magna purus suspendisse felis aenean");
        list.add(dir1115);
        c.setCountry_id(17);
        Directors dir1116 = new Directors("sodales tincidunt aptent", c, "interdum maecenas neque fusce magna");
        list.add(dir1116);
        c.setCountry_id(132);
        Directors dir1117 = new Directors("vesti placerat venenatis risus", c, "bibendum lacinia fermentum eleifend pellentesque");
        list.add(dir1117);
        c.setCountry_id(140);
        Directors dir1118 = new Directors("laoreet ullamcorper", c, "malesuada velit convallis sagittis mattis");
        list.add(dir1118);
        c.setCountry_id(83);
        Directors dir1119 = new Directors("habitasse phasellus", c, "praesent fringilla mattis praesent conubia");
        list.add(dir1119);
        c.setCountry_id(93);
        Directors dir1120 = new Directors("sodales viverra", c, "lorem libero hymenaeos platea consectetuer");
        list.add(dir1120);
        c.setCountry_id(63);
        Directors dir1121 = new Directors("porta porttitor lacus", c, "semper aliquet vitae mollis cursus");
        list.add(dir1121);
        c.setCountry_id(130);
        Directors dir1122 = new Directors("senectus varius mattis mollis", c, "praesent nullam vesti fusce dictum");
        list.add(dir1122);
        c.setCountry_id(126);
        Directors dir1123 = new Directors("eleifend porta sociosqu luctus", c, "imperdiet habitant libero feugiat tumst");
        list.add(dir1123);
        c.setCountry_id(79);
        Directors dir1124 = new Directors("morbi dignissim varius", c, "curae augue facilisis commodo elementum");
        list.add(dir1124);
        c.setCountry_id(120);
        Directors dir1125 = new Directors("imperdiet taciti", c, "scelerisque nullam aliquet sapien sodales");
        list.add(dir1125);
        c.setCountry_id(110);
        Directors dir1126 = new Directors("magna fringilla commodo tempus", c, "mattis aenean purus hendrerit curabitur");
        list.add(dir1126);
        c.setCountry_id(55);
        Directors dir1127 = new Directors("curae molestie wisiaenean cubilia", c, "egestas porttitor bibendum vesti vestibulum");
        list.add(dir1127);
        c.setCountry_id(57);
        Directors dir1128 = new Directors("class dignissim luctus volutpat", c, "imperdiet varius lobortis euismod sollicitudin");
        list.add(dir1128);
        c.setCountry_id(59);
        Directors dir1129 = new Directors("luctus facilisi vesti", c, "convallis praesent convallis aliquam ornare");
        list.add(dir1129);
        c.setCountry_id(26);
        Directors dir1130 = new Directors("ipsum hymenaeos", c, "tellus faucibus ullamcorper litora ipsum");
        list.add(dir1130);
        c.setCountry_id(108);
        Directors dir1131 = new Directors("porta wisiaenean", c, "bulum hymenaeos porta imperdiet pellentesque");
        list.add(dir1131);
        c.setCountry_id(123);
        Directors dir1132 = new Directors("fusce pharetra", c, "facilisis fermentum nullam imperdiet habitasse");
        list.add(dir1132);
        c.setCountry_id(37);
        Directors dir1133 = new Directors("vesti sodales integer", c, "risus tempor eleifend ipsum phasellus");
        list.add(dir1133);
        c.setCountry_id(95);
        Directors dir1134 = new Directors("magna suspendisse wisiaenean", c, "eleifend ligula aptent varius consectetuer");
        list.add(dir1134);
        c.setCountry_id(66);
        Directors dir1135 = new Directors("dictumst hymenaeos posuere fames", c, "feugiat imperdiet morbi fames pulvinar");
        list.add(dir1135);
        c.setCountry_id(130);
        Directors dir1136 = new Directors("luctus posuere consectetuer", c, "metus tumst hymenaeos vesti iaculis");
        list.add(dir1136);
        c.setCountry_id(7);
        Directors dir1137 = new Directors("varius consectetuer magna malesuada", c, "venenatis interdum etiam sollicitudin varius");
        list.add(dir1137);
        c.setCountry_id(120);
        Directors dir1138 = new Directors("vesti facilisi", c, "phasellus conubia suspendisse varius conubia");
        list.add(dir1138);
        c.setCountry_id(125);
        Directors dir1139 = new Directors("sollicitudin sollicitudin laoreet", c, "viverra sagittis pellentesque taciti venenatis");
        list.add(dir1139);
        c.setCountry_id(21);
        Directors dir1140 = new Directors("hymenaeos pellentesque fames proin", c, "vivamus curabitur placerat egestas lobortis");
        list.add(dir1140);
        c.setCountry_id(87);
        Directors dir1141 = new Directors("aliquet mattis placerat", c, "pharetra purus dictum cursus auctor");
        list.add(dir1141);
        c.setCountry_id(96);
        Directors dir1142 = new Directors("mattis nostra porta", c, "dictum aliquam nullam vestibulum luctus");
        list.add(dir1142);
        c.setCountry_id(88);
        Directors dir1143 = new Directors("maecenas risus", c, "consectetuer quisque felis nulla aliquet");
        list.add(dir1143);
        c.setCountry_id(91);
        Directors dir1144 = new Directors("habitasse inceptos", c, "vehicula aliquam inceptos augue tempor");
        list.add(dir1144);
        c.setCountry_id(39);
        Directors dir1145 = new Directors("luctus semper", c, "fermentum pretium vestibulum nullam volutpat");
        list.add(dir1145);
        c.setCountry_id(33);
        Directors dir1146 = new Directors("luctus fermentum", c, "tortor conubia nulla curabitur scelerisque");
        list.add(dir1146);
        c.setCountry_id(122);
        Directors dir1147 = new Directors("placerat eleifend", c, "donec accumsan libero vestibulum platea");
        list.add(dir1147);
        c.setCountry_id(89);
        Directors dir1148 = new Directors("imperdiet nullam", c, "turpis phasellus tortor mattis lectus");
        list.add(dir1148);
        c.setCountry_id(45);
        Directors dir1149 = new Directors("dictumst phasellus", c, "suspendisse augue auctor velit taciti");
        list.add(dir1149);
        c.setCountry_id(143);
        Directors dir1150 = new Directors("quisque tortor", c, "convallis consectetuer litora pharetra platea");
        list.add(dir1150);
        c.setCountry_id(101);
        Directors dir1151 = new Directors("consequat molestie volutpat", c, "porttitor volutpat aenean cursus justo");
        list.add(dir1151);
        c.setCountry_id(112);
        Directors dir1152 = new Directors("lacus tortor", c, "phasellus ultrices posuere ultricies metus");
        list.add(dir1152);
        c.setCountry_id(137);
        Directors dir1153 = new Directors("consectetuer nullam elementum", c, "tumst magna congue vivamus turpis");
        list.add(dir1153);
        c.setCountry_id(20);
        Directors dir1154 = new Directors("lacus varius dictumst viverra", c, "senectus curabitur ornare conubia congue");
        list.add(dir1154);
        c.setCountry_id(85);
        Directors dir1155 = new Directors("magna aptent hymenaeos sollicitudin", c, "faucibus aenean suspendisse lobortis tellus");
        list.add(dir1155);
        c.setCountry_id(3);
        Directors dir1156 = new Directors("hymenaeos pellentesque mattis", c, "porta praesent consectetuer cursus fusce");
        list.add(dir1156);
        c.setCountry_id(140);
        Directors dir1157 = new Directors("ipsum neque pulvinar", c, "hendrerit cubilia fringilla ultrices metus");
        list.add(dir1157);
        c.setCountry_id(105);
        Directors dir1158 = new Directors("praesent mollis hendrerit praesent", c, "pretium fusce class mollis etiam");
        list.add(dir1158);
        c.setCountry_id(111);
        Directors dir1159 = new Directors("purus hendrerit proin", c, "dignissim placerat porttitor aenean venenatis");
        list.add(dir1159);
        c.setCountry_id(145);
        Directors dir1160 = new Directors("facilisi mattis varius aliquet", c, "cubilia quisque malesuada consequat facilisisnunc");
        list.add(dir1160);
        c.setCountry_id(119);
        Directors dir1161 = new Directors("suspendisse lacus", c, "taciti primis facilisis curabitur mollis");
        list.add(dir1161);
        c.setCountry_id(29);
        Directors dir1162 = new Directors("platea vesti", c, "bulum dolor aenean tempor vitae");
        list.add(dir1162);
        c.setCountry_id(127);
        Directors dir1163 = new Directors("integer conubia morbi", c, "habitasse mollis malesuada consectetuer molestie");
        list.add(dir1163);
        c.setCountry_id(92);
        Directors dir1164 = new Directors("lorem tumst auctor", c, "morbi aptent pharetra morbi eleifend");
        list.add(dir1164);
        c.setCountry_id(20);
        Directors dir1165 = new Directors("morbi hendrerit netus congue", c, "iaculis aenean consectetuer fermentum pharetra");
        list.add(dir1165);
        c.setCountry_id(121);
        Directors dir1166 = new Directors("feugiat phasellus malesuada pretium", c, "sodales primis sagittis augue sagittis");
        list.add(dir1166);
        c.setCountry_id(50);
        Directors dir1167 = new Directors("augue feugiat porta", c, "varius bibendum molestie ultrices suspendisse");
        list.add(dir1167);
        c.setCountry_id(10);
        Directors dir1168 = new Directors("eleifend laoreet", c, "ipsum pulvinar elementum aptent sollicitudin");
        list.add(dir1168);
        c.setCountry_id(112);
        Directors dir1169 = new Directors("lectus pretium fusce", c, "aliquam elementum lorem fusce felis");
        list.add(dir1169);
        c.setCountry_id(58);
        Directors dir1170 = new Directors("nonummy neque bibendum", c, "tristique malesuada quisque volutpat ultrices");
        list.add(dir1170);
        c.setCountry_id(22);
        Directors dir1171 = new Directors("wisiaenean volutpat", c, "platea ultricies sagittis praesent egestas");
        list.add(dir1171);
        c.setCountry_id(33);
        Directors dir1172 = new Directors("pharetra bibendum", c, "nulla egestas faucibus platea nullam");
        list.add(dir1172);
        c.setCountry_id(63);
        Directors dir1173 = new Directors("rutrum accumsan convallis", c, "proin risus libero sociosqu phasellus");
        list.add(dir1173);
        c.setCountry_id(81);
        Directors dir1174 = new Directors("cursus nullam", c, "nulla justo ultrices praesent augue");
        list.add(dir1174);
        c.setCountry_id(80);
        Directors dir1175 = new Directors("lectus dictum felis bulum", c, "iaculis turpis morbi pulvinar platea");
        list.add(dir1175);
        c.setCountry_id(138);
        Directors dir1176 = new Directors("etiam malesuada faucibus fusce", c, "iaculis magna pulvinar facilisisnunc tempus");
        list.add(dir1176);
        c.setCountry_id(14);
        Directors dir1177 = new Directors("elementum vestibulum nonummy", c, "integer bibendum volutpat hymenaeos facilisisnunc");
        list.add(dir1177);
        c.setCountry_id(13);
        Directors dir1178 = new Directors("augue vivamus sodales", c, "bibendum volutpat lacus vivamus risus");
        list.add(dir1178);
        c.setCountry_id(146);
        Directors dir1179 = new Directors("vivamus scelerisque", c, "volutpat adipiscing mauris varius auctor");
        list.add(dir1179);
        c.setCountry_id(83);
        Directors dir1180 = new Directors("iaculis adipiscing tumst", c, "adipiscing maecenas turpis fringilla etiam");
        list.add(dir1180);
        c.setCountry_id(118);
        Directors dir1181 = new Directors("velit felis viverra", c, "vehicula commodo sagittis pulvinar ipsum");
        list.add(dir1181);
        c.setCountry_id(68);
        Directors dir1182 = new Directors("curae sagittis lectus lectus", c, "etiam bulum class aliquam netus");
        list.add(dir1182);
        c.setCountry_id(13);
        Directors dir1183 = new Directors("scelerisque luctus facilisis bulum", c, "augue vestibulum lacinia posuere dictum");
        list.add(dir1183);
        c.setCountry_id(98);
        Directors dir1184 = new Directors("ipsum nostra quisque integer", c, "luctus egestas pretium sociosqu facilisis");
        list.add(dir1184);
        c.setCountry_id(78);
        Directors dir1185 = new Directors("ipsum semper dictumst", c, "platea lorem litora accumsan fermentum");
        list.add(dir1185);
        c.setCountry_id(100);
        Directors dir1186 = new Directors("tempus curae vesti wisiaenean", c, "malesuada egestas aliquet nulla sapien");
        list.add(dir1186);
        c.setCountry_id(20);
        Directors dir1187 = new Directors("rutrum aliquam hymenaeos pulvinar", c, "placerat vestibulum vehicula vesti vestibulum");
        list.add(dir1187);
        c.setCountry_id(52);
        Directors dir1188 = new Directors("ipsum euismod vesti venenatis", c, "nonummy quisque scelerisque fermentum rutrum");
        list.add(dir1188);
        c.setCountry_id(114);
        Directors dir1189 = new Directors("vivamus torquent", c, "interdum faucibus auctor tristique elementum");
        list.add(dir1189);
        c.setCountry_id(58);
        Directors dir1190 = new Directors("ultrices mattis suspendisse", c, "lobortis ligula primis purus porttitor");
        list.add(dir1190);
        c.setCountry_id(77);
        Directors dir1191 = new Directors("wisiaenean pretium vestibulum egestas", c, "praesent tellus nulla purus convallis");
        list.add(dir1191);
        c.setCountry_id(121);
        Directors dir1192 = new Directors("mattis ipsum turpis semper", c, "aptent tempus aliquet augue purus");
        list.add(dir1192);
        c.setCountry_id(96);
        Directors dir1193 = new Directors("fames lobortis feugiat laoreet", c, "cursus class feugiat senectus fringilla");
        list.add(dir1193);
        c.setCountry_id(74);
        Directors dir1194 = new Directors("sodales lacus eleifend", c, "venenatis purus senectus class consequat");
        list.add(dir1194);
        c.setCountry_id(114);
        Directors dir1195 = new Directors("congue suspendisse", c, "integer varius lacinia adipiscing vitae");
        list.add(dir1195);
        c.setCountry_id(74);
        Directors dir1196 = new Directors("mattis nonummy conubia", c, "auctor volutpat ipsum faucibus inceptos");
        list.add(dir1196);
        c.setCountry_id(17);
        Directors dir1197 = new Directors("sociosqu posuere", c, "dictum litora torquent fusce posuere");
        list.add(dir1197);
        c.setCountry_id(51);
        Directors dir1198 = new Directors("sapien cursus", c, "vehicula lorem venenatis quisque mollis");
        list.add(dir1198);
        c.setCountry_id(10);
        Directors dir1199 = new Directors("lacus lacus varius", c, "iaculis dictum adipiscing nostra tristique");
        list.add(dir1199);
        c.setCountry_id(65);
        Directors dir1200 = new Directors("donec facilisi rutrum", c, "pulvinar platea aenean wisiaenean ultricies");
        list.add(dir1200);
        c.setCountry_id(41);
        Directors dir1201 = new Directors("nonummy aliquam primis accumsan", c, "neque sagittis placerat proin litora");
        list.add(dir1201);
        c.setCountry_id(88);
        Directors dir1202 = new Directors("volutpat praesent", c, "ultrices nostra phasellus elementum viverra");
        list.add(dir1202);
        c.setCountry_id(131);
        Directors dir1203 = new Directors("praesent ultrices aptent", c, "egestas sodales pharetra donec semper");
        list.add(dir1203);
        c.setCountry_id(41);
        Directors dir1204 = new Directors("rutrum nullam dictum", c, "hymenaeos taciti netus venenatis posuere");
        list.add(dir1204);
        c.setCountry_id(125);
        Directors dir1205 = new Directors("metus commodo wisiaenean curabitur", c, "turpis nonummy faucibus pharetra venenatis");
        list.add(dir1205);
        c.setCountry_id(106);
        Directors dir1206 = new Directors("scelerisque ligula taciti", c, "senectus mauris pharetra lorem hendrerit");
        list.add(dir1206);
        c.setCountry_id(120);
        Directors dir1207 = new Directors("accumsan lobortis sollicitudin neque", c, "suspendisse litora eleifend suspendisse porttitor");
        list.add(dir1207);
        c.setCountry_id(115);
        Directors dir1208 = new Directors("hendrerit commodo mattis auctor", c, "inceptos tumst vehicula ultrices malesuada");
        list.add(dir1208);
        c.setCountry_id(82);
        Directors dir1209 = new Directors("ligula lobortis posuere", c, "eleifend lacinia inceptos vivamus conubia");
        list.add(dir1209);
        c.setCountry_id(66);
        Directors dir1210 = new Directors("dignissim lacinia inceptos", c, "faucibus donec tincidunt hymenaeos habitasse");
        list.add(dir1210);
        c.setCountry_id(54);
        Directors dir1211 = new Directors("ornare varius vesti aptent", c, "viverra dictum wisiaenean fusce lobortis");
        list.add(dir1211);
        c.setCountry_id(106);
        Directors dir1212 = new Directors("sapien sollicitudin", c, "imperdiet quisque morbi neque pharetra");
        list.add(dir1212);
        c.setCountry_id(54);
        Directors dir1213 = new Directors("posuere inceptos molestie", c, "aliquet phasellus convallis primis pellentesque");
        list.add(dir1213);
        c.setCountry_id(119);
        Directors dir1214 = new Directors("nullam porta", c, "taciti eleifend scelerisque ligula fames");
        list.add(dir1214);
        c.setCountry_id(82);
        Directors dir1215 = new Directors("varius ultricies nonummy", c, "phasellus hymenaeos sollicitudin tortor interdum");
        list.add(dir1215);
        c.setCountry_id(75);
        Directors dir1216 = new Directors("faucibus platea torquent", c, "risus malesuada consectetuer hymenaeos litora");
        list.add(dir1216);
        c.setCountry_id(6);
        Directors dir1217 = new Directors("laoreet nostra", c, "fusce libero congue tristique placerat");
        list.add(dir1217);
        c.setCountry_id(52);
        Directors dir1218 = new Directors("auctor aptent", c, "egestas fusce platea phasellus fringilla");
        list.add(dir1218);
        c.setCountry_id(114);
        Directors dir1219 = new Directors("lobortis volutpat sagittis", c, "fusce habitasse volutpat senectus cursus");
        list.add(dir1219);
        c.setCountry_id(17);
        Directors dir1220 = new Directors("lacus habitasse donec", c, "consequat interdum facilisi aliquam sagittis");
        list.add(dir1220);
        c.setCountry_id(145);
        Directors dir1221 = new Directors("scelerisque viverra etiam phasellus", c, "fermentum semper integer auctor hymenaeos");
        list.add(dir1221);
        c.setCountry_id(23);
        Directors dir1222 = new Directors("semper lectus habitant commodo", c, "dictum commodo felis consequat sodales");
        list.add(dir1222);
        c.setCountry_id(140);
        Directors dir1223 = new Directors("bulum imperdiet feugiat elementum", c, "senectus interdum scelerisque molestie consectetuer");
        list.add(dir1223);
        c.setCountry_id(31);
        Directors dir1224 = new Directors("mollis congue ultricies fringilla", c, "fusce mollis tincidunt neque felis");
        list.add(dir1224);
        c.setCountry_id(18);
        Directors dir1225 = new Directors("tempus velit tumst velit", c, "tempus dolor mauris mollis donec");
        list.add(dir1225);
        c.setCountry_id(139);
        Directors dir1226 = new Directors("venenatis laoreet curabitur", c, "faucibus metus habitant lectus platea");
        list.add(dir1226);
        c.setCountry_id(21);
        Directors dir1227 = new Directors("tempus vehicula platea felis", c, "turpis lacinia iaculis semper lacinia");
        list.add(dir1227);
        c.setCountry_id(4);
        Directors dir1228 = new Directors("vestibulum fermentum", c, "porttitor auctor elementum nullam rutrum");
        list.add(dir1228);
        c.setCountry_id(29);
        Directors dir1229 = new Directors("viverra lacus turpis hymenaeos", c, "tellus risus justo neque molestie");
        list.add(dir1229);
        c.setCountry_id(83);
        Directors dir1230 = new Directors("porttitor inceptos", c, "quisque lorem phasellus rutrum tempor");
        list.add(dir1230);
        c.setCountry_id(51);
        Directors dir1231 = new Directors("eleifend habitant faucibus", c, "vivamus primis sodales viverra scelerisque");
        list.add(dir1231);
        c.setCountry_id(21);
        Directors dir1232 = new Directors("volutpat turpis", c, "ultricies placerat morbi nulla aliquet");
        list.add(dir1232);
        c.setCountry_id(62);
        Directors dir1233 = new Directors("pretium lacus", c, "auctor mauris taciti wisiaenean pharetra");
        list.add(dir1233);
        c.setCountry_id(137);
        Directors dir1234 = new Directors("facilisi tumst semper", c, "netus curabitur proin metus fames");
        list.add(dir1234);
        c.setCountry_id(50);
        Directors dir1235 = new Directors("facilisisnunc ipsum elementum mollis", c, "litora felis tincidunt velit curabitur");
        list.add(dir1235);
        c.setCountry_id(60);
        Directors dir1236 = new Directors("magna ipsum nostra lacus", c, "porta nulla luctus nostra egestas");
        list.add(dir1236);
        c.setCountry_id(15);
        Directors dir1237 = new Directors("pulvinar dignissim sociosqu suspendisse", c, "aliquam congue vitae lorem quisque");
        list.add(dir1237);
        c.setCountry_id(8);
        Directors dir1238 = new Directors("auctor proin lacinia bibendum", c, "lacinia cubilia cubilia interdum accumsan");
        list.add(dir1238);
        c.setCountry_id(142);
        Directors dir1239 = new Directors("pellentesque metus fermentum", c, "class venenatis lobortis wisiaenean elementum");
        list.add(dir1239);
        c.setCountry_id(105);
        Directors dir1240 = new Directors("porttitor aliquam", c, "nostra tortor wisiaenean euismod luctus");
        list.add(dir1240);
        c.setCountry_id(123);
        Directors dir1241 = new Directors("luctus eleifend tumst", c, "euismod sollicitudin risus venenatis litora");
        list.add(dir1241);
        c.setCountry_id(10);
        Directors dir1242 = new Directors("laoreet pellentesque aliquet semper", c, "primis magna mattis torquent ipsum");
        list.add(dir1242);
        c.setCountry_id(95);
        Directors dir1243 = new Directors("bibendum elementum purus aenean", c, "bibendum commodo hymenaeos aptent semper");
        list.add(dir1243);
        c.setCountry_id(30);
        Directors dir1244 = new Directors("semper mattis curae mollis", c, "dictum fames mattis accumsan fringilla");
        list.add(dir1244);
        c.setCountry_id(62);
        Directors dir1245 = new Directors("aliquam bulum", c, "tortor tempus proin dictumst fames");
        list.add(dir1245);
        c.setCountry_id(41);
        Directors dir1246 = new Directors("sodales vehicula netus curabitur", c, "vehicula convallis magna donec eleifend");
        list.add(dir1246);
        c.setCountry_id(115);
        Directors dir1247 = new Directors("tellus auctor", c, "pharetra vestibulum aenean placerat bibendum");
        list.add(dir1247);
        c.setCountry_id(144);
        Directors dir1248 = new Directors("porta sagittis", c, "lorem porttitor egestas lobortis dolor");
        list.add(dir1248);
        c.setCountry_id(147);
        Directors dir1249 = new Directors("venenatis tortor facilisi", c, "facilisisnunc nullam phasellus luctus phasellus");
        list.add(dir1249);
        c.setCountry_id(52);
        Directors dir1250 = new Directors("lorem curabitur fermentum aliquam", c, "aptent wisiaenean dignissim mollis vivamus");
        list.add(dir1250);
        c.setCountry_id(70);
        Directors dir1251 = new Directors("ullamcorper class tortor", c, "venenatis convallis eleifend vesti conubia");
        list.add(dir1251);
        c.setCountry_id(92);
        Directors dir1252 = new Directors("integer aliquam pulvinar ullamcorper", c, "fames habitant faucibus tortor vesti");
        list.add(dir1252);
        c.setCountry_id(23);
        Directors dir1253 = new Directors("molestie dolor congue", c, "primis libero netus augue placerat");
        list.add(dir1253);
        c.setCountry_id(11);
        Directors dir1254 = new Directors("faucibus metus nostra hymenaeos", c, "quisque adipiscing eleifend sagittis taciti");
        list.add(dir1254);
        c.setCountry_id(99);
        Directors dir1255 = new Directors("congue egestas", c, "netus posuere magna praesent posuere");
        list.add(dir1255);
        c.setCountry_id(74);
        Directors dir1256 = new Directors("nullam dictumst", c, "facilisis wisiaenean vestibulum purus dolor");
        list.add(dir1256);
        c.setCountry_id(68);
        Directors dir1257 = new Directors("lacus rutrum", c, "cubilia convallis pharetra tristique adipiscing");
        list.add(dir1257);
        c.setCountry_id(134);
        Directors dir1258 = new Directors("phasellus volutpat pulvinar", c, "magna consectetuer curae fringilla dolor");
        list.add(dir1258);
        c.setCountry_id(5);
        Directors dir1259 = new Directors("pretium fusce magna imperdiet", c, "pharetra mauris taciti proin aliquam");
        list.add(dir1259);
        c.setCountry_id(110);
        Directors dir1260 = new Directors("tempus vitae porta", c, "porttitor taciti netus sodales pellentesque");
        list.add(dir1260);
        c.setCountry_id(11);
        Directors dir1261 = new Directors("aliquet porttitor", c, "fermentum cursus netus class elementum");
        list.add(dir1261);
        c.setCountry_id(124);
        Directors dir1262 = new Directors("senectus curabitur", c, "fringilla auctor cubilia mattis mauris");
        list.add(dir1262);
        c.setCountry_id(67);
        Directors dir1263 = new Directors("mauris bulum inceptos scelerisque", c, "scelerisque metus ultrices morbi lorem");
        list.add(dir1263);
        c.setCountry_id(139);
        Directors dir1264 = new Directors("libero senectus primis", c, "nonummy facilisis tristique faucibus bulum");
        list.add(dir1264);
        c.setCountry_id(101);
        Directors dir1265 = new Directors("dolor justo tempus aliquam", c, "suspendisse volutpat nostra dictum cubilia");
        list.add(dir1265);
        c.setCountry_id(46);
        Directors dir1266 = new Directors("euismod commodo", c, "tortor sociosqu facilisi tempor sagittis");
        list.add(dir1266);
        c.setCountry_id(60);
        Directors dir1267 = new Directors("sodales semper pretium convallis", c, "adipiscing nostra fusce dictumst litora");
        list.add(dir1267);
        c.setCountry_id(137);
        Directors dir1268 = new Directors("iaculis dictum volutpat", c, "lobortis bibendum torquent netus sollicitudin");
        list.add(dir1268);
        c.setCountry_id(46);
        Directors dir1269 = new Directors("purus laoreet", c, "mattis tempor donec aenean bulum");
        list.add(dir1269);
        c.setCountry_id(70);
        Directors dir1270 = new Directors("malesuada fermentum magna", c, "magna sociosqu tumst nullam mauris");
        list.add(dir1270);
        c.setCountry_id(10);
        Directors dir1271 = new Directors("aenean primis sodales lacinia", c, "egestas neque convallis euismod pretium");
        list.add(dir1271);
        c.setCountry_id(63);
        Directors dir1272 = new Directors("netus eleifend class", c, "bibendum pharetra turpis interdum aliquam");
        list.add(dir1272);
        c.setCountry_id(121);
        Directors dir1273 = new Directors("scelerisque pretium", c, "mattis inceptos lectus ipsum euismod");
        list.add(dir1273);
        c.setCountry_id(101);
        Directors dir1274 = new Directors("facilisis conubia bulum tellus", c, "pharetra neque pellentesque phasellus eleifend");
        list.add(dir1274);
        c.setCountry_id(16);
        Directors dir1275 = new Directors("molestie tempus etiam", c, "eleifend imperdiet tincidunt lectus interdum");
        list.add(dir1275);
        c.setCountry_id(112);
        Directors dir1276 = new Directors("justo ultrices luctus tumst", c, "aptent risus turpis tempus habitasse");
        list.add(dir1276);
        c.setCountry_id(61);
        Directors dir1277 = new Directors("nulla malesuada aptent torquent", c, "ipsum semper litora taciti aptent");
        list.add(dir1277);
        c.setCountry_id(81);
        Directors dir1278 = new Directors("eleifend cubilia lacus ligula", c, "sodales pharetra mollis neque quisque");
        list.add(dir1278);
        c.setCountry_id(109);
        Directors dir1279 = new Directors("facilisisnunc quisque aliquam", c, "purus platea proin euismod quisque");
        list.add(dir1279);
        c.setCountry_id(71);
        Directors dir1280 = new Directors("iaculis facilisisnunc sociosqu risus", c, "dictum ipsum pretium tempus primis");
        list.add(dir1280);
        c.setCountry_id(120);
        Directors dir1281 = new Directors("velit malesuada sociosqu", c, "fermentum facilisi tristique mollis senectus");
        list.add(dir1281);
        c.setCountry_id(88);
        Directors dir1282 = new Directors("sollicitudin interdum", c, "vehicula augue purus hendrerit metus");
        list.add(dir1282);
        c.setCountry_id(116);
        Directors dir1283 = new Directors("euismod dictumst phasellus mollis", c, "morbi pharetra integer ultrices ipsum");
        list.add(dir1283);
        c.setCountry_id(10);
        Directors dir1284 = new Directors("taciti lobortis", c, "bibendum sociosqu taciti lectus vesti");
        list.add(dir1284);
        c.setCountry_id(86);
        Directors dir1285 = new Directors("augue rutrum sodales", c, "etiam vestibulum lorem sapien mattis");
        list.add(dir1285);
        c.setCountry_id(77);
        Directors dir1286 = new Directors("platea curabitur", c, "suspendisse volutpat imperdiet magna nulla");
        list.add(dir1286);
        c.setCountry_id(16);
        Directors dir1287 = new Directors("dictumst auctor justo", c, "risus phasellus torquent lacinia magna");
        list.add(dir1287);
        c.setCountry_id(56);
        Directors dir1288 = new Directors("dictumst eleifend sollicitudin", c, "metus semper sapien aliquet pretium");
        list.add(dir1288);
        c.setCountry_id(64);
        Directors dir1289 = new Directors("libero tristique", c, "taciti vestibulum auctor dolor bulum");
        list.add(dir1289);
        c.setCountry_id(1);
        Directors dir1290 = new Directors("class cubilia metus luctus", c, "senectus felis lorem netus quisque");
        list.add(dir1290);
        c.setCountry_id(90);
        Directors dir1291 = new Directors("viverra aliquam habitasse egestas", c, "ullamcorper aliquam ultrices fringilla semper");
        list.add(dir1291);
        c.setCountry_id(61);
        Directors dir1292 = new Directors("vitae morbi porttitor", c, "curabitur ligula quisque aliquam commodo");
        list.add(dir1292);
        c.setCountry_id(6);
        Directors dir1293 = new Directors("vivamus mauris sociosqu facilisisnunc", c, "tumst adipiscing faucibus tellus dictum");
        list.add(dir1293);
        c.setCountry_id(42);
        Directors dir1294 = new Directors("ipsum bulum lectus senectus", c, "malesuada mattis adipiscing nonummy pretium");
        list.add(dir1294);
        c.setCountry_id(114);
        Directors dir1295 = new Directors("vivamus neque consequat", c, "velit vestibulum pretium bibendum dictumst");
        list.add(dir1295);
        c.setCountry_id(84);
        Directors dir1296 = new Directors("ornare velit", c, "taciti pellentesque tristique pulvinar lectus");
        list.add(dir1296);
        c.setCountry_id(138);
        Directors dir1297 = new Directors("porta sodales vesti dolor", c, "vestibulum rutrum fusce platea dictum");
        list.add(dir1297);
        c.setCountry_id(135);
        Directors dir1298 = new Directors("curae sagittis aptent sociosqu", c, "ultrices conubia elementum semper tempus");
        list.add(dir1298);
        c.setCountry_id(84);
        Directors dir1299 = new Directors("hendrerit sodales turpis", c, "suspendisse posuere molestie mollis imperdiet");
        list.add(dir1299);
        c.setCountry_id(122);
        Directors dir1300 = new Directors("justo adipiscing vesti dictumst", c, "tempor phasellus tempor vehicula turpis");
        list.add(dir1300);
        c.setCountry_id(39);
        Directors dir1301 = new Directors("eleifend nulla", c, "suspendisse aliquet adipiscing consequat habitant");
        list.add(dir1301);
        c.setCountry_id(75);
        Directors dir1302 = new Directors("litora aliquet dictum tristique", c, "pretium bulum facilisisnunc fusce tellus");
        list.add(dir1302);
        c.setCountry_id(57);
        Directors dir1303 = new Directors("ultricies vitae", c, "ornare ullamcorper tempor porta tempus");
        list.add(dir1303);
        c.setCountry_id(44);
        Directors dir1304 = new Directors("mauris accumsan congue sodales", c, "quisque mollis malesuada placerat suspendisse");
        list.add(dir1304);
        c.setCountry_id(125);
        Directors dir1305 = new Directors("curabitur habitasse cursus", c, "nullam placerat dictumst maecenas interdum");
        list.add(dir1305);
        c.setCountry_id(79);
        Directors dir1306 = new Directors("aenean tortor", c, "litora tempus aenean nullam mattis");
        list.add(dir1306);
        c.setCountry_id(142);
        Directors dir1307 = new Directors("volutpat porta dolor", c, "scelerisque tumst fames consectetuer sodales");
        list.add(dir1307);
        c.setCountry_id(32);
        Directors dir1308 = new Directors("dictumst mattis", c, "phasellus habitasse cursus donec dictum");
        list.add(dir1308);
        c.setCountry_id(9);
        Directors dir1309 = new Directors("felis varius ipsum libero", c, "posuere turpis aptent taciti tellus");
        list.add(dir1309);
        c.setCountry_id(69);
        Directors dir1310 = new Directors("varius venenatis hendrerit", c, "phasellus morbi neque dolor bibendum");
        list.add(dir1310);
        c.setCountry_id(58);
        Directors dir1311 = new Directors("mollis euismod", c, "semper ultrices fames conubia venenatis");
        list.add(dir1311);
        c.setCountry_id(126);
        Directors dir1312 = new Directors("nostra lacinia curabitur aptent", c, "morbi sodales posuere conubia congue");
        list.add(dir1312);
        c.setCountry_id(102);
        Directors dir1313 = new Directors("eleifend faucibus", c, "facilisi fames fermentum phasellus sapien");
        list.add(dir1313);
        c.setCountry_id(101);
        Directors dir1314 = new Directors("ligula fringilla risus", c, "tempus turpis porttitor justo ipsum");
        list.add(dir1314);
        c.setCountry_id(150);
        Directors dir1315 = new Directors("augue phasellus", c, "lacinia mollis ullamcorper euismod facilisis");
        list.add(dir1315);
        c.setCountry_id(42);
        Directors dir1316 = new Directors("lacus cursus neque", c, "litora commodo neque phasellus placerat");
        list.add(dir1316);
        c.setCountry_id(80);
        Directors dir1317 = new Directors("scelerisque etiam porttitor ullamcorper", c, "laoreet cubilia nostra libero vesti");
        list.add(dir1317);
        c.setCountry_id(7);
        Directors dir1318 = new Directors("fusce pharetra taciti", c, "habitant lorem lacus consectetuer mauris");
        list.add(dir1318);
        c.setCountry_id(46);
        Directors dir1319 = new Directors("lectus vesti tellus wisiaenean", c, "feugiat dignissim lectus interdum velit");
        list.add(dir1319);
        c.setCountry_id(99);
        Directors dir1320 = new Directors("quisque bibendum semper", c, "interdum integer lectus aliquam hymenaeos");
        list.add(dir1320);
        c.setCountry_id(17);
        Directors dir1321 = new Directors("lectus nostra", c, "quisque accumsan magna faucibus bibendum");
        list.add(dir1321);
        c.setCountry_id(20);
        Directors dir1322 = new Directors("consequat convallis", c, "dignissim lobortis tempus dolor sociosqu");
        list.add(dir1322);
        c.setCountry_id(90);
        Directors dir1323 = new Directors("tortor risus varius sollicitudin", c, "inceptos luctus ultrices vehicula sollicitudin");
        list.add(dir1323);
        c.setCountry_id(1);
        Directors dir1324 = new Directors("aptent curae", c, "habitasse cubilia maecenas cursus velit");
        list.add(dir1324);
        c.setCountry_id(64);
        Directors dir1325 = new Directors("magna imperdiet varius tellus", c, "aliquet imperdiet tortor adipiscing donec");
        list.add(dir1325);
        c.setCountry_id(132);
        Directors dir1326 = new Directors("tempus accumsan porta", c, "praesent rutrum tempus commodo elementum");
        list.add(dir1326);
        c.setCountry_id(93);
        Directors dir1327 = new Directors("lectus fringilla conubia nostra", c, "pretium hymenaeos risus volutpat vehicula");
        list.add(dir1327);
        c.setCountry_id(106);
        Directors dir1328 = new Directors("commodo ipsum", c, "lacus inceptos curae lacinia class");
        list.add(dir1328);
        c.setCountry_id(38);
        Directors dir1329 = new Directors("pellentesque congue proin", c, "tincidunt ligula posuere maecenas fermentum");
        list.add(dir1329);
        c.setCountry_id(18);
        Directors dir1330 = new Directors("habitasse iaculis", c, "malesuada sociosqu nonummy sodales integer");
        list.add(dir1330);
        c.setCountry_id(63);
        Directors dir1331 = new Directors("lectus vesti", c, "porttitor faucibus taciti quisque platea");
        list.add(dir1331);
        c.setCountry_id(124);
        Directors dir1332 = new Directors("fringilla sodales sociosqu", c, "imperdiet volutpat justo accumsan vesti");
        list.add(dir1332);
        c.setCountry_id(20);
        Directors dir1333 = new Directors("conubia curae nullam facilisi", c, "tempus facilisi sagittis tempus mattis");
        list.add(dir1333);
        c.setCountry_id(110);
        Directors dir1334 = new Directors("tellus augue", c, "felis integer tristique aliquam fames");
        list.add(dir1334);
        c.setCountry_id(44);
        Directors dir1335 = new Directors("sociosqu convallis varius", c, "tempus velit aenean molestie accumsan");
        list.add(dir1335);
        c.setCountry_id(64);
        Directors dir1336 = new Directors("litora luctus", c, "torquent lacus aenean sollicitudin facilisi");
        list.add(dir1336);
        c.setCountry_id(100);
        Directors dir1337 = new Directors("eleifend eleifend", c, "pharetra cursus pretium aptent mattis");
        list.add(dir1337);
        c.setCountry_id(144);
        Directors dir1338 = new Directors("vivamus magna augue mollis", c, "vivamus varius vitae mollis porta");
        list.add(dir1338);
        c.setCountry_id(109);
        Directors dir1339 = new Directors("inceptos bulum magna", c, "donec morbi etiam habitant taciti");
        list.add(dir1339);
        c.setCountry_id(112);
        Directors dir1340 = new Directors("molestie conubia placerat", c, "velit neque pulvinar torquent pulvinar");
        list.add(dir1340);
        c.setCountry_id(9);
        Directors dir1341 = new Directors("facilisi luctus aenean nullam", c, "posuere ipsum vitae libero accumsan");
        list.add(dir1341);
        c.setCountry_id(77);
        Directors dir1342 = new Directors("facilisis accumsan sollicitudin tellus", c, "rutrum tellus posuere auctor dignissim");
        list.add(dir1342);
        c.setCountry_id(131);
        Directors dir1343 = new Directors("velit aliquet morbi rutrum", c, "malesuada congue consectetuer congue tincidunt");
        list.add(dir1343);
        c.setCountry_id(67);
        Directors dir1344 = new Directors("tempus praesent", c, "mollis litora adipiscing facilisi consectetuer");
        list.add(dir1344);
        c.setCountry_id(117);
        Directors dir1345 = new Directors("placerat suspendisse dignissim", c, "eleifend augue tempus tumst bibendum");
        list.add(dir1345);
        c.setCountry_id(50);
        Directors dir1346 = new Directors("iaculis posuere", c, "faucibus quisque wisiaenean porttitor integer");
        list.add(dir1346);
        c.setCountry_id(11);
        Directors dir1347 = new Directors("purus dictumst wisiaenean", c, "mattis tumst feugiat tellus convallis");
        list.add(dir1347);
        c.setCountry_id(150);
        Directors dir1348 = new Directors("integer auctor libero nonummy", c, "commodo laoreet lorem aliquet pellentesque");
        list.add(dir1348);
        c.setCountry_id(15);
        Directors dir1349 = new Directors("vestibulum sollicitudin euismod curae", c, "donec dolor quisque mollis neque");
        list.add(dir1349);
        c.setCountry_id(22);
        Directors dir1350 = new Directors("lorem dignissim interdum", c, "metus fames adipiscing commodo volutpat");
        list.add(dir1350);
        c.setCountry_id(34);
        Directors dir1351 = new Directors("placerat torquent pretium", c, "primis lacinia placerat quisque vehicula");
        list.add(dir1351);
        c.setCountry_id(92);
        Directors dir1352 = new Directors("velit ornare neque tempor", c, "posuere mollis lacus scelerisque etiam");
        list.add(dir1352);
        c.setCountry_id(59);
        Directors dir1353 = new Directors("sagittis class venenatis", c, "posuere conubia proin morbi morbi");
        list.add(dir1353);
        c.setCountry_id(141);
        Directors dir1354 = new Directors("euismod taciti vitae", c, "elementum posuere senectus dolor maecenas");
        list.add(dir1354);
        c.setCountry_id(42);
        Directors dir1355 = new Directors("convallis elementum volutpat fringilla", c, "commodo proin placerat auctor habitasse");
        list.add(dir1355);
        c.setCountry_id(150);
        Directors dir1356 = new Directors("vivamus senectus egestas netus", c, "aenean primis lacus fusce viverra");
        list.add(dir1356);
        c.setCountry_id(79);
        Directors dir1357 = new Directors("ullamcorper elementum aliquam purus", c, "fames primis varius aliquet primis");
        list.add(dir1357);
        c.setCountry_id(17);
        Directors dir1358 = new Directors("elementum ullamcorper", c, "habitasse vitae congue sodales aliquet");
        list.add(dir1358);
        c.setCountry_id(129);
        Directors dir1359 = new Directors("luctus primis mollis", c, "vehicula sagittis fames mauris facilisisnunc");
        list.add(dir1359);
        c.setCountry_id(56);
        Directors dir1360 = new Directors("litora netus molestie", c, "metus adipiscing praesent lorem euismod");
        list.add(dir1360);
        c.setCountry_id(87);
        Directors dir1361 = new Directors("euismod neque", c, "platea venenatis nonummy fermentum aptent");
        list.add(dir1361);
        c.setCountry_id(76);
        Directors dir1362 = new Directors("tristique pulvinar conubia consequat", c, "lacinia scelerisque vitae velit ullamcorper");
        list.add(dir1362);
        c.setCountry_id(121);
        Directors dir1363 = new Directors("lacinia feugiat adipiscing lorem", c, "purus quisque hymenaeos sapien bibendum");
        list.add(dir1363);
        c.setCountry_id(128);
        Directors dir1364 = new Directors("maecenas porttitor magna aliquam", c, "proin fusce lacinia neque nostra");
        list.add(dir1364);
        c.setCountry_id(84);
        Directors dir1365 = new Directors("mollis ultricies hendrerit adipiscing", c, "sociosqu senectus netus dictumst convallis");
        list.add(dir1365);
        c.setCountry_id(66);
        Directors dir1366 = new Directors("proin dictumst", c, "senectus vitae praesent faucibus nulla");
        list.add(dir1366);
        c.setCountry_id(5);
        Directors dir1367 = new Directors("facilisisnunc mauris nostra", c, "suspendisse volutpat habitant dictum vestibulum");
        list.add(dir1367);
        c.setCountry_id(30);
        Directors dir1368 = new Directors("turpis venenatis", c, "convallis dictumst morbi egestas ornare");
        list.add(dir1368);
        c.setCountry_id(28);
        Directors dir1369 = new Directors("senectus lectus", c, "tellus senectus euismod faucibus praesent");
        list.add(dir1369);
        c.setCountry_id(5);
        Directors dir1370 = new Directors("purus tempus", c, "commodo ipsum felis hendrerit hymenaeos");
        list.add(dir1370);
        c.setCountry_id(106);
        Directors dir1371 = new Directors("interdum phasellus consectetuer euismod", c, "aenean habitasse mauris sollicitudin porttitor");
        list.add(dir1371);
        c.setCountry_id(47);
        Directors dir1372 = new Directors("lectus fusce", c, "phasellus etiam ornare lectus netus");
        list.add(dir1372);
        c.setCountry_id(29);
        Directors dir1373 = new Directors("pulvinar inceptos bibendum lorem", c, "placerat sociosqu ipsum risus nullam");
        list.add(dir1373);
        c.setCountry_id(110);
        Directors dir1374 = new Directors("interdum tempus ipsum purus", c, "elementum felis imperdiet facilisi auctor");
        list.add(dir1374);
        c.setCountry_id(32);
        Directors dir1375 = new Directors("maecenas felis sociosqu", c, "accumsan faucibus varius proin mattis");
        list.add(dir1375);
        c.setCountry_id(140);
        Directors dir1376 = new Directors("wisiaenean facilisisnunc hendrerit", c, "tempor feugiat luctus tempor praesent");
        list.add(dir1376);
        c.setCountry_id(4);
        Directors dir1377 = new Directors("tortor consectetuer tortor", c, "facilisisnunc euismod vesti convallis viverra");
        list.add(dir1377);
        c.setCountry_id(62);
        Directors dir1378 = new Directors("iaculis torquent dolor vesti", c, "etiam facilisi magna augue lorem");
        list.add(dir1378);
        c.setCountry_id(120);
        Directors dir1379 = new Directors("tortor euismod", c, "facilisisnunc torquent augue netus donec");
        list.add(dir1379);
        c.setCountry_id(78);
        Directors dir1380 = new Directors("platea egestas dolor tempor", c, "tumst iaculis elementum scelerisque sagittis");
        list.add(dir1380);
        c.setCountry_id(85);
        Directors dir1381 = new Directors("lorem donec", c, "primis ligula tumst egestas ullamcorper");
        list.add(dir1381);
        c.setCountry_id(3);
        Directors dir1382 = new Directors("class primis integer", c, "elementum conubia etiam egestas turpis");
        list.add(dir1382);
        c.setCountry_id(90);
        Directors dir1383 = new Directors("venenatis velit ornare", c, "cursus lectus ipsum egestas volutpat");
        list.add(dir1383);
        c.setCountry_id(113);
        Directors dir1384 = new Directors("nonummy bulum mattis senectus", c, "justo egestas rutrum dignissim convallis");
        list.add(dir1384);
        c.setCountry_id(108);
        Directors dir1385 = new Directors("habitant euismod aliquam luctus", c, "elementum sollicitudin risus platea elementum");
        list.add(dir1385);
        c.setCountry_id(5);
        Directors dir1386 = new Directors("quisque bulum velit torquent", c, "aliquet quisque inceptos ipsum dignissim");
        list.add(dir1386);
        c.setCountry_id(124);
        Directors dir1387 = new Directors("tempus vehicula sapien tumst", c, "etiam vestibulum consectetuer pellentesque inceptos");
        list.add(dir1387);
        c.setCountry_id(31);
        Directors dir1388 = new Directors("metus aenean praesent curabitur", c, "euismod aliquet aenean tumst pellentesque");
        list.add(dir1388);
        c.setCountry_id(11);
        Directors dir1389 = new Directors("wisiaenean porttitor lectus", c, "vestibulum vestibulum porta nostra ultrices");
        list.add(dir1389);
        c.setCountry_id(17);
        Directors dir1390 = new Directors("bulum dolor", c, "tincidunt bibendum porta porttitor maecenas");
        list.add(dir1390);
        c.setCountry_id(120);
        Directors dir1391 = new Directors("iaculis quisque", c, "morbi litora morbi ligula magna");
        list.add(dir1391);
        c.setCountry_id(128);
        Directors dir1392 = new Directors("tempor cubilia vehicula hymenaeos", c, "praesent semper nullam bulum tempor");
        list.add(dir1392);
        c.setCountry_id(87);
        Directors dir1393 = new Directors("fames molestie", c, "sodales feugiat morbi lacinia phasellus");
        list.add(dir1393);
        c.setCountry_id(125);
        Directors dir1394 = new Directors("netus egestas litora bibendum", c, "iaculis torquent luctus hymenaeos fringilla");
        list.add(dir1394);
        c.setCountry_id(30);
        Directors dir1395 = new Directors("litora metus consequat luctus", c, "ornare augue rutrum laoreet facilisi");
        list.add(dir1395);
        c.setCountry_id(144);
        Directors dir1396 = new Directors("pharetra adipiscing bulum vestibulum", c, "habitant pellentesque praesent primis turpis");
        list.add(dir1396);
        c.setCountry_id(13);
        Directors dir1397 = new Directors("viverra laoreet torquent", c, "risus consequat ipsum tellus etiam");
        list.add(dir1397);
        c.setCountry_id(139);
        Directors dir1398 = new Directors("sollicitudin vestibulum fermentum feugiat", c, "conubia placerat aptent pharetra netus");
        list.add(dir1398);
        c.setCountry_id(107);
        Directors dir1399 = new Directors("malesuada nostra lacinia", c, "viverra convallis curae bibendum lorem");
        list.add(dir1399);
        c.setCountry_id(48);
        Directors dir1400 = new Directors("scelerisque bibendum aptent suspendisse", c, "luctus proin dolor iaculis aptent");
        list.add(dir1400);
        c.setCountry_id(82);
        Directors dir1401 = new Directors("augue sodales donec", c, "malesuada aptent aliquet congue turpis");
        list.add(dir1401);
        c.setCountry_id(5);
        Directors dir1402 = new Directors("quisque quisque", c, "scelerisque congue varius curabitur nonummy");
        list.add(dir1402);
        c.setCountry_id(66);
        Directors dir1403 = new Directors("tumst lacus justo", c, "senectus aliquam bibendum dolor felis");
        list.add(dir1403);
        c.setCountry_id(145);
        Directors dir1404 = new Directors("sodales adipiscing fringilla", c, "hendrerit semper tempus morbi sociosqu");
        list.add(dir1404);
        c.setCountry_id(17);
        Directors dir1405 = new Directors("nonummy dictum sapien accumsan", c, "facilisis venenatis sapien facilisisnunc sagittis");
        list.add(dir1405);
        c.setCountry_id(1);
        Directors dir1406 = new Directors("sagittis dictumst fusce lectus", c, "ultrices ullamcorper tumst facilisisnunc semper");
        list.add(dir1406);
        c.setCountry_id(94);
        Directors dir1407 = new Directors("consectetuer pretium sapien", c, "facilisi taciti pulvinar mattis tellus");
        list.add(dir1407);
        c.setCountry_id(48);
        Directors dir1408 = new Directors("ultrices inceptos", c, "feugiat senectus senectus dictum neque");
        list.add(dir1408);
        c.setCountry_id(42);
        Directors dir1409 = new Directors("sodales litora vivamus inceptos", c, "magna suspendisse scelerisque nonummy posuere");
        list.add(dir1409);
        c.setCountry_id(45);
        Directors dir1410 = new Directors("hymenaeos lacus cubilia", c, "tempus iaculis congue bibendum egestas");
        list.add(dir1410);
        c.setCountry_id(98);
        Directors dir1411 = new Directors("metus tortor maecenas", c, "mattis phasellus vitae consequat taciti");
        list.add(dir1411);
        c.setCountry_id(5);
        Directors dir1412 = new Directors("accumsan conubia", c, "molestie mollis primis cubilia egestas");
        list.add(dir1412);
        c.setCountry_id(12);
        Directors dir1413 = new Directors("quisque adipiscing", c, "ultrices mattis adipiscing dictumst rutrum");
        list.add(dir1413);
        c.setCountry_id(40);
        Directors dir1414 = new Directors("auctor platea euismod", c, "augue convallis tortor dignissim elementum");
        list.add(dir1414);
        c.setCountry_id(49);
        Directors dir1415 = new Directors("nulla sapien curabitur consequat", c, "consectetuer euismod class tincidunt ligula");
        list.add(dir1415);
        c.setCountry_id(15);
        Directors dir1416 = new Directors("tincidunt pharetra", c, "ullamcorper porta venenatis tumst phasellus");
        list.add(dir1416);
        c.setCountry_id(85);
        Directors dir1417 = new Directors("platea inceptos tortor", c, "nullam imperdiet neque accumsan tempus");
        list.add(dir1417);
        c.setCountry_id(80);
        Directors dir1418 = new Directors("taciti donec facilisi adipiscing", c, "porta volutpat curabitur aptent nostra");
        list.add(dir1418);
        c.setCountry_id(26);
        Directors dir1419 = new Directors("dictum platea inceptos porttitor", c, "platea laoreet vesti libero rutrum");
        list.add(dir1419);
        c.setCountry_id(33);
        Directors dir1420 = new Directors("pretium faucibus", c, "placerat pellentesque sapien augue senectus");
        list.add(dir1420);
        c.setCountry_id(23);
        Directors dir1421 = new Directors("suspendisse ultricies dictumst ipsum", c, "scelerisque integer imperdiet augue hendrerit");
        list.add(dir1421);
        c.setCountry_id(44);
        Directors dir1422 = new Directors("habitant justo curabitur curabitur", c, "lorem scelerisque torquent donec semper");
        list.add(dir1422);
        c.setCountry_id(95);
        Directors dir1423 = new Directors("semper nulla", c, "tumst curae eleifend lacinia iaculis");
        list.add(dir1423);
        c.setCountry_id(15);
        Directors dir1424 = new Directors("egestas accumsan turpis", c, "vivamus justo lectus nostra primis");
        list.add(dir1424);
        c.setCountry_id(41);
        Directors dir1425 = new Directors("proin bibendum ligula laoreet", c, "commodo libero vesti quisque vehicula");
        list.add(dir1425);
        c.setCountry_id(126);
        Directors dir1426 = new Directors("neque libero wisiaenean purus", c, "habitasse habitasse habitasse ligula fermentum");
        list.add(dir1426);
        c.setCountry_id(127);
        Directors dir1427 = new Directors("egestas auctor tempus", c, "ornare velit vestibulum eleifend elementum");
        list.add(dir1427);
        c.setCountry_id(127);
        Directors dir1428 = new Directors("praesent morbi imperdiet conubia", c, "mattis venenatis dictum lobortis nonummy");
        list.add(dir1428);
        c.setCountry_id(59);
        Directors dir1429 = new Directors("aliquam inceptos", c, "hendrerit aptent integer eleifend tortor");
        list.add(dir1429);
        c.setCountry_id(47);
        Directors dir1430 = new Directors("accumsan faucibus", c, "phasellus scelerisque egestas tincidunt conubia");
        list.add(dir1430);
        c.setCountry_id(144);
        Directors dir1431 = new Directors("sollicitudin augue dolor", c, "morbi torquent aptent pulvinar praesent");
        list.add(dir1431);
        c.setCountry_id(57);
        Directors dir1432 = new Directors("posuere libero eleifend cursus", c, "nonummy accumsan sapien tristique molestie");
        list.add(dir1432);
        c.setCountry_id(113);
        Directors dir1433 = new Directors("curae sodales hendrerit nostra", c, "nonummy donec class laoreet libero");
        list.add(dir1433);
        c.setCountry_id(26);
        Directors dir1434 = new Directors("pulvinar commodo", c, "molestie praesent pellentesque feugiat lacus");
        list.add(dir1434);
        c.setCountry_id(135);
        Directors dir1435 = new Directors("tellus bulum vesti", c, "malesuada lacinia fermentum fusce augue");
        list.add(dir1435);
        c.setCountry_id(44);
        Directors dir1436 = new Directors("congue vivamus mauris consectetuer", c, "turpis vivamus dignissim phasellus inceptos");
        list.add(dir1436);
        c.setCountry_id(69);
        Directors dir1437 = new Directors("platea fusce nostra", c, "faucibus maecenas ullamcorper tempus nonummy");
        list.add(dir1437);
        c.setCountry_id(9);
        Directors dir1438 = new Directors("elementum aliquet lorem", c, "risus venenatis velit litora commodo");
        list.add(dir1438);
        c.setCountry_id(12);
        Directors dir1439 = new Directors("primis tellus proin", c, "netus pellentesque feugiat lacus dolor");
        list.add(dir1439);
        c.setCountry_id(113);
        Directors dir1440 = new Directors("cubilia aptent pharetra volutpat", c, "facilisisnunc habitant facilisi tristique risus");
        list.add(dir1440);
        c.setCountry_id(19);
        Directors dir1441 = new Directors("scelerisque vestibulum", c, "laoreet elementum suspendisse vesti morbi");
        list.add(dir1441);
        c.setCountry_id(138);
        Directors dir1442 = new Directors("vestibulum wisiaenean libero turpis", c, "faucibus curae hendrerit cursus scelerisque");
        list.add(dir1442);
        c.setCountry_id(1);
        Directors dir1443 = new Directors("lobortis risus", c, "pretium pulvinar fermentum inceptos facilisisnunc");
        list.add(dir1443);
        c.setCountry_id(43);
        Directors dir1444 = new Directors("varius conubia", c, "ornare facilisi habitasse nonummy ullamcorper");
        list.add(dir1444);
        c.setCountry_id(18);
        Directors dir1445 = new Directors("adipiscing sapien pharetra", c, "justo pellentesque sollicitudin nulla lacinia");
        list.add(dir1445);
        c.setCountry_id(120);
        Directors dir1446 = new Directors("dictum feugiat taciti eleifend", c, "sollicitudin augue iaculis lorem hymenaeos");
        list.add(dir1446);
        c.setCountry_id(41);
        Directors dir1447 = new Directors("tempus convallis pharetra", c, "posuere felis wisiaenean vestibulum mattis");
        list.add(dir1447);
        c.setCountry_id(11);
        Directors dir1448 = new Directors("vitae tempor magna auctor", c, "aliquet ultrices taciti consequat libero");
        list.add(dir1448);
        c.setCountry_id(41);
        Directors dir1449 = new Directors("pretium etiam tristique", c, "vivamus ipsum ligula lorem dolor");
        list.add(dir1449);
        c.setCountry_id(15);
        Directors dir1450 = new Directors("facilisisnunc adipiscing", c, "primis vitae mollis facilisi luctus");
        list.add(dir1450);
        c.setCountry_id(78);
        Directors dir1451 = new Directors("egestas sagittis tincidunt", c, "dictumst consequat taciti aliquam tempus");
        list.add(dir1451);
        c.setCountry_id(33);
        Directors dir1452 = new Directors("accumsan vestibulum risus", c, "justo tincidunt pulvinar tincidunt posuere");
        list.add(dir1452);
        c.setCountry_id(101);
        Directors dir1453 = new Directors("pulvinar sociosqu aliquet sodales", c, "wisiaenean lacinia fusce malesuada accumsan");
        list.add(dir1453);
        c.setCountry_id(77);
        Directors dir1454 = new Directors("porta quisque placerat", c, "fusce varius velit euismod vesti");
        list.add(dir1454);
        c.setCountry_id(79);
        Directors dir1455 = new Directors("magna tincidunt cursus suspendisse", c, "praesent sagittis cubilia tincidunt nulla");
        list.add(dir1455);
        c.setCountry_id(110);
        Directors dir1456 = new Directors("phasellus sagittis integer neque", c, "class bulum platea pellentesque faucibus");
        list.add(dir1456);
        c.setCountry_id(138);
        Directors dir1457 = new Directors("faucibus donec fermentum", c, "felis rutrum sociosqu consequat senectus");
        list.add(dir1457);
        c.setCountry_id(70);
        Directors dir1458 = new Directors("maecenas etiam", c, "laoreet sagittis curabitur egestas senectus");
        list.add(dir1458);
        c.setCountry_id(41);
        Directors dir1459 = new Directors("commodo sociosqu varius", c, "cubilia ultricies sapien mollis lacus");
        list.add(dir1459);
        c.setCountry_id(135);
        Directors dir1460 = new Directors("tellus facilisi", c, "cubilia magna venenatis venenatis proin");
        list.add(dir1460);
        c.setCountry_id(104);
        Directors dir1461 = new Directors("facilisis dictumst platea class", c, "facilisis ipsum tristique turpis euismod");
        list.add(dir1461);
        c.setCountry_id(106);
        Directors dir1462 = new Directors("aliquam ultricies", c, "inceptos pulvinar nonummy morbi felis");
        list.add(dir1462);
        c.setCountry_id(145);
        Directors dir1463 = new Directors("pellentesque molestie", c, "sodales congue justo habitasse adipiscing");
        list.add(dir1463);
        c.setCountry_id(130);
        Directors dir1464 = new Directors("mollis tumst malesuada augue", c, "mattis pharetra facilisis class venenatis");
        list.add(dir1464);
        c.setCountry_id(124);
        Directors dir1465 = new Directors("consectetuer tortor", c, "proin facilisi fames vitae congue");
        list.add(dir1465);
        c.setCountry_id(145);
        Directors dir1466 = new Directors("conubia adipiscing sociosqu", c, "lacus bibendum scelerisque volutpat iaculis");
        list.add(dir1466);
        c.setCountry_id(31);
        Directors dir1467 = new Directors("felis pulvinar proin", c, "elementum cubilia purus mollis facilisis");
        list.add(dir1467);
        c.setCountry_id(95);
        Directors dir1468 = new Directors("congue euismod inceptos interdum", c, "bulum consequat facilisis fermentum vesti");
        list.add(dir1468);
        c.setCountry_id(86);
        Directors dir1469 = new Directors("lobortis eleifend venenatis ligula", c, "malesuada tincidunt euismod class proin");
        list.add(dir1469);
        c.setCountry_id(118);
        Directors dir1470 = new Directors("volutpat ultrices dictum neque", c, "facilisis quisque fermentum habitant class");
        list.add(dir1470);
        c.setCountry_id(103);
        Directors dir1471 = new Directors("hendrerit fames", c, "ornare bulum lectus placerat tristique");
        list.add(dir1471);
        c.setCountry_id(94);
        Directors dir1472 = new Directors("fringilla adipiscing", c, "libero ipsum tempor posuere aenean");
        list.add(dir1472);
        c.setCountry_id(26);
        Directors dir1473 = new Directors("libero tellus", c, "imperdiet praesent hendrerit lectus proin");
        list.add(dir1473);
        c.setCountry_id(18);
        Directors dir1474 = new Directors("aptent porta", c, "consectetuer tristique inceptos litora aenean");
        list.add(dir1474);
        c.setCountry_id(5);
        Directors dir1475 = new Directors("tincidunt pretium convallis viverra", c, "class proin nonummy sociosqu rutrum");
        list.add(dir1475);
        c.setCountry_id(132);
        Directors dir1476 = new Directors("lacus vesti", c, "varius placerat volutpat ipsum velit");
        list.add(dir1476);
        c.setCountry_id(35);
        Directors dir1477 = new Directors("commodo semper", c, "integer dictumst tincidunt iaculis facilisis");
        list.add(dir1477);
        c.setCountry_id(59);
        Directors dir1478 = new Directors("bibendum vivamus", c, "fermentum faucibus lacinia luctus placerat");
        list.add(dir1478);
        c.setCountry_id(97);
        Directors dir1479 = new Directors("tortor sollicitudin", c, "iaculis netus nulla justo senectus");
        list.add(dir1479);
        c.setCountry_id(100);
        Directors dir1480 = new Directors("laoreet quisque eleifend", c, "auctor semper hymenaeos ultricies proin");
        list.add(dir1480);
        c.setCountry_id(63);
        Directors dir1481 = new Directors("nostra metus lobortis dignissim", c, "facilisi semper faucibus bulum dignissim");
        list.add(dir1481);
        c.setCountry_id(86);
        Directors dir1482 = new Directors("pulvinar senectus", c, "fermentum nonummy platea tumst sollicitudin");
        list.add(dir1482);
        c.setCountry_id(23);
        Directors dir1483 = new Directors("luctus feugiat litora pharetra", c, "aliquet nonummy curabitur dictum porta");
        list.add(dir1483);
        c.setCountry_id(48);
        Directors dir1484 = new Directors("bulum commodo integer lacinia", c, "ultrices venenatis mollis felis auctor");
        list.add(dir1484);
        c.setCountry_id(33);
        Directors dir1485 = new Directors("consequat dictumst", c, "tincidunt facilisi nonummy egestas iaculis");
        list.add(dir1485);
        c.setCountry_id(103);
        Directors dir1486 = new Directors("luctus nonummy", c, "laoreet litora feugiat suspendisse imperdiet");
        list.add(dir1486);
        c.setCountry_id(140);
        Directors dir1487 = new Directors("class turpis", c, "consectetuer dictum tellus habitasse viverra");
        list.add(dir1487);
        c.setCountry_id(51);
        Directors dir1488 = new Directors("velit donec fames", c, "congue curae venenatis pharetra sapien");
        list.add(dir1488);
        c.setCountry_id(92);
        Directors dir1489 = new Directors("dignissim nulla velit", c, "semper sollicitudin consequat interdum tincidunt");
        list.add(dir1489);
        c.setCountry_id(75);
        Directors dir1490 = new Directors("ultricies adipiscing", c, "netus porttitor lectus imperdiet ipsum");
        list.add(dir1490);
        c.setCountry_id(42);
        Directors dir1491 = new Directors("faucibus pretium tortor", c, "nonummy porta tumst molestie praesent");
        list.add(dir1491);
        c.setCountry_id(85);
        Directors dir1492 = new Directors("quisque vitae tincidunt commodo", c, "pretium maecenas platea neque platea");
        list.add(dir1492);
        c.setCountry_id(137);
        Directors dir1493 = new Directors("tellus laoreet", c, "bulum tumst hendrerit fames ullamcorper");
        list.add(dir1493);
        c.setCountry_id(9);
        Directors dir1494 = new Directors("magna consectetuer integer", c, "ipsum dictum tristique phasellus molestie");
        list.add(dir1494);
        c.setCountry_id(23);
        Directors dir1495 = new Directors("bulum magna augue lacinia", c, "ipsum justo hymenaeos commodo lacus");
        list.add(dir1495);
        c.setCountry_id(115);
        Directors dir1496 = new Directors("pharetra tortor sapien molestie", c, "lorem cursus pellentesque iaculis ipsum");
        list.add(dir1496);
        c.setCountry_id(58);
        Directors dir1497 = new Directors("varius varius", c, "sodales placerat lectus conubia tortor");
        list.add(dir1497);
        c.setCountry_id(13);
        Directors dir1498 = new Directors("vestibulum habitasse bulum vesti", c, "molestie accumsan purus hymenaeos nonummy");
        list.add(dir1498);
        c.setCountry_id(107);
        Directors dir1499 = new Directors("scelerisque venenatis inceptos", c, "dictumst curae libero lacinia aenean");
        list.add(dir1499);

        Connection.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            directorsDBM.insertDirectors(iteration);
        });
        Connection.getCon().getTransaction().commit();

    }
}
