package preInsertions;

import DBManager.DirectorsDBM;
import Conn.Connection;
import entities.Countries;
import entities.Directors;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertDirectors2
{

    DirectorsDBM directorsDBM = new DirectorsDBM();
    List<Directors> list = new ArrayList<>();
    Countries c = new Countries();

    public void insert() {

        c.setCountry_id(54);
        Directors dir500 = new Directors("etiam sociosqu", c, "quisque litora tincidunt vivamus taciti");
        list.add(dir500);
        c.setCountry_id(30);
        Directors dir501 = new Directors("ipsum egestas facilisisnunc cursus", c, "semper risus wisiaenean sociosqu maecenas");
        list.add(dir501);
        c.setCountry_id(28);
        Directors dir502 = new Directors("platea lacinia dictum", c, "fames curae tempus tincidunt sociosqu");
        list.add(dir502);
        c.setCountry_id(149);
        Directors dir503 = new Directors("morbi hendrerit wisiaenean aptent", c, "imperdiet commodo lacus rutrum malesuada");
        list.add(dir503);
        c.setCountry_id(128);
        Directors dir504 = new Directors("vitae bibendum", c, "euismod libero fringilla pellentesque phasellus");
        list.add(dir504);
        c.setCountry_id(10);
        Directors dir505 = new Directors("posuere sapien rutrum", c, "pretium varius feugiat lectus nostra");
        list.add(dir505);
        c.setCountry_id(136);
        Directors dir506 = new Directors("praesent dolor donec", c, "fermentum class phasellus luctus ornare");
        list.add(dir506);
        c.setCountry_id(91);
        Directors dir507 = new Directors("bulum praesent etiam", c, "vivamus dictum etiam pretium accumsan");
        list.add(dir507);
        c.setCountry_id(19);
        Directors dir508 = new Directors("dolor cursus sagittis", c, "ultricies pharetra mattis sollicitudin class");
        list.add(dir508);
        c.setCountry_id(60);
        Directors dir509 = new Directors("magna sapien volutpat facilisi", c, "morbi imperdiet nulla faucibus wisiaenean");
        list.add(dir509);
        c.setCountry_id(137);
        Directors dir510 = new Directors("curabitur cursus turpis ultricies", c, "fringilla hymenaeos mauris venenatis imperdiet");
        list.add(dir510);
        c.setCountry_id(145);
        Directors dir511 = new Directors("placerat nulla eleifend", c, "nostra hendrerit praesent purus curabitur");
        list.add(dir511);
        c.setCountry_id(129);
        Directors dir512 = new Directors("hendrerit luctus lobortis", c, "fermentum bulum libero phasellus risus");
        list.add(dir512);
        c.setCountry_id(79);
        Directors dir513 = new Directors("ullamcorper netus conubia", c, "laoreet laoreet posuere suspendisse nullam");
        list.add(dir513);
        c.setCountry_id(107);
        Directors dir514 = new Directors("quisque ornare nonummy luctus", c, "ultricies congue imperdiet etiam dictumst");
        list.add(dir514);
        c.setCountry_id(15);
        Directors dir515 = new Directors("aptent habitant fringilla fringilla", c, "cursus viverra nulla quisque hendrerit");
        list.add(dir515);
        c.setCountry_id(77);
        Directors dir516 = new Directors("semper primis mollis", c, "nulla aliquam tellus molestie placerat");
        list.add(dir516);
        c.setCountry_id(6);
        Directors dir517 = new Directors("pharetra ultricies habitasse", c, "litora accumsan ipsum venenatis integer");
        list.add(dir517);
        c.setCountry_id(37);
        Directors dir518 = new Directors("pharetra vestibulum bulum integer", c, "inceptos ipsum tortor facilisis volutpat");
        list.add(dir518);
        c.setCountry_id(59);
        Directors dir519 = new Directors("lacus adipiscing ornare", c, "wisiaenean rutrum fusce lectus pretium");
        list.add(dir519);
        c.setCountry_id(1);
        Directors dir520 = new Directors("netus vehicula", c, "integer sapien turpis mauris sagittis");
        list.add(dir520);
        c.setCountry_id(55);
        Directors dir521 = new Directors("ligula consectetuer", c, "nonummy facilisi porta habitasse hymenaeos");
        list.add(dir521);
        c.setCountry_id(103);
        Directors dir522 = new Directors("quisque neque", c, "facilisisnunc vitae malesuada torquent torquent");
        list.add(dir522);
        c.setCountry_id(89);
        Directors dir523 = new Directors("semper pellentesque", c, "primis sodales sodales wisiaenean ornare");
        list.add(dir523);
        c.setCountry_id(108);
        Directors dir524 = new Directors("sodales neque vehicula", c, "sollicitudin facilisi interdum dignissim luctus");
        list.add(dir524);
        c.setCountry_id(6);
        Directors dir525 = new Directors("taciti varius porttitor", c, "aliquet pharetra lectus placerat nullam");
        list.add(dir525);
        c.setCountry_id(140);
        Directors dir526 = new Directors("ipsum senectus", c, "inceptos tempus sociosqu quisque tortor");
        list.add(dir526);
        c.setCountry_id(16);
        Directors dir527 = new Directors("mauris praesent neque", c, "viverra eleifend mattis elementum consequat");
        list.add(dir527);
        c.setCountry_id(18);
        Directors dir528 = new Directors("dignissim fringilla", c, "facilisi curae donec pharetra congue");
        list.add(dir528);
        c.setCountry_id(9);
        Directors dir529 = new Directors("sapien rutrum lacus", c, "tempus vitae senectus litora wisiaenean");
        list.add(dir529);
        c.setCountry_id(65);
        Directors dir530 = new Directors("consectetuer elementum egestas", c, "magna habitasse purus ultrices dictumst");
        list.add(dir530);
        c.setCountry_id(103);
        Directors dir531 = new Directors("pretium hendrerit", c, "tumst ornare aenean rutrum commodo");
        list.add(dir531);
        c.setCountry_id(70);
        Directors dir532 = new Directors("dictum imperdiet tempus magna", c, "vestibulum mauris tristique semper lacinia");
        list.add(dir532);
        c.setCountry_id(93);
        Directors dir533 = new Directors("neque fringilla ornare", c, "auctor pharetra netus libero habitant");
        list.add(dir533);
        c.setCountry_id(132);
        Directors dir534 = new Directors("tristique congue", c, "facilisis vivamus sollicitudin facilisi venenatis");
        list.add(dir534);
        c.setCountry_id(15);
        Directors dir535 = new Directors("porta fusce scelerisque porttitor", c, "praesent cubilia sapien justo curae");
        list.add(dir535);
        c.setCountry_id(89);
        Directors dir536 = new Directors("senectus vehicula maecenas", c, "posuere velit proin tempor mollis");
        list.add(dir536);
        c.setCountry_id(48);
        Directors dir537 = new Directors("augue bibendum nulla ornare", c, "tellus dictumst curabitur nonummy malesuada");
        list.add(dir537);
        c.setCountry_id(6);
        Directors dir538 = new Directors("mattis wisiaenean praesent metus", c, "venenatis consequat lobortis volutpat faucibus");
        list.add(dir538);
        c.setCountry_id(47);
        Directors dir539 = new Directors("netus aliquam dictumst", c, "justo magna class turpis ligula");
        list.add(dir539);
        c.setCountry_id(20);
        Directors dir540 = new Directors("convallis rutrum pellentesque quisque", c, "maecenas primis sagittis taciti cubilia");
        list.add(dir540);
        c.setCountry_id(146);
        Directors dir541 = new Directors("habitasse nulla", c, "sollicitudin proin suspendisse sagittis inceptos");
        list.add(dir541);
        c.setCountry_id(100);
        Directors dir542 = new Directors("ornare posuere tristique litora", c, "placerat varius vehicula nostra morbi");
        list.add(dir542);
        c.setCountry_id(136);
        Directors dir543 = new Directors("tincidunt ligula", c, "augue consectetuer iaculis lectus primis");
        list.add(dir543);
        c.setCountry_id(137);
        Directors dir544 = new Directors("magna sagittis fames", c, "sollicitudin class aptent aliquet commodo");
        list.add(dir544);
        c.setCountry_id(129);
        Directors dir545 = new Directors("tellus magna", c, "adipiscing ligula scelerisque maecenas hendrerit");
        list.add(dir545);
        c.setCountry_id(36);
        Directors dir546 = new Directors("imperdiet tempor", c, "eleifend magna nostra primis maecenas");
        list.add(dir546);
        c.setCountry_id(129);
        Directors dir547 = new Directors("lacus viverra tortor venenatis", c, "facilisis habitasse habitasse euismod vesti");
        list.add(dir547);
        c.setCountry_id(82);
        Directors dir548 = new Directors("faucibus integer", c, "pellentesque rutrum taciti sociosqu porta");
        list.add(dir548);
        c.setCountry_id(125);
        Directors dir549 = new Directors("curae faucibus porta", c, "feugiat taciti vesti consectetuer ultricies");
        list.add(dir549);
        c.setCountry_id(41);
        Directors dir550 = new Directors("malesuada hendrerit class facilisisnunc", c, "lobortis maecenas habitasse sociosqu facilisis");
        list.add(dir550);
        c.setCountry_id(16);
        Directors dir551 = new Directors("ultricies bulum vehicula", c, "bibendum torquent viverra cubilia pretium");
        list.add(dir551);
        c.setCountry_id(75);
        Directors dir552 = new Directors("sociosqu adipiscing", c, "lacinia facilisisnunc nonummy tumst tortor");
        list.add(dir552);
        c.setCountry_id(3);
        Directors dir553 = new Directors("pellentesque justo", c, "aliquam aenean hendrerit vestibulum tempor");
        list.add(dir553);
        c.setCountry_id(82);
        Directors dir554 = new Directors("integer egestas scelerisque netus", c, "bibendum fames nullam cubilia purus");
        list.add(dir554);
        c.setCountry_id(73);
        Directors dir555 = new Directors("ornare dictum porta", c, "metus consequat ornare posuere interdum");
        list.add(dir555);
        c.setCountry_id(130);
        Directors dir556 = new Directors("sagittis aenean ornare senectus", c, "ipsum suspendisse platea litora platea");
        list.add(dir556);
        c.setCountry_id(4);
        Directors dir557 = new Directors("sollicitudin posuere dictumst vesti", c, "hymenaeos vivamus pharetra aenean habitasse");
        list.add(dir557);
        c.setCountry_id(38);
        Directors dir558 = new Directors("consectetuer libero torquent pharetra", c, "tortor tempor curabitur tellus fames");
        list.add(dir558);
        c.setCountry_id(71);
        Directors dir559 = new Directors("fringilla varius netus molestie", c, "bulum convallis praesent placerat consequat");
        list.add(dir559);
        c.setCountry_id(120);
        Directors dir560 = new Directors("scelerisque lectus", c, "commodo rutrum etiam vivamus habitasse");
        list.add(dir560);
        c.setCountry_id(100);
        Directors dir561 = new Directors("dignissim nostra hymenaeos maecenas", c, "porta ipsum aptent turpis class");
        list.add(dir561);
        c.setCountry_id(33);
        Directors dir562 = new Directors("purus dictum dolor", c, "dictum platea molestie torquent velit");
        list.add(dir562);
        c.setCountry_id(48);
        Directors dir563 = new Directors("nulla fermentum", c, "vestibulum donec wisiaenean curae metus");
        list.add(dir563);
        c.setCountry_id(21);
        Directors dir564 = new Directors("hendrerit netus scelerisque", c, "adipiscing dignissim nulla faucibus ipsum");
        list.add(dir564);
        c.setCountry_id(95);
        Directors dir565 = new Directors("hymenaeos consequat sodales", c, "vehicula consequat mauris aliquet litora");
        list.add(dir565);
        c.setCountry_id(77);
        Directors dir566 = new Directors("metus tempus", c, "euismod neque sapien scelerisque lacinia");
        list.add(dir566);
        c.setCountry_id(17);
        Directors dir567 = new Directors("viverra integer curabitur facilisisnunc", c, "mattis malesuada ultrices varius nonummy");
        list.add(dir567);
        c.setCountry_id(68);
        Directors dir568 = new Directors("vestibulum dictumst aliquam", c, "placerat adipiscing curae proin hendrerit");
        list.add(dir568);
        c.setCountry_id(14);
        Directors dir569 = new Directors("felis donec fringilla volutpat", c, "tristique consectetuer volutpat fermentum venenatis");
        list.add(dir569);
        c.setCountry_id(136);
        Directors dir570 = new Directors("habitant molestie curae", c, "dolor elementum lacinia phasellus pulvinar");
        list.add(dir570);
        c.setCountry_id(58);
        Directors dir571 = new Directors("tumst ipsum", c, "quisque mattis semper volutpat morbi");
        list.add(dir571);
        c.setCountry_id(37);
        Directors dir572 = new Directors("mollis fames pulvinar", c, "vehicula bulum tortor sagittis consequat");
        list.add(dir572);
        c.setCountry_id(133);
        Directors dir573 = new Directors("malesuada nulla congue sodales", c, "etiam pretium proin vestibulum dictum");
        list.add(dir573);
        c.setCountry_id(124);
        Directors dir574 = new Directors("cubilia ornare aliquam", c, "eleifend pharetra tempus elementum ipsum");
        list.add(dir574);
        c.setCountry_id(55);
        Directors dir575 = new Directors("morbi dictumst tempus", c, "mauris integer phasellus metus euismod");
        list.add(dir575);
        c.setCountry_id(47);
        Directors dir576 = new Directors("ultricies felis proin vehicula", c, "lacinia class tellus litora hymenaeos");
        list.add(dir576);
        c.setCountry_id(98);
        Directors dir577 = new Directors("bibendum porta torquent primis", c, "inceptos commodo bulum facilisi commodo");
        list.add(dir577);
        c.setCountry_id(10);
        Directors dir578 = new Directors("fusce egestas egestas", c, "sagittis scelerisque volutpat inceptos lacinia");
        list.add(dir578);
        c.setCountry_id(132);
        Directors dir579 = new Directors("habitasse tumst aliquam facilisisnunc", c, "habitasse risus ullamcorper fusce donec");
        list.add(dir579);
        c.setCountry_id(65);
        Directors dir580 = new Directors("sapien sollicitudin pharetra phasellus", c, "vestibulum mollis convallis pretium sollicitudin");
        list.add(dir580);
        c.setCountry_id(71);
        Directors dir581 = new Directors("fames lobortis", c, "velit porttitor pulvinar conubia faucibus");
        list.add(dir581);
        c.setCountry_id(58);
        Directors dir582 = new Directors("habitasse euismod", c, "facilisis mollis nullam sodales laoreet");
        list.add(dir582);
        c.setCountry_id(99);
        Directors dir583 = new Directors("interdum faucibus", c, "vesti imperdiet class lobortis lacus");
        list.add(dir583);
        c.setCountry_id(15);
        Directors dir584 = new Directors("dignissim consectetuer", c, "egestas egestas lorem augue velit");
        list.add(dir584);
        c.setCountry_id(72);
        Directors dir585 = new Directors("volutpat euismod", c, "suspendisse dictum interdum fermentum augue");
        list.add(dir585);
        c.setCountry_id(10);
        Directors dir586 = new Directors("turpis sapien consequat", c, "aliquet iaculis felis facilisisnunc porta");
        list.add(dir586);
        c.setCountry_id(101);
        Directors dir587 = new Directors("facilisisnunc posuere", c, "inceptos scelerisque tellus interdum nulla");
        list.add(dir587);
        c.setCountry_id(85);
        Directors dir588 = new Directors("bulum ultricies", c, "velit wisiaenean ultricies volutpat tortor");
        list.add(dir588);
        c.setCountry_id(47);
        Directors dir589 = new Directors("fermentum ultrices hendrerit", c, "aliquet convallis laoreet fermentum nonummy");
        list.add(dir589);
        c.setCountry_id(97);
        Directors dir590 = new Directors("luctus vestibulum suspendisse", c, "integer velit ipsum fermentum interdum");
        list.add(dir590);
        c.setCountry_id(19);
        Directors dir591 = new Directors("suspendisse consequat sagittis", c, "accumsan molestie egestas lobortis vesti");
        list.add(dir591);
        c.setCountry_id(106);
        Directors dir592 = new Directors("ultricies risus neque", c, "bibendum metus elementum vitae malesuada");
        list.add(dir592);
        c.setCountry_id(39);
        Directors dir593 = new Directors("magna pharetra pretium facilisisnunc", c, "bulum vehicula sociosqu auctor vitae");
        list.add(dir593);
        c.setCountry_id(134);
        Directors dir594 = new Directors("fames euismod", c, "elementum turpis malesuada tincidunt tempus");
        list.add(dir594);
        c.setCountry_id(118);
        Directors dir595 = new Directors("malesuada nulla", c, "euismod nonummy sodales risus morbi");
        list.add(dir595);
        c.setCountry_id(26);
        Directors dir596 = new Directors("lacus dictumst mauris maecenas", c, "convallis dignissim pharetra varius morbi");
        list.add(dir596);
        c.setCountry_id(90);
        Directors dir597 = new Directors("dolor etiam malesuada etiam", c, "pretium primis congue proin praesent");
        list.add(dir597);
        c.setCountry_id(56);
        Directors dir598 = new Directors("imperdiet phasellus", c, "venenatis metus augue litora fermentum");
        list.add(dir598);
        c.setCountry_id(48);
        Directors dir599 = new Directors("mollis ipsum", c, "dignissim ullamcorper metus dignissim nonummy");
        list.add(dir599);
        c.setCountry_id(98);
        Directors dir600 = new Directors("luctus ultrices lacinia pretium", c, "vesti volutpat turpis cursus mattis");
        list.add(dir600);
        c.setCountry_id(77);
        Directors dir601 = new Directors("lacinia etiam", c, "posuere mauris nullam wisiaenean bibendum");
        list.add(dir601);
        c.setCountry_id(29);
        Directors dir602 = new Directors("commodo malesuada", c, "praesent luctus nulla ligula tempus");
        list.add(dir602);
        c.setCountry_id(79);
        Directors dir603 = new Directors("cubilia maecenas", c, "congue facilisis vehicula cubilia viverra");
        list.add(dir603);
        c.setCountry_id(5);
        Directors dir604 = new Directors("nonummy consequat integer", c, "aliquam litora ultrices purus tincidunt");
        list.add(dir604);
        c.setCountry_id(148);
        Directors dir605 = new Directors("convallis tristique", c, "lectus faucibus fames fermentum neque");
        list.add(dir605);
        c.setCountry_id(58);
        Directors dir606 = new Directors("malesuada etiam consequat", c, "faucibus lacinia ipsum ultricies bulum");
        list.add(dir606);
        c.setCountry_id(76);
        Directors dir607 = new Directors("tincidunt consequat augue pulvinar", c, "nulla proin ultricies dictum iaculis");
        list.add(dir607);
        c.setCountry_id(122);
        Directors dir608 = new Directors("vehicula sodales luctus vivamus", c, "lorem interdum justo libero iaculis");
        list.add(dir608);
        c.setCountry_id(130);
        Directors dir609 = new Directors("senectus justo", c, "quisque ultrices convallis molestie ullamcorper");
        list.add(dir609);
        c.setCountry_id(40);
        Directors dir610 = new Directors("laoreet proin consequat", c, "molestie pretium accumsan imperdiet facilisi");
        list.add(dir610);
        c.setCountry_id(12);
        Directors dir611 = new Directors("tempus porta", c, "feugiat tincidunt tempor consequat tempus");
        list.add(dir611);
        c.setCountry_id(1);
        Directors dir612 = new Directors("rutrum euismod vivamus molestie", c, "magna aptent luctus accumsan bulum");
        list.add(dir612);
        c.setCountry_id(105);
        Directors dir613 = new Directors("consectetuer imperdiet porttitor praesent", c, "wisiaenean curae consectetuer pretium facilisi");
        list.add(dir613);
        c.setCountry_id(18);
        Directors dir614 = new Directors("velit purus", c, "egestas morbi sodales habitasse libero");
        list.add(dir614);
        c.setCountry_id(31);
        Directors dir615 = new Directors("cursus proin", c, "aliquam nulla consequat fringilla ullamcorper");
        list.add(dir615);
        c.setCountry_id(5);
        Directors dir616 = new Directors("porta elementum lacinia cubilia", c, "pharetra tempor felis integer accumsan");
        list.add(dir616);
        c.setCountry_id(60);
        Directors dir617 = new Directors("neque vestibulum luctus lacus", c, "pulvinar ultricies curabitur lorem auctor");
        list.add(dir617);
        c.setCountry_id(147);
        Directors dir618 = new Directors("eleifend varius suspendisse", c, "cursus imperdiet felis curae interdum");
        list.add(dir618);
        c.setCountry_id(56);
        Directors dir619 = new Directors("pharetra iaculis", c, "habitasse accumsan inceptos tincidunt suspendisse");
        list.add(dir619);
        c.setCountry_id(61);
        Directors dir620 = new Directors("venenatis sapien bibendum", c, "curae platea habitasse aptent cubilia");
        list.add(dir620);
        c.setCountry_id(132);
        Directors dir621 = new Directors("faucibus mattis", c, "lectus aliquam congue aenean curae");
        list.add(dir621);
        c.setCountry_id(5);
        Directors dir622 = new Directors("congue bulum posuere pellentesque", c, "neque ligula venenatis sagittis interdum");
        list.add(dir622);
        c.setCountry_id(55);
        Directors dir623 = new Directors("ultrices litora lorem nullam", c, "facilisisnunc malesuada adipiscing facilisi habitant");
        list.add(dir623);
        c.setCountry_id(101);
        Directors dir624 = new Directors("curabitur pretium laoreet", c, "sodales ligula neque hendrerit elementum");
        list.add(dir624);
        c.setCountry_id(23);
        Directors dir625 = new Directors("pharetra magna class fusce", c, "litora ultrices venenatis porta justo");
        list.add(dir625);
        c.setCountry_id(68);
        Directors dir626 = new Directors("euismod mollis porta", c, "wisiaenean hymenaeos aptent turpis lorem");
        list.add(dir626);
        c.setCountry_id(123);
        Directors dir627 = new Directors("hendrerit libero habitant aliquam", c, "egestas viverra risus tellus venenatis");
        list.add(dir627);
        c.setCountry_id(118);
        Directors dir628 = new Directors("netus mattis bulum", c, "dictum lobortis tumst molestie fusce");
        list.add(dir628);
        c.setCountry_id(49);
        Directors dir629 = new Directors("sagittis ipsum", c, "ipsum phasellus adipiscing morbi molestie");
        list.add(dir629);
        c.setCountry_id(47);
        Directors dir630 = new Directors("pulvinar inceptos eleifend felis", c, "ultricies lectus nullam ornare lobortis");
        list.add(dir630);
        c.setCountry_id(94);
        Directors dir631 = new Directors("turpis tortor", c, "pharetra vivamus pulvinar vivamus hymenaeos");
        list.add(dir631);
        c.setCountry_id(78);
        Directors dir632 = new Directors("dignissim litora", c, "vivamus nullam accumsan mattis conubia");
        list.add(dir632);
        c.setCountry_id(135);
        Directors dir633 = new Directors("ultrices tumst sociosqu velit", c, "dictum dignissim lacus euismod cubilia");
        list.add(dir633);
        c.setCountry_id(126);
        Directors dir634 = new Directors("iaculis accumsan integer", c, "libero sapien lectus donec porta");
        list.add(dir634);
        c.setCountry_id(139);
        Directors dir635 = new Directors("primis wisiaenean bulum", c, "porttitor taciti donec feugiat varius");
        list.add(dir635);
        c.setCountry_id(64);
        Directors dir636 = new Directors("consequat consectetuer", c, "aliquam neque facilisisnunc fames bibendum");
        list.add(dir636);
        c.setCountry_id(47);
        Directors dir637 = new Directors("fringilla pretium", c, "luctus curae justo venenatis felis");
        list.add(dir637);
        c.setCountry_id(129);
        Directors dir638 = new Directors("dictum fringilla ipsum", c, "tortor vivamus ultricies vitae mollis");
        list.add(dir638);
        c.setCountry_id(50);
        Directors dir639 = new Directors("nonummy etiam posuere", c, "sociosqu tortor consequat curae felis");
        list.add(dir639);
        c.setCountry_id(65);
        Directors dir640 = new Directors("commodo curabitur luctus sociosqu", c, "auctor ornare eleifend ornare laoreet");
        list.add(dir640);
        c.setCountry_id(66);
        Directors dir641 = new Directors("mauris congue", c, "sodales cubilia aptent varius morbi");
        list.add(dir641);
        c.setCountry_id(82);
        Directors dir642 = new Directors("ipsum imperdiet rutrum tortor", c, "lectus facilisisnunc ipsum lacinia faucibus");
        list.add(dir642);
        c.setCountry_id(39);
        Directors dir643 = new Directors("habitant consectetuer eleifend", c, "morbi convallis mattis mollis fermentum");
        list.add(dir643);
        c.setCountry_id(46);
        Directors dir644 = new Directors("wisiaenean luctus", c, "tempor sollicitudin venenatis adipiscing taciti");
        list.add(dir644);
        c.setCountry_id(99);
        Directors dir645 = new Directors("cubilia lacus", c, "vehicula libero vivamus luctus nulla");
        list.add(dir645);
        c.setCountry_id(132);
        Directors dir646 = new Directors("dictumst posuere fusce", c, "vivamus facilisi lacinia fusce ipsum");
        list.add(dir646);
        c.setCountry_id(122);
        Directors dir647 = new Directors("phasellus dictum fermentum dictum", c, "tristique convallis senectus lorem facilisisnunc");
        list.add(dir647);
        c.setCountry_id(135);
        Directors dir648 = new Directors("lacus bulum ultricies semper", c, "lacinia ultrices egestas suspendisse praesent");
        list.add(dir648);
        c.setCountry_id(62);
        Directors dir649 = new Directors("hendrerit tempus sociosqu", c, "vitae wisiaenean nulla porta velit");
        list.add(dir649);
        c.setCountry_id(87);
        Directors dir650 = new Directors("iaculis laoreet", c, "fringilla ultrices tincidunt velit porttitor");
        list.add(dir650);
        c.setCountry_id(118);
        Directors dir651 = new Directors("inceptos tempus", c, "convallis curae volutpat suspendisse ipsum");
        list.add(dir651);
        c.setCountry_id(4);
        Directors dir652 = new Directors("fames lorem consequat", c, "volutpat nonummy litora adipiscing pulvinar");
        list.add(dir652);
        c.setCountry_id(69);
        Directors dir653 = new Directors("iaculis torquent", c, "augue proin pellentesque hymenaeos magna");
        list.add(dir653);
        c.setCountry_id(30);
        Directors dir654 = new Directors("tempor platea", c, "fringilla cubilia morbi eleifend consequat");
        list.add(dir654);
        c.setCountry_id(15);
        Directors dir655 = new Directors("auctor suspendisse wisiaenean", c, "mauris tempus dignissim fringilla commodo");
        list.add(dir655);
        c.setCountry_id(5);
        Directors dir656 = new Directors("felis velit purus", c, "morbi senectus facilisisnunc velit tempus");
        list.add(dir656);
        c.setCountry_id(123);
        Directors dir657 = new Directors("neque netus", c, "fusce etiam laoreet nonummy curabitur");
        list.add(dir657);
        c.setCountry_id(5);
        Directors dir658 = new Directors("donec bulum tempor", c, "tumst habitant donec pulvinar neque");
        list.add(dir658);
        c.setCountry_id(10);
        Directors dir659 = new Directors("vesti wisiaenean", c, "lorem sapien accumsan aliquet suspendisse");
        list.add(dir659);
        c.setCountry_id(36);
        Directors dir660 = new Directors("pellentesque conubia fames", c, "facilisisnunc commodo primis vestibulum dolor");
        list.add(dir660);
        c.setCountry_id(17);
        Directors dir661 = new Directors("risus praesent luctus", c, "facilisi ultricies ultricies hendrerit convallis");
        list.add(dir661);
        c.setCountry_id(88);
        Directors dir662 = new Directors("donec nulla curae", c, "sociosqu vehicula platea faucibus dictum");
        list.add(dir662);
        c.setCountry_id(17);
        Directors dir663 = new Directors("cursus adipiscing", c, "molestie felis dolor pulvinar adipiscing");
        list.add(dir663);
        c.setCountry_id(17);
        Directors dir664 = new Directors("phasellus integer convallis habitant", c, "iaculis ligula facilisisnunc tellus dignissim");
        list.add(dir664);
        c.setCountry_id(57);
        Directors dir665 = new Directors("egestas donec bibendum varius", c, "facilisi aenean consequat aptent elementum");
        list.add(dir665);
        c.setCountry_id(119);
        Directors dir666 = new Directors("faucibus aliquam varius morbi", c, "hendrerit primis convallis vestibulum tempor");
        list.add(dir666);
        c.setCountry_id(61);
        Directors dir667 = new Directors("nullam pretium", c, "pulvinar congue facilisi proin aptent");
        list.add(dir667);
        c.setCountry_id(39);
        Directors dir668 = new Directors("curabitur justo velit adipiscing", c, "phasellus bibendum auctor phasellus ultricies");
        list.add(dir668);
        c.setCountry_id(69);
        Directors dir669 = new Directors("lacinia hendrerit rutrum", c, "porta fringilla vestibulum bulum sociosqu");
        list.add(dir669);
        c.setCountry_id(17);
        Directors dir670 = new Directors("mollis luctus bulum", c, "consectetuer dictumst donec lacus facilisisnunc");
        list.add(dir670);
        c.setCountry_id(61);
        Directors dir671 = new Directors("felis purus facilisi suspendisse", c, "nonummy interdum porta ligula vivamus");
        list.add(dir671);
        c.setCountry_id(13);
        Directors dir672 = new Directors("ultrices habitasse bibendum vivamus", c, "sociosqu scelerisque praesent placerat venenatis");
        list.add(dir672);
        c.setCountry_id(144);
        Directors dir673 = new Directors("platea ipsum", c, "wisiaenean volutpat adipiscing felis habitasse");
        list.add(dir673);
        c.setCountry_id(33);
        Directors dir674 = new Directors("auctor pellentesque curabitur sodales", c, "dictum egestas morbi class inceptos");
        list.add(dir674);
        c.setCountry_id(52);
        Directors dir675 = new Directors("tempus eleifend", c, "integer tempor pulvinar malesuada accumsan");
        list.add(dir675);
        c.setCountry_id(43);
        Directors dir676 = new Directors("facilisisnunc turpis conubia", c, "egestas lacinia tincidunt semper hendrerit");
        list.add(dir676);
        c.setCountry_id(28);
        Directors dir677 = new Directors("tincidunt hendrerit porttitor", c, "lectus turpis nullam sodales tristique");
        list.add(dir677);
        c.setCountry_id(5);
        Directors dir678 = new Directors("aliquet justo nullam", c, "fusce consequat sagittis ipsum integer");
        list.add(dir678);
        c.setCountry_id(21);
        Directors dir679 = new Directors("hymenaeos sociosqu", c, "risus nostra faucibus aenean viverra");
        list.add(dir679);
        c.setCountry_id(69);
        Directors dir680 = new Directors("aenean molestie", c, "varius tempus iaculis maecenas sagittis");
        list.add(dir680);
        c.setCountry_id(143);
        Directors dir681 = new Directors("congue facilisisnunc", c, "dignissim auctor hendrerit conubia tellus");
        list.add(dir681);
        c.setCountry_id(123);
        Directors dir682 = new Directors("vehicula tincidunt", c, "imperdiet fermentum inceptos turpis cubilia");
        list.add(dir682);
        c.setCountry_id(83);
        Directors dir683 = new Directors("aenean habitant facilisis", c, "class viverra ornare phasellus inceptos");
        list.add(dir683);
        c.setCountry_id(148);
        Directors dir684 = new Directors("quisque hymenaeos", c, "nostra nulla adipiscing litora morbi");
        list.add(dir684);
        c.setCountry_id(15);
        Directors dir685 = new Directors("etiam egestas pharetra", c, "mattis metus cursus proin vitae");
        list.add(dir685);
        c.setCountry_id(144);
        Directors dir686 = new Directors("cubilia tellus", c, "pulvinar adipiscing magna commodo nonummy");
        list.add(dir686);
        c.setCountry_id(122);
        Directors dir687 = new Directors("justo congue cursus", c, "fames ipsum malesuada consectetuer facilisisnunc");
        list.add(dir687);
        c.setCountry_id(93);
        Directors dir688 = new Directors("feugiat vehicula faucibus fermentum", c, "iaculis integer justo purus vesti");
        list.add(dir688);
        c.setCountry_id(0);
        Directors dir689 = new Directors("viverra lacus", c, "placerat risus vivamus pretium pellentesque");
        list.add(dir689);
        c.setCountry_id(148);
        Directors dir690 = new Directors("ultrices quisque volutpat", c, "ultricies taciti fringilla nostra ultricies");
        list.add(dir690);
        c.setCountry_id(104);
        Directors dir691 = new Directors("litora bibendum", c, "porttitor maecenas habitasse integer ullamcorper");
        list.add(dir691);
        c.setCountry_id(109);
        Directors dir692 = new Directors("tincidunt fusce aenean ultrices", c, "dignissim risus porttitor fringilla tempor");
        list.add(dir692);
        c.setCountry_id(44);
        Directors dir693 = new Directors("sodales auctor tellus", c, "sollicitudin vestibulum nulla venenatis nonummy");
        list.add(dir693);
        c.setCountry_id(5);
        Directors dir694 = new Directors("tortor pellentesque", c, "velit senectus dictumst feugiat euismod");
        list.add(dir694);
        c.setCountry_id(31);
        Directors dir695 = new Directors("conubia hymenaeos", c, "nonummy iaculis dictum lacus aliquet");
        list.add(dir695);
        c.setCountry_id(35);
        Directors dir696 = new Directors("taciti pellentesque", c, "dolor lacus lobortis phasellus facilisi");
        list.add(dir696);
        c.setCountry_id(6);
        Directors dir697 = new Directors("mauris habitasse", c, "vehicula tincidunt viverra habitasse cursus");
        list.add(dir697);
        c.setCountry_id(61);
        Directors dir698 = new Directors("litora dictumst", c, "etiam consectetuer varius phasellus maecenas");
        list.add(dir698);
        c.setCountry_id(22);
        Directors dir699 = new Directors("vivamus viverra", c, "integer ligula facilisis curae nullam");
        list.add(dir699);
        c.setCountry_id(57);
        Directors dir700 = new Directors("nostra vitae aptent velit", c, "inceptos rutrum purus maecenas habitasse");
        list.add(dir700);
        c.setCountry_id(18);
        Directors dir701 = new Directors("placerat proin praesent", c, "senectus nullam torquent inceptos facilisis");
        list.add(dir701);
        c.setCountry_id(120);
        Directors dir702 = new Directors("auctor suspendisse magna viverra", c, "ipsum magna fames elementum primis");
        list.add(dir702);
        c.setCountry_id(7);
        Directors dir703 = new Directors("senectus tristique etiam", c, "fermentum libero habitasse magna vehicula");
        list.add(dir703);
        c.setCountry_id(127);
        Directors dir704 = new Directors("pretium felis curabitur", c, "faucibus feugiat cubilia feugiat purus");
        list.add(dir704);
        c.setCountry_id(145);
        Directors dir705 = new Directors("vesti ipsum", c, "senectus morbi consequat magna hendrerit");
        list.add(dir705);
        c.setCountry_id(88);
        Directors dir706 = new Directors("nulla consectetuer phasellus fermentum", c, "mollis molestie accumsan adipiscing tristique");
        list.add(dir706);
        c.setCountry_id(29);
        Directors dir707 = new Directors("senectus lectus ligula pharetra", c, "convallis vivamus taciti hymenaeos torquent");
        list.add(dir707);
        c.setCountry_id(3);
        Directors dir708 = new Directors("lobortis curae vitae egestas", c, "dictum dictumst commodo curabitur accumsan");
        list.add(dir708);
        c.setCountry_id(102);
        Directors dir709 = new Directors("augue vitae", c, "hymenaeos pharetra curabitur nullam ornare");
        list.add(dir709);
        c.setCountry_id(55);
        Directors dir710 = new Directors("ligula nostra", c, "torquent fusce vitae aliquet pretium");
        list.add(dir710);
        c.setCountry_id(144);
        Directors dir711 = new Directors("proin praesent felis", c, "purus tumst congue adipiscing taciti");
        list.add(dir711);
        c.setCountry_id(143);
        Directors dir712 = new Directors("suspendisse habitasse fringilla", c, "purus faucibus volutpat senectus vitae");
        list.add(dir712);
        c.setCountry_id(99);
        Directors dir713 = new Directors("maecenas facilisisnunc dignissim", c, "semper mauris sociosqu conubia morbi");
        list.add(dir713);
        c.setCountry_id(138);
        Directors dir714 = new Directors("convallis volutpat tumst sagittis", c, "ligula ultrices wisiaenean quisque donec");
        list.add(dir714);
        c.setCountry_id(96);
        Directors dir715 = new Directors("fringilla proin torquent", c, "conubia dictumst proin ullamcorper augue");
        list.add(dir715);
        c.setCountry_id(20);
        Directors dir716 = new Directors("purus volutpat facilisi", c, "porttitor tumst tempus auctor pharetra");
        list.add(dir716);
        c.setCountry_id(149);
        Directors dir717 = new Directors("accumsan senectus", c, "senectus dictumst facilisisnunc aliquet egestas");
        list.add(dir717);
        c.setCountry_id(115);
        Directors dir718 = new Directors("volutpat taciti consequat pellentesque", c, "fermentum consequat interdum vestibulum inceptos");
        list.add(dir718);
        c.setCountry_id(15);
        Directors dir719 = new Directors("conubia facilisisnunc luctus", c, "risus libero conubia posuere lectus");
        list.add(dir719);
        c.setCountry_id(12);
        Directors dir720 = new Directors("cubilia nostra", c, "curae class pulvinar venenatis ullamcorper");
        list.add(dir720);
        c.setCountry_id(31);
        Directors dir721 = new Directors("vestibulum luctus", c, "tincidunt vestibulum porttitor vivamus feugiat");
        list.add(dir721);
        c.setCountry_id(91);
        Directors dir722 = new Directors("facilisisnunc dolor curabitur lacus", c, "etiam dolor vivamus pharetra ullamcorper");
        list.add(dir722);
        c.setCountry_id(51);
        Directors dir723 = new Directors("lobortis magna fermentum nulla", c, "semper phasellus vitae dictum lobortis");
        list.add(dir723);
        c.setCountry_id(138);
        Directors dir724 = new Directors("sociosqu pharetra varius nonummy", c, "nonummy proin sollicitudin lacinia interdum");
        list.add(dir724);
        c.setCountry_id(60);
        Directors dir725 = new Directors("cursus netus", c, "fringilla tempor sociosqu faucibus luctus");
        list.add(dir725);
        c.setCountry_id(137);
        Directors dir726 = new Directors("egestas aliquet ultrices", c, "hendrerit tristique venenatis donec dignissim");
        list.add(dir726);
        c.setCountry_id(28);
        Directors dir727 = new Directors("elementum porttitor nulla", c, "aptent senectus felis inceptos facilisisnunc");
        list.add(dir727);
        c.setCountry_id(0);
        Directors dir728 = new Directors("faucibus mattis curabitur lacinia", c, "justo facilisi euismod habitasse volutpat");
        list.add(dir728);
        c.setCountry_id(86);
        Directors dir729 = new Directors("dictumst hymenaeos dolor", c, "nulla ullamcorper tortor consectetuer lobortis");
        list.add(dir729);
        c.setCountry_id(38);
        Directors dir730 = new Directors("facilisis imperdiet porta", c, "primis pharetra iaculis fusce maecenas");
        list.add(dir730);
        c.setCountry_id(115);
        Directors dir731 = new Directors("netus lectus velit", c, "dolor tumst ligula torquent porta");
        list.add(dir731);
        c.setCountry_id(56);
        Directors dir732 = new Directors("consequat nullam sodales facilisi", c, "sagittis vehicula nostra adipiscing maecenas");
        list.add(dir732);
        c.setCountry_id(54);
        Directors dir733 = new Directors("tristique etiam velit nulla", c, "ornare venenatis imperdiet rutrum pellentesque");
        list.add(dir733);
        c.setCountry_id(32);
        Directors dir734 = new Directors("lacinia consectetuer", c, "imperdiet volutpat netus nulla mattis");
        list.add(dir734);
        c.setCountry_id(11);
        Directors dir735 = new Directors("cursus consectetuer hymenaeos", c, "aliquam tincidunt pellentesque feugiat ullamcorper");
        list.add(dir735);
        c.setCountry_id(70);
        Directors dir736 = new Directors("imperdiet sociosqu ipsum", c, "sagittis fringilla lobortis feugiat metus");
        list.add(dir736);
        c.setCountry_id(98);
        Directors dir737 = new Directors("maecenas tortor dictum", c, "nulla mollis semper vesti hendrerit");
        list.add(dir737);
        c.setCountry_id(2);
        Directors dir738 = new Directors("phasellus aenean", c, "egestas sapien nulla congue ullamcorper");
        list.add(dir738);
        c.setCountry_id(134);
        Directors dir739 = new Directors("mollis ullamcorper", c, "feugiat semper fusce cursus viverra");
        list.add(dir739);
        c.setCountry_id(78);
        Directors dir740 = new Directors("tempor facilisi taciti auctor", c, "lectus torquent velit ultrices senectus");
        list.add(dir740);
        c.setCountry_id(55);
        Directors dir741 = new Directors("conubia taciti praesent", c, "molestie pellentesque curae dignissim viverra");
        list.add(dir741);
        c.setCountry_id(23);
        Directors dir742 = new Directors("dictum posuere hendrerit", c, "vitae inceptos ligula risus aliquam");
        list.add(dir742);
        c.setCountry_id(130);
        Directors dir743 = new Directors("sollicitudin facilisis maecenas suspendisse", c, "varius tellus pharetra bibendum nulla");
        list.add(dir743);
        c.setCountry_id(129);
        Directors dir744 = new Directors("vitae posuere congue venenatis", c, "fusce praesent aenean accumsan aenean");
        list.add(dir744);
        c.setCountry_id(42);
        Directors dir745 = new Directors("tortor magna maecenas mattis", c, "bibendum lacus aenean nulla adipiscing");
        list.add(dir745);
        c.setCountry_id(55);
        Directors dir746 = new Directors("iaculis aenean", c, "aenean elementum consequat ligula tumst");
        list.add(dir746);
        c.setCountry_id(112);
        Directors dir747 = new Directors("cursus hymenaeos ultrices", c, "platea ipsum mollis turpis convallis");
        list.add(dir747);
        c.setCountry_id(71);
        Directors dir748 = new Directors("fusce tempor", c, "mollis ultricies posuere tumst facilisis");
        list.add(dir748);
        c.setCountry_id(146);
        Directors dir749 = new Directors("bulum quisque", c, "convallis malesuada lacinia varius vestibulum");
        list.add(dir749);
        c.setCountry_id(131);
        Directors dir750 = new Directors("tempor dictum senectus turpis", c, "primis commodo consequat vehicula libero");
        list.add(dir750);
        c.setCountry_id(89);
        Directors dir751 = new Directors("mattis sodales nullam interdum", c, "rutrum sociosqu nonummy scelerisque aptent");
        list.add(dir751);
        c.setCountry_id(132);
        Directors dir752 = new Directors("libero tincidunt", c, "volutpat viverra facilisi donec accumsan");
        list.add(dir752);
        c.setCountry_id(106);
        Directors dir753 = new Directors("conubia dignissim fringilla pharetra", c, "ornare risus fermentum curae porta");
        list.add(dir753);
        c.setCountry_id(58);
        Directors dir754 = new Directors("accumsan senectus ligula mollis", c, "curae venenatis risus luctus tortor");
        list.add(dir754);
        c.setCountry_id(107);
        Directors dir755 = new Directors("dignissim netus purus", c, "ornare tellus proin wisiaenean volutpat");
        list.add(dir755);
        c.setCountry_id(137);
        Directors dir756 = new Directors("libero posuere vesti aptent", c, "luctus proin eleifend lectus purus");
        list.add(dir756);
        c.setCountry_id(86);
        Directors dir757 = new Directors("vitae volutpat magna", c, "platea ultrices donec curabitur fusce");
        list.add(dir757);
        c.setCountry_id(19);
        Directors dir758 = new Directors("tellus mattis", c, "justo felis tortor neque malesuada");
        list.add(dir758);
        c.setCountry_id(49);
        Directors dir759 = new Directors("feugiat nostra mauris maecenas", c, "platea curabitur euismod convallis habitant");
        list.add(dir759);
        c.setCountry_id(127);
        Directors dir760 = new Directors("integer facilisi consectetuer", c, "senectus ipsum purus torquent phasellus");
        list.add(dir760);
        c.setCountry_id(50);
        Directors dir761 = new Directors("fames inceptos cubilia", c, "inceptos sapien wisiaenean aptent maecenas");
        list.add(dir761);
        c.setCountry_id(63);
        Directors dir762 = new Directors("proin eleifend sollicitudin ullamcorper", c, "auctor aptent imperdiet hymenaeos elementum");
        list.add(dir762);
        c.setCountry_id(0);
        Directors dir763 = new Directors("libero inceptos tincidunt", c, "auctor hymenaeos dolor nulla augue");
        list.add(dir763);
        c.setCountry_id(77);
        Directors dir764 = new Directors("imperdiet ornare inceptos", c, "dictumst facilisisnunc convallis cursus aenean");
        list.add(dir764);
        c.setCountry_id(40);
        Directors dir765 = new Directors("adipiscing interdum ipsum", c, "lobortis lobortis habitasse vivamus tortor");
        list.add(dir765);
        c.setCountry_id(110);
        Directors dir766 = new Directors("lobortis tempor luctus", c, "conubia convallis morbi pellentesque imperdiet");
        list.add(dir766);
        c.setCountry_id(5);
        Directors dir767 = new Directors("litora litora maecenas", c, "maecenas placerat sociosqu pellentesque laoreet");
        list.add(dir767);
        c.setCountry_id(104);
        Directors dir768 = new Directors("tellus sagittis pharetra", c, "justo eleifend fringilla imperdiet laoreet");
        list.add(dir768);
        c.setCountry_id(29);
        Directors dir769 = new Directors("ligula pharetra praesent dolor", c, "curae euismod tortor convallis fermentum");
        list.add(dir769);
        c.setCountry_id(40);
        Directors dir770 = new Directors("tellus vehicula pharetra lorem", c, "molestie primis facilisi malesuada tumst");
        list.add(dir770);
        c.setCountry_id(75);
        Directors dir771 = new Directors("donec cubilia lobortis risus", c, "magna velit vivamus aliquam venenatis");
        list.add(dir771);
        c.setCountry_id(128);
        Directors dir772 = new Directors("lacinia aenean sociosqu elementum", c, "pulvinar malesuada donec tristique proin");
        list.add(dir772);
        c.setCountry_id(24);
        Directors dir773 = new Directors("viverra nulla viverra", c, "rutrum auctor proin egestas vesti");
        list.add(dir773);
        c.setCountry_id(99);
        Directors dir774 = new Directors("ornare ipsum aliquam", c, "lectus laoreet turpis lorem class");
        list.add(dir774);
        c.setCountry_id(106);
        Directors dir775 = new Directors("semper commodo porta", c, "vitae facilisisnunc lacinia pharetra sollicitudin");
        list.add(dir775);
        c.setCountry_id(36);
        Directors dir776 = new Directors("justo egestas consectetuer", c, "varius varius egestas neque adipiscing");
        list.add(dir776);
        c.setCountry_id(146);
        Directors dir777 = new Directors("scelerisque fusce litora", c, "posuere tincidunt vesti bibendum quisque");
        list.add(dir777);
        c.setCountry_id(86);
        Directors dir778 = new Directors("praesent cubilia", c, "netus fames litora pharetra nulla");
        list.add(dir778);
        c.setCountry_id(30);
        Directors dir779 = new Directors("magna dictumst suspendisse", c, "aliquam purus rutrum porta nullam");
        list.add(dir779);
        c.setCountry_id(77);
        Directors dir780 = new Directors("lacus porttitor", c, "semper purus curae venenatis sapien");
        list.add(dir780);
        c.setCountry_id(67);
        Directors dir781 = new Directors("mollis inceptos lectus", c, "mauris hendrerit velit morbi bibendum");
        list.add(dir781);
        c.setCountry_id(146);
        Directors dir782 = new Directors("morbi ullamcorper vestibulum", c, "sapien commodo lectus vestibulum facilisis");
        list.add(dir782);
        c.setCountry_id(59);
        Directors dir783 = new Directors("wisiaenean hendrerit", c, "facilisi pretium vesti malesuada tristique");
        list.add(dir783);
        c.setCountry_id(103);
        Directors dir784 = new Directors("adipiscing vitae cursus", c, "dignissim augue nulla bulum sociosqu");
        list.add(dir784);
        c.setCountry_id(148);
        Directors dir785 = new Directors("quisque nullam curabitur accumsan", c, "laoreet velit tellus bulum vitae");
        list.add(dir785);
        c.setCountry_id(97);
        Directors dir786 = new Directors("vivamus lobortis donec", c, "cursus vivamus pulvinar commodo aliquet");
        list.add(dir786);
        c.setCountry_id(84);
        Directors dir787 = new Directors("fames primis phasellus tincidunt", c, "placerat lobortis ultricies dignissim luctus");
        list.add(dir787);
        c.setCountry_id(114);
        Directors dir788 = new Directors("aenean porttitor", c, "auctor porta ultricies lobortis facilisisnunc");
        list.add(dir788);
        c.setCountry_id(118);
        Directors dir789 = new Directors("taciti ipsum", c, "conubia platea aenean sollicitudin vestibulum");
        list.add(dir789);
        c.setCountry_id(3);
        Directors dir790 = new Directors("venenatis porta aliquet", c, "libero pulvinar inceptos lobortis porta");
        list.add(dir790);
        c.setCountry_id(74);
        Directors dir791 = new Directors("velit cubilia curae", c, "volutpat molestie fringilla platea wisiaenean");
        list.add(dir791);
        c.setCountry_id(16);
        Directors dir792 = new Directors("rutrum ornare", c, "dolor hendrerit quisque bibendum imperdiet");
        list.add(dir792);
        c.setCountry_id(6);
        Directors dir793 = new Directors("habitant sapien lorem", c, "consectetuer ipsum lacinia proin porta");
        list.add(dir793);
        c.setCountry_id(59);
        Directors dir794 = new Directors("fringilla dictum class vivamus", c, "vehicula ornare ipsum class litora");
        list.add(dir794);
        c.setCountry_id(135);
        Directors dir795 = new Directors("lorem neque praesent", c, "hymenaeos inceptos purus tempor conubia");
        list.add(dir795);
        c.setCountry_id(73);
        Directors dir796 = new Directors("bibendum fusce mauris", c, "nulla sociosqu mauris vehicula cursus");
        list.add(dir796);
        c.setCountry_id(26);
        Directors dir797 = new Directors("imperdiet ultrices commodo malesuada", c, "sollicitudin iaculis tempus faucibus litora");
        list.add(dir797);
        c.setCountry_id(99);
        Directors dir798 = new Directors("morbi metus praesent lacinia", c, "vitae posuere phasellus iaculis varius");
        list.add(dir798);
        c.setCountry_id(132);
        Directors dir799 = new Directors("aptent primis malesuada integer", c, "commodo accumsan vitae ligula cubilia");
        list.add(dir799);
        c.setCountry_id(130);
        Directors dir800 = new Directors("suspendisse taciti", c, "imperdiet ligula curae congue faucibus");
        list.add(dir800);
        c.setCountry_id(68);
        Directors dir801 = new Directors("netus congue bibendum", c, "conubia wisiaenean quisque aptent eleifend");
        list.add(dir801);
        c.setCountry_id(82);
        Directors dir802 = new Directors("magna etiam nullam", c, "pharetra luctus bibendum tempor suspendisse");
        list.add(dir802);
        c.setCountry_id(56);
        Directors dir803 = new Directors("porttitor inceptos laoreet vehicula", c, "maecenas facilisisnunc habitant fermentum litora");
        list.add(dir803);
        c.setCountry_id(148);
        Directors dir804 = new Directors("senectus vitae neque", c, "pharetra ligula class aptent fusce");
        list.add(dir804);
        c.setCountry_id(139);
        Directors dir805 = new Directors("lobortis nostra", c, "cubilia varius porta habitasse elementum");
        list.add(dir805);
        c.setCountry_id(13);
        Directors dir806 = new Directors("aliquet facilisi", c, "facilisis mauris aliquet augue phasellus");
        list.add(dir806);
        c.setCountry_id(58);
        Directors dir807 = new Directors("senectus mauris conubia porta", c, "tellus iaculis fusce turpis mollis");
        list.add(dir807);
        c.setCountry_id(73);
        Directors dir808 = new Directors("proin porta pharetra", c, "lorem lorem malesuada taciti tincidunt");
        list.add(dir808);
        c.setCountry_id(39);
        Directors dir809 = new Directors("habitant vesti lectus", c, "morbi vestibulum auctor vestibulum consequat");
        list.add(dir809);
        c.setCountry_id(138);
        Directors dir810 = new Directors("mattis litora", c, "maecenas vestibulum praesent facilisisnunc semper");
        list.add(dir810);
        c.setCountry_id(66);
        Directors dir811 = new Directors("fringilla aliquam accumsan mollis", c, "bulum torquent bulum fames nulla");
        list.add(dir811);
        c.setCountry_id(20);
        Directors dir812 = new Directors("purus vesti nonummy tempor", c, "euismod cubilia rutrum velit vesti");
        list.add(dir812);
        c.setCountry_id(125);
        Directors dir813 = new Directors("molestie fringilla imperdiet vesti", c, "donec dolor mollis molestie quisque");
        list.add(dir813);
        c.setCountry_id(52);
        Directors dir814 = new Directors("metus viverra auctor", c, "ullamcorper euismod magna lectus hymenaeos");
        list.add(dir814);
        c.setCountry_id(21);
        Directors dir815 = new Directors("netus fermentum eleifend", c, "ornare conubia mauris magna hymenaeos");
        list.add(dir815);
        c.setCountry_id(49);
        Directors dir816 = new Directors("suspendisse magna litora", c, "class lacus vivamus venenatis donec");
        list.add(dir816);
        c.setCountry_id(123);
        Directors dir817 = new Directors("nostra feugiat bibendum conubia", c, "eleifend facilisi pellentesque conubia metus");
        list.add(dir817);
        c.setCountry_id(120);
        Directors dir818 = new Directors("egestas lacus ultricies habitant", c, "rutrum ipsum quisque dictum tincidunt");
        list.add(dir818);
        c.setCountry_id(41);
        Directors dir819 = new Directors("pulvinar ultrices velit placerat", c, "dignissim facilisi senectus turpis platea");
        list.add(dir819);
        c.setCountry_id(58);
        Directors dir820 = new Directors("felis mattis habitant", c, "nonummy purus hendrerit aliquet porttitor");
        list.add(dir820);
        c.setCountry_id(44);
        Directors dir821 = new Directors("mollis facilisi adipiscing", c, "sociosqu suspendisse mauris accumsan sollicitudin");
        list.add(dir821);
        c.setCountry_id(95);
        Directors dir822 = new Directors("aenean viverra", c, "porta imperdiet etiam proin facilisis");
        list.add(dir822);
        c.setCountry_id(35);
        Directors dir823 = new Directors("pellentesque iaculis justo", c, "ligula mattis justo quisque dignissim");
        list.add(dir823);
        c.setCountry_id(19);
        Directors dir824 = new Directors("egestas congue", c, "ligula maecenas bulum augue conubia");
        list.add(dir824);
        c.setCountry_id(127);
        Directors dir825 = new Directors("tempor sollicitudin risus", c, "neque fames lectus litora torquent");
        list.add(dir825);
        c.setCountry_id(50);
        Directors dir826 = new Directors("lacus mauris tempus", c, "placerat dictumst viverra volutpat senectus");
        list.add(dir826);
        c.setCountry_id(67);
        Directors dir827 = new Directors("habitant dictum", c, "aliquam taciti tempor imperdiet tempor");
        list.add(dir827);
        c.setCountry_id(69);
        Directors dir828 = new Directors("consequat tempus", c, "neque nulla tincidunt risus bibendum");
        list.add(dir828);
        c.setCountry_id(51);
        Directors dir829 = new Directors("maecenas bibendum ultrices", c, "pretium dictum sapien wisiaenean cubilia");
        list.add(dir829);
        c.setCountry_id(95);
        Directors dir830 = new Directors("phasellus porttitor", c, "congue torquent nulla dictumst scelerisque");
        list.add(dir830);
        c.setCountry_id(36);
        Directors dir831 = new Directors("pharetra tellus phasellus", c, "iaculis imperdiet metus lacus dictum");
        list.add(dir831);
        c.setCountry_id(17);
        Directors dir832 = new Directors("mattis purus aenean", c, "consectetuer volutpat cursus ipsum donec");
        list.add(dir832);
        c.setCountry_id(33);
        Directors dir833 = new Directors("facilisisnunc nonummy", c, "vestibulum neque augue turpis nulla");
        list.add(dir833);
        c.setCountry_id(136);
        Directors dir834 = new Directors("nostra netus", c, "ultrices etiam varius torquent etiam");
        list.add(dir834);
        c.setCountry_id(140);
        Directors dir835 = new Directors("aenean viverra taciti convallis", c, "nullam euismod posuere metus pharetra");
        list.add(dir835);
        c.setCountry_id(150);
        Directors dir836 = new Directors("pharetra sollicitudin nostra", c, "interdum nullam sollicitudin tincidunt morbi");
        list.add(dir836);
        c.setCountry_id(50);
        Directors dir837 = new Directors("imperdiet lobortis felis", c, "consequat vivamus dignissim nostra ultrices");
        list.add(dir837);
        c.setCountry_id(35);
        Directors dir838 = new Directors("euismod laoreet tincidunt morbi", c, "tempor accumsan vestibulum vestibulum tortor");
        list.add(dir838);
        c.setCountry_id(34);
        Directors dir839 = new Directors("netus hendrerit fermentum", c, "pharetra morbi nullam placerat hendrerit");
        list.add(dir839);
        c.setCountry_id(107);
        Directors dir840 = new Directors("lacus elementum", c, "lacinia ipsum porta varius adipiscing");
        list.add(dir840);
        c.setCountry_id(55);
        Directors dir841 = new Directors("taciti phasellus neque posuere", c, "vesti conubia bulum sapien etiam");
        list.add(dir841);
        c.setCountry_id(49);
        Directors dir842 = new Directors("pharetra bulum nonummy", c, "feugiat laoreet habitasse aliquet malesuada");
        list.add(dir842);
        c.setCountry_id(118);
        Directors dir843 = new Directors("vitae mauris", c, "lacus curabitur inceptos neque quisque");
        list.add(dir843);
        c.setCountry_id(143);
        Directors dir844 = new Directors("vivamus sapien", c, "dignissim pulvinar convallis lobortis laoreet");
        list.add(dir844);
        c.setCountry_id(75);
        Directors dir845 = new Directors("rutrum nullam euismod conubia", c, "placerat viverra posuere porttitor platea");
        list.add(dir845);
        c.setCountry_id(75);
        Directors dir846 = new Directors("praesent viverra", c, "auctor bibendum vitae neque nullam");
        list.add(dir846);
        c.setCountry_id(58);
        Directors dir847 = new Directors("pretium tincidunt fusce habitasse", c, "auctor morbi adipiscing mattis scelerisque");
        list.add(dir847);
        c.setCountry_id(22);
        Directors dir848 = new Directors("imperdiet ultrices", c, "libero dolor tincidunt ullamcorper lectus");
        list.add(dir848);
        c.setCountry_id(107);
        Directors dir849 = new Directors("class phasellus", c, "consectetuer volutpat cursus ultricies nonummy");
        list.add(dir849);
        c.setCountry_id(6);
        Directors dir850 = new Directors("velit vehicula velit lectus", c, "elementum taciti cubilia pharetra porttitor");
        list.add(dir850);
        c.setCountry_id(132);
        Directors dir851 = new Directors("habitasse nonummy aliquet", c, "tumst inceptos eleifend mollis mollis");
        list.add(dir851);
        c.setCountry_id(21);
        Directors dir852 = new Directors("scelerisque morbi dictum", c, "habitasse netus auctor ipsum congue");
        list.add(dir852);
        c.setCountry_id(113);
        Directors dir853 = new Directors("varius lectus dictumst", c, "sollicitudin eleifend congue maecenas praesent");
        list.add(dir853);
        c.setCountry_id(67);
        Directors dir854 = new Directors("platea suspendisse platea magna", c, "pretium litora laoreet consectetuer egestas");
        list.add(dir854);
        c.setCountry_id(51);
        Directors dir855 = new Directors("sollicitudin suspendisse dignissim convallis", c, "tempor mattis auctor netus conubia");
        list.add(dir855);
        c.setCountry_id(102);
        Directors dir856 = new Directors("bibendum aliquam ultricies hymenaeos", c, "faucibus mauris vesti libero etiam");
        list.add(dir856);
        c.setCountry_id(1);
        Directors dir857 = new Directors("praesent justo", c, "lacinia fames imperdiet tellus tristique");
        list.add(dir857);
        c.setCountry_id(145);
        Directors dir858 = new Directors("euismod velit", c, "cubilia malesuada tumst laoreet convallis");
        list.add(dir858);
        c.setCountry_id(111);
        Directors dir859 = new Directors("vehicula nullam bibendum", c, "consectetuer wisiaenean laoreet taciti senectus");
        list.add(dir859);
        c.setCountry_id(106);
        Directors dir860 = new Directors("habitant curabitur neque", c, "tristique ullamcorper facilisi commodo elementum");
        list.add(dir860);
        c.setCountry_id(10);
        Directors dir861 = new Directors("pellentesque hymenaeos adipiscing", c, "lobortis faucibus aenean porttitor rutrum");
        list.add(dir861);
        c.setCountry_id(83);
        Directors dir862 = new Directors("lacinia adipiscing", c, "magna euismod conubia congue cubilia");
        list.add(dir862);
        c.setCountry_id(22);
        Directors dir863 = new Directors("inceptos rutrum", c, "scelerisque euismod suspendisse viverra sodales");
        list.add(dir863);
        c.setCountry_id(8);
        Directors dir864 = new Directors("porta proin torquent", c, "maecenas sollicitudin risus volutpat aptent");
        list.add(dir864);
        c.setCountry_id(149);
        Directors dir865 = new Directors("mattis cubilia ullamcorper luctus", c, "laoreet habitasse fames elementum augue");
        list.add(dir865);
        c.setCountry_id(32);
        Directors dir866 = new Directors("auctor iaculis facilisis", c, "fermentum sociosqu rutrum habitant ullamcorper");
        list.add(dir866);
        c.setCountry_id(138);
        Directors dir867 = new Directors("tempus tortor tincidunt mauris", c, "metus laoreet justo convallis lectus");
        list.add(dir867);
        c.setCountry_id(113);
        Directors dir868 = new Directors("lacinia facilisi", c, "cubilia congue pellentesque lacus porttitor");
        list.add(dir868);
        c.setCountry_id(23);
        Directors dir869 = new Directors("facilisis aliquet nonummy pharetra", c, "facilisis dictumst sagittis habitant ornare");
        list.add(dir869);
        c.setCountry_id(57);
        Directors dir870 = new Directors("tempus tumst", c, "maecenas venenatis tempus tempor dictumst");
        list.add(dir870);
        c.setCountry_id(123);
        Directors dir871 = new Directors("auctor tempus ultricies", c, "lacinia nulla nullam curabitur proin");
        list.add(dir871);
        c.setCountry_id(62);
        Directors dir872 = new Directors("platea proin bulum aliquet", c, "lectus bibendum risus placerat convallis");
        list.add(dir872);
        c.setCountry_id(16);
        Directors dir873 = new Directors("vestibulum malesuada velit nostra", c, "ornare etiam neque molestie dictum");
        list.add(dir873);
        c.setCountry_id(55);
        Directors dir874 = new Directors("nulla congue vehicula scelerisque", c, "luctus curae accumsan vestibulum porttitor");
        list.add(dir874);
        c.setCountry_id(146);
        Directors dir875 = new Directors("fusce vivamus faucibus fermentum", c, "laoreet fames tempor neque facilisis");
        list.add(dir875);
        c.setCountry_id(26);
        Directors dir876 = new Directors("consequat platea", c, "curabitur fringilla malesuada fusce tumst");
        list.add(dir876);
        c.setCountry_id(29);
        Directors dir877 = new Directors("curae vitae taciti nostra", c, "ipsum aliquet dictum varius bibendum");
        list.add(dir877);
        c.setCountry_id(42);
        Directors dir878 = new Directors("iaculis nostra convallis", c, "platea malesuada dignissim sagittis facilisi");
        list.add(dir878);
        c.setCountry_id(95);
        Directors dir879 = new Directors("dictumst mollis", c, "donec consequat convallis dignissim aptent");
        list.add(dir879);
        c.setCountry_id(7);
        Directors dir880 = new Directors("quisque justo aliquet", c, "semper sapien primis lectus dictumst");
        list.add(dir880);
        c.setCountry_id(145);
        Directors dir881 = new Directors("sodales bibendum sociosqu rutrum", c, "vestibulum dictumst proin auctor tellus");
        list.add(dir881);
        c.setCountry_id(81);
        Directors dir882 = new Directors("primis tumst", c, "primis sollicitudin tumst maecenas mollis");
        list.add(dir882);
        c.setCountry_id(82);
        Directors dir883 = new Directors("aliquet elementum laoreet", c, "curabitur class donec lacus libero");
        list.add(dir883);
        c.setCountry_id(118);
        Directors dir884 = new Directors("vehicula sapien sollicitudin", c, "habitasse cubilia felis senectus lacinia");
        list.add(dir884);
        c.setCountry_id(112);
        Directors dir885 = new Directors("vestibulum tellus lacinia integer", c, "fringilla euismod torquent euismod tumst");
        list.add(dir885);
        c.setCountry_id(103);
        Directors dir886 = new Directors("pulvinar habitant vestibulum", c, "libero luctus magna dolor euismod");
        list.add(dir886);
        c.setCountry_id(1);
        Directors dir887 = new Directors("pharetra dictumst vestibulum nostra", c, "dictumst tincidunt porttitor rutrum lacus");
        list.add(dir887);
        c.setCountry_id(14);
        Directors dir888 = new Directors("varius mollis", c, "curabitur porta dictumst pulvinar viverra");
        list.add(dir888);
        c.setCountry_id(1);
        Directors dir889 = new Directors("litora proin lectus felis", c, "primis turpis egestas libero facilisi");
        list.add(dir889);
        c.setCountry_id(130);
        Directors dir890 = new Directors("phasellus sollicitudin etiam consectetuer", c, "sollicitudin commodo molestie fusce iaculis");
        list.add(dir890);
        c.setCountry_id(93);
        Directors dir891 = new Directors("nulla vesti purus taciti", c, "eleifend lectus proin bibendum volutpat");
        list.add(dir891);
        c.setCountry_id(106);
        Directors dir892 = new Directors("suspendisse vitae", c, "convallis egestas felis torquent nostra");
        list.add(dir892);
        c.setCountry_id(83);
        Directors dir893 = new Directors("rutrum luctus venenatis curabitur", c, "varius ultricies malesuada lacinia neque");
        list.add(dir893);
        c.setCountry_id(140);
        Directors dir894 = new Directors("euismod suspendisse pretium semper", c, "posuere justo nullam facilisi praesent");
        list.add(dir894);
        c.setCountry_id(25);
        Directors dir895 = new Directors("fames lacinia praesent", c, "quisque egestas porttitor libero volutpat");
        list.add(dir895);
        c.setCountry_id(136);
        Directors dir896 = new Directors("ornare aliquet felis convallis", c, "litora pretium ipsum vesti curae");
        list.add(dir896);
        c.setCountry_id(28);
        Directors dir897 = new Directors("aliquam augue facilisi etiam", c, "mattis posuere tincidunt ultricies vehicula");
        list.add(dir897);
        c.setCountry_id(95);
        Directors dir898 = new Directors("felis adipiscing semper", c, "habitasse dignissim porta platea pellentesque");
        list.add(dir898);
        c.setCountry_id(34);
        Directors dir899 = new Directors("fusce lacinia", c, "vehicula iaculis vivamus nullam torquent");
        list.add(dir899);
        c.setCountry_id(30);
        Directors dir900 = new Directors("libero libero vehicula", c, "fusce aliquet netus platea nullam");
        list.add(dir900);
        c.setCountry_id(13);
        Directors dir901 = new Directors("senectus volutpat porta", c, "inceptos viverra nostra mattis adipiscing");
        list.add(dir901);
        c.setCountry_id(134);
        Directors dir902 = new Directors("tempor lacus etiam tempor", c, "tristique sodales curae senectus cubilia");
        list.add(dir902);
        c.setCountry_id(48);
        Directors dir903 = new Directors("porttitor lobortis", c, "scelerisque pulvinar purus tortor lobortis");
        list.add(dir903);
        c.setCountry_id(134);
        Directors dir904 = new Directors("semper tumst", c, "adipiscing accumsan porta molestie tempor");
        list.add(dir904);
        c.setCountry_id(39);
        Directors dir905 = new Directors("placerat fames scelerisque habitasse", c, "bibendum torquent facilisis nonummy mollis");
        list.add(dir905);
        c.setCountry_id(124);
        Directors dir906 = new Directors("nulla sagittis ullamcorper", c, "quisque mattis interdum porta tristique");
        list.add(dir906);
        c.setCountry_id(3);
        Directors dir907 = new Directors("netus tellus lobortis", c, "purus fringilla sociosqu vesti litora");
        list.add(dir907);
        c.setCountry_id(141);
        Directors dir908 = new Directors("lectus dictumst maecenas", c, "maecenas phasellus donec vehicula tellus");
        list.add(dir908);
        c.setCountry_id(0);
        Directors dir909 = new Directors("imperdiet risus", c, "consequat aliquet lacus cursus tumst");
        list.add(dir909);
        c.setCountry_id(88);
        Directors dir910 = new Directors("curae adipiscing", c, "imperdiet ornare sapien felis varius");
        list.add(dir910);
        c.setCountry_id(115);
        Directors dir911 = new Directors("etiam cursus phasellus", c, "feugiat tincidunt cubilia lorem tumst");
        list.add(dir911);
        c.setCountry_id(118);
        Directors dir912 = new Directors("faucibus adipiscing vivamus pellentesque", c, "feugiat curae mollis pharetra nostra");
        list.add(dir912);
        c.setCountry_id(14);
        Directors dir913 = new Directors("interdum dignissim", c, "sociosqu scelerisque ultrices curae etiam");
        list.add(dir913);
        c.setCountry_id(22);
        Directors dir914 = new Directors("senectus integer tempus", c, "suspendisse malesuada fames curae placerat");
        list.add(dir914);
        c.setCountry_id(106);
        Directors dir915 = new Directors("aenean habitasse dictum nulla", c, "cursus convallis dignissim dictumst torquent");
        list.add(dir915);
        c.setCountry_id(135);
        Directors dir916 = new Directors("pulvinar laoreet aptent ligula", c, "facilisisnunc adipiscing pulvinar mauris semper");
        list.add(dir916);
        c.setCountry_id(136);
        Directors dir917 = new Directors("dictum curae convallis", c, "neque primis iaculis nonummy nonummy");
        list.add(dir917);
        c.setCountry_id(16);
        Directors dir918 = new Directors("nostra velit", c, "magna velit semper mattis eleifend");
        list.add(dir918);
        c.setCountry_id(59);
        Directors dir919 = new Directors("aliquam tortor", c, "proin aenean semper dictum facilisi");
        list.add(dir919);
        c.setCountry_id(123);
        Directors dir920 = new Directors("primis eleifend", c, "ultrices tortor integer feugiat bulum");
        list.add(dir920);
        c.setCountry_id(19);
        Directors dir921 = new Directors("ultrices ullamcorper", c, "rutrum pretium etiam justo proin");
        list.add(dir921);
        c.setCountry_id(39);
        Directors dir922 = new Directors("facilisi fusce", c, "cubilia malesuada neque cursus rutrum");
        list.add(dir922);
        c.setCountry_id(127);
        Directors dir923 = new Directors("curae phasellus", c, "fames commodo tellus fusce libero");
        list.add(dir923);
        c.setCountry_id(115);
        Directors dir924 = new Directors("lobortis sollicitudin ullamcorper", c, "class iaculis praesent ipsum turpis");
        list.add(dir924);
        c.setCountry_id(131);
        Directors dir925 = new Directors("ultrices vitae scelerisque venenatis", c, "hendrerit cubilia etiam integer volutpat");
        list.add(dir925);
        c.setCountry_id(121);
        Directors dir926 = new Directors("nulla justo", c, "bulum sodales wisiaenean curae ultricies");
        list.add(dir926);
        c.setCountry_id(33);
        Directors dir927 = new Directors("iaculis convallis", c, "congue integer porttitor fringilla risus");
        list.add(dir927);
        c.setCountry_id(31);
        Directors dir928 = new Directors("fringilla vitae", c, "viverra posuere dolor vesti primis");
        list.add(dir928);
        c.setCountry_id(148);
        Directors dir929 = new Directors("volutpat malesuada varius", c, "vitae euismod consequat donec tempus");
        list.add(dir929);
        c.setCountry_id(75);
        Directors dir930 = new Directors("ullamcorper platea maecenas", c, "class torquent interdum neque fames");
        list.add(dir930);
        c.setCountry_id(25);
        Directors dir931 = new Directors("torquent molestie torquent", c, "velit bulum tellus tempor porttitor");
        list.add(dir931);
        c.setCountry_id(16);
        Directors dir932 = new Directors("hendrerit dictum", c, "nulla inceptos iaculis pretium laoreet");
        list.add(dir932);
        c.setCountry_id(10);
        Directors dir933 = new Directors("wisiaenean lorem proin tumst", c, "class convallis proin nonummy ultrices");
        list.add(dir933);
        c.setCountry_id(25);
        Directors dir934 = new Directors("nonummy neque", c, "lacinia adipiscing maecenas congue wisiaenean");
        list.add(dir934);
        c.setCountry_id(60);
        Directors dir935 = new Directors("lobortis nonummy mauris conubia", c, "vestibulum pharetra congue praesent phasellus");
        list.add(dir935);
        c.setCountry_id(0);
        Directors dir936 = new Directors("neque dolor semper sociosqu", c, "eleifend inceptos varius cubilia sociosqu");
        list.add(dir936);
        c.setCountry_id(65);
        Directors dir937 = new Directors("praesent habitant tellus", c, "curabitur etiam congue torquent auctor");
        list.add(dir937);
        c.setCountry_id(116);
        Directors dir938 = new Directors("augue senectus mollis", c, "lorem platea pharetra facilisisnunc varius");
        list.add(dir938);
        c.setCountry_id(92);
        Directors dir939 = new Directors("hendrerit posuere", c, "adipiscing ullamcorper consequat phasellus rutrum");
        list.add(dir939);
        c.setCountry_id(35);
        Directors dir940 = new Directors("pretium egestas", c, "bibendum inceptos vestibulum praesent mattis");
        list.add(dir940);
        c.setCountry_id(115);
        Directors dir941 = new Directors("ipsum venenatis tellus class", c, "pharetra pretium morbi nonummy proin");
        list.add(dir941);
        c.setCountry_id(63);
        Directors dir942 = new Directors("adipiscing consectetuer ligula facilisi", c, "inceptos curae bibendum quisque facilisis");
        list.add(dir942);
        c.setCountry_id(3);
        Directors dir943 = new Directors("nonummy velit", c, "posuere ligula curabitur neque ultricies");
        list.add(dir943);
        c.setCountry_id(142);
        Directors dir944 = new Directors("tempus phasellus", c, "ultrices posuere viverra lectus porttitor");
        list.add(dir944);
        c.setCountry_id(138);
        Directors dir945 = new Directors("felis lorem dictumst", c, "neque sapien vitae lectus fringilla");
        list.add(dir945);
        c.setCountry_id(94);
        Directors dir946 = new Directors("posuere tempor", c, "platea accumsan luctus facilisi augue");
        list.add(dir946);
        c.setCountry_id(72);
        Directors dir947 = new Directors("sagittis risus velit", c, "fringilla volutpat porta rutrum dictum");
        list.add(dir947);
        c.setCountry_id(144);
        Directors dir948 = new Directors("malesuada malesuada", c, "luctus tumst placerat convallis pulvinar");
        list.add(dir948);
        c.setCountry_id(66);
        Directors dir949 = new Directors("pellentesque luctus scelerisque congue", c, "volutpat semper platea imperdiet tempus");
        list.add(dir949);
        c.setCountry_id(24);
        Directors dir950 = new Directors("posuere ornare elementum litora", c, "ornare laoreet commodo morbi adipiscing");
        list.add(dir950);
        c.setCountry_id(103);
        Directors dir951 = new Directors("facilisis tincidunt", c, "sociosqu interdum primis imperdiet nullam");
        list.add(dir951);
        c.setCountry_id(67);
        Directors dir952 = new Directors("interdum viverra sagittis auctor", c, "nullam phasellus lacus vestibulum laoreet");
        list.add(dir952);
        c.setCountry_id(97);
        Directors dir953 = new Directors("litora interdum nostra", c, "lacinia rutrum nostra mollis lacus");
        list.add(dir953);
        c.setCountry_id(69);
        Directors dir954 = new Directors("viverra neque morbi", c, "scelerisque senectus porta habitant tempus");
        list.add(dir954);
        c.setCountry_id(114);
        Directors dir955 = new Directors("auctor mattis hendrerit turpis", c, "sapien metus ipsum adipiscing porttitor");
        list.add(dir955);
        c.setCountry_id(18);
        Directors dir956 = new Directors("class egestas inceptos nonummy", c, "turpis mauris lectus purus hendrerit");
        list.add(dir956);
        c.setCountry_id(131);
        Directors dir957 = new Directors("vestibulum curabitur", c, "imperdiet lacus cursus habitant rutrum");
        list.add(dir957);
        c.setCountry_id(11);
        Directors dir958 = new Directors("primis tempor lectus", c, "ipsum adipiscing nullam volutpat fringilla");
        list.add(dir958);
        c.setCountry_id(118);
        Directors dir959 = new Directors("wisiaenean praesent", c, "nonummy tortor proin habitant consectetuer");
        list.add(dir959);
        c.setCountry_id(148);
        Directors dir960 = new Directors("sollicitudin sapien cursus", c, "tristique faucibus fermentum nonummy taciti");
        list.add(dir960);
        c.setCountry_id(65);
        Directors dir961 = new Directors("vivamus curae", c, "lacus risus dignissim senectus scelerisque");
        list.add(dir961);
        c.setCountry_id(137);
        Directors dir962 = new Directors("tincidunt iaculis", c, "justo lectus etiam metus tempor");
        list.add(dir962);
        c.setCountry_id(32);
        Directors dir963 = new Directors("justo mauris magna fringilla", c, "vivamus dictum velit sagittis molestie");
        list.add(dir963);
        c.setCountry_id(42);
        Directors dir964 = new Directors("placerat eleifend conubia aliquet", c, "augue primis tempor primis nulla");
        list.add(dir964);
        c.setCountry_id(8);
        Directors dir965 = new Directors("conubia ligula", c, "tincidunt wisiaenean magna sodales risus");
        list.add(dir965);
        c.setCountry_id(33);
        Directors dir966 = new Directors("porttitor nonummy", c, "tristique mattis vestibulum sodales convallis");
        list.add(dir966);
        c.setCountry_id(71);
        Directors dir967 = new Directors("lacus euismod praesent", c, "nostra donec lobortis fames litora");
        list.add(dir967);
        c.setCountry_id(63);
        Directors dir968 = new Directors("dolor porttitor eleifend ultrices", c, "commodo nonummy bibendum morbi bulum");
        list.add(dir968);
        c.setCountry_id(67);
        Directors dir969 = new Directors("semper fusce", c, "molestie vehicula tortor habitasse sagittis");
        list.add(dir969);
        c.setCountry_id(24);
        Directors dir970 = new Directors("praesent luctus", c, "placerat nonummy sollicitudin pulvinar purus");
        list.add(dir970);
        c.setCountry_id(6);
        Directors dir971 = new Directors("cubilia sagittis", c, "fermentum dictum facilisis primis justo");
        list.add(dir971);
        c.setCountry_id(36);
        Directors dir972 = new Directors("lobortis placerat congue", c, "turpis elementum ultricies sociosqu neque");
        list.add(dir972);
        c.setCountry_id(5);
        Directors dir973 = new Directors("bulum cursus", c, "fringilla magna aliquam wisiaenean cursus");
        list.add(dir973);
        c.setCountry_id(96);
        Directors dir974 = new Directors("sapien lacinia", c, "fermentum aliquam lacinia metus iaculis");
        list.add(dir974);
        c.setCountry_id(77);
        Directors dir975 = new Directors("lorem neque class", c, "placerat fermentum nostra pellentesque taciti");
        list.add(dir975);
        c.setCountry_id(62);
        Directors dir976 = new Directors("habitasse pretium quisque", c, "facilisi feugiat vesti aptent conubia");
        list.add(dir976);
        c.setCountry_id(1);
        Directors dir977 = new Directors("dignissim fames", c, "convallis auctor rutrum curabitur fames");
        list.add(dir977);
        c.setCountry_id(46);
        Directors dir978 = new Directors("praesent nulla", c, "wisiaenean tumst auctor adipiscing accumsan");
        list.add(dir978);
        c.setCountry_id(117);
        Directors dir979 = new Directors("fusce sociosqu", c, "venenatis imperdiet porta neque tortor");
        list.add(dir979);
        c.setCountry_id(116);
        Directors dir980 = new Directors("senectus tempor mauris risus", c, "augue maecenas libero malesuada lorem");
        list.add(dir980);
        c.setCountry_id(24);
        Directors dir981 = new Directors("lorem velit", c, "pharetra interdum pellentesque vivamus tempus");
        list.add(dir981);
        c.setCountry_id(135);
        Directors dir982 = new Directors("faucibus class hymenaeos ultrices", c, "cursus placerat egestas ullamcorper viverra");
        list.add(dir982);
        c.setCountry_id(118);
        Directors dir983 = new Directors("tempus pulvinar", c, "volutpat vitae ultricies tumst facilisis");
        list.add(dir983);
        c.setCountry_id(34);
        Directors dir984 = new Directors("curabitur ultricies pulvinar bibendum", c, "iaculis semper porta tellus mollis");
        list.add(dir984);
        c.setCountry_id(66);
        Directors dir985 = new Directors("faucibus habitant", c, "porta lacus hymenaeos purus dignissim");
        list.add(dir985);
        c.setCountry_id(88);
        Directors dir986 = new Directors("risus habitasse", c, "molestie primis fusce cursus nostra");
        list.add(dir986);
        c.setCountry_id(68);
        Directors dir987 = new Directors("varius sodales", c, "inceptos praesent iaculis inceptos porttitor");
        list.add(dir987);
        c.setCountry_id(84);
        Directors dir988 = new Directors("volutpat placerat quisque elementum", c, "nullam lacinia risus consequat facilisisnunc");
        list.add(dir988);
        c.setCountry_id(28);
        Directors dir989 = new Directors("varius ullamcorper", c, "facilisis volutpat bulum convallis congue");
        list.add(dir989);
        c.setCountry_id(80);
        Directors dir990 = new Directors("hendrerit pretium venenatis aptent", c, "sodales vehicula luctus tincidunt curabitur");
        list.add(dir990);
        c.setCountry_id(84);
        Directors dir991 = new Directors("molestie velit litora curabitur", c, "nullam turpis scelerisque mattis sagittis");
        list.add(dir991);
        c.setCountry_id(62);
        Directors dir992 = new Directors("neque integer lorem curabitur", c, "platea lorem primis dignissim felis");
        list.add(dir992);
        c.setCountry_id(55);
        Directors dir993 = new Directors("congue congue vesti", c, "hymenaeos fringilla placerat egestas vehicula");
        list.add(dir993);
        c.setCountry_id(80);
        Directors dir994 = new Directors("sagittis ultrices", c, "volutpat aliquam maecenas risus dignissim");
        list.add(dir994);
        c.setCountry_id(53);
        Directors dir995 = new Directors("dolor laoreet fusce", c, "pellentesque fusce nulla sagittis phasellus");
        list.add(dir995);
        c.setCountry_id(43);
        Directors dir996 = new Directors("libero nostra", c, "bibendum molestie risus ipsum vestibulum");
        list.add(dir996);
        c.setCountry_id(63);
        Directors dir997 = new Directors("aenean velit praesent nostra", c, "maecenas vestibulum mollis metus interdum");
        list.add(dir997);
        c.setCountry_id(102);
        Directors dir998 = new Directors("lacus felis ultrices", c, "suspendisse sagittis lacinia risus class");
        list.add(dir998);
        c.setCountry_id(93);
        Directors dir999 = new Directors("euismod aenean ultricies", c, "feugiat risus nulla imperdiet lacinia");
        list.add(dir999);

        Connection.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            directorsDBM.insertDirectors(iteration);
        });
        Connection.getCon().getTransaction().commit();

    }
}
