package preInsertions;

import DBManager.GenresDBM;
import Conn.Connection;
import entities.Genres;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertGenres
{

    GenresDBM genresDBM = new GenresDBM();
    List<Genres> list = new ArrayList<>();

    public void insert() {

        Genres gen0 = new Genres(1, "porta");
        list.add(gen0);
        Genres gen1 = new Genres(2, "consequat");
        list.add(gen1);
        Genres gen2 = new Genres(3, "vestibulum eleifend");
        list.add(gen2);
        Genres gen3 = new Genres(4, "varius");
        list.add(gen3);
        Genres gen4 = new Genres(5, "velit");
        list.add(gen4);
        Genres gen5 = new Genres(6, "ipsum porttitor");
        list.add(gen5);
        Genres gen6 = new Genres(7, "torquent");
        list.add(gen6);
        Genres gen7 = new Genres(8, "metus");
        list.add(gen7);
        Genres gen8 = new Genres(9, "posuere");
        list.add(gen8);
        Genres gen9 = new Genres(10, "libero");
        list.add(gen9);
        Genres gen10 = new Genres(11, "porta neque");
        list.add(gen10);
        Genres gen11 = new Genres(12, "congue");
        list.add(gen11);
        Genres gen12 = new Genres(13, "turpis habitant");
        list.add(gen12);
        Genres gen13 = new Genres(14, "quisque convallis");
        list.add(gen13);
        Genres gen14 = new Genres(15, "iaculis");
        list.add(gen14);
        Genres gen15 = new Genres(16, "interdum proin");
        list.add(gen15);
        Genres gen16 = new Genres(17, "laoreet praesent");
        list.add(gen16);
        Genres gen17 = new Genres(18, "nulla");
        list.add(gen17);
        Genres gen18 = new Genres(19, "rutrum");
        list.add(gen18);
        Genres gen19 = new Genres(20, "porttitor");
        list.add(gen19);
        Genres gen20 = new Genres(21, "molestie");
        list.add(gen20);
        Genres gen21 = new Genres(22, "commodo donec");
        list.add(gen21);
        Genres gen22 = new Genres(23, "class");
        list.add(gen22);
        Genres gen23 = new Genres(24, "dignissim");
        list.add(gen23);
        Genres gen24 = new Genres(25, "suspendisse");
        list.add(gen24);
        Genres gen25 = new Genres(26, "facilisisnunc fermentum");
        list.add(gen25);
        Genres gen26 = new Genres(27, "tincidunt");
        list.add(gen26);
        Genres gen27 = new Genres(28, "accumsan felis");
        list.add(gen27);
        Genres gen28 = new Genres(29, "aliquam vivamus");
        list.add(gen28);
        Genres gen29 = new Genres(30, "fames");
        list.add(gen29);
        Genres gen30 = new Genres(31, "tempus");
        list.add(gen30);
        Genres gen31 = new Genres(32, "netus imperdiet");
        list.add(gen31);
        Genres gen32 = new Genres(33, "lacinia cubilia");
        list.add(gen32);
        Genres gen33 = new Genres(34, "semper auctor");
        list.add(gen33);
        Genres gen34 = new Genres(35, "dignissim");
        list.add(gen34);
        Genres gen35 = new Genres(36, "neque");
        list.add(gen35);
        Genres gen36 = new Genres(37, "hendrerit");
        list.add(gen36);
        Genres gen37 = new Genres(38, "laoreet");
        list.add(gen37);
        Genres gen38 = new Genres(39, "tempor");
        list.add(gen38);
        Genres gen39 = new Genres(40, "aliquet tempus");
        list.add(gen39);
        Genres gen40 = new Genres(41, "metus aptent");
        list.add(gen40);
        Genres gen41 = new Genres(42, "ipsum");
        list.add(gen41);
        Genres gen42 = new Genres(43, "mauris tristique");
        list.add(gen42);
        Genres gen43 = new Genres(44, "habitant bulum");
        list.add(gen43);
        Genres gen44 = new Genres(45, "convallis proin");
        list.add(gen44);
        Genres gen45 = new Genres(46, "dictum");
        list.add(gen45);
        Genres gen46 = new Genres(47, "curae ullamcorper");
        list.add(gen46);
        Genres gen47 = new Genres(48, "purus donec");
        list.add(gen47);
        Genres gen48 = new Genres(49, "curae hymenaeos");
        list.add(gen48);
        Genres gen49 = new Genres(50, "iaculis");
        list.add(gen49);
        Genres gen50 = new Genres(51, "aliquet");
        list.add(gen50);
        Genres gen51 = new Genres(52, "lacus");
        list.add(gen51);
        Genres gen52 = new Genres(53, "iaculis");
        list.add(gen52);
        Genres gen53 = new Genres(54, "proin");
        list.add(gen53);
        Genres gen54 = new Genres(55, "aliquet nulla");
        list.add(gen54);
        Genres gen55 = new Genres(56, "phasellus");
        list.add(gen55);
        Genres gen56 = new Genres(57, "imperdiet");
        list.add(gen56);
        Genres gen57 = new Genres(58, "laoreet accumsan");
        list.add(gen57);
        Genres gen58 = new Genres(59, "laoreet");
        list.add(gen58);
        Genres gen59 = new Genres(60, "tempor lobortis");
        list.add(gen59);
        Genres gen60 = new Genres(61, "facilisi scelerisque");
        list.add(gen60);
        Genres gen61 = new Genres(62, "rutrum");
        list.add(gen61);
        Genres gen62 = new Genres(63, "nullam");
        list.add(gen62);
        Genres gen63 = new Genres(64, "molestie");
        list.add(gen63);
        Genres gen64 = new Genres(65, "nonummy");
        list.add(gen64);
        Genres gen65 = new Genres(66, "phasellus");
        list.add(gen65);
        Genres gen66 = new Genres(67, "integer");
        list.add(gen66);
        Genres gen67 = new Genres(68, "praesent");
        list.add(gen67);
        Genres gen68 = new Genres(69, "sociosqu");
        list.add(gen68);
        Genres gen69 = new Genres(70, "taciti inceptos");
        list.add(gen69);
        Genres gen70 = new Genres(71, "dictum");
        list.add(gen70);
        Genres gen71 = new Genres(72, "proin");
        list.add(gen71);
        Genres gen72 = new Genres(73, "turpis");
        list.add(gen72);
        Genres gen73 = new Genres(74, "phasellus");
        list.add(gen73);
        Genres gen74 = new Genres(75, "porttitor");
        list.add(gen74);
        Genres gen75 = new Genres(76, "bibendum porta");
        list.add(gen75);
        Genres gen76 = new Genres(77, "consectetuer");
        list.add(gen76);
        Genres gen77 = new Genres(78, "tristique mollis");
        list.add(gen77);
        Genres gen78 = new Genres(79, "vivamus");
        list.add(gen78);
        Genres gen79 = new Genres(80, "volutpat euismod");
        list.add(gen79);
        Genres gen80 = new Genres(81, "hendrerit");
        list.add(gen80);
        Genres gen81 = new Genres(82, "torquent");
        list.add(gen81);
        Genres gen82 = new Genres(83, "purus senectus");
        list.add(gen82);
        Genres gen83 = new Genres(84, "vestibulum");
        list.add(gen83);
        Genres gen84 = new Genres(85, "lectus");
        list.add(gen84);
        Genres gen85 = new Genres(86, "netus nostra");
        list.add(gen85);
        Genres gen86 = new Genres(87, "volutpat");
        list.add(gen86);
        Genres gen87 = new Genres(88, "placerat");
        list.add(gen87);
        Genres gen88 = new Genres(89, "pellentesque pharetra");
        list.add(gen88);
        Genres gen89 = new Genres(90, "auctor");
        list.add(gen89);
        Genres gen90 = new Genres(91, "facilisi");
        list.add(gen90);
        Genres gen91 = new Genres(92, "tristique");
        list.add(gen91);
        Genres gen92 = new Genres(93, "purus");
        list.add(gen92);
        Genres gen93 = new Genres(94, "quisque netus");
        list.add(gen93);
        Genres gen94 = new Genres(95, "mauris");
        list.add(gen94);
        Genres gen95 = new Genres(96, "laoreet");
        list.add(gen95);
        Genres gen96 = new Genres(97, "facilisisnunc");
        list.add(gen96);
        Genres gen97 = new Genres(98, "interdum");
        list.add(gen97);
        Genres gen98 = new Genres(99, "sapien");
        list.add(gen98);
        Genres gen99 = new Genres(100, "integer");
        list.add(gen99);
        Genres gen100 = new Genres(101, "venenatis");
        list.add(gen100);
        Genres gen101 = new Genres(102, "taciti posuere");
        list.add(gen101);
        Genres gen102 = new Genres(103, "tempus nonummy");
        list.add(gen102);
        Genres gen103 = new Genres(104, "pretium euismod");
        list.add(gen103);
        Genres gen104 = new Genres(105, "bibendum maecenas");
        list.add(gen104);
        Genres gen105 = new Genres(106, "metus");
        list.add(gen105);
        Genres gen106 = new Genres(107, "phasellus");
        list.add(gen106);
        Genres gen107 = new Genres(108, "facilisisnunc");
        list.add(gen107);
        Genres gen108 = new Genres(109, "maecenas");
        list.add(gen108);
        Genres gen109 = new Genres(110, "cursus nonummy");
        list.add(gen109);
        Genres gen110 = new Genres(111, "ultrices convallis");
        list.add(gen110);
        Genres gen111 = new Genres(112, "inceptos");
        list.add(gen111);
        Genres gen112 = new Genres(113, "accumsan");
        list.add(gen112);
        Genres gen113 = new Genres(114, "habitant");
        list.add(gen113);
        Genres gen114 = new Genres(115, "faucibus adipiscing");
        list.add(gen114);
        Genres gen115 = new Genres(116, "magna");
        list.add(gen115);
        Genres gen116 = new Genres(117, "inceptos");
        list.add(gen116);
        Genres gen117 = new Genres(118, "bulum");
        list.add(gen117);
        Genres gen118 = new Genres(119, "dictum imperdiet");
        list.add(gen118);
        Genres gen119 = new Genres(120, "morbi laoreet");
        list.add(gen119);
        Genres gen120 = new Genres(121, "pretium luctus");
        list.add(gen120);
        Genres gen121 = new Genres(122, "lacinia adipiscing");
        list.add(gen121);
        Genres gen122 = new Genres(123, "lorem sodales");
        list.add(gen122);
        Genres gen123 = new Genres(124, "lobortis");
        list.add(gen123);
        Genres gen124 = new Genres(125, "vitae conubia");
        list.add(gen124);
        Genres gen125 = new Genres(126, "phasellus");
        list.add(gen125);
        Genres gen126 = new Genres(127, "ligula");
        list.add(gen126);
        Genres gen127 = new Genres(128, "fringilla");
        list.add(gen127);
        Genres gen128 = new Genres(129, "risus");
        list.add(gen128);
        Genres gen129 = new Genres(130, "dictumst wisiaenean");
        list.add(gen129);
        Genres gen130 = new Genres(131, "primis");
        list.add(gen130);
        Genres gen131 = new Genres(132, "convallis");
        list.add(gen131);
        Genres gen132 = new Genres(133, "iaculis turpis");
        list.add(gen132);
        Genres gen133 = new Genres(134, "lobortis");
        list.add(gen133);
        Genres gen134 = new Genres(135, "phasellus inceptos");
        list.add(gen134);
        Genres gen135 = new Genres(136, "semper tumst");
        list.add(gen135);
        Genres gen136 = new Genres(137, "proin fringilla");
        list.add(gen136);
        Genres gen137 = new Genres(138, "suspendisse");
        list.add(gen137);
        Genres gen138 = new Genres(139, "consectetuer");
        list.add(gen138);
        Genres gen139 = new Genres(140, "ornare neque");
        list.add(gen139);
        Genres gen140 = new Genres(141, "fusce");
        list.add(gen140);
        Genres gen141 = new Genres(142, "vesti");
        list.add(gen141);
        Genres gen142 = new Genres(143, "vivamus");
        list.add(gen142);
        Genres gen143 = new Genres(144, "lacinia");
        list.add(gen143);
        Genres gen144 = new Genres(145, "vestibulum");
        list.add(gen144);
        Genres gen145 = new Genres(146, "tellus habitasse");
        list.add(gen145);
        Genres gen146 = new Genres(147, "accumsan phasellus");
        list.add(gen146);
        Genres gen147 = new Genres(148, "ipsum taciti");
        list.add(gen147);
        Genres gen148 = new Genres(149, "senectus");
        list.add(gen148);
        Genres gen149 = new Genres(150, "integer");
        list.add(gen149);

		
		Connection con = new Connection();
        con.setCon();
        con.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            genresDBM.insertGenres(iteration, con);
        });
        con.getCon().getTransaction().commit();
		con.closeCon();

    }
}
