package preInsertions;

import DBManager.NetworksDBM;
import Conn.Connection;
import entities.Countries;
import entities.Networks;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Lucas
 */
public class InsertNetworks
{

    NetworksDBM networksDBM = new NetworksDBM();
    List<Networks> list = new ArrayList<>();
    Countries c = new Countries();

    public void insert() {

        c.setCountry_id(92);
        Networks netw0 = new Networks(1, "fermentum", c, "fames augue hendrerit volutpat vesti");
        list.add(netw0);
        c.setCountry_id(109);
        Networks netw1 = new Networks(2, "facilisi habitasse", c, "lorem morbi iaculis integer habitant");
        list.add(netw1);
        c.setCountry_id(15);
        Networks netw2 = new Networks(3, "vitae", c, "dictum ipsum venenatis vestibulum ullamcorper");
        list.add(netw2);
        c.setCountry_id(7);
        Networks netw3 = new Networks(4, "bulum", c, "rutrum congue varius viverra litora");
        list.add(netw3);
        c.setCountry_id(9);
        Networks netw4 = new Networks(5, "malesuada sagittis", c, "mattis suspendisse sodales egestas vestibulum");
        list.add(netw4);
        c.setCountry_id(22);
        Networks netw5 = new Networks(6, "mollis", c, "ligula fusce fringilla scelerisque quisque");
        list.add(netw5);
        c.setCountry_id(31);
        Networks netw6 = new Networks(7, "cubilia iaculis", c, "dictum eleifend turpis porta porttitor");
        list.add(netw6);
        c.setCountry_id(61);
        Networks netw7 = new Networks(8, "volutpat turpis", c, "venenatis quisque placerat aptent molestie");
        list.add(netw7);
        c.setCountry_id(125);
        Networks netw8 = new Networks(9, "senectus", c, "feugiat sagittis molestie conubia libero");
        list.add(netw8);
        c.setCountry_id(72);
        Networks netw9 = new Networks(10, "lectus", c, "inceptos aliquam justo consectetuer tempus");
        list.add(netw9);
        c.setCountry_id(66);
        Networks netw10 = new Networks(11, "ornare", c, "fames pretium class porta risus");
        list.add(netw10);
        c.setCountry_id(53);
        Networks netw11 = new Networks(12, "etiam", c, "ornare rutrum pretium curabitur iaculis");
        list.add(netw11);
        c.setCountry_id(99);
        Networks netw12 = new Networks(13, "convallis tumst", c, "consequat platea primis nullam proin");
        list.add(netw12);
        c.setCountry_id(28);
        Networks netw13 = new Networks(14, "aliquam", c, "pulvinar facilisi primis class netus");
        list.add(netw13);
        c.setCountry_id(64);
        Networks netw14 = new Networks(15, "nullam molestie", c, "libero hendrerit venenatis lacinia accumsan");
        list.add(netw14);
        c.setCountry_id(99);
        Networks netw15 = new Networks(16, "mauris", c, "semper quisque turpis litora litora");
        list.add(netw15);
        c.setCountry_id(64);
        Networks netw16 = new Networks(17, "tempus taciti", c, "aptent viverra ultrices consectetuer varius");
        list.add(netw16);
        c.setCountry_id(84);
        Networks netw17 = new Networks(18, "consectetuer", c, "wisiaenean sagittis lobortis iaculis hymenaeos");
        list.add(netw17);
        c.setCountry_id(127);
        Networks netw18 = new Networks(19, "pellentesque", c, "class ornare habitasse pharetra curabitur");
        list.add(netw18);
        c.setCountry_id(140);
        Networks netw19 = new Networks(20, "velit", c, "neque netus malesuada facilisis sagittis");
        list.add(netw19);
        c.setCountry_id(17);
        Networks netw20 = new Networks(21, "tempus", c, "sagittis lectus phasellus aenean curabitur");
        list.add(netw20);
        c.setCountry_id(119);
        Networks netw21 = new Networks(22, "sodales", c, "fames vivamus cursus bibendum lacinia");
        list.add(netw21);
        c.setCountry_id(127);
        Networks netw22 = new Networks(23, "tortor purus", c, "litora netus cursus vesti convallis");
        list.add(netw22);
        c.setCountry_id(50);
        Networks netw23 = new Networks(24, "neque", c, "sociosqu imperdiet justo habitasse vestibulum");
        list.add(netw23);
        c.setCountry_id(115);
        Networks netw24 = new Networks(25, "ipsum", c, "felis lorem cubilia mattis purus");
        list.add(netw24);
        c.setCountry_id(19);
        Networks netw25 = new Networks(26, "curae", c, "aliquet nonummy euismod etiam dolor");
        list.add(netw25);
        c.setCountry_id(61);
        Networks netw26 = new Networks(27, "molestie", c, "mollis commodo interdum ornare facilisis");
        list.add(netw26);
        c.setCountry_id(138);
        Networks netw27 = new Networks(28, "elementum hymenaeos", c, "risus aptent ligula suspendisse primis");
        list.add(netw27);
        c.setCountry_id(122);
        Networks netw28 = new Networks(29, "fames", c, "fusce faucibus mattis posuere inceptos");
        list.add(netw28);
        c.setCountry_id(33);
        Networks netw29 = new Networks(30, "ullamcorper", c, "ultricies curabitur feugiat lorem commodo");
        list.add(netw29);
        c.setCountry_id(9);
        Networks netw30 = new Networks(31, "dolor neque", c, "tristique luctus class turpis adipiscing");
        list.add(netw30);
        c.setCountry_id(24);
        Networks netw31 = new Networks(32, "egestas netus", c, "bulum nulla lobortis sagittis torquent");
        list.add(netw31);
        c.setCountry_id(1);
        Networks netw32 = new Networks(33, "class", c, "libero facilisisnunc mauris tristique venenatis");
        list.add(netw32);
        c.setCountry_id(5);
        Networks netw33 = new Networks(34, "aliquet", c, "nonummy luctus aenean fermentum felis");
        list.add(netw33);
        c.setCountry_id(37);
        Networks netw34 = new Networks(35, "class hendrerit", c, "tincidunt accumsan porttitor curae euismod");
        list.add(netw34);
        c.setCountry_id(51);
        Networks netw35 = new Networks(36, "justo", c, "ipsum quisque etiam nostra neque");
        list.add(netw35);
        c.setCountry_id(27);
        Networks netw36 = new Networks(37, "ipsum", c, "imperdiet tumst volutpat risus felis");
        list.add(netw36);
        c.setCountry_id(36);
        Networks netw37 = new Networks(38, "praesent", c, "ullamcorper lobortis turpis lectus proin");
        list.add(netw37);
        c.setCountry_id(30);
        Networks netw38 = new Networks(39, "proin", c, "inceptos felis mollis cubilia bulum");
        list.add(netw38);
        c.setCountry_id(98);
        Networks netw39 = new Networks(40, "ultrices lectus", c, "tristique velit nonummy aenean mattis");
        list.add(netw39);
        c.setCountry_id(77);
        Networks netw40 = new Networks(41, "nonummy", c, "taciti lectus morbi integer bulum");
        list.add(netw40);
        c.setCountry_id(3);
        Networks netw41 = new Networks(42, "dictumst", c, "dictum aliquet morbi aliquet egestas");
        list.add(netw41);
        c.setCountry_id(114);
        Networks netw42 = new Networks(43, "nulla torquent", c, "fames consectetuer aptent eleifend netus");
        list.add(netw42);
        c.setCountry_id(26);
        Networks netw43 = new Networks(44, "eleifend", c, "curabitur felis iaculis convallis auctor");
        list.add(netw43);
        c.setCountry_id(111);
        Networks netw44 = new Networks(45, "malesuada", c, "feugiat nullam elementum purus pellentesque");
        list.add(netw44);
        c.setCountry_id(143);
        Networks netw45 = new Networks(46, "feugiat", c, "quisque dictum purus conubia metus");
        list.add(netw45);
        c.setCountry_id(131);
        Networks netw46 = new Networks(47, "consequat", c, "vitae eleifend proin augue sodales");
        list.add(netw46);
        c.setCountry_id(25);
        Networks netw47 = new Networks(48, "dictum", c, "aenean porttitor vesti inceptos facilisis");
        list.add(netw47);
        c.setCountry_id(119);
        Networks netw48 = new Networks(49, "curae", c, "justo curabitur platea commodo egestas");
        list.add(netw48);
        c.setCountry_id(129);
        Networks netw49 = new Networks(50, "scelerisque platea", c, "auctor eleifend auctor suspendisse mollis");
        list.add(netw49);
        c.setCountry_id(64);
        Networks netw50 = new Networks(51, "nostra", c, "nonummy tellus tellus wisiaenean nullam");
        list.add(netw50);
        c.setCountry_id(94);
        Networks netw51 = new Networks(52, "ultrices nonummy", c, "fermentum lacus commodo malesuada etiam");
        list.add(netw51);
        c.setCountry_id(135);
        Networks netw52 = new Networks(53, "sodales", c, "senectus suspendisse libero aliquet venenatis");
        list.add(netw52);
        c.setCountry_id(55);
        Networks netw53 = new Networks(54, "torquent", c, "netus molestie ornare maecenas ullamcorper");
        list.add(netw53);
        c.setCountry_id(76);
        Networks netw54 = new Networks(55, "venenatis", c, "bulum ornare quisque dictumst tincidunt");
        list.add(netw54);
        c.setCountry_id(27);
        Networks netw55 = new Networks(56, "porta", c, "platea sapien auctor elementum accumsan");
        list.add(netw55);
        c.setCountry_id(121);
        Networks netw56 = new Networks(57, "magna", c, "augue dignissim litora sollicitudin consequat");
        list.add(netw56);
        c.setCountry_id(63);
        Networks netw57 = new Networks(58, "luctus", c, "taciti facilisisnunc maecenas vivamus wisiaenean");
        list.add(netw57);
        c.setCountry_id(59);
        Networks netw58 = new Networks(59, "pulvinar", c, "fusce ultricies facilisisnunc habitant lectus");
        list.add(netw58);
        c.setCountry_id(67);
        Networks netw59 = new Networks(60, "dictumst", c, "platea scelerisque wisiaenean sapien mattis");
        list.add(netw59);
        c.setCountry_id(120);
        Networks netw60 = new Networks(61, "inceptos pharetra", c, "velit consequat vivamus ullamcorper velit");
        list.add(netw60);
        c.setCountry_id(63);
        Networks netw61 = new Networks(62, "neque", c, "aliquet varius inceptos curae fusce");
        list.add(netw61);
        c.setCountry_id(78);
        Networks netw62 = new Networks(63, "ullamcorper viverra", c, "bibendum sodales hendrerit viverra fames");
        list.add(netw62);
        c.setCountry_id(108);
        Networks netw63 = new Networks(64, "fermentum morbi", c, "cubilia lacinia luctus laoreet metus");
        list.add(netw63);
        c.setCountry_id(23);
        Networks netw64 = new Networks(65, "morbi", c, "dolor accumsan hendrerit elementum lobortis");
        list.add(netw64);
        c.setCountry_id(80);
        Networks netw65 = new Networks(66, "tempus", c, "sollicitudin euismod sapien mollis suspendisse");
        list.add(netw65);
        c.setCountry_id(149);
        Networks netw66 = new Networks(67, "convallis", c, "imperdiet tortor libero facilisis ipsum");
        list.add(netw66);
        c.setCountry_id(13);
        Networks netw67 = new Networks(68, "egestas", c, "vesti curae pharetra mattis semper");
        list.add(netw67);
        c.setCountry_id(16);
        Networks netw68 = new Networks(69, "tellus", c, "habitasse conubia tempus nullam curae");
        list.add(netw68);
        c.setCountry_id(16);
        Networks netw69 = new Networks(70, "vesti", c, "porta vesti placerat nonummy conubia");
        list.add(netw69);
        c.setCountry_id(96);
        Networks netw70 = new Networks(71, "feugiat", c, "volutpat mollis vesti maecenas ornare");
        list.add(netw70);
        c.setCountry_id(22);
        Networks netw71 = new Networks(72, "neque ultrices", c, "tumst rutrum vehicula donec pellentesque");
        list.add(netw71);
        c.setCountry_id(98);
        Networks netw72 = new Networks(73, "convallis", c, "vivamus morbi tristique interdum vivamus");
        list.add(netw72);
        c.setCountry_id(25);
        Networks netw73 = new Networks(74, "hendrerit habitasse", c, "dignissim turpis risus sapien tincidunt");
        list.add(netw73);
        c.setCountry_id(107);
        Networks netw74 = new Networks(75, "semper habitant", c, "inceptos euismod consequat tellus scelerisque");
        list.add(netw74);
        c.setCountry_id(36);
        Networks netw75 = new Networks(76, "vitae dolor", c, "lobortis vitae nostra sociosqu rutrum");
        list.add(netw75);
        c.setCountry_id(87);
        Networks netw76 = new Networks(77, "praesent lectus", c, "rutrum sodales libero integer ligula");
        list.add(netw76);
        c.setCountry_id(5);
        Networks netw77 = new Networks(78, "aliquam", c, "mattis congue etiam sodales congue");
        list.add(netw77);
        c.setCountry_id(123);
        Networks netw78 = new Networks(79, "porta", c, "commodo senectus ligula dolor lacinia");
        list.add(netw78);
        c.setCountry_id(120);
        Networks netw79 = new Networks(80, "torquent", c, "eleifend tincidunt aenean consequat curabitur");
        list.add(netw79);
        c.setCountry_id(49);
        Networks netw80 = new Networks(81, "morbi", c, "ornare cursus commodo class congue");
        list.add(netw80);
        c.setCountry_id(136);
        Networks netw81 = new Networks(82, "fusce phasellus", c, "wisiaenean conubia habitant accumsan taciti");
        list.add(netw81);
        c.setCountry_id(24);
        Networks netw82 = new Networks(83, "dictum fermentum", c, "faucibus euismod quisque vivamus vesti");
        list.add(netw82);
        c.setCountry_id(55);
        Networks netw83 = new Networks(84, "turpis integer", c, "neque ultricies curabitur luctus aptent");
        list.add(netw83);
        c.setCountry_id(22);
        Networks netw84 = new Networks(85, "faucibus", c, "tellus interdum netus viverra phasellus");
        list.add(netw84);
        c.setCountry_id(104);
        Networks netw85 = new Networks(86, "sagittis", c, "nulla quisque habitant vitae ultrices");
        list.add(netw85);
        c.setCountry_id(49);
        Networks netw86 = new Networks(87, "mauris neque", c, "molestie sollicitudin senectus imperdiet felis");
        list.add(netw86);
        c.setCountry_id(140);
        Networks netw87 = new Networks(88, "etiam metus", c, "platea placerat interdum varius mollis");
        list.add(netw87);
        c.setCountry_id(32);
        Networks netw88 = new Networks(89, "molestie dictumst", c, "primis placerat fringilla facilisis tempor");
        list.add(netw88);
        c.setCountry_id(24);
        Networks netw89 = new Networks(90, "nonummy", c, "nullam wisiaenean placerat mattis suspendisse");
        list.add(netw89);
        c.setCountry_id(17);
        Networks netw90 = new Networks(91, "placerat", c, "phasellus tristique consequat wisiaenean tempor");
        list.add(netw90);
        c.setCountry_id(114);
        Networks netw91 = new Networks(92, "placerat", c, "morbi pulvinar donec tincidunt pharetra");
        list.add(netw91);
        c.setCountry_id(19);
        Networks netw92 = new Networks(93, "laoreet", c, "viverra varius purus nulla ullamcorper");
        list.add(netw92);
        c.setCountry_id(120);
        Networks netw93 = new Networks(94, "varius neque", c, "nulla neque tumst facilisi ipsum");
        list.add(netw93);
        c.setCountry_id(114);
        Networks netw94 = new Networks(95, "curae lacinia", c, "posuere mauris augue vivamus pulvinar");
        list.add(netw94);
        c.setCountry_id(70);
        Networks netw95 = new Networks(96, "bibendum", c, "habitasse platea dolor ligula habitant");
        list.add(netw95);
        c.setCountry_id(129);
        Networks netw96 = new Networks(97, "consectetuer maecenas", c, "inceptos felis pharetra tortor bulum");
        list.add(netw96);
        c.setCountry_id(108);
        Networks netw97 = new Networks(98, "auctor", c, "tellus tristique scelerisque rutrum aliquam");
        list.add(netw97);
        c.setCountry_id(42);
        Networks netw98 = new Networks(99, "libero facilisis", c, "tortor lacinia praesent vestibulum ultricies");
        list.add(netw98);
        c.setCountry_id(132);
        Networks netw99 = new Networks(100, "mattis", c, "sapien tellus euismod eleifend mollis");
        list.add(netw99);
        c.setCountry_id(51);
        Networks netw100 = new Networks(101, "justo inceptos", c, "nullam auctor magna conubia pellentesque");
        list.add(netw100);
        c.setCountry_id(116);
        Networks netw101 = new Networks(102, "netus vestibulum", c, "consectetuer tempor malesuada mollis imperdiet");
        list.add(netw101);
        c.setCountry_id(98);
        Networks netw102 = new Networks(103, "fames", c, "viverra velit mattis lacinia placerat");
        list.add(netw102);
        c.setCountry_id(45);
        Networks netw103 = new Networks(104, "facilisisnunc dolor", c, "bulum venenatis augue aliquam risus");
        list.add(netw103);
        c.setCountry_id(135);
        Networks netw104 = new Networks(105, "sodales morbi", c, "elementum venenatis sapien netus luctus");
        list.add(netw104);
        c.setCountry_id(46);
        Networks netw105 = new Networks(106, "torquent senectus", c, "lectus molestie laoreet turpis placerat");
        list.add(netw105);
        c.setCountry_id(27);
        Networks netw106 = new Networks(107, "ligula", c, "consequat ligula feugiat etiam nulla");
        list.add(netw106);
        c.setCountry_id(115);
        Networks netw107 = new Networks(108, "ultricies", c, "elementum mattis curabitur porta dictumst");
        list.add(netw107);
        c.setCountry_id(42);
        Networks netw108 = new Networks(109, "imperdiet", c, "augue tortor litora porta rutrum");
        list.add(netw108);
        c.setCountry_id(47);
        Networks netw109 = new Networks(110, "augue rutrum", c, "mauris maecenas adipiscing aenean felis");
        list.add(netw109);
        c.setCountry_id(110);
        Networks netw110 = new Networks(111, "interdum praesent", c, "etiam donec tellus taciti semper");
        list.add(netw110);
        c.setCountry_id(13);
        Networks netw111 = new Networks(112, "integer", c, "primis accumsan aptent pulvinar suspendisse");
        list.add(netw111);
        c.setCountry_id(93);
        Networks netw112 = new Networks(113, "adipiscing", c, "nostra sollicitudin dictum faucibus rutrum");
        list.add(netw112);
        c.setCountry_id(120);
        Networks netw113 = new Networks(114, "magna", c, "neque adipiscing bibendum commodo aliquam");
        list.add(netw113);
        c.setCountry_id(104);
        Networks netw114 = new Networks(115, "tempor", c, "lorem pulvinar lacus ipsum vivamus");
        list.add(netw114);
        c.setCountry_id(120);
        Networks netw115 = new Networks(116, "purus", c, "quisque proin pellentesque lobortis nostra");
        list.add(netw115);
        c.setCountry_id(145);
        Networks netw116 = new Networks(117, "dictumst ligula", c, "sagittis scelerisque sagittis placerat litora");
        list.add(netw116);
        c.setCountry_id(7);
        Networks netw117 = new Networks(118, "congue vehicula", c, "vesti suspendisse nullam malesuada senectus");
        list.add(netw117);
        c.setCountry_id(114);
        Networks netw118 = new Networks(119, "euismod", c, "netus fames posuere laoreet aptent");
        list.add(netw118);
        c.setCountry_id(50);
        Networks netw119 = new Networks(120, "integer dictumst", c, "mollis habitant vehicula habitasse malesuada");
        list.add(netw119);
        c.setCountry_id(16);
        Networks netw120 = new Networks(121, "mattis facilisi", c, "egestas convallis auctor class purus");
        list.add(netw120);
        c.setCountry_id(117);
        Networks netw121 = new Networks(122, "ipsum maecenas", c, "vitae accumsan lorem neque tincidunt");
        list.add(netw121);
        c.setCountry_id(70);
        Networks netw122 = new Networks(123, "elementum scelerisque", c, "lacus convallis donec imperdiet primis");
        list.add(netw122);
        c.setCountry_id(84);
        Networks netw123 = new Networks(124, "egestas", c, "ultricies netus tincidunt sodales aliquam");
        list.add(netw123);
        c.setCountry_id(120);
        Networks netw124 = new Networks(125, "nulla", c, "accumsan interdum inceptos commodo euismod");
        list.add(netw124);
        c.setCountry_id(67);
        Networks netw125 = new Networks(126, "neque tristique", c, "laoreet egestas lorem aliquam primis");
        list.add(netw125);
        c.setCountry_id(91);
        Networks netw126 = new Networks(127, "conubia", c, "dictum adipiscing pretium posuere proin");
        list.add(netw126);
        c.setCountry_id(30);
        Networks netw127 = new Networks(128, "nullam metus", c, "facilisis pulvinar integer euismod primis");
        list.add(netw127);
        c.setCountry_id(61);
        Networks netw128 = new Networks(129, "metus", c, "turpis consequat laoreet pellentesque fames");
        list.add(netw128);
        c.setCountry_id(138);
        Networks netw129 = new Networks(130, "mauris", c, "sagittis taciti laoreet felis netus");
        list.add(netw129);
        c.setCountry_id(117);
        Networks netw130 = new Networks(131, "convallis", c, "nullam vestibulum scelerisque fermentum purus");
        list.add(netw130);
        c.setCountry_id(46);
        Networks netw131 = new Networks(132, "vitae", c, "ipsum metus risus tumst ultrices");
        list.add(netw131);
        c.setCountry_id(8);
        Networks netw132 = new Networks(133, "facilisi lobortis", c, "curae curabitur congue vivamus hendrerit");
        list.add(netw132);
        c.setCountry_id(12);
        Networks netw133 = new Networks(134, "dictumst", c, "adipiscing curae euismod imperdiet taciti");
        list.add(netw133);
        c.setCountry_id(135);
        Networks netw134 = new Networks(135, "proin", c, "porttitor habitant scelerisque congue wisiaenean");
        list.add(netw134);
        c.setCountry_id(150);
        Networks netw135 = new Networks(136, "malesuada", c, "sodales vestibulum pellentesque adipiscing platea");
        list.add(netw135);
        c.setCountry_id(64);
        Networks netw136 = new Networks(137, "turpis", c, "lacinia feugiat nulla elementum consequat");
        list.add(netw136);
        c.setCountry_id(56);
        Networks netw137 = new Networks(138, "ornare bibendum", c, "malesuada fames faucibus dictum hendrerit");
        list.add(netw137);
        c.setCountry_id(142);
        Networks netw138 = new Networks(139, "nulla platea", c, "accumsan tellus libero dictum habitasse");
        list.add(netw138);
        c.setCountry_id(60);
        Networks netw139 = new Networks(140, "tristique", c, "wisiaenean torquent lacus pulvinar cursus");
        list.add(netw139);
        c.setCountry_id(17);
        Networks netw140 = new Networks(141, "turpis", c, "pharetra porttitor libero suspendisse elementum");
        list.add(netw140);
        c.setCountry_id(34);
        Networks netw141 = new Networks(142, "tortor", c, "sociosqu bulum risus semper mauris");
        list.add(netw141);
        c.setCountry_id(97);
        Networks netw142 = new Networks(143, "lacus", c, "curae vitae faucibus curae libero");
        list.add(netw142);
        c.setCountry_id(129);
        Networks netw143 = new Networks(144, "mollis", c, "libero facilisi tortor tumst porta");
        list.add(netw143);
        c.setCountry_id(80);
        Networks netw144 = new Networks(145, "vivamus", c, "felis curae varius mollis tincidunt");
        list.add(netw144);
        c.setCountry_id(93);
        Networks netw145 = new Networks(146, "vesti", c, "aliquet curabitur tincidunt nullam sapien");
        list.add(netw145);
        c.setCountry_id(44);
        Networks netw146 = new Networks(147, "habitasse", c, "dignissim tempus vesti ullamcorper commodo");
        list.add(netw146);
        c.setCountry_id(57);
        Networks netw147 = new Networks(148, "tincidunt", c, "integer cubilia nonummy habitant quisque");
        list.add(netw147);
        c.setCountry_id(18);
        Networks netw148 = new Networks(149, "lorem porta", c, "fusce commodo lobortis consequat pellentesque");
        list.add(netw148);
        c.setCountry_id(98);
        Networks netw149 = new Networks(150, "tumst", c, "augue scelerisque elementum euismod vesti");
        list.add(netw149);
        c.setCountry_id(62);
        Networks netw150 = new Networks(151, "imperdiet", c, "lacus fringilla nonummy ligula cursus");
        list.add(netw150);
        c.setCountry_id(138);
        Networks netw151 = new Networks(152, "facilisisnunc", c, "cubilia varius convallis hendrerit senectus");
        list.add(netw151);
        c.setCountry_id(55);
        Networks netw152 = new Networks(153, "class", c, "litora class venenatis tristique bibendum");
        list.add(netw152);
        c.setCountry_id(83);
        Networks netw153 = new Networks(154, "libero", c, "mollis conubia vestibulum proin cubilia");
        list.add(netw153);
        c.setCountry_id(16);
        Networks netw154 = new Networks(155, "litora primis", c, "consectetuer fames egestas volutpat consequat");
        list.add(netw154);
        c.setCountry_id(129);
        Networks netw155 = new Networks(156, "sollicitudin", c, "sollicitudin maecenas aliquam consequat sapien");
        list.add(netw155);
        c.setCountry_id(8);
        Networks netw156 = new Networks(157, "facilisi", c, "neque tempus donec aptent sapien");
        list.add(netw156);
        c.setCountry_id(120);
        Networks netw157 = new Networks(158, "libero", c, "velit fusce auctor aptent sollicitudin");
        list.add(netw157);
        c.setCountry_id(53);
        Networks netw158 = new Networks(159, "faucibus", c, "posuere lacus quisque aliquam feugiat");
        list.add(netw158);
        c.setCountry_id(29);
        Networks netw159 = new Networks(160, "cubilia", c, "commodo fringilla fermentum semper ipsum");
        list.add(netw159);
        c.setCountry_id(18);
        Networks netw160 = new Networks(161, "eleifend", c, "tortor habitasse lacus ullamcorper egestas");
        list.add(netw160);
        c.setCountry_id(91);
        Networks netw161 = new Networks(162, "inceptos", c, "platea nonummy venenatis aliquet commodo");
        list.add(netw161);
        c.setCountry_id(123);
        Networks netw162 = new Networks(163, "dignissim", c, "hymenaeos maecenas quisque tempus rutrum");
        list.add(netw162);
        c.setCountry_id(88);
        Networks netw163 = new Networks(164, "sociosqu", c, "augue tempor felis vehicula volutpat");
        list.add(netw163);
        c.setCountry_id(33);
        Networks netw164 = new Networks(165, "libero", c, "torquent cubilia consequat facilisi vesti");
        list.add(netw164);
        c.setCountry_id(134);
        Networks netw165 = new Networks(166, "ornare purus", c, "inceptos varius fermentum tellus aptent");
        list.add(netw165);
        c.setCountry_id(40);
        Networks netw166 = new Networks(167, "velit netus", c, "molestie tellus magna vestibulum suspendisse");
        list.add(netw166);
        c.setCountry_id(78);
        Networks netw167 = new Networks(168, "faucibus", c, "quisque elementum sociosqu praesent elementum");
        list.add(netw167);
        c.setCountry_id(108);
        Networks netw168 = new Networks(169, "sociosqu", c, "wisiaenean vesti euismod scelerisque cursus");
        list.add(netw168);
        c.setCountry_id(42);
        Networks netw169 = new Networks(170, "etiam sociosqu", c, "luctus adipiscing tempus fringilla tincidunt");
        list.add(netw169);
        c.setCountry_id(8);
        Networks netw170 = new Networks(171, "aliquam", c, "conubia tellus vehicula dolor tempus");
        list.add(netw170);
        c.setCountry_id(28);
        Networks netw171 = new Networks(172, "platea", c, "magna nulla purus platea lobortis");
        list.add(netw171);
        c.setCountry_id(61);
        Networks netw172 = new Networks(173, "dictum", c, "posuere vesti vestibulum imperdiet placerat");
        list.add(netw172);
        c.setCountry_id(19);
        Networks netw173 = new Networks(174, "risus", c, "sodales consequat lacus quisque hendrerit");
        list.add(netw173);
        c.setCountry_id(57);
        Networks netw174 = new Networks(175, "tumst platea", c, "nostra laoreet luctus lacus varius");
        list.add(netw174);
        c.setCountry_id(87);
        Networks netw175 = new Networks(176, "hymenaeos", c, "accumsan vitae quisque senectus nostra");
        list.add(netw175);
        c.setCountry_id(83);
        Networks netw176 = new Networks(177, "mattis", c, "malesuada lacinia pretium praesent tellus");
        list.add(netw176);
        c.setCountry_id(90);
        Networks netw177 = new Networks(178, "habitasse", c, "placerat curabitur aptent suspendisse dictum");
        list.add(netw177);
        c.setCountry_id(55);
        Networks netw178 = new Networks(179, "dictumst", c, "egestas justo fermentum rutrum cursus");
        list.add(netw178);
        c.setCountry_id(48);
        Networks netw179 = new Networks(180, "phasellus", c, "metus dictumst ultricies venenatis maecenas");
        list.add(netw179);
        c.setCountry_id(8);
        Networks netw180 = new Networks(181, "consectetuer", c, "venenatis facilisi pretium luctus nulla");
        list.add(netw180);
        c.setCountry_id(107);
        Networks netw181 = new Networks(182, "molestie", c, "vestibulum integer elementum libero class");
        list.add(netw181);
        c.setCountry_id(144);
        Networks netw182 = new Networks(183, "quisque", c, "fringilla curae consectetuer pretium auctor");
        list.add(netw182);
        c.setCountry_id(10);
        Networks netw183 = new Networks(184, "facilisisnunc", c, "cursus imperdiet interdum porta lacinia");
        list.add(netw183);
        c.setCountry_id(113);
        Networks netw184 = new Networks(185, "turpis", c, "morbi praesent senectus metus lacinia");
        list.add(netw184);
        c.setCountry_id(29);
        Networks netw185 = new Networks(186, "rutrum", c, "justo auctor auctor nostra class");
        list.add(netw185);
        c.setCountry_id(40);
        Networks netw186 = new Networks(187, "maecenas", c, "lorem libero justo vitae augue");
        list.add(netw186);
        c.setCountry_id(6);
        Networks netw187 = new Networks(188, "neque", c, "platea pellentesque rutrum nonummy class");
        list.add(netw187);
        c.setCountry_id(117);
        Networks netw188 = new Networks(189, "porta praesent", c, "tumst adipiscing augue facilisi interdum");
        list.add(netw188);
        c.setCountry_id(68);
        Networks netw189 = new Networks(190, "iaculis", c, "aptent luctus porta mattis dictum");
        list.add(netw189);
        c.setCountry_id(19);
        Networks netw190 = new Networks(191, "sagittis pharetra", c, "taciti libero consectetuer velit porta");
        list.add(netw190);
        c.setCountry_id(27);
        Networks netw191 = new Networks(192, "integer", c, "turpis ornare porttitor ipsum semper");
        list.add(netw191);
        c.setCountry_id(109);
        Networks netw192 = new Networks(193, "luctus", c, "molestie sollicitudin sagittis lacinia fames");
        list.add(netw192);
        c.setCountry_id(47);
        Networks netw193 = new Networks(194, "felis", c, "pharetra euismod imperdiet venenatis mauris");
        list.add(netw193);
        c.setCountry_id(128);
        Networks netw194 = new Networks(195, "aptent", c, "pharetra sapien tincidunt aptent mauris");
        list.add(netw194);
        c.setCountry_id(11);
        Networks netw195 = new Networks(196, "nostra fermentum", c, "viverra pellentesque class augue molestie");
        list.add(netw195);
        c.setCountry_id(113);
        Networks netw196 = new Networks(197, "justo tincidunt", c, "tumst euismod congue tempus curae");
        list.add(netw196);
        c.setCountry_id(46);
        Networks netw197 = new Networks(198, "risus", c, "fermentum fusce auctor phasellus fermentum");
        list.add(netw197);
        c.setCountry_id(93);
        Networks netw198 = new Networks(199, "praesent", c, "primis posuere vestibulum lobortis dolor");
        list.add(netw198);
        c.setCountry_id(51);
        Networks netw199 = new Networks(200, "senectus", c, "vitae dolor fringilla vivamus magna");
        list.add(netw199);
        c.setCountry_id(90);
        Networks netw200 = new Networks(201, "accumsan", c, "faucibus phasellus lorem lectus porttitor");
        list.add(netw200);
        c.setCountry_id(27);
        Networks netw201 = new Networks(202, "ultricies consectetuer", c, "bulum ipsum tempus ligula purus");
        list.add(netw201);
        c.setCountry_id(147);
        Networks netw202 = new Networks(203, "nullam nonummy", c, "laoreet dignissim tortor dictumst habitasse");
        list.add(netw202);
        c.setCountry_id(79);
        Networks netw203 = new Networks(204, "class praesent", c, "nonummy metus scelerisque facilisis dignissim");
        list.add(netw203);
        c.setCountry_id(121);
        Networks netw204 = new Networks(205, "dignissim", c, "interdum pharetra commodo ornare laoreet");
        list.add(netw204);
        c.setCountry_id(37);
        Networks netw205 = new Networks(206, "vivamus", c, "aliquam neque morbi velit libero");
        list.add(netw205);
        c.setCountry_id(56);
        Networks netw206 = new Networks(207, "consequat", c, "vivamus sollicitudin fusce dignissim tortor");
        list.add(netw206);
        c.setCountry_id(83);
        Networks netw207 = new Networks(208, "dignissim", c, "primis commodo commodo consequat sodales");
        list.add(netw207);
        c.setCountry_id(108);
        Networks netw208 = new Networks(209, "tellus vehicula", c, "luctus lorem vitae litora morbi");
        list.add(netw208);
        c.setCountry_id(138);
        Networks netw209 = new Networks(210, "sagittis facilisis", c, "tempor iaculis dignissim iaculis ipsum");
        list.add(netw209);
        c.setCountry_id(68);
        Networks netw210 = new Networks(211, "platea interdum", c, "volutpat metus senectus egestas libero");
        list.add(netw210);
        c.setCountry_id(78);
        Networks netw211 = new Networks(212, "posuere", c, "pharetra congue posuere conubia libero");
        list.add(netw211);
        c.setCountry_id(44);
        Networks netw212 = new Networks(213, "eleifend", c, "fermentum hymenaeos lacus class augue");
        list.add(netw212);
        c.setCountry_id(37);
        Networks netw213 = new Networks(214, "feugiat", c, "nostra phasellus sagittis risus justo");
        list.add(netw213);
        c.setCountry_id(17);
        Networks netw214 = new Networks(215, "ullamcorper", c, "tincidunt adipiscing conubia turpis porta");
        list.add(netw214);
        c.setCountry_id(149);
        Networks netw215 = new Networks(216, "interdum", c, "sollicitudin lorem ornare curae tortor");
        list.add(netw215);
        c.setCountry_id(38);
        Networks netw216 = new Networks(217, "habitasse", c, "aptent ultrices donec primis curae");
        list.add(netw216);
        c.setCountry_id(52);
        Networks netw217 = new Networks(218, "cursus", c, "mauris mauris torquent posuere porta");
        list.add(netw217);
        c.setCountry_id(37);
        Networks netw218 = new Networks(219, "cubilia", c, "cubilia consectetuer molestie donec vehicula");
        list.add(netw218);
        c.setCountry_id(74);
        Networks netw219 = new Networks(220, "ipsum", c, "malesuada dictumst nonummy aliquam maecenas");
        list.add(netw219);
        c.setCountry_id(56);
        Networks netw220 = new Networks(221, "curae", c, "viverra posuere ultricies elementum inceptos");
        list.add(netw220);
        c.setCountry_id(76);
        Networks netw221 = new Networks(222, "integer convallis", c, "imperdiet magna aliquet nulla integer");
        list.add(netw221);
        c.setCountry_id(139);
        Networks netw222 = new Networks(223, "nostra eleifend", c, "posuere congue varius dignissim habitant");
        list.add(netw222);
        c.setCountry_id(98);
        Networks netw223 = new Networks(224, "quisque habitant", c, "primis fringilla laoreet lorem pretium");
        list.add(netw223);
        c.setCountry_id(5);
        Networks netw224 = new Networks(225, "mauris rutrum", c, "habitasse molestie bibendum rutrum taciti");
        list.add(netw224);
        c.setCountry_id(101);
        Networks netw225 = new Networks(226, "ligula adipiscing", c, "hendrerit aptent euismod dolor nostra");
        list.add(netw225);
        c.setCountry_id(67);
        Networks netw226 = new Networks(227, "libero", c, "lacinia turpis vesti rutrum morbi");
        list.add(netw226);
        c.setCountry_id(47);
        Networks netw227 = new Networks(228, "curabitur", c, "aenean dolor curabitur cubilia molestie");
        list.add(netw227);
        c.setCountry_id(36);
        Networks netw228 = new Networks(229, "tempor", c, "ornare turpis mollis pulvinar egestas");
        list.add(netw228);
        c.setCountry_id(10);
        Networks netw229 = new Networks(230, "congue conubia", c, "vitae ornare tumst vesti platea");
        list.add(netw229);
        c.setCountry_id(51);
        Networks netw230 = new Networks(231, "pulvinar nullam", c, "consequat tellus fermentum pellentesque inceptos");
        list.add(netw230);
        c.setCountry_id(14);
        Networks netw231 = new Networks(232, "mauris", c, "euismod varius convallis commodo lectus");
        list.add(netw231);
        c.setCountry_id(63);
        Networks netw232 = new Networks(233, "conubia", c, "fusce sapien nullam lacus cubilia");
        list.add(netw232);
        c.setCountry_id(14);
        Networks netw233 = new Networks(234, "bulum purus", c, "mattis turpis tumst mattis molestie");
        list.add(netw233);
        c.setCountry_id(140);
        Networks netw234 = new Networks(235, "senectus proin", c, "dignissim velit nulla imperdiet vitae");
        list.add(netw234);
        c.setCountry_id(102);
        Networks netw235 = new Networks(236, "ligula", c, "varius congue convallis scelerisque facilisi");
        list.add(netw235);
        c.setCountry_id(63);
        Networks netw236 = new Networks(237, "felis velit", c, "habitant porta fames vesti turpis");
        list.add(netw236);
        c.setCountry_id(38);
        Networks netw237 = new Networks(238, "interdum", c, "habitasse feugiat hymenaeos cursus turpis");
        list.add(netw237);
        c.setCountry_id(146);
        Networks netw238 = new Networks(239, "volutpat fringilla", c, "tempus fringilla morbi senectus etiam");
        list.add(netw238);
        c.setCountry_id(118);
        Networks netw239 = new Networks(240, "venenatis", c, "ultrices lorem ornare tempus lacus");
        list.add(netw239);
        c.setCountry_id(130);
        Networks netw240 = new Networks(241, "aptent fringilla", c, "turpis convallis proin velit aenean");
        list.add(netw240);
        c.setCountry_id(96);
        Networks netw241 = new Networks(242, "dictum", c, "dolor turpis eleifend convallis aptent");
        list.add(netw241);
        c.setCountry_id(77);
        Networks netw242 = new Networks(243, "molestie adipiscing", c, "tempus suspendisse commodo tortor aptent");
        list.add(netw242);
        c.setCountry_id(141);
        Networks netw243 = new Networks(244, "dignissim", c, "vestibulum lobortis cursus vivamus pharetra");
        list.add(netw243);
        c.setCountry_id(90);
        Networks netw244 = new Networks(245, "vesti", c, "sapien wisiaenean tincidunt ultrices taciti");
        list.add(netw244);
        c.setCountry_id(150);
        Networks netw245 = new Networks(246, "nonummy senectus", c, "augue feugiat accumsan congue convallis");
        list.add(netw245);
        c.setCountry_id(50);
        Networks netw246 = new Networks(247, "praesent", c, "sagittis torquent platea tellus platea");
        list.add(netw246);
        c.setCountry_id(106);
        Networks netw247 = new Networks(248, "varius lobortis", c, "interdum scelerisque sollicitudin faucibus eleifend");
        list.add(netw247);
        c.setCountry_id(28);
        Networks netw248 = new Networks(249, "sociosqu etiam", c, "mattis tempus etiam habitant fringilla");
        list.add(netw248);
        c.setCountry_id(22);
        Networks netw249 = new Networks(250, "porttitor", c, "primis inceptos hymenaeos velit feugiat");
        list.add(netw249);
        c.setCountry_id(19);
        Networks netw250 = new Networks(251, "vestibulum semper", c, "mattis cubilia nullam justo porttitor");
        list.add(netw250);
        c.setCountry_id(85);
        Networks netw251 = new Networks(252, "luctus", c, "lobortis lectus vivamus habitant facilisis");
        list.add(netw251);
        c.setCountry_id(148);
        Networks netw252 = new Networks(253, "tempor", c, "nonummy pharetra vivamus placerat tempor");
        list.add(netw252);
        c.setCountry_id(111);
        Networks netw253 = new Networks(254, "laoreet", c, "curabitur nulla curabitur aliquam venenatis");
        list.add(netw253);
        c.setCountry_id(21);
        Networks netw254 = new Networks(255, "dictum", c, "morbi curae aptent hendrerit vitae");
        list.add(netw254);
        c.setCountry_id(57);
        Networks netw255 = new Networks(256, "justo", c, "maecenas inceptos tumst facilisi facilisis");
        list.add(netw255);
        c.setCountry_id(127);
        Networks netw256 = new Networks(257, "facilisisnunc laoreet", c, "platea viverra torquent scelerisque aenean");
        list.add(netw256);
        c.setCountry_id(94);
        Networks netw257 = new Networks(258, "consequat dictum", c, "fringilla sollicitudin conubia nonummy facilisi");
        list.add(netw257);
        c.setCountry_id(7);
        Networks netw258 = new Networks(259, "pulvinar", c, "morbi neque ultricies senectus facilisi");
        list.add(netw258);
        c.setCountry_id(105);
        Networks netw259 = new Networks(260, "dictum facilisis", c, "fringilla convallis egestas faucibus egestas");
        list.add(netw259);
        c.setCountry_id(132);
        Networks netw260 = new Networks(261, "donec", c, "pharetra laoreet facilisi tempor ultrices");
        list.add(netw260);
        c.setCountry_id(147);
        Networks netw261 = new Networks(262, "lacus tempus", c, "eleifend lobortis wisiaenean molestie libero");
        list.add(netw261);
        c.setCountry_id(95);
        Networks netw262 = new Networks(263, "litora", c, "nostra lectus convallis donec sodales");
        list.add(netw262);
        c.setCountry_id(3);
        Networks netw263 = new Networks(264, "curae", c, "rutrum commodo tellus tempor lectus");
        list.add(netw263);
        c.setCountry_id(150);
        Networks netw264 = new Networks(265, "convallis facilisi", c, "luctus vestibulum cursus facilisis turpis");
        list.add(netw264);
        c.setCountry_id(58);
        Networks netw265 = new Networks(266, "vivamus facilisi", c, "consectetuer praesent congue vesti habitant");
        list.add(netw265);
        c.setCountry_id(11);
        Networks netw266 = new Networks(267, "taciti", c, "faucibus wisiaenean venenatis semper libero");
        list.add(netw266);
        c.setCountry_id(134);
        Networks netw267 = new Networks(268, "nonummy", c, "facilisis platea adipiscing magna molestie");
        list.add(netw267);
        c.setCountry_id(132);
        Networks netw268 = new Networks(269, "porttitor", c, "pellentesque sociosqu nullam aliquet wisiaenean");
        list.add(netw268);
        c.setCountry_id(105);
        Networks netw269 = new Networks(270, "facilisisnunc", c, "nostra magna convallis convallis lorem");
        list.add(netw269);
        c.setCountry_id(129);
        Networks netw270 = new Networks(271, "ligula", c, "mattis primis augue cubilia lacinia");
        list.add(netw270);
        c.setCountry_id(149);
        Networks netw271 = new Networks(272, "dignissim conubia", c, "aptent eleifend platea fames taciti");
        list.add(netw271);
        c.setCountry_id(50);
        Networks netw272 = new Networks(273, "eleifend", c, "lectus imperdiet conubia dolor ullamcorper");
        list.add(netw272);
        c.setCountry_id(67);
        Networks netw273 = new Networks(274, "sagittis", c, "praesent lobortis metus sapien augue");
        list.add(netw273);
        c.setCountry_id(5);
        Networks netw274 = new Networks(275, "fermentum fringilla", c, "litora maecenas congue magna ligula");
        list.add(netw274);
        c.setCountry_id(9);
        Networks netw275 = new Networks(276, "justo", c, "nonummy donec cubilia lobortis sodales");
        list.add(netw275);
        c.setCountry_id(89);
        Networks netw276 = new Networks(277, "nonummy felis", c, "magna ipsum dolor risus posuere");
        list.add(netw276);
        c.setCountry_id(60);
        Networks netw277 = new Networks(278, "facilisis", c, "donec sagittis lorem convallis nullam");
        list.add(netw277);
        c.setCountry_id(3);
        Networks netw278 = new Networks(279, "volutpat tempus", c, "nullam libero wisiaenean suspendisse augue");
        list.add(netw278);
        c.setCountry_id(129);
        Networks netw279 = new Networks(280, "porta", c, "metus quisque consequat commodo primis");
        list.add(netw279);
        c.setCountry_id(130);
        Networks netw280 = new Networks(281, "phasellus", c, "commodo eleifend wisiaenean proin vesti");
        list.add(netw280);
        c.setCountry_id(64);
        Networks netw281 = new Networks(282, "etiam", c, "elementum ornare litora maecenas commodo");
        list.add(netw281);
        c.setCountry_id(42);
        Networks netw282 = new Networks(283, "ullamcorper", c, "convallis sociosqu turpis facilisi placerat");
        list.add(netw282);
        c.setCountry_id(36);
        Networks netw283 = new Networks(284, "habitasse", c, "augue vitae etiam euismod euismod");
        list.add(netw283);
        c.setCountry_id(85);
        Networks netw284 = new Networks(285, "sapien posuere", c, "consequat mollis nulla fringilla dictumst");
        list.add(netw284);
        c.setCountry_id(81);
        Networks netw285 = new Networks(286, "rutrum", c, "sodales aenean sagittis proin pretium");
        list.add(netw285);
        c.setCountry_id(74);
        Networks netw286 = new Networks(287, "ultrices", c, "mattis velit wisiaenean semper justo");
        list.add(netw286);
        c.setCountry_id(80);
        Networks netw287 = new Networks(288, "sollicitudin dictumst", c, "dictum rutrum pellentesque lorem pharetra");
        list.add(netw287);
        c.setCountry_id(113);
        Networks netw288 = new Networks(289, "adipiscing", c, "phasellus habitant etiam faucibus conubia");
        list.add(netw288);
        c.setCountry_id(85);
        Networks netw289 = new Networks(290, "molestie ornare", c, "vestibulum bibendum purus nulla senectus");
        list.add(netw289);
        c.setCountry_id(64);
        Networks netw290 = new Networks(291, "elementum", c, "rutrum habitant malesuada tristique cubilia");
        list.add(netw290);
        c.setCountry_id(65);
        Networks netw291 = new Networks(292, "porttitor", c, "tristique primis lorem egestas wisiaenean");
        list.add(netw291);
        c.setCountry_id(51);
        Networks netw292 = new Networks(293, "varius", c, "habitant sapien pellentesque neque ipsum");
        list.add(netw292);
        c.setCountry_id(17);
        Networks netw293 = new Networks(294, "felis", c, "sollicitudin convallis felis curabitur ornare");
        list.add(netw293);
        c.setCountry_id(72);
        Networks netw294 = new Networks(295, "curabitur", c, "interdum dictum ultricies sapien sollicitudin");
        list.add(netw294);
        c.setCountry_id(54);
        Networks netw295 = new Networks(296, "varius sagittis", c, "luctus molestie bulum curae neque");
        list.add(netw295);
        c.setCountry_id(47);
        Networks netw296 = new Networks(297, "cursus luctus", c, "placerat netus euismod volutpat sagittis");
        list.add(netw296);
        c.setCountry_id(127);
        Networks netw297 = new Networks(298, "sapien ligula", c, "sodales augue mattis viverra platea");
        list.add(netw297);
        c.setCountry_id(56);
        Networks netw298 = new Networks(299, "litora netus", c, "adipiscing felis nostra pretium integer");
        list.add(netw298);
        c.setCountry_id(8);
        Networks netw299 = new Networks(300, "dictumst justo", c, "commodo torquent elementum pulvinar neque");
        list.add(netw299);

        		
		Connection con = new Connection();
        con.setCon();
        con.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            networksDBM.insertNetworks(iteration, con);
        });
        con.getCon().getTransaction().commit();
		con.closeCon();

    }
}
