package preInsertions;

import DBManager.BookSeriesDBM;
import Conn.Connection;
import entities.BookSeries;
import enums.SerieTypeEnum;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertBookSeries
{

    BookSeriesDBM bookSeriesDBM = new BookSeriesDBM();
    List<BookSeries> list = new ArrayList<>();

    public void insert() {

        BookSeries bs0 = new BookSeries(1, "fusce velit", 9, SerieTypeEnum.HQ, "tumst maecenas consectetuer consectetuer pellentesque");
        list.add(bs0);
        BookSeries bs1 = new BookSeries(2, "hendrerit", 8, SerieTypeEnum.LIVRO, "feugiat felis justo wisiaenean ullamcorper");
        list.add(bs1);
        BookSeries bs2 = new BookSeries(3, "tempus", 9, SerieTypeEnum.LIVRO, "facilisi habitant cursus lobortis integer");
        list.add(bs2);
        BookSeries bs3 = new BookSeries(4, "praesent suspendisse", 6, SerieTypeEnum.MANGA, "dictumst facilisisnunc auctor tortor class");
        list.add(bs3);
        BookSeries bs4 = new BookSeries(5, "cubilia habitasse", 0, SerieTypeEnum.HQ, "euismod habitant bibendum fusce wisiaenean");
        list.add(bs4);
        BookSeries bs5 = new BookSeries(6, "lectus", 10, SerieTypeEnum.MANGA, "sapien nostra aptent rutrum torquent");
        list.add(bs5);
        BookSeries bs6 = new BookSeries(7, "consectetuer aliquam", 5, SerieTypeEnum.MANGA, "quisque venenatis curabitur justo habitasse");
        list.add(bs6);
        BookSeries bs7 = new BookSeries(8, "varius aptent", 4, SerieTypeEnum.HQ, "molestie nostra vestibulum iaculis semper");
        list.add(bs7);
        BookSeries bs8 = new BookSeries(9, "sodales adipiscing", 10, SerieTypeEnum.HQ, "tristique class accumsan purus etiam");
        list.add(bs8);
        BookSeries bs9 = new BookSeries(10, "litora varius", 10, SerieTypeEnum.LIVRO, "lacinia hymenaeos iaculis interdum velit");
        list.add(bs9);
        BookSeries bs10 = new BookSeries(11, "adipiscing", 4, SerieTypeEnum.MANGA, "donec luctus platea metus aliquet");
        list.add(bs10);
        BookSeries bs11 = new BookSeries(12, "sodales", 9, SerieTypeEnum.HQ, "posuere ligula vesti nostra ullamcorper");
        list.add(bs11);
        BookSeries bs12 = new BookSeries(13, "convallis porta", 5, SerieTypeEnum.MANGA, "risus cubilia facilisis primis taciti");
        list.add(bs12);
        BookSeries bs13 = new BookSeries(14, "velit", 9, SerieTypeEnum.LIVRO, "pretium habitasse vivamus nostra dignissim");
        list.add(bs13);
        BookSeries bs14 = new BookSeries(15, "ipsum tristique", 9, SerieTypeEnum.MANGA, "tortor donec cursus pretium libero");
        list.add(bs14);
        BookSeries bs15 = new BookSeries(16, "porttitor phasellus", 1, SerieTypeEnum.MANGA, "volutpat habitant platea egestas convallis");
        list.add(bs15);
        BookSeries bs16 = new BookSeries(17, "maecenas", 1, SerieTypeEnum.MANGA, "luctus mattis ipsum nostra felis");
        list.add(bs16);
        BookSeries bs17 = new BookSeries(18, "platea", 0, SerieTypeEnum.LIVRO, "consectetuer aliquam velit tortor eleifend");
        list.add(bs17);
        BookSeries bs18 = new BookSeries(19, "volutpat", 6, SerieTypeEnum.MANGA, "commodo felis torquent etiam morbi");
        list.add(bs18);
        BookSeries bs19 = new BookSeries(20, "nulla vivamus", 2, SerieTypeEnum.MANGA, "curae ligula venenatis iaculis taciti");
        list.add(bs19);
        BookSeries bs20 = new BookSeries(21, "aliquet", 6, SerieTypeEnum.LIVRO, "senectus platea nonummy dignissim egestas");
        list.add(bs20);
        BookSeries bs21 = new BookSeries(22, "adipiscing semper", 7, SerieTypeEnum.HQ, "luctus senectus sollicitudin pulvinar feugiat");
        list.add(bs21);
        BookSeries bs22 = new BookSeries(23, "facilisisnunc", 9, SerieTypeEnum.MANGA, "platea ultricies risus mauris tempor");
        list.add(bs22);
        BookSeries bs23 = new BookSeries(24, "faucibus", 5, SerieTypeEnum.LIVRO, "pretium fermentum vestibulum dictum lacus");
        list.add(bs23);
        BookSeries bs24 = new BookSeries(25, "ligula", 4, SerieTypeEnum.LIVRO, "sociosqu ipsum porta donec mollis");
        list.add(bs24);
        BookSeries bs25 = new BookSeries(26, "tempor", 2, SerieTypeEnum.HQ, "dignissim congue suspendisse fames facilisisnunc");
        list.add(bs25);
        BookSeries bs26 = new BookSeries(27, "vivamus", 9, SerieTypeEnum.MANGA, "hendrerit cursus class turpis laoreet");
        list.add(bs26);
        BookSeries bs27 = new BookSeries(28, "ullamcorper", 6, SerieTypeEnum.HQ, "phasellus sollicitudin ultricies habitasse interdum");
        list.add(bs27);
        BookSeries bs28 = new BookSeries(29, "nulla", 3, SerieTypeEnum.HQ, "accumsan accumsan integer mollis purus");
        list.add(bs28);
        BookSeries bs29 = new BookSeries(30, "risus", 7, SerieTypeEnum.HQ, "congue ligula etiam inceptos faucibus");
        list.add(bs29);
        BookSeries bs30 = new BookSeries(31, "suspendisse", 9, SerieTypeEnum.HQ, "tristique metus interdum facilisisnunc senectus");
        list.add(bs30);
        BookSeries bs31 = new BookSeries(32, "dictumst consectetuer", 7, SerieTypeEnum.MANGA, "dictumst aenean placerat tristique nullam");
        list.add(bs31);
        BookSeries bs32 = new BookSeries(33, "porta", 10, SerieTypeEnum.LIVRO, "auctor velit hymenaeos tortor sodales");
        list.add(bs32);
        BookSeries bs33 = new BookSeries(34, "adipiscing tincidunt", 10, SerieTypeEnum.HQ, "porttitor congue senectus felis libero");
        list.add(bs33);
        BookSeries bs34 = new BookSeries(35, "vitae", 10, SerieTypeEnum.MANGA, "ornare posuere torquent ultricies nonummy");
        list.add(bs34);
        BookSeries bs35 = new BookSeries(36, "facilisis interdum", 6, SerieTypeEnum.HQ, "pretium fusce scelerisque sociosqu proin");
        list.add(bs35);
        BookSeries bs36 = new BookSeries(37, "facilisisnunc", 3, SerieTypeEnum.LIVRO, "lacinia posuere proin malesuada rutrum");
        list.add(bs36);
        BookSeries bs37 = new BookSeries(38, "luctus", 8, SerieTypeEnum.HQ, "ultricies habitant libero facilisisnunc tincidunt");
        list.add(bs37);
        BookSeries bs38 = new BookSeries(39, "phasellus", 7, SerieTypeEnum.MANGA, "nonummy class interdum tortor auctor");
        list.add(bs38);
        BookSeries bs39 = new BookSeries(40, "consequat", 4, SerieTypeEnum.LIVRO, "commodo quisque congue placerat cubilia");
        list.add(bs39);
        BookSeries bs40 = new BookSeries(41, "lectus vivamus", 1, SerieTypeEnum.HQ, "imperdiet curabitur habitasse faucibus varius");
        list.add(bs40);
        BookSeries bs41 = new BookSeries(42, "feugiat sapien", 0, SerieTypeEnum.LIVRO, "metus aliquam habitasse cursus habitasse");
        list.add(bs41);
        BookSeries bs42 = new BookSeries(43, "cursus", 9, SerieTypeEnum.LIVRO, "ipsum luctus sociosqu risus varius");
        list.add(bs42);
        BookSeries bs43 = new BookSeries(44, "mattis", 7, SerieTypeEnum.HQ, "iaculis pellentesque commodo vitae nonummy");
        list.add(bs43);
        BookSeries bs44 = new BookSeries(45, "integer", 10, SerieTypeEnum.LIVRO, "risus mollis congue nullam sociosqu");
        list.add(bs44);
        BookSeries bs45 = new BookSeries(46, "dictum auctor", 5, SerieTypeEnum.MANGA, "molestie risus facilisis accumsan cursus");
        list.add(bs45);
        BookSeries bs46 = new BookSeries(47, "sapien bulum", 3, SerieTypeEnum.MANGA, "euismod fames feugiat integer turpis");
        list.add(bs46);
        BookSeries bs47 = new BookSeries(48, "pellentesque", 6, SerieTypeEnum.MANGA, "habitasse facilisisnunc aptent semper praesent");
        list.add(bs47);
        BookSeries bs48 = new BookSeries(49, "ultricies nulla", 9, SerieTypeEnum.LIVRO, "pretium lobortis donec adipiscing imperdiet");
        list.add(bs48);
        BookSeries bs49 = new BookSeries(50, "imperdiet vesti", 0, SerieTypeEnum.HQ, "consequat vivamus scelerisque nulla wisiaenean");
        list.add(bs49);
        BookSeries bs50 = new BookSeries(51, "taciti", 3, SerieTypeEnum.MANGA, "augue torquent vitae laoreet wisiaenean");
        list.add(bs50);
        BookSeries bs51 = new BookSeries(52, "suspendisse", 3, SerieTypeEnum.MANGA, "congue lectus rutrum convallis rutrum");
        list.add(bs51);
        BookSeries bs52 = new BookSeries(53, "laoreet", 1, SerieTypeEnum.LIVRO, "torquent integer proin morbi scelerisque");
        list.add(bs52);
        BookSeries bs53 = new BookSeries(54, "ornare", 3, SerieTypeEnum.LIVRO, "imperdiet feugiat justo lacus ullamcorper");
        list.add(bs53);
        BookSeries bs54 = new BookSeries(55, "praesent ultricies", 4, SerieTypeEnum.MANGA, "interdum scelerisque vesti augue sociosqu");
        list.add(bs54);
        BookSeries bs55 = new BookSeries(56, "ornare", 9, SerieTypeEnum.MANGA, "ornare volutpat mattis iaculis bibendum");
        list.add(bs55);
        BookSeries bs56 = new BookSeries(57, "elementum", 4, SerieTypeEnum.HQ, "venenatis consequat habitant taciti mattis");
        list.add(bs56);
        BookSeries bs57 = new BookSeries(58, "purus", 7, SerieTypeEnum.HQ, "class pharetra commodo aliquam elementum");
        list.add(bs57);
        BookSeries bs58 = new BookSeries(59, "nostra", 5, SerieTypeEnum.MANGA, "morbi sapien integer felis sagittis");
        list.add(bs58);
        BookSeries bs59 = new BookSeries(60, "consequat donec", 6, SerieTypeEnum.LIVRO, "felis litora placerat aptent dignissim");
        list.add(bs59);
        BookSeries bs60 = new BookSeries(61, "aptent", 3, SerieTypeEnum.LIVRO, "feugiat fringilla varius litora etiam");
        list.add(bs60);
        BookSeries bs61 = new BookSeries(62, "dictum", 10, SerieTypeEnum.LIVRO, "maecenas augue dolor mattis habitant");
        list.add(bs61);
        BookSeries bs62 = new BookSeries(63, "wisiaenean", 1, SerieTypeEnum.HQ, "habitant volutpat adipiscing primis tumst");
        list.add(bs62);
        BookSeries bs63 = new BookSeries(64, "tellus", 9, SerieTypeEnum.LIVRO, "pellentesque quisque hymenaeos cubilia hymenaeos");
        list.add(bs63);
        BookSeries bs64 = new BookSeries(65, "nullam", 0, SerieTypeEnum.MANGA, "eleifend donec integer vehicula lorem");
        list.add(bs64);
        BookSeries bs65 = new BookSeries(66, "cubilia", 0, SerieTypeEnum.MANGA, "consequat elementum nonummy nostra interdum");
        list.add(bs65);
        BookSeries bs66 = new BookSeries(67, "phasellus suspendisse", 2, SerieTypeEnum.MANGA, "tortor cubilia pellentesque adipiscing mollis");
        list.add(bs66);
        BookSeries bs67 = new BookSeries(68, "posuere", 1, SerieTypeEnum.HQ, "lorem ullamcorper tumst torquent auctor");
        list.add(bs67);
        BookSeries bs68 = new BookSeries(69, "viverra", 1, SerieTypeEnum.LIVRO, "habitant sapien morbi molestie porttitor");
        list.add(bs68);
        BookSeries bs69 = new BookSeries(70, "iaculis", 10, SerieTypeEnum.LIVRO, "hymenaeos imperdiet porta iaculis nullam");
        list.add(bs69);
        BookSeries bs70 = new BookSeries(71, "purus", 8, SerieTypeEnum.MANGA, "facilisisnunc consectetuer mauris malesuada tempor");
        list.add(bs70);
        BookSeries bs71 = new BookSeries(72, "tincidunt litora", 3, SerieTypeEnum.HQ, "integer molestie lacinia velit fames");
        list.add(bs71);
        BookSeries bs72 = new BookSeries(73, "morbi", 4, SerieTypeEnum.MANGA, "ligula auctor class magna ipsum");
        list.add(bs72);
        BookSeries bs73 = new BookSeries(74, "placerat quisque", 7, SerieTypeEnum.HQ, "elementum dictumst ultricies euismod laoreet");
        list.add(bs73);
        BookSeries bs74 = new BookSeries(75, "porta", 4, SerieTypeEnum.LIVRO, "dictum semper venenatis nonummy convallis");
        list.add(bs74);
        BookSeries bs75 = new BookSeries(76, "fringilla nonummy", 3, SerieTypeEnum.LIVRO, "faucibus malesuada aenean taciti class");
        list.add(bs75);
        BookSeries bs76 = new BookSeries(77, "phasellus", 5, SerieTypeEnum.MANGA, "habitant dictum torquent dictumst tortor");
        list.add(bs76);
        BookSeries bs77 = new BookSeries(78, "accumsan", 2, SerieTypeEnum.HQ, "vesti consequat justo ornare aenean");
        list.add(bs77);
        BookSeries bs78 = new BookSeries(79, "sagittis", 9, SerieTypeEnum.LIVRO, "nullam primis lobortis facilisisnunc elementum");
        list.add(bs78);
        BookSeries bs79 = new BookSeries(80, "curae", 2, SerieTypeEnum.LIVRO, "tellus class nostra bulum donec");
        list.add(bs79);
        BookSeries bs80 = new BookSeries(81, "tellus sodales", 0, SerieTypeEnum.MANGA, "curae volutpat mattis interdum vesti");
        list.add(bs80);
        BookSeries bs81 = new BookSeries(82, "dolor", 3, SerieTypeEnum.LIVRO, "sapien feugiat etiam cursus lorem");
        list.add(bs81);
        BookSeries bs82 = new BookSeries(83, "maecenas", 5, SerieTypeEnum.HQ, "commodo dictumst bulum vesti congue");
        list.add(bs82);
        BookSeries bs83 = new BookSeries(84, "hymenaeos", 6, SerieTypeEnum.LIVRO, "lacinia aptent sodales vesti consectetuer");
        list.add(bs83);
        BookSeries bs84 = new BookSeries(85, "nulla", 7, SerieTypeEnum.MANGA, "tempor volutpat habitant quisque torquent");
        list.add(bs84);
        BookSeries bs85 = new BookSeries(86, "inceptos", 8, SerieTypeEnum.MANGA, "augue semper netus porttitor tumst");
        list.add(bs85);
        BookSeries bs86 = new BookSeries(87, "scelerisque", 4, SerieTypeEnum.LIVRO, "nullam commodo bulum libero vestibulum");
        list.add(bs86);
        BookSeries bs87 = new BookSeries(88, "purus congue", 0, SerieTypeEnum.LIVRO, "adipiscing rutrum purus bibendum vitae");
        list.add(bs87);
        BookSeries bs88 = new BookSeries(89, "metus", 8, SerieTypeEnum.MANGA, "venenatis neque placerat pharetra aenean");
        list.add(bs88);
        BookSeries bs89 = new BookSeries(90, "neque", 10, SerieTypeEnum.MANGA, "dignissim consectetuer lorem tortor bibendum");
        list.add(bs89);
        BookSeries bs90 = new BookSeries(91, "aptent", 2, SerieTypeEnum.LIVRO, "nonummy fringilla convallis wisiaenean vivamus");
        list.add(bs90);
        BookSeries bs91 = new BookSeries(92, "hymenaeos", 2, SerieTypeEnum.HQ, "ultricies tumst porttitor porta tortor");
        list.add(bs91);
        BookSeries bs92 = new BookSeries(93, "conubia", 1, SerieTypeEnum.HQ, "ipsum felis vitae cubilia bulum");
        list.add(bs92);
        BookSeries bs93 = new BookSeries(94, "wisiaenean iaculis", 7, SerieTypeEnum.MANGA, "dignissim aenean laoreet platea mollis");
        list.add(bs93);
        BookSeries bs94 = new BookSeries(95, "sodales faucibus", 8, SerieTypeEnum.HQ, "varius volutpat porta tincidunt pretium");
        list.add(bs94);
        BookSeries bs95 = new BookSeries(96, "tellus", 1, SerieTypeEnum.LIVRO, "felis posuere nostra vitae turpis");
        list.add(bs95);
        BookSeries bs96 = new BookSeries(97, "pulvinar rutrum", 4, SerieTypeEnum.MANGA, "platea senectus mattis libero magna");
        list.add(bs96);
        BookSeries bs97 = new BookSeries(98, "molestie", 8, SerieTypeEnum.MANGA, "sollicitudin platea euismod lectus felis");
        list.add(bs97);
        BookSeries bs98 = new BookSeries(99, "congue", 2, SerieTypeEnum.MANGA, "hendrerit elementum rutrum convallis hymenaeos");
        list.add(bs98);
        BookSeries bs99 = new BookSeries(100, "nullam commodo", 2, SerieTypeEnum.MANGA, "suspendisse porta magna nulla facilisis");
        list.add(bs99);
        BookSeries bs100 = new BookSeries(101, "phasellus donec", 9, SerieTypeEnum.LIVRO, "integer venenatis nullam commodo litora");
        list.add(bs100);
        BookSeries bs101 = new BookSeries(102, "torquent", 0, SerieTypeEnum.MANGA, "habitasse donec dignissim lorem litora");
        list.add(bs101);
        BookSeries bs102 = new BookSeries(103, "consequat", 7, SerieTypeEnum.HQ, "aliquam congue tristique cubilia facilisis");
        list.add(bs102);
        BookSeries bs103 = new BookSeries(104, "habitasse", 4, SerieTypeEnum.MANGA, "maecenas ultricies sollicitudin sociosqu pharetra");
        list.add(bs103);
        BookSeries bs104 = new BookSeries(105, "ligula consequat", 0, SerieTypeEnum.HQ, "pulvinar etiam tempor pellentesque tempor");
        list.add(bs104);
        BookSeries bs105 = new BookSeries(106, "porta", 1, SerieTypeEnum.LIVRO, "tortor tellus nullam mauris consectetuer");
        list.add(bs105);
        BookSeries bs106 = new BookSeries(107, "facilisis", 9, SerieTypeEnum.HQ, "felis tellus phasellus venenatis litora");
        list.add(bs106);
        BookSeries bs107 = new BookSeries(108, "ullamcorper cursus", 4, SerieTypeEnum.MANGA, "semper torquent iaculis conubia hymenaeos");
        list.add(bs107);
        BookSeries bs108 = new BookSeries(109, "fames", 6, SerieTypeEnum.MANGA, "tellus neque ornare dolor adipiscing");
        list.add(bs108);
        BookSeries bs109 = new BookSeries(110, "malesuada", 10, SerieTypeEnum.LIVRO, "ornare netus sodales placerat lacus");
        list.add(bs109);
        BookSeries bs110 = new BookSeries(111, "phasellus aliquet", 5, SerieTypeEnum.MANGA, "congue porta senectus fames vesti");
        list.add(bs110);
        BookSeries bs111 = new BookSeries(112, "molestie", 6, SerieTypeEnum.LIVRO, "velit porttitor fusce feugiat dictumst");
        list.add(bs111);
        BookSeries bs112 = new BookSeries(113, "feugiat", 1, SerieTypeEnum.LIVRO, "rutrum litora congue ornare pulvinar");
        list.add(bs112);
        BookSeries bs113 = new BookSeries(114, "senectus", 1, SerieTypeEnum.MANGA, "ipsum risus bulum pharetra bibendum");
        list.add(bs113);
        BookSeries bs114 = new BookSeries(115, "fringilla", 10, SerieTypeEnum.LIVRO, "convallis sociosqu feugiat malesuada ultrices");
        list.add(bs114);
        BookSeries bs115 = new BookSeries(116, "primis", 6, SerieTypeEnum.LIVRO, "scelerisque proin mauris ultricies luctus");
        list.add(bs115);
        BookSeries bs116 = new BookSeries(117, "posuere", 4, SerieTypeEnum.HQ, "ultricies bulum proin accumsan fusce");
        list.add(bs116);
        BookSeries bs117 = new BookSeries(118, "tortor", 2, SerieTypeEnum.LIVRO, "iaculis vehicula libero pellentesque integer");
        list.add(bs117);
        BookSeries bs118 = new BookSeries(119, "sapien", 6, SerieTypeEnum.MANGA, "nullam molestie quisque inceptos sapien");
        list.add(bs118);
        BookSeries bs119 = new BookSeries(120, "fermentum", 1, SerieTypeEnum.LIVRO, "tempor dolor mollis aliquam proin");
        list.add(bs119);
        BookSeries bs120 = new BookSeries(121, "sollicitudin tempus", 3, SerieTypeEnum.MANGA, "inceptos semper auctor nullam risus");
        list.add(bs120);
        BookSeries bs121 = new BookSeries(122, "proin class", 3, SerieTypeEnum.HQ, "libero lobortis malesuada imperdiet ornare");
        list.add(bs121);
        BookSeries bs122 = new BookSeries(123, "praesent", 10, SerieTypeEnum.HQ, "phasellus vivamus rutrum fermentum interdum");
        list.add(bs122);
        BookSeries bs123 = new BookSeries(124, "fringilla", 9, SerieTypeEnum.MANGA, "vitae bulum neque aliquam pretium");
        list.add(bs123);
        BookSeries bs124 = new BookSeries(125, "nostra quisque", 6, SerieTypeEnum.MANGA, "fames convallis suspendisse etiam vehicula");
        list.add(bs124);
        BookSeries bs125 = new BookSeries(126, "congue", 6, SerieTypeEnum.MANGA, "quisque neque vivamus posuere semper");
        list.add(bs125);
        BookSeries bs126 = new BookSeries(127, "ullamcorper faucibus", 3, SerieTypeEnum.LIVRO, "rutrum augue dictum sagittis facilisi");
        list.add(bs126);
        BookSeries bs127 = new BookSeries(128, "imperdiet", 8, SerieTypeEnum.MANGA, "vesti vehicula etiam fames aenean");
        list.add(bs127);
        BookSeries bs128 = new BookSeries(129, "tristique", 2, SerieTypeEnum.MANGA, "auctor elementum pharetra pellentesque magna");
        list.add(bs128);
        BookSeries bs129 = new BookSeries(130, "pretium", 7, SerieTypeEnum.HQ, "inceptos mollis vitae mattis aenean");
        list.add(bs129);
        BookSeries bs130 = new BookSeries(131, "felis", 7, SerieTypeEnum.HQ, "augue lacinia fames luctus mauris");
        list.add(bs130);
        BookSeries bs131 = new BookSeries(132, "wisiaenean elementum", 3, SerieTypeEnum.MANGA, "inceptos sociosqu viverra fermentum bulum");
        list.add(bs131);
        BookSeries bs132 = new BookSeries(133, "nonummy", 6, SerieTypeEnum.HQ, "fermentum tristique tempus pulvinar feugiat");
        list.add(bs132);
        BookSeries bs133 = new BookSeries(134, "nostra nostra", 1, SerieTypeEnum.MANGA, "ullamcorper molestie netus ipsum pretium");
        list.add(bs133);
        BookSeries bs134 = new BookSeries(135, "facilisis", 2, SerieTypeEnum.MANGA, "dolor hymenaeos purus proin ligula");
        list.add(bs134);
        BookSeries bs135 = new BookSeries(136, "aenean", 6, SerieTypeEnum.MANGA, "vestibulum semper curae tumst tumst");
        list.add(bs135);
        BookSeries bs136 = new BookSeries(137, "vesti", 2, SerieTypeEnum.HQ, "ornare tristique turpis consequat platea");
        list.add(bs136);
        BookSeries bs137 = new BookSeries(138, "convallis", 6, SerieTypeEnum.MANGA, "lacinia magna dignissim facilisis tortor");
        list.add(bs137);
        BookSeries bs138 = new BookSeries(139, "felis", 10, SerieTypeEnum.MANGA, "nullam malesuada ullamcorper torquent ultrices");
        list.add(bs138);
        BookSeries bs139 = new BookSeries(140, "vehicula imperdiet", 9, SerieTypeEnum.MANGA, "nulla mattis sapien posuere pulvinar");
        list.add(bs139);
        BookSeries bs140 = new BookSeries(141, "integer nostra", 1, SerieTypeEnum.HQ, "habitasse velit libero curae hendrerit");
        list.add(bs140);
        BookSeries bs141 = new BookSeries(142, "magna", 10, SerieTypeEnum.HQ, "aliquet senectus cubilia lectus consequat");
        list.add(bs141);
        BookSeries bs142 = new BookSeries(143, "sodales", 4, SerieTypeEnum.LIVRO, "elementum porttitor dictumst litora pretium");
        list.add(bs142);
        BookSeries bs143 = new BookSeries(144, "curabitur", 3, SerieTypeEnum.HQ, "tincidunt interdum lacus cubilia fringilla");
        list.add(bs143);
        BookSeries bs144 = new BookSeries(145, "lobortis", 7, SerieTypeEnum.HQ, "lorem hendrerit ipsum litora tempus");
        list.add(bs144);
        BookSeries bs145 = new BookSeries(146, "elementum nulla", 3, SerieTypeEnum.HQ, "torquent quisque rutrum praesent dignissim");
        list.add(bs145);
        BookSeries bs146 = new BookSeries(147, "sapien", 6, SerieTypeEnum.HQ, "sociosqu tempor bibendum facilisis purus");
        list.add(bs146);
        BookSeries bs147 = new BookSeries(148, "egestas", 5, SerieTypeEnum.LIVRO, "viverra mollis venenatis metus curabitur");
        list.add(bs147);
        BookSeries bs148 = new BookSeries(149, "vestibulum", 10, SerieTypeEnum.HQ, "sollicitudin accumsan tumst laoreet feugiat");
        list.add(bs148);
        BookSeries bs149 = new BookSeries(150, "mauris", 6, SerieTypeEnum.LIVRO, "elementum lacinia ullamcorper suspendisse euismod");
        list.add(bs149);
        BookSeries bs150 = new BookSeries(151, "porttitor eleifend", 10, SerieTypeEnum.MANGA, "nulla conubia congue adipiscing mauris");
        list.add(bs150);
        BookSeries bs151 = new BookSeries(152, "tempor", 7, SerieTypeEnum.LIVRO, "ligula consectetuer tellus aptent lacus");
        list.add(bs151);
        BookSeries bs152 = new BookSeries(153, "mauris", 6, SerieTypeEnum.LIVRO, "justo phasellus tincidunt turpis ligula");
        list.add(bs152);
        BookSeries bs153 = new BookSeries(154, "consectetuer", 3, SerieTypeEnum.LIVRO, "lobortis velit luctus fames litora");
        list.add(bs153);
        BookSeries bs154 = new BookSeries(155, "felis", 8, SerieTypeEnum.LIVRO, "facilisi proin justo sociosqu egestas");
        list.add(bs154);
        BookSeries bs155 = new BookSeries(156, "ligula", 10, SerieTypeEnum.MANGA, "euismod malesuada elementum tumst lacus");
        list.add(bs155);
        BookSeries bs156 = new BookSeries(157, "nullam", 6, SerieTypeEnum.LIVRO, "netus lacus vestibulum metus vestibulum");
        list.add(bs156);
        BookSeries bs157 = new BookSeries(158, "tempus", 0, SerieTypeEnum.LIVRO, "varius tempus euismod aliquam elementum");
        list.add(bs157);
        BookSeries bs158 = new BookSeries(159, "mattis adipiscing", 7, SerieTypeEnum.MANGA, "habitasse nulla mauris congue auctor");
        list.add(bs158);
        BookSeries bs159 = new BookSeries(160, "fames", 5, SerieTypeEnum.MANGA, "scelerisque felis mollis taciti rutrum");
        list.add(bs159);
        BookSeries bs160 = new BookSeries(161, "vesti", 5, SerieTypeEnum.MANGA, "bibendum proin phasellus lacus iaculis");
        list.add(bs160);
        BookSeries bs161 = new BookSeries(162, "torquent dolor", 5, SerieTypeEnum.MANGA, "lacus egestas pellentesque ullamcorper iaculis");
        list.add(bs161);
        BookSeries bs162 = new BookSeries(163, "lectus", 8, SerieTypeEnum.HQ, "convallis donec vestibulum congue dolor");
        list.add(bs162);
        BookSeries bs163 = new BookSeries(164, "maecenas", 5, SerieTypeEnum.HQ, "taciti iaculis laoreet fames bibendum");
        list.add(bs163);
        BookSeries bs164 = new BookSeries(165, "nulla", 4, SerieTypeEnum.HQ, "netus netus tellus sodales convallis");
        list.add(bs164);
        BookSeries bs165 = new BookSeries(166, "consectetuer", 1, SerieTypeEnum.HQ, "etiam nonummy libero justo phasellus");
        list.add(bs165);
        BookSeries bs166 = new BookSeries(167, "dictum", 10, SerieTypeEnum.MANGA, "sollicitudin lorem commodo varius scelerisque");
        list.add(bs166);
        BookSeries bs167 = new BookSeries(168, "platea morbi", 9, SerieTypeEnum.LIVRO, "tristique aenean imperdiet tumst sodales");
        list.add(bs167);
        BookSeries bs168 = new BookSeries(169, "velit", 3, SerieTypeEnum.MANGA, "facilisi consectetuer taciti hymenaeos congue");
        list.add(bs168);
        BookSeries bs169 = new BookSeries(170, "senectus cursus", 4, SerieTypeEnum.LIVRO, "ornare sollicitudin commodo justo pulvinar");
        list.add(bs169);
        BookSeries bs170 = new BookSeries(171, "fames", 7, SerieTypeEnum.HQ, "pretium libero morbi fames conubia");
        list.add(bs170);
        BookSeries bs171 = new BookSeries(172, "adipiscing placerat", 5, SerieTypeEnum.MANGA, "bulum euismod felis lacus bibendum");
        list.add(bs171);
        BookSeries bs172 = new BookSeries(173, "maecenas", 4, SerieTypeEnum.MANGA, "luctus varius tumst taciti fames");
        list.add(bs172);
        BookSeries bs173 = new BookSeries(174, "neque", 5, SerieTypeEnum.LIVRO, "platea dictum commodo ultrices ultrices");
        list.add(bs173);
        BookSeries bs174 = new BookSeries(175, "rutrum purus", 2, SerieTypeEnum.LIVRO, "lacinia libero curae laoreet ultrices");
        list.add(bs174);
        BookSeries bs175 = new BookSeries(176, "viverra", 4, SerieTypeEnum.HQ, "metus litora interdum feugiat integer");
        list.add(bs175);
        BookSeries bs176 = new BookSeries(177, "tincidunt", 1, SerieTypeEnum.HQ, "feugiat bibendum malesuada tellus consectetuer");
        list.add(bs176);
        BookSeries bs177 = new BookSeries(178, "aliquam", 9, SerieTypeEnum.HQ, "malesuada dictum quisque luctus tempor");
        list.add(bs177);
        BookSeries bs178 = new BookSeries(179, "euismod hymenaeos", 6, SerieTypeEnum.HQ, "turpis facilisisnunc maecenas mollis lorem");
        list.add(bs178);
        BookSeries bs179 = new BookSeries(180, "tempor", 10, SerieTypeEnum.LIVRO, "primis hendrerit lacus eleifend placerat");
        list.add(bs179);
        BookSeries bs180 = new BookSeries(181, "metus", 3, SerieTypeEnum.LIVRO, "tincidunt viverra vestibulum felis auctor");
        list.add(bs180);
        BookSeries bs181 = new BookSeries(182, "porta fermentum", 2, SerieTypeEnum.HQ, "praesent vesti primis auctor fames");
        list.add(bs181);
        BookSeries bs182 = new BookSeries(183, "cursus", 10, SerieTypeEnum.MANGA, "rutrum donec magna dolor conubia");
        list.add(bs182);
        BookSeries bs183 = new BookSeries(184, "facilisis", 1, SerieTypeEnum.MANGA, "senectus proin senectus aenean netus");
        list.add(bs183);
        BookSeries bs184 = new BookSeries(185, "lobortis", 2, SerieTypeEnum.MANGA, "ligula purus pellentesque ornare ligula");
        list.add(bs184);
        BookSeries bs185 = new BookSeries(186, "quisque", 9, SerieTypeEnum.HQ, "mattis bulum interdum pharetra sollicitudin");
        list.add(bs185);
        BookSeries bs186 = new BookSeries(187, "adipiscing volutpat", 7, SerieTypeEnum.MANGA, "nullam dolor felis sapien lacinia");
        list.add(bs186);
        BookSeries bs187 = new BookSeries(188, "porttitor cursus", 7, SerieTypeEnum.LIVRO, "vesti tempor ultrices consectetuer dignissim");
        list.add(bs187);
        BookSeries bs188 = new BookSeries(189, "aptent torquent", 3, SerieTypeEnum.HQ, "vehicula adipiscing vitae curae congue");
        list.add(bs188);
        BookSeries bs189 = new BookSeries(190, "interdum tortor", 1, SerieTypeEnum.LIVRO, "tristique lacus curabitur wisiaenean accumsan");
        list.add(bs189);
        BookSeries bs190 = new BookSeries(191, "congue vitae", 8, SerieTypeEnum.MANGA, "mollis egestas taciti faucibus auctor");
        list.add(bs190);
        BookSeries bs191 = new BookSeries(192, "platea", 8, SerieTypeEnum.MANGA, "hymenaeos tristique nonummy ligula facilisi");
        list.add(bs191);
        BookSeries bs192 = new BookSeries(193, "inceptos", 8, SerieTypeEnum.MANGA, "placerat senectus magna tristique curae");
        list.add(bs192);
        BookSeries bs193 = new BookSeries(194, "pellentesque", 0, SerieTypeEnum.MANGA, "tortor venenatis sodales tempus tumst");
        list.add(bs193);
        BookSeries bs194 = new BookSeries(195, "torquent", 10, SerieTypeEnum.HQ, "fusce justo faucibus aptent eleifend");
        list.add(bs194);
        BookSeries bs195 = new BookSeries(196, "integer pulvinar", 3, SerieTypeEnum.MANGA, "semper felis neque imperdiet mollis");
        list.add(bs195);
        BookSeries bs196 = new BookSeries(197, "posuere", 5, SerieTypeEnum.LIVRO, "tempus dolor justo etiam donec");
        list.add(bs196);
        BookSeries bs197 = new BookSeries(198, "magna", 4, SerieTypeEnum.LIVRO, "ullamcorper habitasse porttitor facilisis vitae");
        list.add(bs197);
        BookSeries bs198 = new BookSeries(199, "vehicula class", 1, SerieTypeEnum.LIVRO, "nullam maecenas habitasse lectus vesti");
        list.add(bs198);
        BookSeries bs199 = new BookSeries(200, "libero", 2, SerieTypeEnum.LIVRO, "interdum tempor inceptos tempor aliquam");
        list.add(bs199);
        BookSeries bs200 = new BookSeries(201, "dictum semper", 8, SerieTypeEnum.LIVRO, "curae tempor interdum libero vesti");
        list.add(bs200);
        BookSeries bs201 = new BookSeries(202, "euismod ipsum", 7, SerieTypeEnum.MANGA, "integer tempus proin hymenaeos cursus");
        list.add(bs201);
        BookSeries bs202 = new BookSeries(203, "maecenas laoreet", 1, SerieTypeEnum.LIVRO, "congue ultricies risus augue facilisis");
        list.add(bs202);
        BookSeries bs203 = new BookSeries(204, "egestas", 8, SerieTypeEnum.MANGA, "laoreet adipiscing molestie nulla mollis");
        list.add(bs203);
        BookSeries bs204 = new BookSeries(205, "sociosqu", 1, SerieTypeEnum.LIVRO, "integer inceptos fusce augue sagittis");
        list.add(bs204);
        BookSeries bs205 = new BookSeries(206, "metus morbi", 0, SerieTypeEnum.HQ, "egestas lectus praesent facilisi sodales");
        list.add(bs205);
        BookSeries bs206 = new BookSeries(207, "ligula justo", 7, SerieTypeEnum.HQ, "ornare aptent velit vehicula ultricies");
        list.add(bs206);
        BookSeries bs207 = new BookSeries(208, "wisiaenean", 4, SerieTypeEnum.LIVRO, "justo nonummy lacinia consequat quisque");
        list.add(bs207);
        BookSeries bs208 = new BookSeries(209, "porttitor lectus", 2, SerieTypeEnum.HQ, "phasellus proin facilisisnunc curae porta");
        list.add(bs208);
        BookSeries bs209 = new BookSeries(210, "taciti", 5, SerieTypeEnum.LIVRO, "facilisi consequat aenean habitant augue");
        list.add(bs209);
        BookSeries bs210 = new BookSeries(211, "ligula", 4, SerieTypeEnum.MANGA, "dignissim cubilia posuere molestie magna");
        list.add(bs210);
        BookSeries bs211 = new BookSeries(212, "torquent ultrices", 3, SerieTypeEnum.HQ, "laoreet adipiscing neque bulum taciti");
        list.add(bs211);
        BookSeries bs212 = new BookSeries(213, "habitasse interdum", 3, SerieTypeEnum.LIVRO, "lobortis facilisis libero risus aenean");
        list.add(bs212);
        BookSeries bs213 = new BookSeries(214, "lacinia", 1, SerieTypeEnum.HQ, "elementum mattis interdum faucibus eleifend");
        list.add(bs213);
        BookSeries bs214 = new BookSeries(215, "congue dolor", 5, SerieTypeEnum.MANGA, "porta malesuada hymenaeos quisque justo");
        list.add(bs214);
        BookSeries bs215 = new BookSeries(216, "hymenaeos", 1, SerieTypeEnum.LIVRO, "accumsan conubia vivamus porta aptent");
        list.add(bs215);
        BookSeries bs216 = new BookSeries(217, "integer", 0, SerieTypeEnum.HQ, "mattis laoreet velit velit ullamcorper");
        list.add(bs216);
        BookSeries bs217 = new BookSeries(218, "mattis", 6, SerieTypeEnum.MANGA, "dignissim phasellus dictumst posuere egestas");
        list.add(bs217);
        BookSeries bs218 = new BookSeries(219, "faucibus", 4, SerieTypeEnum.LIVRO, "maecenas mollis facilisisnunc cursus netus");
        list.add(bs218);
        BookSeries bs219 = new BookSeries(220, "fringilla", 0, SerieTypeEnum.LIVRO, "justo conubia cubilia nullam taciti");
        list.add(bs219);
        BookSeries bs220 = new BookSeries(221, "curae praesent", 7, SerieTypeEnum.LIVRO, "elementum ullamcorper integer senectus bulum");
        list.add(bs220);
        BookSeries bs221 = new BookSeries(222, "platea", 9, SerieTypeEnum.HQ, "scelerisque malesuada ligula tempor malesuada");
        list.add(bs221);
        BookSeries bs222 = new BookSeries(223, "porttitor", 4, SerieTypeEnum.LIVRO, "platea rutrum habitant faucibus dignissim");
        list.add(bs222);
        BookSeries bs223 = new BookSeries(224, "lorem", 3, SerieTypeEnum.LIVRO, "volutpat lorem inceptos lobortis egestas");
        list.add(bs223);
        BookSeries bs224 = new BookSeries(225, "feugiat", 7, SerieTypeEnum.MANGA, "ultrices platea mauris feugiat nullam");
        list.add(bs224);
        BookSeries bs225 = new BookSeries(226, "phasellus", 10, SerieTypeEnum.LIVRO, "magna commodo taciti mattis nostra");
        list.add(bs225);
        BookSeries bs226 = new BookSeries(227, "dictumst interdum", 0, SerieTypeEnum.MANGA, "etiam senectus accumsan integer facilisis");
        list.add(bs226);
        BookSeries bs227 = new BookSeries(228, "interdum", 0, SerieTypeEnum.MANGA, "vivamus facilisi maecenas sagittis nonummy");
        list.add(bs227);
        BookSeries bs228 = new BookSeries(229, "faucibus fermentum", 4, SerieTypeEnum.HQ, "mauris ultricies ullamcorper imperdiet eleifend");
        list.add(bs228);
        BookSeries bs229 = new BookSeries(230, "convallis", 1, SerieTypeEnum.MANGA, "varius interdum euismod torquent euismod");
        list.add(bs229);
        BookSeries bs230 = new BookSeries(231, "porttitor", 9, SerieTypeEnum.HQ, "senectus fames libero faucibus integer");
        list.add(bs230);
        BookSeries bs231 = new BookSeries(232, "ullamcorper", 9, SerieTypeEnum.HQ, "semper rutrum molestie nulla nulla");
        list.add(bs231);
        BookSeries bs232 = new BookSeries(233, "vestibulum", 5, SerieTypeEnum.MANGA, "nostra justo interdum donec varius");
        list.add(bs232);
        BookSeries bs233 = new BookSeries(234, "dictumst", 4, SerieTypeEnum.LIVRO, "luctus volutpat mattis senectus litora");
        list.add(bs233);
        BookSeries bs234 = new BookSeries(235, "scelerisque", 5, SerieTypeEnum.HQ, "scelerisque congue porttitor dolor velit");
        list.add(bs234);
        BookSeries bs235 = new BookSeries(236, "commodo", 0, SerieTypeEnum.HQ, "class rutrum pretium risus primis");
        list.add(bs235);
        BookSeries bs236 = new BookSeries(237, "conubia", 10, SerieTypeEnum.MANGA, "pellentesque phasellus class curae lobortis");
        list.add(bs236);
        BookSeries bs237 = new BookSeries(238, "integer", 3, SerieTypeEnum.MANGA, "venenatis lacus habitasse morbi iaculis");
        list.add(bs237);
        BookSeries bs238 = new BookSeries(239, "facilisis", 0, SerieTypeEnum.HQ, "bibendum morbi tumst nostra wisiaenean");
        list.add(bs238);
        BookSeries bs239 = new BookSeries(240, "ullamcorper ornare", 8, SerieTypeEnum.MANGA, "aliquet curabitur porta mattis imperdiet");
        list.add(bs239);
        BookSeries bs240 = new BookSeries(241, "consequat", 3, SerieTypeEnum.HQ, "cubilia inceptos pharetra vehicula proin");
        list.add(bs240);
        BookSeries bs241 = new BookSeries(242, "taciti commodo", 10, SerieTypeEnum.HQ, "semper tempor auctor facilisis semper");
        list.add(bs241);
        BookSeries bs242 = new BookSeries(243, "congue aliquam", 7, SerieTypeEnum.MANGA, "neque luctus curae bibendum nulla");
        list.add(bs242);
        BookSeries bs243 = new BookSeries(244, "facilisi", 3, SerieTypeEnum.HQ, "velit fames senectus fusce fusce");
        list.add(bs243);
        BookSeries bs244 = new BookSeries(245, "elementum tortor", 6, SerieTypeEnum.MANGA, "ultrices tristique posuere sagittis phasellus");
        list.add(bs244);
        BookSeries bs245 = new BookSeries(246, "pharetra", 2, SerieTypeEnum.HQ, "laoreet bibendum hendrerit ligula nullam");
        list.add(bs245);
        BookSeries bs246 = new BookSeries(247, "bulum commodo", 2, SerieTypeEnum.LIVRO, "primis tumst varius venenatis integer");
        list.add(bs246);
        BookSeries bs247 = new BookSeries(248, "maecenas", 10, SerieTypeEnum.LIVRO, "lectus mollis fusce lacinia inceptos");
        list.add(bs247);
        BookSeries bs248 = new BookSeries(249, "ullamcorper congue", 1, SerieTypeEnum.HQ, "fusce placerat imperdiet congue curae");
        list.add(bs248);
        BookSeries bs249 = new BookSeries(250, "consectetuer lacinia", 1, SerieTypeEnum.HQ, "neque consectetuer dictumst cursus platea");
        list.add(bs249);
        BookSeries bs250 = new BookSeries(251, "venenatis", 6, SerieTypeEnum.LIVRO, "cursus hymenaeos egestas imperdiet interdum");
        list.add(bs250);
        BookSeries bs251 = new BookSeries(252, "pulvinar platea", 6, SerieTypeEnum.LIVRO, "consectetuer donec eleifend ornare viverra");
        list.add(bs251);
        BookSeries bs252 = new BookSeries(253, "inceptos", 8, SerieTypeEnum.MANGA, "tincidunt ultricies metus ornare lobortis");
        list.add(bs252);
        BookSeries bs253 = new BookSeries(254, "elementum consequat", 0, SerieTypeEnum.LIVRO, "inceptos imperdiet euismod tempus cubilia");
        list.add(bs253);
        BookSeries bs254 = new BookSeries(255, "fermentum pretium", 0, SerieTypeEnum.HQ, "facilisisnunc tumst auctor faucibus tempor");
        list.add(bs254);
        BookSeries bs255 = new BookSeries(256, "tristique placerat", 0, SerieTypeEnum.HQ, "posuere scelerisque tellus laoreet placerat");
        list.add(bs255);
        BookSeries bs256 = new BookSeries(257, "torquent", 3, SerieTypeEnum.LIVRO, "donec auctor tincidunt elementum ultricies");
        list.add(bs256);
        BookSeries bs257 = new BookSeries(258, "consequat", 0, SerieTypeEnum.HQ, "tristique volutpat sociosqu cubilia senectus");
        list.add(bs257);
        BookSeries bs258 = new BookSeries(259, "congue habitasse", 8, SerieTypeEnum.MANGA, "sollicitudin senectus commodo facilisis ultricies");
        list.add(bs258);
        BookSeries bs259 = new BookSeries(260, "aliquet inceptos", 8, SerieTypeEnum.MANGA, "quisque posuere aliquam placerat semper");
        list.add(bs259);
        BookSeries bs260 = new BookSeries(261, "aliquet", 6, SerieTypeEnum.HQ, "elementum egestas bulum mollis lectus");
        list.add(bs260);
        BookSeries bs261 = new BookSeries(262, "pretium", 9, SerieTypeEnum.MANGA, "placerat sodales laoreet auctor facilisi");
        list.add(bs261);
        BookSeries bs262 = new BookSeries(263, "cursus phasellus", 9, SerieTypeEnum.LIVRO, "bibendum ullamcorper risus hendrerit justo");
        list.add(bs262);
        BookSeries bs263 = new BookSeries(264, "interdum", 1, SerieTypeEnum.HQ, "mollis ornare volutpat turpis dignissim");
        list.add(bs263);
        BookSeries bs264 = new BookSeries(265, "vesti", 9, SerieTypeEnum.HQ, "commodo porta malesuada sodales dignissim");
        list.add(bs264);
        BookSeries bs265 = new BookSeries(266, "vitae", 8, SerieTypeEnum.MANGA, "pulvinar eleifend curabitur fusce senectus");
        list.add(bs265);
        BookSeries bs266 = new BookSeries(267, "porttitor", 3, SerieTypeEnum.LIVRO, "aliquet morbi lorem consectetuer fermentum");
        list.add(bs266);
        BookSeries bs267 = new BookSeries(268, "fermentum felis", 6, SerieTypeEnum.MANGA, "imperdiet accumsan vesti elementum felis");
        list.add(bs267);
        BookSeries bs268 = new BookSeries(269, "risus", 9, SerieTypeEnum.HQ, "quisque dignissim netus posuere conubia");
        list.add(bs268);
        BookSeries bs269 = new BookSeries(270, "hendrerit", 1, SerieTypeEnum.HQ, "aptent habitant dictumst dictum mollis");
        list.add(bs269);
        BookSeries bs270 = new BookSeries(271, "volutpat lobortis", 6, SerieTypeEnum.HQ, "ultrices elementum risus tincidunt lobortis");
        list.add(bs270);
        BookSeries bs271 = new BookSeries(272, "sagittis", 0, SerieTypeEnum.MANGA, "platea tincidunt sodales nullam praesent");
        list.add(bs271);
        BookSeries bs272 = new BookSeries(273, "mauris", 10, SerieTypeEnum.HQ, "taciti primis ornare ornare elementum");
        list.add(bs272);
        BookSeries bs273 = new BookSeries(274, "porttitor", 4, SerieTypeEnum.LIVRO, "commodo torquent scelerisque magna quisque");
        list.add(bs273);
        BookSeries bs274 = new BookSeries(275, "interdum", 8, SerieTypeEnum.HQ, "habitant fusce fringilla lorem lacus");
        list.add(bs274);
        BookSeries bs275 = new BookSeries(276, "tellus pulvinar", 10, SerieTypeEnum.HQ, "vivamus porta torquent pretium tellus");
        list.add(bs275);
        BookSeries bs276 = new BookSeries(277, "ullamcorper magna", 8, SerieTypeEnum.MANGA, "fermentum senectus facilisis platea vesti");
        list.add(bs276);
        BookSeries bs277 = new BookSeries(278, "curae", 6, SerieTypeEnum.MANGA, "rutrum morbi semper posuere tristique");
        list.add(bs277);
        BookSeries bs278 = new BookSeries(279, "tortor", 8, SerieTypeEnum.MANGA, "morbi pretium aptent quisque justo");
        list.add(bs278);
        BookSeries bs279 = new BookSeries(280, "aenean", 3, SerieTypeEnum.HQ, "inceptos vitae sollicitudin luctus inceptos");
        list.add(bs279);
        BookSeries bs280 = new BookSeries(281, "magna", 9, SerieTypeEnum.HQ, "pretium accumsan dignissim molestie convallis");
        list.add(bs280);
        BookSeries bs281 = new BookSeries(282, "ullamcorper", 8, SerieTypeEnum.HQ, "quisque porttitor bulum rutrum ipsum");
        list.add(bs281);
        BookSeries bs282 = new BookSeries(283, "fusce accumsan", 9, SerieTypeEnum.LIVRO, "tumst turpis pretium elementum cubilia");
        list.add(bs282);
        BookSeries bs283 = new BookSeries(284, "tempus", 1, SerieTypeEnum.HQ, "libero nullam donec pharetra fames");
        list.add(bs283);
        BookSeries bs284 = new BookSeries(285, "aptent aliquam", 0, SerieTypeEnum.HQ, "pharetra aliquam netus cursus pulvinar");
        list.add(bs284);
        BookSeries bs285 = new BookSeries(286, "neque", 6, SerieTypeEnum.HQ, "lectus maecenas tristique eleifend bulum");
        list.add(bs285);
        BookSeries bs286 = new BookSeries(287, "platea varius", 9, SerieTypeEnum.MANGA, "class mollis lobortis consectetuer quisque");
        list.add(bs286);
        BookSeries bs287 = new BookSeries(288, "posuere", 4, SerieTypeEnum.LIVRO, "nonummy etiam sagittis eleifend vesti");
        list.add(bs287);
        BookSeries bs288 = new BookSeries(289, "quisque", 0, SerieTypeEnum.HQ, "vehicula lacus litora lacus magna");
        list.add(bs288);
        BookSeries bs289 = new BookSeries(290, "mollis mattis", 2, SerieTypeEnum.HQ, "wisiaenean pulvinar magna scelerisque sapien");
        list.add(bs289);
        BookSeries bs290 = new BookSeries(291, "elementum", 0, SerieTypeEnum.LIVRO, "ullamcorper ultricies commodo etiam ultricies");
        list.add(bs290);
        BookSeries bs291 = new BookSeries(292, "taciti", 6, SerieTypeEnum.HQ, "consequat auctor quisque cubilia bulum");
        list.add(bs291);
        BookSeries bs292 = new BookSeries(293, "primis", 6, SerieTypeEnum.MANGA, "viverra consequat luctus scelerisque habitant");
        list.add(bs292);
        BookSeries bs293 = new BookSeries(294, "ullamcorper", 2, SerieTypeEnum.LIVRO, "cubilia euismod porttitor mauris hendrerit");
        list.add(bs293);
        BookSeries bs294 = new BookSeries(295, "sapien", 2, SerieTypeEnum.MANGA, "fames volutpat nostra tempus consectetuer");
        list.add(bs294);
        BookSeries bs295 = new BookSeries(296, "platea sociosqu", 7, SerieTypeEnum.HQ, "sollicitudin praesent quisque vestibulum nonummy");
        list.add(bs295);
        BookSeries bs296 = new BookSeries(297, "hendrerit", 6, SerieTypeEnum.LIVRO, "donec vitae ultrices facilisi tellus");
        list.add(bs296);
        BookSeries bs297 = new BookSeries(298, "feugiat", 7, SerieTypeEnum.LIVRO, "morbi commodo nostra senectus pharetra");
        list.add(bs297);
        BookSeries bs298 = new BookSeries(299, "maecenas", 7, SerieTypeEnum.MANGA, "lorem neque accumsan malesuada sagittis");
        list.add(bs298);
        BookSeries bs299 = new BookSeries(300, "libero", 6, SerieTypeEnum.MANGA, "facilisi justo consequat mattis aenean");
        list.add(bs299);
        BookSeries bs300 = new BookSeries(301, "justo", 8, SerieTypeEnum.HQ, "vestibulum wisiaenean ornare pretium nonummy");
        list.add(bs300);
        BookSeries bs301 = new BookSeries(302, "aliquam inceptos", 1, SerieTypeEnum.HQ, "praesent lacinia adipiscing mollis taciti");
        list.add(bs301);
        BookSeries bs302 = new BookSeries(303, "morbi", 6, SerieTypeEnum.HQ, "cursus eleifend malesuada quisque phasellus");
        list.add(bs302);
        BookSeries bs303 = new BookSeries(304, "tortor litora", 2, SerieTypeEnum.MANGA, "purus pulvinar posuere lacinia dictum");
        list.add(bs303);
        BookSeries bs304 = new BookSeries(305, "habitasse sociosqu", 4, SerieTypeEnum.LIVRO, "maecenas curae sodales sodales nulla");
        list.add(bs304);
        BookSeries bs305 = new BookSeries(306, "eleifend", 6, SerieTypeEnum.HQ, "ipsum aenean class curabitur tellus");
        list.add(bs305);
        BookSeries bs306 = new BookSeries(307, "lacus", 9, SerieTypeEnum.LIVRO, "vitae inceptos aliquam curae ipsum");
        list.add(bs306);
        BookSeries bs307 = new BookSeries(308, "nullam magna", 10, SerieTypeEnum.LIVRO, "sodales convallis auctor dictum maecenas");
        list.add(bs307);
        BookSeries bs308 = new BookSeries(309, "sociosqu", 4, SerieTypeEnum.LIVRO, "metus justo proin elementum bibendum");
        list.add(bs308);
        BookSeries bs309 = new BookSeries(310, "fames", 10, SerieTypeEnum.MANGA, "lobortis pretium maecenas ornare accumsan");
        list.add(bs309);
        BookSeries bs310 = new BookSeries(311, "sodales sapien", 2, SerieTypeEnum.MANGA, "feugiat hymenaeos volutpat imperdiet iaculis");
        list.add(bs310);
        BookSeries bs311 = new BookSeries(312, "vesti", 2, SerieTypeEnum.MANGA, "sapien torquent congue tempor facilisi");
        list.add(bs311);
        BookSeries bs312 = new BookSeries(313, "convallis", 4, SerieTypeEnum.MANGA, "aenean tempus porta laoreet ultricies");
        list.add(bs312);
        BookSeries bs313 = new BookSeries(314, "lectus", 10, SerieTypeEnum.HQ, "ornare lorem congue conubia pharetra");
        list.add(bs313);
        BookSeries bs314 = new BookSeries(315, "taciti", 2, SerieTypeEnum.HQ, "pulvinar tempus consequat dolor pellentesque");
        list.add(bs314);
        BookSeries bs315 = new BookSeries(316, "ornare dolor", 8, SerieTypeEnum.MANGA, "tellus aliquet consectetuer scelerisque vivamus");
        list.add(bs315);
        BookSeries bs316 = new BookSeries(317, "conubia", 8, SerieTypeEnum.MANGA, "purus viverra bibendum egestas ultrices");
        list.add(bs316);
        BookSeries bs317 = new BookSeries(318, "aptent", 2, SerieTypeEnum.LIVRO, "eleifend vestibulum turpis praesent commodo");
        list.add(bs317);
        BookSeries bs318 = new BookSeries(319, "tortor", 7, SerieTypeEnum.MANGA, "sociosqu feugiat pharetra dolor quisque");
        list.add(bs318);
        BookSeries bs319 = new BookSeries(320, "mattis purus", 5, SerieTypeEnum.LIVRO, "porta ornare lacinia maecenas iaculis");
        list.add(bs319);
        BookSeries bs320 = new BookSeries(321, "ornare", 1, SerieTypeEnum.LIVRO, "metus rutrum volutpat rutrum pharetra");
        list.add(bs320);
        BookSeries bs321 = new BookSeries(322, "mollis bibendum", 7, SerieTypeEnum.LIVRO, "lacinia dolor scelerisque porttitor molestie");
        list.add(bs321);
        BookSeries bs322 = new BookSeries(323, "tortor", 1, SerieTypeEnum.HQ, "malesuada fusce molestie cubilia cubilia");
        list.add(bs322);
        BookSeries bs323 = new BookSeries(324, "commodo", 10, SerieTypeEnum.MANGA, "vitae ornare hendrerit morbi torquent");
        list.add(bs323);
        BookSeries bs324 = new BookSeries(325, "viverra", 9, SerieTypeEnum.HQ, "consectetuer tempor magna volutpat venenatis");
        list.add(bs324);
        BookSeries bs325 = new BookSeries(326, "vesti maecenas", 3, SerieTypeEnum.LIVRO, "mattis habitant magna porttitor turpis");
        list.add(bs325);
        BookSeries bs326 = new BookSeries(327, "vesti", 7, SerieTypeEnum.HQ, "semper tincidunt dignissim tempor fermentum");
        list.add(bs326);
        BookSeries bs327 = new BookSeries(328, "suspendisse", 1, SerieTypeEnum.MANGA, "donec lectus auctor vivamus aptent");
        list.add(bs327);
        BookSeries bs328 = new BookSeries(329, "justo", 0, SerieTypeEnum.LIVRO, "egestas rutrum mattis mollis facilisi");
        list.add(bs328);
        BookSeries bs329 = new BookSeries(330, "augue", 6, SerieTypeEnum.HQ, "faucibus tellus taciti facilisisnunc class");
        list.add(bs329);
        BookSeries bs330 = new BookSeries(331, "vesti", 7, SerieTypeEnum.MANGA, "tempor pellentesque lobortis aenean habitant");
        list.add(bs330);
        BookSeries bs331 = new BookSeries(332, "dictum", 4, SerieTypeEnum.LIVRO, "congue tumst bibendum lacus fermentum");
        list.add(bs331);
        BookSeries bs332 = new BookSeries(333, "ullamcorper", 10, SerieTypeEnum.HQ, "adipiscing dolor mauris placerat porttitor");
        list.add(bs332);
        BookSeries bs333 = new BookSeries(334, "taciti", 2, SerieTypeEnum.HQ, "pharetra pretium vestibulum nostra felis");
        list.add(bs333);
        BookSeries bs334 = new BookSeries(335, "vehicula consequat", 10, SerieTypeEnum.HQ, "facilisisnunc sagittis facilisis eleifend mattis");
        list.add(bs334);
        BookSeries bs335 = new BookSeries(336, "bibendum", 7, SerieTypeEnum.LIVRO, "curabitur sapien fermentum facilisis imperdiet");
        list.add(bs335);
        BookSeries bs336 = new BookSeries(337, "consequat", 9, SerieTypeEnum.MANGA, "congue tempus consectetuer mauris lacinia");
        list.add(bs336);
        BookSeries bs337 = new BookSeries(338, "porta", 2, SerieTypeEnum.LIVRO, "justo facilisi praesent malesuada augue");
        list.add(bs337);
        BookSeries bs338 = new BookSeries(339, "proin", 3, SerieTypeEnum.LIVRO, "aliquet nostra interdum primis metus");
        list.add(bs338);
        BookSeries bs339 = new BookSeries(340, "vestibulum", 4, SerieTypeEnum.MANGA, "proin nonummy turpis magna posuere");
        list.add(bs339);
        BookSeries bs340 = new BookSeries(341, "aliquam", 4, SerieTypeEnum.HQ, "adipiscing feugiat feugiat ornare ullamcorper");
        list.add(bs340);
        BookSeries bs341 = new BookSeries(342, "fermentum", 7, SerieTypeEnum.HQ, "lobortis adipiscing consectetuer ullamcorper aptent");
        list.add(bs341);
        BookSeries bs342 = new BookSeries(343, "habitant", 2, SerieTypeEnum.MANGA, "tumst platea lacus dictum tellus");
        list.add(bs342);
        BookSeries bs343 = new BookSeries(344, "dictumst imperdiet", 8, SerieTypeEnum.HQ, "aenean tellus pharetra conubia malesuada");
        list.add(bs343);
        BookSeries bs344 = new BookSeries(345, "lectus", 7, SerieTypeEnum.HQ, "luctus turpis libero wisiaenean bibendum");
        list.add(bs344);
        BookSeries bs345 = new BookSeries(346, "curae", 4, SerieTypeEnum.MANGA, "iaculis nullam consequat wisiaenean sociosqu");
        list.add(bs345);
        BookSeries bs346 = new BookSeries(347, "pretium", 9, SerieTypeEnum.MANGA, "tristique rutrum augue morbi curae");
        list.add(bs346);
        BookSeries bs347 = new BookSeries(348, "turpis", 8, SerieTypeEnum.LIVRO, "taciti pellentesque semper aptent integer");
        list.add(bs347);
        BookSeries bs348 = new BookSeries(349, "iaculis sodales", 4, SerieTypeEnum.LIVRO, "pharetra lacinia facilisis bibendum tempor");
        list.add(bs348);
        BookSeries bs349 = new BookSeries(350, "faucibus", 1, SerieTypeEnum.HQ, "hendrerit porta magna fusce maecenas");
        list.add(bs349);
        BookSeries bs350 = new BookSeries(351, "habitant tempor", 10, SerieTypeEnum.HQ, "habitasse ipsum molestie cubilia semper");
        list.add(bs350);
        BookSeries bs351 = new BookSeries(352, "praesent", 7, SerieTypeEnum.HQ, "lorem viverra nostra risus euismod");
        list.add(bs351);
        BookSeries bs352 = new BookSeries(353, "quisque", 3, SerieTypeEnum.MANGA, "consectetuer primis faucibus faucibus venenatis");
        list.add(bs352);
        BookSeries bs353 = new BookSeries(354, "fusce", 7, SerieTypeEnum.MANGA, "fermentum etiam hymenaeos molestie primis");
        list.add(bs353);
        BookSeries bs354 = new BookSeries(355, "aliquet quisque", 2, SerieTypeEnum.HQ, "varius fusce pretium morbi tempus");
        list.add(bs354);
        BookSeries bs355 = new BookSeries(356, "senectus", 5, SerieTypeEnum.MANGA, "etiam morbi facilisisnunc aliquam purus");
        list.add(bs355);
        BookSeries bs356 = new BookSeries(357, "mattis", 3, SerieTypeEnum.MANGA, "hendrerit laoreet porttitor aliquet lectus");
        list.add(bs356);
        BookSeries bs357 = new BookSeries(358, "augue", 0, SerieTypeEnum.LIVRO, "purus magna viverra accumsan purus");
        list.add(bs357);
        BookSeries bs358 = new BookSeries(359, "congue hymenaeos", 1, SerieTypeEnum.HQ, "pulvinar nonummy mauris mollis hendrerit");
        list.add(bs358);
        BookSeries bs359 = new BookSeries(360, "cursus habitasse", 10, SerieTypeEnum.HQ, "morbi vesti dictumst dolor praesent");
        list.add(bs359);
        BookSeries bs360 = new BookSeries(361, "tortor", 2, SerieTypeEnum.LIVRO, "inceptos feugiat magna volutpat curabitur");
        list.add(bs360);
        BookSeries bs361 = new BookSeries(362, "lobortis aenean", 6, SerieTypeEnum.MANGA, "purus tempus facilisi interdum magna");
        list.add(bs361);
        BookSeries bs362 = new BookSeries(363, "tristique", 8, SerieTypeEnum.LIVRO, "vehicula tristique dolor congue fermentum");
        list.add(bs362);
        BookSeries bs363 = new BookSeries(364, "vitae fusce", 3, SerieTypeEnum.LIVRO, "auctor facilisisnunc phasellus ullamcorper magna");
        list.add(bs363);
        BookSeries bs364 = new BookSeries(365, "class lobortis", 5, SerieTypeEnum.HQ, "aliquam platea semper sollicitudin dolor");
        list.add(bs364);
        BookSeries bs365 = new BookSeries(366, "cubilia", 3, SerieTypeEnum.HQ, "tellus aliquet fusce cubilia phasellus");
        list.add(bs365);
        BookSeries bs366 = new BookSeries(367, "porttitor", 8, SerieTypeEnum.HQ, "tempor cubilia pharetra mauris pharetra");
        list.add(bs366);
        BookSeries bs367 = new BookSeries(368, "torquent porta", 9, SerieTypeEnum.HQ, "dictumst vivamus proin rutrum commodo");
        list.add(bs367);
        BookSeries bs368 = new BookSeries(369, "tortor", 10, SerieTypeEnum.HQ, "lacus lorem interdum wisiaenean vivamus");
        list.add(bs368);
        BookSeries bs369 = new BookSeries(370, "volutpat", 7, SerieTypeEnum.LIVRO, "elementum eleifend platea turpis quisque");
        list.add(bs369);
        BookSeries bs370 = new BookSeries(371, "fames volutpat", 8, SerieTypeEnum.MANGA, "pellentesque tumst pellentesque torquent convallis");
        list.add(bs370);
        BookSeries bs371 = new BookSeries(372, "libero", 10, SerieTypeEnum.LIVRO, "tempus vitae metus tortor primis");
        list.add(bs371);
        BookSeries bs372 = new BookSeries(373, "posuere vesti", 1, SerieTypeEnum.LIVRO, "felis tortor euismod nonummy praesent");
        list.add(bs372);
        BookSeries bs373 = new BookSeries(374, "lobortis", 3, SerieTypeEnum.HQ, "luctus vestibulum sagittis integer imperdiet");
        list.add(bs373);
        BookSeries bs374 = new BookSeries(375, "turpis", 9, SerieTypeEnum.HQ, "semper neque taciti felis volutpat");
        list.add(bs374);
        BookSeries bs375 = new BookSeries(376, "facilisi vesti", 3, SerieTypeEnum.LIVRO, "eleifend pellentesque tempus ipsum taciti");
        list.add(bs375);
        BookSeries bs376 = new BookSeries(377, "adipiscing", 3, SerieTypeEnum.MANGA, "sagittis tristique habitasse ultrices aliquam");
        list.add(bs376);
        BookSeries bs377 = new BookSeries(378, "tristique", 7, SerieTypeEnum.HQ, "dignissim taciti pharetra porttitor facilisis");
        list.add(bs377);
        BookSeries bs378 = new BookSeries(379, "velit", 5, SerieTypeEnum.HQ, "viverra facilisi tristique ipsum nulla");
        list.add(bs378);
        BookSeries bs379 = new BookSeries(380, "sodales taciti", 1, SerieTypeEnum.MANGA, "pharetra pharetra egestas tempor accumsan");
        list.add(bs379);
        BookSeries bs380 = new BookSeries(381, "cursus", 5, SerieTypeEnum.MANGA, "adipiscing libero ipsum porta curae");
        list.add(bs380);
        BookSeries bs381 = new BookSeries(382, "adipiscing lorem", 8, SerieTypeEnum.LIVRO, "vesti conubia viverra ultricies pharetra");
        list.add(bs381);
        BookSeries bs382 = new BookSeries(383, "viverra", 10, SerieTypeEnum.MANGA, "augue aliquam curabitur tellus elementum");
        list.add(bs382);
        BookSeries bs383 = new BookSeries(384, "porta consequat", 7, SerieTypeEnum.HQ, "viverra wisiaenean posuere ligula netus");
        list.add(bs383);
        BookSeries bs384 = new BookSeries(385, "tempor", 6, SerieTypeEnum.LIVRO, "nostra proin mauris consequat lectus");
        list.add(bs384);
        BookSeries bs385 = new BookSeries(386, "tumst", 1, SerieTypeEnum.HQ, "litora ipsum hymenaeos vitae nullam");
        list.add(bs385);
        BookSeries bs386 = new BookSeries(387, "mauris", 7, SerieTypeEnum.LIVRO, "imperdiet suspendisse mattis habitasse vehicula");
        list.add(bs386);
        BookSeries bs387 = new BookSeries(388, "pharetra pharetra", 3, SerieTypeEnum.LIVRO, "congue accumsan nullam praesent vehicula");
        list.add(bs387);
        BookSeries bs388 = new BookSeries(389, "eleifend", 1, SerieTypeEnum.LIVRO, "bulum velit auctor bulum felis");
        list.add(bs388);
        BookSeries bs389 = new BookSeries(390, "neque vehicula", 2, SerieTypeEnum.HQ, "maecenas aliquet ullamcorper mollis imperdiet");
        list.add(bs389);
        BookSeries bs390 = new BookSeries(391, "tincidunt", 2, SerieTypeEnum.MANGA, "vivamus euismod sodales interdum lorem");
        list.add(bs390);
        BookSeries bs391 = new BookSeries(392, "tellus", 4, SerieTypeEnum.HQ, "aliquam hymenaeos imperdiet felis viverra");
        list.add(bs391);
        BookSeries bs392 = new BookSeries(393, "elementum", 4, SerieTypeEnum.MANGA, "commodo ultricies suspendisse habitasse sapien");
        list.add(bs392);
        BookSeries bs393 = new BookSeries(394, "fames commodo", 1, SerieTypeEnum.HQ, "proin consequat purus mattis justo");
        list.add(bs393);
        BookSeries bs394 = new BookSeries(395, "tellus", 5, SerieTypeEnum.LIVRO, "bibendum hendrerit netus porta praesent");
        list.add(bs394);
        BookSeries bs395 = new BookSeries(396, "dictum laoreet", 10, SerieTypeEnum.MANGA, "primis litora felis primis molestie");
        list.add(bs395);
        BookSeries bs396 = new BookSeries(397, "auctor egestas", 8, SerieTypeEnum.MANGA, "ullamcorper ipsum sociosqu sociosqu bibendum");
        list.add(bs396);
        BookSeries bs397 = new BookSeries(398, "tortor", 0, SerieTypeEnum.MANGA, "cursus curae curabitur sodales taciti");
        list.add(bs397);
        BookSeries bs398 = new BookSeries(399, "integer lectus", 7, SerieTypeEnum.MANGA, "class dictum eleifend justo accumsan");
        list.add(bs398);
        BookSeries bs399 = new BookSeries(400, "porta class", 0, SerieTypeEnum.MANGA, "elementum dictum aptent vestibulum interdum");
        list.add(bs399);
        BookSeries bs400 = new BookSeries(401, "sollicitudin", 0, SerieTypeEnum.HQ, "tempor morbi auctor turpis rutrum");
        list.add(bs400);
        BookSeries bs401 = new BookSeries(402, "curabitur imperdiet", 4, SerieTypeEnum.MANGA, "wisiaenean habitasse litora tumst molestie");
        list.add(bs401);
        BookSeries bs402 = new BookSeries(403, "adipiscing", 2, SerieTypeEnum.HQ, "lectus habitant velit ullamcorper primis");
        list.add(bs402);
        BookSeries bs403 = new BookSeries(404, "porttitor", 2, SerieTypeEnum.HQ, "suspendisse egestas purus inceptos placerat");
        list.add(bs403);
        BookSeries bs404 = new BookSeries(405, "cubilia", 0, SerieTypeEnum.MANGA, "cursus egestas tellus fames justo");
        list.add(bs404);
        BookSeries bs405 = new BookSeries(406, "dictum", 4, SerieTypeEnum.HQ, "praesent maecenas interdum placerat elementum");
        list.add(bs405);
        BookSeries bs406 = new BookSeries(407, "taciti egestas", 8, SerieTypeEnum.HQ, "vivamus morbi tortor facilisi aenean");
        list.add(bs406);
        BookSeries bs407 = new BookSeries(408, "turpis", 2, SerieTypeEnum.LIVRO, "metus proin ornare posuere laoreet");
        list.add(bs407);
        BookSeries bs408 = new BookSeries(409, "metus", 3, SerieTypeEnum.LIVRO, "suspendisse fermentum hymenaeos lorem proin");
        list.add(bs408);
        BookSeries bs409 = new BookSeries(410, "nullam hendrerit", 0, SerieTypeEnum.LIVRO, "sodales semper porttitor quisque curae");
        list.add(bs409);
        BookSeries bs410 = new BookSeries(411, "fames", 9, SerieTypeEnum.MANGA, "venenatis hendrerit laoreet class tempor");
        list.add(bs410);
        BookSeries bs411 = new BookSeries(412, "dolor", 6, SerieTypeEnum.LIVRO, "facilisi iaculis semper inceptos torquent");
        list.add(bs411);
        BookSeries bs412 = new BookSeries(413, "etiam", 10, SerieTypeEnum.LIVRO, "molestie facilisi viverra libero porttitor");
        list.add(bs412);
        BookSeries bs413 = new BookSeries(414, "luctus", 5, SerieTypeEnum.HQ, "mollis torquent ultricies nonummy consequat");
        list.add(bs413);
        BookSeries bs414 = new BookSeries(415, "facilisis", 4, SerieTypeEnum.HQ, "ullamcorper lacinia metus iaculis placerat");
        list.add(bs414);
        BookSeries bs415 = new BookSeries(416, "nostra", 9, SerieTypeEnum.LIVRO, "malesuada curabitur sollicitudin viverra elementum");
        list.add(bs415);
        BookSeries bs416 = new BookSeries(417, "turpis facilisisnunc", 4, SerieTypeEnum.MANGA, "pharetra justo ullamcorper tumst ipsum");
        list.add(bs416);
        BookSeries bs417 = new BookSeries(418, "ornare ligula", 1, SerieTypeEnum.MANGA, "tristique egestas pulvinar neque faucibus");
        list.add(bs417);
        BookSeries bs418 = new BookSeries(419, "placerat", 8, SerieTypeEnum.MANGA, "aenean risus ullamcorper wisiaenean neque");
        list.add(bs418);
        BookSeries bs419 = new BookSeries(420, "fusce", 9, SerieTypeEnum.MANGA, "interdum wisiaenean fames aptent nostra");
        list.add(bs419);
        BookSeries bs420 = new BookSeries(421, "luctus", 8, SerieTypeEnum.HQ, "aenean conubia hendrerit purus fermentum");
        list.add(bs420);
        BookSeries bs421 = new BookSeries(422, "facilisis", 4, SerieTypeEnum.HQ, "egestas pretium litora fames senectus");
        list.add(bs421);
        BookSeries bs422 = new BookSeries(423, "platea", 0, SerieTypeEnum.LIVRO, "scelerisque varius velit integer vestibulum");
        list.add(bs422);
        BookSeries bs423 = new BookSeries(424, "consectetuer mauris", 0, SerieTypeEnum.HQ, "bulum aptent tincidunt fames ullamcorper");
        list.add(bs423);
        BookSeries bs424 = new BookSeries(425, "platea", 0, SerieTypeEnum.LIVRO, "egestas ligula feugiat cubilia vivamus");
        list.add(bs424);
        BookSeries bs425 = new BookSeries(426, "elementum", 4, SerieTypeEnum.LIVRO, "dignissim iaculis interdum sagittis porttitor");
        list.add(bs425);
        BookSeries bs426 = new BookSeries(427, "commodo", 3, SerieTypeEnum.HQ, "fermentum varius sagittis libero feugiat");
        list.add(bs426);
        BookSeries bs427 = new BookSeries(428, "ipsum", 3, SerieTypeEnum.LIVRO, "faucibus mattis nonummy nonummy habitant");
        list.add(bs427);
        BookSeries bs428 = new BookSeries(429, "posuere", 1, SerieTypeEnum.LIVRO, "molestie tempor praesent placerat iaculis");
        list.add(bs428);
        BookSeries bs429 = new BookSeries(430, "rutrum", 3, SerieTypeEnum.MANGA, "fringilla laoreet interdum felis scelerisque");
        list.add(bs429);
        BookSeries bs430 = new BookSeries(431, "curabitur facilisisnunc", 4, SerieTypeEnum.HQ, "tellus maecenas pretium netus semper");
        list.add(bs430);
        BookSeries bs431 = new BookSeries(432, "hymenaeos", 3, SerieTypeEnum.HQ, "bibendum morbi malesuada platea convallis");
        list.add(bs431);
        BookSeries bs432 = new BookSeries(433, "cursus libero", 3, SerieTypeEnum.HQ, "rutrum risus augue bibendum posuere");
        list.add(bs432);
        BookSeries bs433 = new BookSeries(434, "fermentum", 8, SerieTypeEnum.HQ, "habitant rutrum vivamus dictum iaculis");
        list.add(bs433);
        BookSeries bs434 = new BookSeries(435, "justo", 8, SerieTypeEnum.MANGA, "sapien quisque tristique vesti faucibus");
        list.add(bs434);
        BookSeries bs435 = new BookSeries(436, "libero", 3, SerieTypeEnum.LIVRO, "maecenas tempor lorem habitasse faucibus");
        list.add(bs435);
        BookSeries bs436 = new BookSeries(437, "faucibus risus", 5, SerieTypeEnum.HQ, "tristique posuere lorem aenean egestas");
        list.add(bs436);
        BookSeries bs437 = new BookSeries(438, "euismod", 2, SerieTypeEnum.LIVRO, "fames mollis adipiscing curabitur class");
        list.add(bs437);
        BookSeries bs438 = new BookSeries(439, "vivamus", 10, SerieTypeEnum.MANGA, "hendrerit pharetra lacus mattis porttitor");
        list.add(bs438);
        BookSeries bs439 = new BookSeries(440, "suspendisse risus", 6, SerieTypeEnum.HQ, "rutrum iaculis turpis risus torquent");
        list.add(bs439);
        BookSeries bs440 = new BookSeries(441, "habitant", 6, SerieTypeEnum.HQ, "platea egestas netus vestibulum inceptos");
        list.add(bs440);
        BookSeries bs441 = new BookSeries(442, "eleifend", 8, SerieTypeEnum.HQ, "augue taciti curabitur volutpat ligula");
        list.add(bs441);
        BookSeries bs442 = new BookSeries(443, "curae", 8, SerieTypeEnum.MANGA, "velit tellus mollis placerat vehicula");
        list.add(bs442);
        BookSeries bs443 = new BookSeries(444, "euismod litora", 6, SerieTypeEnum.LIVRO, "felis tumst lacinia facilisisnunc pretium");
        list.add(bs443);
        BookSeries bs444 = new BookSeries(445, "praesent etiam", 8, SerieTypeEnum.LIVRO, "purus tumst luctus tortor commodo");
        list.add(bs444);
        BookSeries bs445 = new BookSeries(446, "libero porttitor", 9, SerieTypeEnum.HQ, "class nostra interdum feugiat integer");
        list.add(bs445);
        BookSeries bs446 = new BookSeries(447, "taciti", 3, SerieTypeEnum.MANGA, "hendrerit dictumst aenean conubia maecenas");
        list.add(bs446);
        BookSeries bs447 = new BookSeries(448, "pretium feugiat", 1, SerieTypeEnum.MANGA, "conubia velit venenatis tempus pretium");
        list.add(bs447);
        BookSeries bs448 = new BookSeries(449, "turpis tempus", 2, SerieTypeEnum.MANGA, "congue cursus viverra taciti curae");
        list.add(bs448);
        BookSeries bs449 = new BookSeries(450, "habitant varius", 6, SerieTypeEnum.LIVRO, "lacus inceptos hymenaeos mollis tumst");
        list.add(bs449);
        BookSeries bs450 = new BookSeries(451, "vesti interdum", 5, SerieTypeEnum.LIVRO, "ultricies pulvinar conubia auctor tumst");
        list.add(bs450);
        BookSeries bs451 = new BookSeries(452, "dignissim", 1, SerieTypeEnum.HQ, "mattis sollicitudin neque magna consectetuer");
        list.add(bs451);
        BookSeries bs452 = new BookSeries(453, "tempus mauris", 0, SerieTypeEnum.HQ, "tincidunt curae pellentesque sodales sapien");
        list.add(bs452);
        BookSeries bs453 = new BookSeries(454, "phasellus", 3, SerieTypeEnum.MANGA, "libero scelerisque accumsan conubia ornare");
        list.add(bs453);
        BookSeries bs454 = new BookSeries(455, "venenatis", 7, SerieTypeEnum.LIVRO, "vehicula rutrum lobortis pellentesque ligula");
        list.add(bs454);
        BookSeries bs455 = new BookSeries(456, "placerat", 10, SerieTypeEnum.LIVRO, "molestie congue hymenaeos egestas magna");
        list.add(bs455);
        BookSeries bs456 = new BookSeries(457, "pulvinar", 2, SerieTypeEnum.MANGA, "netus torquent accumsan vitae laoreet");
        list.add(bs456);
        BookSeries bs457 = new BookSeries(458, "netus", 6, SerieTypeEnum.MANGA, "conubia congue nostra sodales etiam");
        list.add(bs457);
        BookSeries bs458 = new BookSeries(459, "accumsan adipiscing", 4, SerieTypeEnum.LIVRO, "commodo vivamus tempus consectetuer rutrum");
        list.add(bs458);
        BookSeries bs459 = new BookSeries(460, "consequat", 4, SerieTypeEnum.HQ, "lobortis litora auctor sodales consectetuer");
        list.add(bs459);
        BookSeries bs460 = new BookSeries(461, "posuere", 3, SerieTypeEnum.HQ, "facilisisnunc dolor lobortis velit tellus");
        list.add(bs460);
        BookSeries bs461 = new BookSeries(462, "sapien tumst", 6, SerieTypeEnum.MANGA, "litora molestie dignissim morbi dolor");
        list.add(bs461);
        BookSeries bs462 = new BookSeries(463, "bulum", 0, SerieTypeEnum.MANGA, "placerat lacus ligula sagittis wisiaenean");
        list.add(bs462);
        BookSeries bs463 = new BookSeries(464, "tempus", 2, SerieTypeEnum.MANGA, "facilisi senectus habitasse aenean aliquam");
        list.add(bs463);
        BookSeries bs464 = new BookSeries(465, "tincidunt", 0, SerieTypeEnum.HQ, "tumst ornare molestie laoreet conubia");
        list.add(bs464);
        BookSeries bs465 = new BookSeries(466, "eleifend", 0, SerieTypeEnum.HQ, "pellentesque justo consequat praesent fermentum");
        list.add(bs465);
        BookSeries bs466 = new BookSeries(467, "dolor", 6, SerieTypeEnum.HQ, "facilisi euismod aptent molestie euismod");
        list.add(bs466);
        BookSeries bs467 = new BookSeries(468, "justo", 2, SerieTypeEnum.MANGA, "fermentum iaculis lobortis hendrerit sociosqu");
        list.add(bs467);
        BookSeries bs468 = new BookSeries(469, "ornare", 1, SerieTypeEnum.MANGA, "accumsan lobortis aliquam venenatis congue");
        list.add(bs468);
        BookSeries bs469 = new BookSeries(470, "praesent lacinia", 9, SerieTypeEnum.LIVRO, "ligula quisque lacus adipiscing egestas");
        list.add(bs469);
        BookSeries bs470 = new BookSeries(471, "commodo", 9, SerieTypeEnum.HQ, "metus senectus accumsan sollicitudin pretium");
        list.add(bs470);
        BookSeries bs471 = new BookSeries(472, "felis primis", 7, SerieTypeEnum.MANGA, "adipiscing auctor fusce maecenas sollicitudin");
        list.add(bs471);
        BookSeries bs472 = new BookSeries(473, "proin", 2, SerieTypeEnum.MANGA, "cubilia ultrices class aptent faucibus");
        list.add(bs472);
        BookSeries bs473 = new BookSeries(474, "fringilla lacinia", 7, SerieTypeEnum.MANGA, "litora porttitor tumst felis vitae");
        list.add(bs473);
        BookSeries bs474 = new BookSeries(475, "praesent semper", 10, SerieTypeEnum.MANGA, "auctor viverra venenatis adipiscing venenatis");
        list.add(bs474);
        BookSeries bs475 = new BookSeries(476, "sociosqu nostra", 10, SerieTypeEnum.LIVRO, "vesti molestie lacinia fermentum vitae");
        list.add(bs475);
        BookSeries bs476 = new BookSeries(477, "senectus dignissim", 4, SerieTypeEnum.LIVRO, "nonummy cursus habitant porta suspendisse");
        list.add(bs476);
        BookSeries bs477 = new BookSeries(478, "phasellus purus", 2, SerieTypeEnum.MANGA, "lorem venenatis aenean fames lectus");
        list.add(bs477);
        BookSeries bs478 = new BookSeries(479, "sodales", 9, SerieTypeEnum.HQ, "dictum vehicula vehicula maecenas dolor");
        list.add(bs478);
        BookSeries bs479 = new BookSeries(480, "sapien", 2, SerieTypeEnum.LIVRO, "mauris lacus mauris egestas lectus");
        list.add(bs479);
        BookSeries bs480 = new BookSeries(481, "quisque", 0, SerieTypeEnum.LIVRO, "elementum adipiscing conubia curae hendrerit");
        list.add(bs480);
        BookSeries bs481 = new BookSeries(482, "tempor turpis", 10, SerieTypeEnum.MANGA, "phasellus pellentesque quisque feugiat volutpat");
        list.add(bs481);
        BookSeries bs482 = new BookSeries(483, "magna", 0, SerieTypeEnum.LIVRO, "semper tincidunt morbi euismod hendrerit");
        list.add(bs482);
        BookSeries bs483 = new BookSeries(484, "posuere", 8, SerieTypeEnum.HQ, "quisque elementum venenatis torquent ipsum");
        list.add(bs483);
        BookSeries bs484 = new BookSeries(485, "nullam", 1, SerieTypeEnum.MANGA, "tristique aptent laoreet consequat mauris");
        list.add(bs484);
        BookSeries bs485 = new BookSeries(486, "phasellus", 7, SerieTypeEnum.LIVRO, "vivamus tristique curae ipsum ligula");
        list.add(bs485);
        BookSeries bs486 = new BookSeries(487, "etiam scelerisque", 4, SerieTypeEnum.MANGA, "hymenaeos porttitor dolor feugiat sapien");
        list.add(bs486);
        BookSeries bs487 = new BookSeries(488, "volutpat", 7, SerieTypeEnum.HQ, "interdum metus curabitur primis tristique");
        list.add(bs487);
        BookSeries bs488 = new BookSeries(489, "varius", 3, SerieTypeEnum.MANGA, "vitae praesent senectus neque neque");
        list.add(bs488);
        BookSeries bs489 = new BookSeries(490, "lacinia", 7, SerieTypeEnum.LIVRO, "tempor praesent accumsan commodo venenatis");
        list.add(bs489);
        BookSeries bs490 = new BookSeries(491, "ipsum integer", 3, SerieTypeEnum.MANGA, "donec viverra turpis tristique maecenas");
        list.add(bs490);
        BookSeries bs491 = new BookSeries(492, "placerat vivamus", 8, SerieTypeEnum.LIVRO, "aenean congue felis wisiaenean ultrices");
        list.add(bs491);
        BookSeries bs492 = new BookSeries(493, "imperdiet tellus", 8, SerieTypeEnum.LIVRO, "aliquam morbi varius aliquam aptent");
        list.add(bs492);
        BookSeries bs493 = new BookSeries(494, "risus fames", 0, SerieTypeEnum.HQ, "lacinia semper pellentesque congue proin");
        list.add(bs493);
        BookSeries bs494 = new BookSeries(495, "primis", 2, SerieTypeEnum.MANGA, "vehicula ultricies sodales inceptos lectus");
        list.add(bs494);
        BookSeries bs495 = new BookSeries(496, "sollicitudin", 8, SerieTypeEnum.LIVRO, "ultrices hendrerit lacinia interdum tortor");
        list.add(bs495);
        BookSeries bs496 = new BookSeries(497, "facilisisnunc", 8, SerieTypeEnum.LIVRO, "sagittis nonummy felis sodales quisque");
        list.add(bs496);
        BookSeries bs497 = new BookSeries(498, "aenean turpis", 7, SerieTypeEnum.LIVRO, "ligula tristique pulvinar sociosqu adipiscing");
        list.add(bs497);
        BookSeries bs498 = new BookSeries(499, "phasellus", 0, SerieTypeEnum.HQ, "sodales etiam lobortis bibendum adipiscing");
        list.add(bs498);
        BookSeries bs499 = new BookSeries(500, "aliquam feugiat", 5, SerieTypeEnum.MANGA, "inceptos tristique neque phasellus dictum");
        list.add(bs499);

        Connection.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            bookSeriesDBM.insertBookSeries(iteration);
        });
        Connection.getCon().getTransaction().commit();
    }
}
