package preInsertions;

import DBManager.BookSeriesDBM;
import Conn.Connection;
import entities.BookSeries;
import enums.SerieTypeEnum;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertBookSeries2
{

    BookSeriesDBM bookSeriesDBM = new BookSeriesDBM();
    List<BookSeries> list = new ArrayList<>();

    public void insert() {

        BookSeries bs500 = new BookSeries(501, "ullamcorper", 7, SerieTypeEnum.HQ, "bulum semper lobortis quisque aenean");
        list.add(bs500);
        BookSeries bs501 = new BookSeries(502, "integer molestie", 8, SerieTypeEnum.HQ, "adipiscing fames laoreet pharetra ligula");
        list.add(bs501);
        BookSeries bs502 = new BookSeries(503, "cursus", 9, SerieTypeEnum.LIVRO, "commodo augue tincidunt turpis aliquam");
        list.add(bs502);
        BookSeries bs503 = new BookSeries(504, "fusce", 1, SerieTypeEnum.MANGA, "pretium morbi euismod tempus magna");
        list.add(bs503);
        BookSeries bs504 = new BookSeries(505, "scelerisque", 7, SerieTypeEnum.HQ, "interdum tempus ligula nostra ultrices");
        list.add(bs504);
        BookSeries bs505 = new BookSeries(506, "adipiscing", 0, SerieTypeEnum.MANGA, "imperdiet tempor elementum mollis phasellus");
        list.add(bs505);
        BookSeries bs506 = new BookSeries(507, "hendrerit", 10, SerieTypeEnum.MANGA, "pellentesque faucibus nullam pulvinar fermentum");
        list.add(bs506);
        BookSeries bs507 = new BookSeries(508, "semper", 3, SerieTypeEnum.MANGA, "ultricies fames nulla inceptos tortor");
        list.add(bs507);
        BookSeries bs508 = new BookSeries(509, "semper", 10, SerieTypeEnum.HQ, "posuere posuere proin aliquet tristique");
        list.add(bs508);
        BookSeries bs509 = new BookSeries(510, "posuere", 8, SerieTypeEnum.MANGA, "torquent venenatis facilisis turpis pharetra");
        list.add(bs509);
        BookSeries bs510 = new BookSeries(511, "hymenaeos", 5, SerieTypeEnum.LIVRO, "fermentum ipsum faucibus purus nonummy");
        list.add(bs510);
        BookSeries bs511 = new BookSeries(512, "torquent cursus", 2, SerieTypeEnum.MANGA, "bibendum iaculis viverra varius bibendum");
        list.add(bs511);
        BookSeries bs512 = new BookSeries(513, "placerat faucibus", 5, SerieTypeEnum.MANGA, "interdum eleifend ultrices commodo lobortis");
        list.add(bs512);
        BookSeries bs513 = new BookSeries(514, "ultrices", 7, SerieTypeEnum.LIVRO, "fusce quisque felis dolor luctus");
        list.add(bs513);
        BookSeries bs514 = new BookSeries(515, "nullam tempus", 3, SerieTypeEnum.MANGA, "nullam curabitur convallis felis donec");
        list.add(bs514);
        BookSeries bs515 = new BookSeries(516, "lorem", 9, SerieTypeEnum.LIVRO, "phasellus senectus praesent senectus lacinia");
        list.add(bs515);
        BookSeries bs516 = new BookSeries(517, "fringilla senectus", 1, SerieTypeEnum.HQ, "varius cursus mollis fames volutpat");
        list.add(bs516);
        BookSeries bs517 = new BookSeries(518, "vestibulum risus", 8, SerieTypeEnum.LIVRO, "quisque hymenaeos euismod etiam inceptos");
        list.add(bs517);
        BookSeries bs518 = new BookSeries(519, "porttitor", 4, SerieTypeEnum.MANGA, "tincidunt risus tristique luctus facilisi");
        list.add(bs518);
        BookSeries bs519 = new BookSeries(520, "vesti vivamus", 2, SerieTypeEnum.MANGA, "interdum vestibulum felis lorem tellus");
        list.add(bs519);
        BookSeries bs520 = new BookSeries(521, "faucibus", 0, SerieTypeEnum.MANGA, "malesuada ullamcorper pharetra class ipsum");
        list.add(bs520);
        BookSeries bs521 = new BookSeries(522, "praesent", 1, SerieTypeEnum.LIVRO, "turpis inceptos facilisisnunc pretium porttitor");
        list.add(bs521);
        BookSeries bs522 = new BookSeries(523, "nostra", 5, SerieTypeEnum.MANGA, "feugiat purus neque phasellus congue");
        list.add(bs522);
        BookSeries bs523 = new BookSeries(524, "commodo netus", 2, SerieTypeEnum.LIVRO, "vestibulum phasellus sollicitudin facilisi faucibus");
        list.add(bs523);
        BookSeries bs524 = new BookSeries(525, "eleifend sollicitudin", 7, SerieTypeEnum.MANGA, "adipiscing auctor sapien tellus fermentum");
        list.add(bs524);
        BookSeries bs525 = new BookSeries(526, "venenatis", 10, SerieTypeEnum.HQ, "tempor semper fusce malesuada curabitur");
        list.add(bs525);
        BookSeries bs526 = new BookSeries(527, "molestie", 7, SerieTypeEnum.LIVRO, "aliquam tristique magna facilisi aptent");
        list.add(bs526);
        BookSeries bs527 = new BookSeries(528, "curae tempus", 1, SerieTypeEnum.HQ, "congue hymenaeos cubilia egestas quisque");
        list.add(bs527);
        BookSeries bs528 = new BookSeries(529, "sociosqu", 2, SerieTypeEnum.HQ, "hymenaeos fusce consectetuer turpis nullam");
        list.add(bs528);
        BookSeries bs529 = new BookSeries(530, "fermentum class", 0, SerieTypeEnum.MANGA, "molestie maecenas etiam proin vehicula");
        list.add(bs529);
        BookSeries bs530 = new BookSeries(531, "hendrerit", 6, SerieTypeEnum.HQ, "maecenas fames integer ultricies tincidunt");
        list.add(bs530);
        BookSeries bs531 = new BookSeries(532, "cursus sodales", 6, SerieTypeEnum.MANGA, "primis fermentum maecenas habitasse vehicula");
        list.add(bs531);
        BookSeries bs532 = new BookSeries(533, "ultricies", 1, SerieTypeEnum.HQ, "aenean luctus ultrices consectetuer cursus");
        list.add(bs532);
        BookSeries bs533 = new BookSeries(534, "habitant sociosqu", 5, SerieTypeEnum.LIVRO, "porta vitae pretium conubia elementum");
        list.add(bs533);
        BookSeries bs534 = new BookSeries(535, "molestie", 4, SerieTypeEnum.HQ, "hymenaeos facilisisnunc quisque integer suspendisse");
        list.add(bs534);
        BookSeries bs535 = new BookSeries(536, "dictumst", 4, SerieTypeEnum.HQ, "luctus tortor felis augue varius");
        list.add(bs535);
        BookSeries bs536 = new BookSeries(537, "hendrerit", 5, SerieTypeEnum.HQ, "cursus tumst auctor commodo lacinia");
        list.add(bs536);
        BookSeries bs537 = new BookSeries(538, "aptent", 6, SerieTypeEnum.HQ, "scelerisque libero curae augue wisiaenean");
        list.add(bs537);
        BookSeries bs538 = new BookSeries(539, "accumsan", 8, SerieTypeEnum.MANGA, "platea iaculis vitae adipiscing torquent");
        list.add(bs538);
        BookSeries bs539 = new BookSeries(540, "mattis", 5, SerieTypeEnum.MANGA, "aenean mauris litora vehicula hymenaeos");
        list.add(bs539);
        BookSeries bs540 = new BookSeries(541, "purus", 4, SerieTypeEnum.MANGA, "libero cubilia convallis aliquet curae");
        list.add(bs540);
        BookSeries bs541 = new BookSeries(542, "egestas", 10, SerieTypeEnum.MANGA, "fringilla class lorem ullamcorper nostra");
        list.add(bs541);
        BookSeries bs542 = new BookSeries(543, "egestas", 10, SerieTypeEnum.LIVRO, "justo phasellus aenean maecenas class");
        list.add(bs542);
        BookSeries bs543 = new BookSeries(544, "turpis", 6, SerieTypeEnum.LIVRO, "adipiscing taciti vestibulum euismod fermentum");
        list.add(bs543);
        BookSeries bs544 = new BookSeries(545, "taciti dolor", 6, SerieTypeEnum.HQ, "pretium morbi nostra posuere primis");
        list.add(bs544);
        BookSeries bs545 = new BookSeries(546, "suspendisse", 2, SerieTypeEnum.LIVRO, "convallis magna platea tempor fusce");
        list.add(bs545);
        BookSeries bs546 = new BookSeries(547, "lacus", 2, SerieTypeEnum.HQ, "pretium libero tellus tincidunt ornare");
        list.add(bs546);
        BookSeries bs547 = new BookSeries(548, "egestas egestas", 8, SerieTypeEnum.HQ, "conubia volutpat class tempor porta");
        list.add(bs547);
        BookSeries bs548 = new BookSeries(549, "dolor maecenas", 5, SerieTypeEnum.LIVRO, "volutpat placerat egestas senectus dictumst");
        list.add(bs548);
        BookSeries bs549 = new BookSeries(550, "sociosqu", 9, SerieTypeEnum.MANGA, "tempus lectus nonummy euismod laoreet");
        list.add(bs549);
        BookSeries bs550 = new BookSeries(551, "faucibus", 8, SerieTypeEnum.MANGA, "etiam molestie augue nulla aptent");
        list.add(bs550);
        BookSeries bs551 = new BookSeries(552, "adipiscing", 8, SerieTypeEnum.HQ, "facilisisnunc ornare tortor dignissim tincidunt");
        list.add(bs551);
        BookSeries bs552 = new BookSeries(553, "fames vivamus", 5, SerieTypeEnum.LIVRO, "pellentesque conubia placerat tellus habitasse");
        list.add(bs552);
        BookSeries bs553 = new BookSeries(554, "suspendisse lacinia", 2, SerieTypeEnum.LIVRO, "velit elementum litora malesuada aliquet");
        list.add(bs553);
        BookSeries bs554 = new BookSeries(555, "tellus", 8, SerieTypeEnum.HQ, "proin habitasse placerat egestas lobortis");
        list.add(bs554);
        BookSeries bs555 = new BookSeries(556, "platea habitasse", 0, SerieTypeEnum.LIVRO, "aliquet malesuada mollis tumst tortor");
        list.add(bs555);
        BookSeries bs556 = new BookSeries(557, "ornare", 5, SerieTypeEnum.LIVRO, "libero phasellus dolor eleifend bibendum");
        list.add(bs556);
        BookSeries bs557 = new BookSeries(558, "hymenaeos", 8, SerieTypeEnum.MANGA, "netus conubia aptent adipiscing posuere");
        list.add(bs557);
        BookSeries bs558 = new BookSeries(559, "conubia magna", 5, SerieTypeEnum.HQ, "sollicitudin sodales mattis sociosqu etiam");
        list.add(bs558);
        BookSeries bs559 = new BookSeries(560, "sociosqu fames", 2, SerieTypeEnum.HQ, "sociosqu torquent sodales nulla nostra");
        list.add(bs559);
        BookSeries bs560 = new BookSeries(561, "curae ultrices", 10, SerieTypeEnum.HQ, "sociosqu faucibus dictum sagittis facilisisnunc");
        list.add(bs560);
        BookSeries bs561 = new BookSeries(562, "platea", 5, SerieTypeEnum.LIVRO, "laoreet vesti elementum placerat nulla");
        list.add(bs561);
        BookSeries bs562 = new BookSeries(563, "laoreet", 4, SerieTypeEnum.HQ, "porta feugiat ornare iaculis volutpat");
        list.add(bs562);
        BookSeries bs563 = new BookSeries(564, "neque", 8, SerieTypeEnum.MANGA, "cursus torquent tellus dignissim facilisis");
        list.add(bs563);
        BookSeries bs564 = new BookSeries(565, "facilisi", 1, SerieTypeEnum.LIVRO, "litora imperdiet auctor iaculis dictumst");
        list.add(bs564);
        BookSeries bs565 = new BookSeries(566, "sollicitudin", 6, SerieTypeEnum.MANGA, "dictum cursus nullam curabitur porta");
        list.add(bs565);
        BookSeries bs566 = new BookSeries(567, "litora risus", 1, SerieTypeEnum.LIVRO, "nulla proin nonummy faucibus convallis");
        list.add(bs566);
        BookSeries bs567 = new BookSeries(568, "consectetuer", 8, SerieTypeEnum.LIVRO, "augue mauris auctor primis etiam");
        list.add(bs567);
        BookSeries bs568 = new BookSeries(569, "semper", 0, SerieTypeEnum.MANGA, "etiam justo proin magna wisiaenean");
        list.add(bs568);
        BookSeries bs569 = new BookSeries(570, "libero dignissim", 5, SerieTypeEnum.LIVRO, "venenatis ultricies interdum inceptos lobortis");
        list.add(bs569);
        BookSeries bs570 = new BookSeries(571, "lacus", 10, SerieTypeEnum.HQ, "consectetuer praesent quisque habitasse eleifend");
        list.add(bs570);
        BookSeries bs571 = new BookSeries(572, "ornare", 0, SerieTypeEnum.MANGA, "bulum bulum convallis quisque semper");
        list.add(bs571);
        BookSeries bs572 = new BookSeries(573, "donec", 9, SerieTypeEnum.LIVRO, "malesuada euismod senectus aliquet nulla");
        list.add(bs572);
        BookSeries bs573 = new BookSeries(574, "etiam", 3, SerieTypeEnum.LIVRO, "justo praesent viverra mollis dictum");
        list.add(bs573);
        BookSeries bs574 = new BookSeries(575, "aenean", 4, SerieTypeEnum.LIVRO, "dictumst laoreet curae pellentesque malesuada");
        list.add(bs574);
        BookSeries bs575 = new BookSeries(576, "sapien accumsan", 0, SerieTypeEnum.LIVRO, "primis luctus accumsan ornare litora");
        list.add(bs575);
        BookSeries bs576 = new BookSeries(577, "inceptos cubilia", 2, SerieTypeEnum.HQ, "nulla ultrices egestas suspendisse mollis");
        list.add(bs576);
        BookSeries bs577 = new BookSeries(578, "viverra", 6, SerieTypeEnum.LIVRO, "donec auctor sociosqu sapien lacinia");
        list.add(bs577);
        BookSeries bs578 = new BookSeries(579, "imperdiet", 0, SerieTypeEnum.LIVRO, "class lacus luctus ornare tempus");
        list.add(bs578);
        BookSeries bs579 = new BookSeries(580, "libero", 4, SerieTypeEnum.MANGA, "placerat litora tincidunt fringilla consectetuer");
        list.add(bs579);
        BookSeries bs580 = new BookSeries(581, "facilisi magna", 2, SerieTypeEnum.MANGA, "semper class senectus morbi felis");
        list.add(bs580);
        BookSeries bs581 = new BookSeries(582, "lacus risus", 8, SerieTypeEnum.LIVRO, "lorem turpis auctor tincidunt egestas");
        list.add(bs581);
        BookSeries bs582 = new BookSeries(583, "tumst", 10, SerieTypeEnum.HQ, "litora nulla conubia habitant senectus");
        list.add(bs582);
        BookSeries bs583 = new BookSeries(584, "nullam vesti", 4, SerieTypeEnum.MANGA, "platea lectus cubilia dignissim ultrices");
        list.add(bs583);
        BookSeries bs584 = new BookSeries(585, "adipiscing cursus", 7, SerieTypeEnum.LIVRO, "volutpat rutrum pulvinar risus rutrum");
        list.add(bs584);
        BookSeries bs585 = new BookSeries(586, "eleifend", 4, SerieTypeEnum.HQ, "donec netus varius fusce justo");
        list.add(bs585);
        BookSeries bs586 = new BookSeries(587, "aliquam rutrum", 3, SerieTypeEnum.HQ, "elementum neque ornare curae vitae");
        list.add(bs586);
        BookSeries bs587 = new BookSeries(588, "curae feugiat", 10, SerieTypeEnum.HQ, "senectus aptent platea platea taciti");
        list.add(bs587);
        BookSeries bs588 = new BookSeries(589, "etiam faucibus", 0, SerieTypeEnum.MANGA, "ultricies tempus vitae phasellus proin");
        list.add(bs588);
        BookSeries bs589 = new BookSeries(590, "curabitur molestie", 10, SerieTypeEnum.HQ, "consectetuer semper nostra eleifend primis");
        list.add(bs589);
        BookSeries bs590 = new BookSeries(591, "ullamcorper", 9, SerieTypeEnum.MANGA, "maecenas pulvinar dictum sagittis lacinia");
        list.add(bs590);
        BookSeries bs591 = new BookSeries(592, "dictumst", 10, SerieTypeEnum.LIVRO, "facilisisnunc lectus felis tortor vitae");
        list.add(bs591);
        BookSeries bs592 = new BookSeries(593, "facilisis porttitor", 1, SerieTypeEnum.HQ, "molestie aliquet vesti ultrices curabitur");
        list.add(bs592);
        BookSeries bs593 = new BookSeries(594, "dictum commodo", 2, SerieTypeEnum.HQ, "tortor vesti lacinia imperdiet consequat");
        list.add(bs593);
        BookSeries bs594 = new BookSeries(595, "mattis", 4, SerieTypeEnum.LIVRO, "habitasse sollicitudin wisiaenean morbi sociosqu");
        list.add(bs594);
        BookSeries bs595 = new BookSeries(596, "risus", 2, SerieTypeEnum.LIVRO, "aptent aenean litora semper fringilla");
        list.add(bs595);
        BookSeries bs596 = new BookSeries(597, "velit", 4, SerieTypeEnum.MANGA, "consequat justo facilisis pharetra litora");
        list.add(bs596);
        BookSeries bs597 = new BookSeries(598, "dolor", 8, SerieTypeEnum.HQ, "pretium bibendum sodales donec velit");
        list.add(bs597);
        BookSeries bs598 = new BookSeries(599, "aliquet conubia", 7, SerieTypeEnum.MANGA, "integer molestie risus egestas torquent");
        list.add(bs598);
        BookSeries bs599 = new BookSeries(600, "consequat lobortis", 2, SerieTypeEnum.HQ, "aenean tincidunt pellentesque bibendum mauris");
        list.add(bs599);
        BookSeries bs600 = new BookSeries(601, "adipiscing", 10, SerieTypeEnum.LIVRO, "fermentum vehicula ligula sagittis senectus");
        list.add(bs600);
        BookSeries bs601 = new BookSeries(602, "taciti", 9, SerieTypeEnum.HQ, "ipsum suspendisse taciti scelerisque hymenaeos");
        list.add(bs601);
        BookSeries bs602 = new BookSeries(603, "ultrices dictumst", 6, SerieTypeEnum.LIVRO, "varius aptent ultricies curabitur facilisisnunc");
        list.add(bs602);
        BookSeries bs603 = new BookSeries(604, "tincidunt", 2, SerieTypeEnum.MANGA, "aliquet porta consectetuer habitant posuere");
        list.add(bs603);
        BookSeries bs604 = new BookSeries(605, "ultrices", 2, SerieTypeEnum.HQ, "wisiaenean malesuada augue viverra consequat");
        list.add(bs604);
        BookSeries bs605 = new BookSeries(606, "fames", 4, SerieTypeEnum.MANGA, "metus turpis vesti congue elementum");
        list.add(bs605);
        BookSeries bs606 = new BookSeries(607, "nulla", 6, SerieTypeEnum.LIVRO, "class donec mattis rutrum primis");
        list.add(bs606);
        BookSeries bs607 = new BookSeries(608, "ligula", 6, SerieTypeEnum.LIVRO, "vivamus ultricies morbi lorem imperdiet");
        list.add(bs607);
        BookSeries bs608 = new BookSeries(609, "sollicitudin porttitor", 0, SerieTypeEnum.LIVRO, "nullam nostra donec vestibulum ligula");
        list.add(bs608);
        BookSeries bs609 = new BookSeries(610, "auctor habitasse", 2, SerieTypeEnum.HQ, "euismod donec morbi pellentesque metus");
        list.add(bs609);
        BookSeries bs610 = new BookSeries(611, "volutpat", 0, SerieTypeEnum.LIVRO, "tempus aenean lacinia aliquet malesuada");
        list.add(bs610);
        BookSeries bs611 = new BookSeries(612, "nostra curae", 0, SerieTypeEnum.HQ, "proin cursus commodo egestas nostra");
        list.add(bs611);
        BookSeries bs612 = new BookSeries(613, "bibendum", 6, SerieTypeEnum.MANGA, "luctus imperdiet bibendum vesti consequat");
        list.add(bs612);
        BookSeries bs613 = new BookSeries(614, "vivamus facilisis", 1, SerieTypeEnum.HQ, "wisiaenean ipsum ultrices sociosqu phasellus");
        list.add(bs613);
        BookSeries bs614 = new BookSeries(615, "primis consectetuer", 7, SerieTypeEnum.HQ, "turpis mauris augue quisque facilisis");
        list.add(bs614);
        BookSeries bs615 = new BookSeries(616, "sagittis", 7, SerieTypeEnum.LIVRO, "fringilla euismod conubia tumst lacinia");
        list.add(bs615);
        BookSeries bs616 = new BookSeries(617, "wisiaenean", 4, SerieTypeEnum.MANGA, "lorem curabitur sodales laoreet justo");
        list.add(bs616);
        BookSeries bs617 = new BookSeries(618, "felis taciti", 7, SerieTypeEnum.MANGA, "aptent curabitur laoreet posuere vesti");
        list.add(bs617);
        BookSeries bs618 = new BookSeries(619, "feugiat", 9, SerieTypeEnum.LIVRO, "laoreet bibendum nonummy ultricies posuere");
        list.add(bs618);
        BookSeries bs619 = new BookSeries(620, "morbi", 7, SerieTypeEnum.MANGA, "fringilla fames aliquam pulvinar dolor");
        list.add(bs619);
        BookSeries bs620 = new BookSeries(621, "aliquam", 5, SerieTypeEnum.MANGA, "torquent eleifend placerat sociosqu scelerisque");
        list.add(bs620);
        BookSeries bs621 = new BookSeries(622, "aenean", 8, SerieTypeEnum.HQ, "augue convallis wisiaenean litora interdum");
        list.add(bs621);
        BookSeries bs622 = new BookSeries(623, "euismod", 3, SerieTypeEnum.LIVRO, "aliquet tempus feugiat augue laoreet");
        list.add(bs622);
        BookSeries bs623 = new BookSeries(624, "ipsum", 1, SerieTypeEnum.HQ, "taciti congue feugiat fusce lobortis");
        list.add(bs623);
        BookSeries bs624 = new BookSeries(625, "proin", 3, SerieTypeEnum.HQ, "metus bulum phasellus ultrices nostra");
        list.add(bs624);
        BookSeries bs625 = new BookSeries(626, "nostra faucibus", 7, SerieTypeEnum.LIVRO, "volutpat adipiscing luctus nullam pretium");
        list.add(bs625);
        BookSeries bs626 = new BookSeries(627, "velit", 8, SerieTypeEnum.HQ, "vitae habitasse aenean litora lectus");
        list.add(bs626);
        BookSeries bs627 = new BookSeries(628, "lacinia", 3, SerieTypeEnum.MANGA, "adipiscing feugiat sagittis lobortis tumst");
        list.add(bs627);
        BookSeries bs628 = new BookSeries(629, "lacus feugiat", 6, SerieTypeEnum.HQ, "dolor tempor habitasse placerat lacus");
        list.add(bs628);
        BookSeries bs629 = new BookSeries(630, "consectetuer molestie", 9, SerieTypeEnum.LIVRO, "primis bulum bibendum porta fusce");
        list.add(bs629);
        BookSeries bs630 = new BookSeries(631, "pellentesque", 7, SerieTypeEnum.LIVRO, "fusce tincidunt vehicula hendrerit vivamus");
        list.add(bs630);
        BookSeries bs631 = new BookSeries(632, "commodo", 5, SerieTypeEnum.MANGA, "scelerisque nullam adipiscing pharetra velit");
        list.add(bs631);
        BookSeries bs632 = new BookSeries(633, "vestibulum mauris", 2, SerieTypeEnum.HQ, "metus dolor molestie hymenaeos volutpat");
        list.add(bs632);
        BookSeries bs633 = new BookSeries(634, "conubia", 3, SerieTypeEnum.LIVRO, "metus primis egestas volutpat aenean");
        list.add(bs633);
        BookSeries bs634 = new BookSeries(635, "turpis", 4, SerieTypeEnum.LIVRO, "tempor phasellus senectus proin aenean");
        list.add(bs634);
        BookSeries bs635 = new BookSeries(636, "taciti", 9, SerieTypeEnum.HQ, "sapien congue auctor accumsan fringilla");
        list.add(bs635);
        BookSeries bs636 = new BookSeries(637, "integer", 8, SerieTypeEnum.MANGA, "pulvinar mollis sollicitudin accumsan aenean");
        list.add(bs636);
        BookSeries bs637 = new BookSeries(638, "luctus", 0, SerieTypeEnum.HQ, "donec senectus tumst primis facilisisnunc");
        list.add(bs637);
        BookSeries bs638 = new BookSeries(639, "ipsum", 3, SerieTypeEnum.LIVRO, "fringilla adipiscing fringilla habitasse porta");
        list.add(bs638);
        BookSeries bs639 = new BookSeries(640, "scelerisque", 1, SerieTypeEnum.LIVRO, "neque mattis integer etiam curabitur");
        list.add(bs639);
        BookSeries bs640 = new BookSeries(641, "neque", 8, SerieTypeEnum.LIVRO, "vivamus habitant hendrerit libero curabitur");
        list.add(bs640);
        BookSeries bs641 = new BookSeries(642, "dictumst", 7, SerieTypeEnum.HQ, "risus lobortis facilisisnunc donec porta");
        list.add(bs641);
        BookSeries bs642 = new BookSeries(643, "accumsan", 8, SerieTypeEnum.LIVRO, "integer vitae quisque semper pharetra");
        list.add(bs642);
        BookSeries bs643 = new BookSeries(644, "curabitur", 5, SerieTypeEnum.MANGA, "praesent facilisi fusce lorem ultricies");
        list.add(bs643);
        BookSeries bs644 = new BookSeries(645, "dolor", 6, SerieTypeEnum.HQ, "habitant velit euismod etiam auctor");
        list.add(bs644);
        BookSeries bs645 = new BookSeries(646, "lorem fusce", 0, SerieTypeEnum.MANGA, "quisque molestie tincidunt hendrerit imperdiet");
        list.add(bs645);
        BookSeries bs646 = new BookSeries(647, "volutpat euismod", 5, SerieTypeEnum.MANGA, "lorem pretium nostra netus aptent");
        list.add(bs646);
        BookSeries bs647 = new BookSeries(648, "habitasse", 9, SerieTypeEnum.MANGA, "venenatis consequat volutpat phasellus class");
        list.add(bs647);
        BookSeries bs648 = new BookSeries(649, "commodo", 9, SerieTypeEnum.HQ, "vitae nonummy placerat pharetra sagittis");
        list.add(bs648);
        BookSeries bs649 = new BookSeries(650, "mauris", 10, SerieTypeEnum.HQ, "sociosqu facilisisnunc hendrerit adipiscing hendrerit");
        list.add(bs649);
        BookSeries bs650 = new BookSeries(651, "cursus netus", 4, SerieTypeEnum.MANGA, "tellus augue phasellus fames porta");
        list.add(bs650);
        BookSeries bs651 = new BookSeries(652, "pretium placerat", 4, SerieTypeEnum.MANGA, "eleifend felis mauris malesuada ipsum");
        list.add(bs651);
        BookSeries bs652 = new BookSeries(653, "ullamcorper consequat", 7, SerieTypeEnum.LIVRO, "dignissim risus turpis aptent convallis");
        list.add(bs652);
        BookSeries bs653 = new BookSeries(654, "phasellus", 5, SerieTypeEnum.LIVRO, "varius consequat fermentum vitae commodo");
        list.add(bs653);
        BookSeries bs654 = new BookSeries(655, "tempus torquent", 3, SerieTypeEnum.LIVRO, "egestas fringilla vesti pretium congue");
        list.add(bs654);
        BookSeries bs655 = new BookSeries(656, "felis", 3, SerieTypeEnum.MANGA, "tincidunt placerat fames consectetuer fringilla");
        list.add(bs655);
        BookSeries bs656 = new BookSeries(657, "scelerisque conubia", 5, SerieTypeEnum.MANGA, "iaculis egestas sollicitudin dictum congue");
        list.add(bs656);
        BookSeries bs657 = new BookSeries(658, "ullamcorper", 8, SerieTypeEnum.HQ, "venenatis ultricies vivamus ligula commodo");
        list.add(bs657);
        BookSeries bs658 = new BookSeries(659, "consectetuer", 8, SerieTypeEnum.LIVRO, "semper malesuada platea felis commodo");
        list.add(bs658);
        BookSeries bs659 = new BookSeries(660, "dignissim wisiaenean", 2, SerieTypeEnum.MANGA, "litora habitasse faucibus viverra donec");
        list.add(bs659);
        BookSeries bs660 = new BookSeries(661, "facilisi", 2, SerieTypeEnum.HQ, "nullam curae feugiat conubia integer");
        list.add(bs660);
        BookSeries bs661 = new BookSeries(662, "aliquet", 7, SerieTypeEnum.LIVRO, "sodales lectus pharetra euismod proin");
        list.add(bs661);
        BookSeries bs662 = new BookSeries(663, "risus", 4, SerieTypeEnum.HQ, "tellus facilisi suspendisse venenatis morbi");
        list.add(bs662);
        BookSeries bs663 = new BookSeries(664, "venenatis", 10, SerieTypeEnum.LIVRO, "conubia facilisis sapien dictumst aptent");
        list.add(bs663);
        BookSeries bs664 = new BookSeries(665, "placerat molestie", 2, SerieTypeEnum.LIVRO, "placerat maecenas vivamus imperdiet molestie");
        list.add(bs664);
        BookSeries bs665 = new BookSeries(666, "aenean fringilla", 9, SerieTypeEnum.HQ, "placerat rutrum sodales dictum proin");
        list.add(bs665);
        BookSeries bs666 = new BookSeries(667, "lacus scelerisque", 9, SerieTypeEnum.HQ, "fusce suspendisse neque mauris ornare");
        list.add(bs666);
        BookSeries bs667 = new BookSeries(668, "dolor facilisis", 6, SerieTypeEnum.HQ, "pellentesque lobortis pellentesque pretium wisiaenean");
        list.add(bs667);
        BookSeries bs668 = new BookSeries(669, "dictum", 7, SerieTypeEnum.LIVRO, "bibendum nulla molestie luctus malesuada");
        list.add(bs668);
        BookSeries bs669 = new BookSeries(670, "volutpat suspendisse", 3, SerieTypeEnum.HQ, "litora varius scelerisque mauris porttitor");
        list.add(bs669);
        BookSeries bs670 = new BookSeries(671, "consectetuer", 9, SerieTypeEnum.HQ, "ullamcorper posuere dictumst viverra consectetuer");
        list.add(bs670);
        BookSeries bs671 = new BookSeries(672, "phasellus", 6, SerieTypeEnum.MANGA, "cubilia ultricies vestibulum ultricies rutrum");
        list.add(bs671);
        BookSeries bs672 = new BookSeries(673, "curae ultrices", 3, SerieTypeEnum.MANGA, "torquent volutpat conubia morbi consectetuer");
        list.add(bs672);
        BookSeries bs673 = new BookSeries(674, "suspendisse morbi", 9, SerieTypeEnum.HQ, "accumsan auctor dictum integer elementum");
        list.add(bs673);
        BookSeries bs674 = new BookSeries(675, "tempus curae", 8, SerieTypeEnum.HQ, "fringilla porttitor etiam augue velit");
        list.add(bs674);
        BookSeries bs675 = new BookSeries(676, "bibendum", 0, SerieTypeEnum.HQ, "mattis posuere maecenas platea fusce");
        list.add(bs675);
        BookSeries bs676 = new BookSeries(677, "vehicula", 0, SerieTypeEnum.HQ, "malesuada bibendum risus mattis vivamus");
        list.add(bs676);
        BookSeries bs677 = new BookSeries(678, "taciti lorem", 5, SerieTypeEnum.LIVRO, "aliquam dignissim pellentesque lacinia nonummy");
        list.add(bs677);
        BookSeries bs678 = new BookSeries(679, "tortor pharetra", 5, SerieTypeEnum.LIVRO, "dictum tristique sapien lacinia dignissim");
        list.add(bs678);
        BookSeries bs679 = new BookSeries(680, "laoreet", 3, SerieTypeEnum.LIVRO, "suspendisse turpis primis dignissim viverra");
        list.add(bs679);
        BookSeries bs680 = new BookSeries(681, "dictum", 10, SerieTypeEnum.MANGA, "cubilia aenean sollicitudin molestie nullam");
        list.add(bs680);
        BookSeries bs681 = new BookSeries(682, "molestie cursus", 7, SerieTypeEnum.MANGA, "dignissim pretium tortor nostra maecenas");
        list.add(bs681);
        BookSeries bs682 = new BookSeries(683, "sodales nonummy", 9, SerieTypeEnum.LIVRO, "auctor aliquam metus wisiaenean suspendisse");
        list.add(bs682);
        BookSeries bs683 = new BookSeries(684, "integer facilisisnunc", 10, SerieTypeEnum.LIVRO, "taciti ullamcorper placerat pretium curae");
        list.add(bs683);
        BookSeries bs684 = new BookSeries(685, "imperdiet facilisis", 8, SerieTypeEnum.MANGA, "dignissim interdum fames bulum consectetuer");
        list.add(bs684);
        BookSeries bs685 = new BookSeries(686, "facilisi", 6, SerieTypeEnum.MANGA, "praesent lacus pharetra aenean eleifend");
        list.add(bs685);
        BookSeries bs686 = new BookSeries(687, "fames laoreet", 6, SerieTypeEnum.MANGA, "lacinia tristique taciti magna habitant");
        list.add(bs686);
        BookSeries bs687 = new BookSeries(688, "tellus", 2, SerieTypeEnum.LIVRO, "adipiscing wisiaenean pretium proin sagittis");
        list.add(bs687);
        BookSeries bs688 = new BookSeries(689, "augue", 0, SerieTypeEnum.MANGA, "senectus habitant mauris fringilla donec");
        list.add(bs688);
        BookSeries bs689 = new BookSeries(690, "aenean", 10, SerieTypeEnum.HQ, "justo vivamus vesti turpis nullam");
        list.add(bs689);
        BookSeries bs690 = new BookSeries(691, "rutrum", 3, SerieTypeEnum.LIVRO, "netus aliquet feugiat vitae phasellus");
        list.add(bs690);
        BookSeries bs691 = new BookSeries(692, "aenean cursus", 8, SerieTypeEnum.MANGA, "tumst dictumst aenean pretium consectetuer");
        list.add(bs691);
        BookSeries bs692 = new BookSeries(693, "pharetra", 4, SerieTypeEnum.HQ, "lectus vesti viverra habitant donec");
        list.add(bs692);
        BookSeries bs693 = new BookSeries(694, "magna", 2, SerieTypeEnum.MANGA, "fames facilisis morbi mollis sodales");
        list.add(bs693);
        BookSeries bs694 = new BookSeries(695, "netus neque", 10, SerieTypeEnum.HQ, "vivamus semper maecenas libero consequat");
        list.add(bs694);
        BookSeries bs695 = new BookSeries(696, "proin", 8, SerieTypeEnum.MANGA, "interdum pulvinar inceptos ipsum habitant");
        list.add(bs695);
        BookSeries bs696 = new BookSeries(697, "purus", 7, SerieTypeEnum.HQ, "lacus augue vehicula suspendisse vestibulum");
        list.add(bs696);
        BookSeries bs697 = new BookSeries(698, "mattis donec", 9, SerieTypeEnum.MANGA, "scelerisque ultrices ornare fringilla auctor");
        list.add(bs697);
        BookSeries bs698 = new BookSeries(699, "cursus feugiat", 1, SerieTypeEnum.HQ, "magna metus iaculis molestie ullamcorper");
        list.add(bs698);
        BookSeries bs699 = new BookSeries(700, "pretium", 6, SerieTypeEnum.MANGA, "facilisis turpis etiam luctus eleifend");
        list.add(bs699);
        BookSeries bs700 = new BookSeries(701, "augue magna", 8, SerieTypeEnum.HQ, "tristique feugiat egestas augue pharetra");
        list.add(bs700);
        BookSeries bs701 = new BookSeries(702, "proin", 9, SerieTypeEnum.MANGA, "posuere commodo vehicula fames imperdiet");
        list.add(bs701);
        BookSeries bs702 = new BookSeries(703, "semper", 7, SerieTypeEnum.HQ, "fermentum tellus lacinia curabitur senectus");
        list.add(bs702);
        BookSeries bs703 = new BookSeries(704, "primis", 2, SerieTypeEnum.MANGA, "bulum accumsan molestie phasellus magna");
        list.add(bs703);
        BookSeries bs704 = new BookSeries(705, "integer", 8, SerieTypeEnum.HQ, "aenean imperdiet vestibulum convallis proin");
        list.add(bs704);
        BookSeries bs705 = new BookSeries(706, "eleifend", 7, SerieTypeEnum.MANGA, "magna euismod primis eleifend torquent");
        list.add(bs705);
        BookSeries bs706 = new BookSeries(707, "imperdiet", 9, SerieTypeEnum.LIVRO, "tumst feugiat facilisis tristique varius");
        list.add(bs706);
        BookSeries bs707 = new BookSeries(708, "sodales", 5, SerieTypeEnum.HQ, "sociosqu dignissim proin fringilla fames");
        list.add(bs707);
        BookSeries bs708 = new BookSeries(709, "aliquam proin", 7, SerieTypeEnum.HQ, "hymenaeos scelerisque fringilla tempus nulla");
        list.add(bs708);
        BookSeries bs709 = new BookSeries(710, "bulum", 9, SerieTypeEnum.LIVRO, "magna neque justo elementum sollicitudin");
        list.add(bs709);
        BookSeries bs710 = new BookSeries(711, "integer", 9, SerieTypeEnum.MANGA, "cursus convallis quisque ullamcorper ultricies");
        list.add(bs710);
        BookSeries bs711 = new BookSeries(712, "proin", 4, SerieTypeEnum.LIVRO, "porta augue lectus elementum euismod");
        list.add(bs711);
        BookSeries bs712 = new BookSeries(713, "ligula", 10, SerieTypeEnum.MANGA, "fringilla tristique tumst cursus hendrerit");
        list.add(bs712);
        BookSeries bs713 = new BookSeries(714, "viverra", 2, SerieTypeEnum.MANGA, "dignissim venenatis lacinia dolor hymenaeos");
        list.add(bs713);
        BookSeries bs714 = new BookSeries(715, "vestibulum", 1, SerieTypeEnum.HQ, "maecenas aliquam habitasse interdum sodales");
        list.add(bs714);
        BookSeries bs715 = new BookSeries(716, "auctor", 5, SerieTypeEnum.LIVRO, "pulvinar sodales pretium conubia porttitor");
        list.add(bs715);
        BookSeries bs716 = new BookSeries(717, "bulum", 10, SerieTypeEnum.HQ, "netus neque aptent justo dolor");
        list.add(bs716);
        BookSeries bs717 = new BookSeries(718, "taciti facilisi", 2, SerieTypeEnum.HQ, "integer consequat dictum justo rutrum");
        list.add(bs717);
        BookSeries bs718 = new BookSeries(719, "lobortis", 6, SerieTypeEnum.MANGA, "porttitor mollis fringilla placerat faucibus");
        list.add(bs718);
        BookSeries bs719 = new BookSeries(720, "molestie", 10, SerieTypeEnum.LIVRO, "ultrices dignissim viverra placerat netus");
        list.add(bs719);
        BookSeries bs720 = new BookSeries(721, "laoreet velit", 9, SerieTypeEnum.MANGA, "tortor senectus auctor euismod adipiscing");
        list.add(bs720);
        BookSeries bs721 = new BookSeries(722, "aliquam", 5, SerieTypeEnum.LIVRO, "sodales habitant integer malesuada pulvinar");
        list.add(bs721);
        BookSeries bs722 = new BookSeries(723, "laoreet", 1, SerieTypeEnum.LIVRO, "wisiaenean bulum etiam fusce pretium");
        list.add(bs722);
        BookSeries bs723 = new BookSeries(724, "sociosqu", 8, SerieTypeEnum.HQ, "rutrum tellus nulla tempus ullamcorper");
        list.add(bs723);
        BookSeries bs724 = new BookSeries(725, "mollis velit", 10, SerieTypeEnum.MANGA, "posuere molestie facilisis quisque feugiat");
        list.add(bs724);
        BookSeries bs725 = new BookSeries(726, "cubilia posuere", 0, SerieTypeEnum.HQ, "phasellus facilisisnunc facilisis semper primis");
        list.add(bs725);
        BookSeries bs726 = new BookSeries(727, "fames", 3, SerieTypeEnum.LIVRO, "senectus placerat fringilla posuere fringilla");
        list.add(bs726);
        BookSeries bs727 = new BookSeries(728, "hymenaeos", 2, SerieTypeEnum.MANGA, "purus platea elementum bulum mauris");
        list.add(bs727);
        BookSeries bs728 = new BookSeries(729, "ultrices aptent", 4, SerieTypeEnum.LIVRO, "nonummy libero tumst tempor etiam");
        list.add(bs728);
        BookSeries bs729 = new BookSeries(730, "pretium", 8, SerieTypeEnum.LIVRO, "viverra ultricies facilisis felis tempus");
        list.add(bs729);
        BookSeries bs730 = new BookSeries(731, "lacus", 4, SerieTypeEnum.MANGA, "porttitor conubia commodo vehicula accumsan");
        list.add(bs730);
        BookSeries bs731 = new BookSeries(732, "porta", 6, SerieTypeEnum.LIVRO, "risus fermentum conubia viverra dolor");
        list.add(bs731);
        BookSeries bs732 = new BookSeries(733, "accumsan", 0, SerieTypeEnum.MANGA, "adipiscing accumsan fermentum mauris faucibus");
        list.add(bs732);
        BookSeries bs733 = new BookSeries(734, "semper", 0, SerieTypeEnum.MANGA, "curae donec vehicula facilisisnunc nonummy");
        list.add(bs733);
        BookSeries bs734 = new BookSeries(735, "rutrum maecenas", 8, SerieTypeEnum.LIVRO, "fringilla justo congue rutrum tellus");
        list.add(bs734);
        BookSeries bs735 = new BookSeries(736, "molestie", 8, SerieTypeEnum.LIVRO, "primis suspendisse metus facilisis ultrices");
        list.add(bs735);
        BookSeries bs736 = new BookSeries(737, "habitasse", 5, SerieTypeEnum.LIVRO, "adipiscing bibendum elementum ipsum fermentum");
        list.add(bs736);
        BookSeries bs737 = new BookSeries(738, "bibendum", 9, SerieTypeEnum.LIVRO, "facilisis accumsan ligula tumst eleifend");
        list.add(bs737);
        BookSeries bs738 = new BookSeries(739, "metus", 10, SerieTypeEnum.LIVRO, "ultricies vivamus consequat accumsan tristique");
        list.add(bs738);
        BookSeries bs739 = new BookSeries(740, "hymenaeos lorem", 0, SerieTypeEnum.HQ, "nulla fames ullamcorper cubilia proin");
        list.add(bs739);
        BookSeries bs740 = new BookSeries(741, "malesuada cubilia", 9, SerieTypeEnum.HQ, "lacinia auctor maecenas proin luctus");
        list.add(bs740);
        BookSeries bs741 = new BookSeries(742, "iaculis congue", 0, SerieTypeEnum.HQ, "mollis tempus facilisis nostra elementum");
        list.add(bs741);
        BookSeries bs742 = new BookSeries(743, "porta", 0, SerieTypeEnum.LIVRO, "porttitor molestie semper posuere congue");
        list.add(bs742);
        BookSeries bs743 = new BookSeries(744, "euismod", 4, SerieTypeEnum.LIVRO, "dictumst hendrerit viverra litora hendrerit");
        list.add(bs743);
        BookSeries bs744 = new BookSeries(745, "laoreet", 1, SerieTypeEnum.LIVRO, "porttitor ornare risus hymenaeos vehicula");
        list.add(bs744);
        BookSeries bs745 = new BookSeries(746, "nostra", 5, SerieTypeEnum.MANGA, "auctor malesuada taciti consectetuer adipiscing");
        list.add(bs745);
        BookSeries bs746 = new BookSeries(747, "aenean risus", 0, SerieTypeEnum.HQ, "lacinia feugiat sollicitudin molestie nullam");
        list.add(bs746);
        BookSeries bs747 = new BookSeries(748, "fringilla sollicitudin", 6, SerieTypeEnum.HQ, "sollicitudin lorem mollis sagittis consequat");
        list.add(bs747);
        BookSeries bs748 = new BookSeries(749, "elementum", 9, SerieTypeEnum.MANGA, "nullam semper curabitur egestas wisiaenean");
        list.add(bs748);
        BookSeries bs749 = new BookSeries(750, "aptent", 9, SerieTypeEnum.MANGA, "habitasse dictumst cursus pharetra tumst");
        list.add(bs749);
        BookSeries bs750 = new BookSeries(751, "convallis vesti", 4, SerieTypeEnum.HQ, "neque lacinia eleifend sodales platea");
        list.add(bs750);
        BookSeries bs751 = new BookSeries(752, "lacinia nulla", 9, SerieTypeEnum.MANGA, "purus donec fringilla primis ipsum");
        list.add(bs751);
        BookSeries bs752 = new BookSeries(753, "sollicitudin lacus", 3, SerieTypeEnum.HQ, "netus neque posuere tempus dignissim");
        list.add(bs752);
        BookSeries bs753 = new BookSeries(754, "platea etiam", 9, SerieTypeEnum.LIVRO, "taciti torquent dictum feugiat lacus");
        list.add(bs753);
        BookSeries bs754 = new BookSeries(755, "netus", 5, SerieTypeEnum.MANGA, "laoreet tincidunt venenatis dictumst tellus");
        list.add(bs754);
        BookSeries bs755 = new BookSeries(756, "etiam", 3, SerieTypeEnum.MANGA, "habitant cursus elementum lectus lobortis");
        list.add(bs755);
        BookSeries bs756 = new BookSeries(757, "conubia nonummy", 9, SerieTypeEnum.HQ, "aliquet semper libero laoreet risus");
        list.add(bs756);
        BookSeries bs757 = new BookSeries(758, "varius nonummy", 0, SerieTypeEnum.LIVRO, "quisque euismod ullamcorper nonummy metus");
        list.add(bs757);
        BookSeries bs758 = new BookSeries(759, "turpis", 9, SerieTypeEnum.HQ, "aliquam felis fermentum fusce ultricies");
        list.add(bs758);
        BookSeries bs759 = new BookSeries(760, "fermentum", 7, SerieTypeEnum.HQ, "dignissim cubilia sodales lacus feugiat");
        list.add(bs759);
        BookSeries bs760 = new BookSeries(761, "risus", 4, SerieTypeEnum.LIVRO, "fusce nonummy tincidunt luctus pharetra");
        list.add(bs760);
        BookSeries bs761 = new BookSeries(762, "etiam tincidunt", 4, SerieTypeEnum.LIVRO, "metus integer auctor vesti egestas");
        list.add(bs761);
        BookSeries bs762 = new BookSeries(763, "bibendum varius", 0, SerieTypeEnum.LIVRO, "posuere vivamus bulum aliquet elementum");
        list.add(bs762);
        BookSeries bs763 = new BookSeries(764, "ornare", 5, SerieTypeEnum.MANGA, "ornare sapien sociosqu semper facilisis");
        list.add(bs763);
        BookSeries bs764 = new BookSeries(765, "venenatis", 4, SerieTypeEnum.LIVRO, "auctor feugiat consequat suspendisse primis");
        list.add(bs764);
        BookSeries bs765 = new BookSeries(766, "primis", 4, SerieTypeEnum.LIVRO, "tumst lacinia volutpat commodo mattis");
        list.add(bs765);
        BookSeries bs766 = new BookSeries(767, "magna", 4, SerieTypeEnum.MANGA, "consectetuer ornare aptent posuere metus");
        list.add(bs766);
        BookSeries bs767 = new BookSeries(768, "scelerisque", 1, SerieTypeEnum.LIVRO, "augue aliquam facilisi interdum torquent");
        list.add(bs767);
        BookSeries bs768 = new BookSeries(769, "cubilia", 3, SerieTypeEnum.HQ, "habitant vitae wisiaenean torquent posuere");
        list.add(bs768);
        BookSeries bs769 = new BookSeries(770, "volutpat", 9, SerieTypeEnum.HQ, "platea facilisisnunc wisiaenean senectus porttitor");
        list.add(bs769);
        BookSeries bs770 = new BookSeries(771, "ultricies", 1, SerieTypeEnum.HQ, "proin ipsum primis pulvinar turpis");
        list.add(bs770);
        BookSeries bs771 = new BookSeries(772, "fames", 5, SerieTypeEnum.MANGA, "imperdiet proin fusce fusce porta");
        list.add(bs771);
        BookSeries bs772 = new BookSeries(773, "mollis habitant", 7, SerieTypeEnum.LIVRO, "cursus pharetra facilisis lacus eleifend");
        list.add(bs772);
        BookSeries bs773 = new BookSeries(774, "mauris", 8, SerieTypeEnum.MANGA, "senectus tortor vestibulum interdum facilisi");
        list.add(bs773);
        BookSeries bs774 = new BookSeries(775, "metus", 4, SerieTypeEnum.HQ, "dignissim sapien primis tortor accumsan");
        list.add(bs774);
        BookSeries bs775 = new BookSeries(776, "facilisi", 6, SerieTypeEnum.HQ, "ultricies vitae platea auctor dictum");
        list.add(bs775);
        BookSeries bs776 = new BookSeries(777, "tristique suspendisse", 2, SerieTypeEnum.HQ, "sagittis etiam tincidunt tumst senectus");
        list.add(bs776);
        BookSeries bs777 = new BookSeries(778, "praesent", 9, SerieTypeEnum.HQ, "pulvinar mollis laoreet velit praesent");
        list.add(bs777);
        BookSeries bs778 = new BookSeries(779, "magna suspendisse", 6, SerieTypeEnum.LIVRO, "tortor sagittis lacus tincidunt malesuada");
        list.add(bs778);
        BookSeries bs779 = new BookSeries(780, "ullamcorper", 10, SerieTypeEnum.LIVRO, "varius vehicula bulum nonummy proin");
        list.add(bs779);
        BookSeries bs780 = new BookSeries(781, "ipsum", 7, SerieTypeEnum.MANGA, "semper felis turpis pretium convallis");
        list.add(bs780);
        BookSeries bs781 = new BookSeries(782, "pulvinar", 4, SerieTypeEnum.LIVRO, "semper praesent imperdiet facilisis tempor");
        list.add(bs781);
        BookSeries bs782 = new BookSeries(783, "dignissim", 8, SerieTypeEnum.MANGA, "senectus imperdiet consectetuer posuere fames");
        list.add(bs782);
        BookSeries bs783 = new BookSeries(784, "habitant", 3, SerieTypeEnum.MANGA, "quisque curabitur lacus neque pellentesque");
        list.add(bs783);
        BookSeries bs784 = new BookSeries(785, "posuere dolor", 10, SerieTypeEnum.MANGA, "turpis velit velit quisque tellus");
        list.add(bs784);
        BookSeries bs785 = new BookSeries(786, "varius fames", 9, SerieTypeEnum.LIVRO, "lorem fermentum vehicula pharetra tristique");
        list.add(bs785);
        BookSeries bs786 = new BookSeries(787, "porttitor torquent", 3, SerieTypeEnum.HQ, "semper primis lectus conubia habitant");
        list.add(bs786);
        BookSeries bs787 = new BookSeries(788, "lectus", 7, SerieTypeEnum.MANGA, "pharetra tellus sociosqu tincidunt lorem");
        list.add(bs787);
        BookSeries bs788 = new BookSeries(789, "netus cubilia", 1, SerieTypeEnum.HQ, "hendrerit curae fusce pellentesque vesti");
        list.add(bs788);
        BookSeries bs789 = new BookSeries(790, "feugiat", 5, SerieTypeEnum.MANGA, "iaculis accumsan porta dignissim augue");
        list.add(bs789);
        BookSeries bs790 = new BookSeries(791, "cursus", 4, SerieTypeEnum.HQ, "tortor ultricies senectus luctus lorem");
        list.add(bs790);
        BookSeries bs791 = new BookSeries(792, "hymenaeos", 1, SerieTypeEnum.MANGA, "accumsan mollis wisiaenean nostra magna");
        list.add(bs791);
        BookSeries bs792 = new BookSeries(793, "tellus", 5, SerieTypeEnum.MANGA, "scelerisque felis lacinia justo nostra");
        list.add(bs792);
        BookSeries bs793 = new BookSeries(794, "sagittis tempus", 3, SerieTypeEnum.MANGA, "netus curae lacinia inceptos platea");
        list.add(bs793);
        BookSeries bs794 = new BookSeries(795, "maecenas", 7, SerieTypeEnum.LIVRO, "tortor consectetuer morbi consequat neque");
        list.add(bs794);
        BookSeries bs795 = new BookSeries(796, "nulla", 1, SerieTypeEnum.HQ, "bibendum dictumst imperdiet tellus hendrerit");
        list.add(bs795);
        BookSeries bs796 = new BookSeries(797, "fames", 10, SerieTypeEnum.LIVRO, "sollicitudin suspendisse sollicitudin placerat inceptos");
        list.add(bs796);
        BookSeries bs797 = new BookSeries(798, "ultricies scelerisque", 9, SerieTypeEnum.MANGA, "dolor etiam nostra placerat egestas");
        list.add(bs797);
        BookSeries bs798 = new BookSeries(799, "luctus augue", 3, SerieTypeEnum.LIVRO, "malesuada mauris phasellus lacinia dignissim");
        list.add(bs798);
        BookSeries bs799 = new BookSeries(800, "dolor", 6, SerieTypeEnum.HQ, "interdum viverra semper vivamus wisiaenean");
        list.add(bs799);
        BookSeries bs800 = new BookSeries(801, "etiam", 6, SerieTypeEnum.HQ, "facilisisnunc nulla congue habitant consectetuer");
        list.add(bs800);
        BookSeries bs801 = new BookSeries(802, "vitae", 2, SerieTypeEnum.MANGA, "sociosqu hymenaeos litora facilisis senectus");
        list.add(bs801);
        BookSeries bs802 = new BookSeries(803, "integer", 4, SerieTypeEnum.LIVRO, "scelerisque risus lectus tortor hymenaeos");
        list.add(bs802);
        BookSeries bs803 = new BookSeries(804, "sodales", 7, SerieTypeEnum.LIVRO, "consectetuer rutrum fringilla ullamcorper molestie");
        list.add(bs803);
        BookSeries bs804 = new BookSeries(805, "consectetuer", 5, SerieTypeEnum.MANGA, "nullam vivamus facilisisnunc etiam ligula");
        list.add(bs804);
        BookSeries bs805 = new BookSeries(806, "maecenas justo", 1, SerieTypeEnum.MANGA, "porta sollicitudin ultricies justo iaculis");
        list.add(bs805);
        BookSeries bs806 = new BookSeries(807, "porta", 0, SerieTypeEnum.HQ, "scelerisque venenatis iaculis tempor ullamcorper");
        list.add(bs806);
        BookSeries bs807 = new BookSeries(808, "purus", 9, SerieTypeEnum.MANGA, "curabitur quisque lorem hymenaeos rutrum");
        list.add(bs807);
        BookSeries bs808 = new BookSeries(809, "volutpat laoreet", 6, SerieTypeEnum.HQ, "justo primis platea netus class");
        list.add(bs808);
        BookSeries bs809 = new BookSeries(810, "torquent aliquam", 1, SerieTypeEnum.MANGA, "vehicula maecenas ipsum bulum scelerisque");
        list.add(bs809);
        BookSeries bs810 = new BookSeries(811, "tempus luctus", 4, SerieTypeEnum.MANGA, "praesent felis faucibus congue porta");
        list.add(bs810);
        BookSeries bs811 = new BookSeries(812, "conubia class", 7, SerieTypeEnum.LIVRO, "inceptos habitant mauris imperdiet mollis");
        list.add(bs811);
        BookSeries bs812 = new BookSeries(813, "neque", 2, SerieTypeEnum.MANGA, "porttitor facilisi donec facilisi volutpat");
        list.add(bs812);
        BookSeries bs813 = new BookSeries(814, "justo", 1, SerieTypeEnum.HQ, "metus imperdiet etiam magna tortor");
        list.add(bs813);
        BookSeries bs814 = new BookSeries(815, "ultricies nonummy", 4, SerieTypeEnum.LIVRO, "primis scelerisque sagittis praesent aenean");
        list.add(bs814);
        BookSeries bs815 = new BookSeries(816, "pulvinar euismod", 3, SerieTypeEnum.MANGA, "litora eleifend nulla mollis netus");
        list.add(bs815);
        BookSeries bs816 = new BookSeries(817, "hendrerit", 2, SerieTypeEnum.LIVRO, "platea vehicula curae etiam vivamus");
        list.add(bs816);
        BookSeries bs817 = new BookSeries(818, "pulvinar", 0, SerieTypeEnum.MANGA, "auctor libero curae interdum consectetuer");
        list.add(bs817);
        BookSeries bs818 = new BookSeries(819, "elementum semper", 8, SerieTypeEnum.MANGA, "dolor iaculis netus maecenas inceptos");
        list.add(bs818);
        BookSeries bs819 = new BookSeries(820, "conubia", 5, SerieTypeEnum.MANGA, "ipsum curae ornare lacus posuere");
        list.add(bs819);
        BookSeries bs820 = new BookSeries(821, "consectetuer donec", 8, SerieTypeEnum.HQ, "vestibulum bulum sociosqu tumst turpis");
        list.add(bs820);
        BookSeries bs821 = new BookSeries(822, "aliquam vivamus", 10, SerieTypeEnum.MANGA, "tristique torquent varius feugiat scelerisque");
        list.add(bs821);
        BookSeries bs822 = new BookSeries(823, "ullamcorper", 6, SerieTypeEnum.LIVRO, "suspendisse fusce ultricies lobortis volutpat");
        list.add(bs822);
        BookSeries bs823 = new BookSeries(824, "hymenaeos", 4, SerieTypeEnum.LIVRO, "convallis laoreet vitae cursus libero");
        list.add(bs823);
        BookSeries bs824 = new BookSeries(825, "imperdiet", 4, SerieTypeEnum.LIVRO, "velit hymenaeos phasellus integer viverra");
        list.add(bs824);
        BookSeries bs825 = new BookSeries(826, "justo sagittis", 3, SerieTypeEnum.MANGA, "taciti adipiscing dictum lacinia vestibulum");
        list.add(bs825);
        BookSeries bs826 = new BookSeries(827, "egestas", 7, SerieTypeEnum.LIVRO, "sodales metus commodo tincidunt scelerisque");
        list.add(bs826);
        BookSeries bs827 = new BookSeries(828, "egestas", 9, SerieTypeEnum.LIVRO, "risus lorem porta elementum lacinia");
        list.add(bs827);
        BookSeries bs828 = new BookSeries(829, "primis", 3, SerieTypeEnum.MANGA, "libero semper consequat risus scelerisque");
        list.add(bs828);
        BookSeries bs829 = new BookSeries(830, "magna", 1, SerieTypeEnum.MANGA, "bulum iaculis morbi facilisisnunc turpis");
        list.add(bs829);
        BookSeries bs830 = new BookSeries(831, "libero", 7, SerieTypeEnum.MANGA, "inceptos vivamus rutrum scelerisque conubia");
        list.add(bs830);
        BookSeries bs831 = new BookSeries(832, "lacus", 6, SerieTypeEnum.HQ, "sagittis pharetra habitant hendrerit tellus");
        list.add(bs831);
        BookSeries bs832 = new BookSeries(833, "porta", 2, SerieTypeEnum.HQ, "metus consectetuer habitant ultrices iaculis");
        list.add(bs832);
        BookSeries bs833 = new BookSeries(834, "feugiat", 6, SerieTypeEnum.MANGA, "hymenaeos rutrum rutrum magna pharetra");
        list.add(bs833);
        BookSeries bs834 = new BookSeries(835, "congue", 1, SerieTypeEnum.MANGA, "auctor vehicula dignissim quisque aliquet");
        list.add(bs834);
        BookSeries bs835 = new BookSeries(836, "fames", 1, SerieTypeEnum.MANGA, "habitasse hendrerit bibendum pharetra vivamus");
        list.add(bs835);
        BookSeries bs836 = new BookSeries(837, "mattis", 10, SerieTypeEnum.LIVRO, "vivamus suspendisse sodales magna laoreet");
        list.add(bs836);
        BookSeries bs837 = new BookSeries(838, "eleifend", 4, SerieTypeEnum.MANGA, "risus habitant volutpat fusce venenatis");
        list.add(bs837);
        BookSeries bs838 = new BookSeries(839, "vestibulum aliquam", 9, SerieTypeEnum.MANGA, "semper molestie tempus ullamcorper nullam");
        list.add(bs838);
        BookSeries bs839 = new BookSeries(840, "pellentesque felis", 7, SerieTypeEnum.MANGA, "bibendum integer cubilia morbi interdum");
        list.add(bs839);
        BookSeries bs840 = new BookSeries(841, "lobortis", 7, SerieTypeEnum.HQ, "praesent egestas morbi ornare hymenaeos");
        list.add(bs840);
        BookSeries bs841 = new BookSeries(842, "placerat pellentesque", 2, SerieTypeEnum.HQ, "morbi auctor risus justo consequat");
        list.add(bs841);
        BookSeries bs842 = new BookSeries(843, "pellentesque phasellus", 3, SerieTypeEnum.MANGA, "maecenas lectus egestas eleifend phasellus");
        list.add(bs842);
        BookSeries bs843 = new BookSeries(844, "aenean facilisi", 1, SerieTypeEnum.MANGA, "mauris bulum tellus tortor risus");
        list.add(bs843);
        BookSeries bs844 = new BookSeries(845, "etiam", 9, SerieTypeEnum.LIVRO, "aliquam praesent tincidunt senectus risus");
        list.add(bs844);
        BookSeries bs845 = new BookSeries(846, "lectus hendrerit", 10, SerieTypeEnum.MANGA, "tumst pharetra mattis fermentum tumst");
        list.add(bs845);
        BookSeries bs846 = new BookSeries(847, "morbi", 9, SerieTypeEnum.LIVRO, "inceptos euismod accumsan feugiat auctor");
        list.add(bs846);
        BookSeries bs847 = new BookSeries(848, "turpis lobortis", 5, SerieTypeEnum.MANGA, "bibendum curae auctor lobortis litora");
        list.add(bs847);
        BookSeries bs848 = new BookSeries(849, "justo", 4, SerieTypeEnum.MANGA, "tristique laoreet cursus feugiat morbi");
        list.add(bs848);
        BookSeries bs849 = new BookSeries(850, "taciti sagittis", 6, SerieTypeEnum.LIVRO, "elementum platea integer primis lacus");
        list.add(bs849);
        BookSeries bs850 = new BookSeries(851, "mattis", 6, SerieTypeEnum.MANGA, "libero tempus congue tincidunt sociosqu");
        list.add(bs850);
        BookSeries bs851 = new BookSeries(852, "porta", 2, SerieTypeEnum.MANGA, "consequat nulla posuere donec sociosqu");
        list.add(bs851);
        BookSeries bs852 = new BookSeries(853, "elementum", 6, SerieTypeEnum.MANGA, "tempor bulum dolor mauris aliquet");
        list.add(bs852);
        BookSeries bs853 = new BookSeries(854, "ipsum", 7, SerieTypeEnum.HQ, "justo libero molestie vehicula consequat");
        list.add(bs853);
        BookSeries bs854 = new BookSeries(855, "nullam", 7, SerieTypeEnum.HQ, "morbi varius phasellus mattis hendrerit");
        list.add(bs854);
        BookSeries bs855 = new BookSeries(856, "volutpat", 9, SerieTypeEnum.LIVRO, "taciti curae dictum venenatis elementum");
        list.add(bs855);
        BookSeries bs856 = new BookSeries(857, "hendrerit", 10, SerieTypeEnum.HQ, "fusce nulla fames vivamus magna");
        list.add(bs856);
        BookSeries bs857 = new BookSeries(858, "cubilia", 5, SerieTypeEnum.HQ, "pretium lacinia varius sodales viverra");
        list.add(bs857);
        BookSeries bs858 = new BookSeries(859, "quisque ornare", 9, SerieTypeEnum.HQ, "nonummy ultricies tumst vivamus dictum");
        list.add(bs858);
        BookSeries bs859 = new BookSeries(860, "volutpat", 3, SerieTypeEnum.HQ, "semper dictumst conubia suspendisse posuere");
        list.add(bs859);
        BookSeries bs860 = new BookSeries(861, "netus", 1, SerieTypeEnum.LIVRO, "turpis aptent malesuada convallis facilisisnunc");
        list.add(bs860);
        BookSeries bs861 = new BookSeries(862, "sapien", 3, SerieTypeEnum.MANGA, "imperdiet inceptos tempus class ligula");
        list.add(bs861);
        BookSeries bs862 = new BookSeries(863, "litora", 4, SerieTypeEnum.LIVRO, "netus consectetuer egestas dictum malesuada");
        list.add(bs862);
        BookSeries bs863 = new BookSeries(864, "habitasse", 1, SerieTypeEnum.HQ, "consequat dictum aenean platea conubia");
        list.add(bs863);
        BookSeries bs864 = new BookSeries(865, "faucibus", 8, SerieTypeEnum.HQ, "varius vivamus fringilla rutrum iaculis");
        list.add(bs864);
        BookSeries bs865 = new BookSeries(866, "pellentesque", 0, SerieTypeEnum.LIVRO, "risus tellus egestas faucibus bulum");
        list.add(bs865);
        BookSeries bs866 = new BookSeries(867, "porttitor", 9, SerieTypeEnum.LIVRO, "dolor fringilla sagittis libero elementum");
        list.add(bs866);
        BookSeries bs867 = new BookSeries(868, "viverra", 1, SerieTypeEnum.LIVRO, "fames consectetuer accumsan integer mattis");
        list.add(bs867);
        BookSeries bs868 = new BookSeries(869, "tortor", 4, SerieTypeEnum.LIVRO, "placerat consequat egestas auctor lectus");
        list.add(bs868);
        BookSeries bs869 = new BookSeries(870, "habitasse bibendum", 2, SerieTypeEnum.LIVRO, "hendrerit conubia tempor ligula lobortis");
        list.add(bs869);
        BookSeries bs870 = new BookSeries(871, "sapien", 3, SerieTypeEnum.LIVRO, "lobortis volutpat lacinia torquent ultrices");
        list.add(bs870);
        BookSeries bs871 = new BookSeries(872, "hymenaeos vehicula", 7, SerieTypeEnum.MANGA, "nullam lorem hendrerit adipiscing nulla");
        list.add(bs871);
        BookSeries bs872 = new BookSeries(873, "aptent", 8, SerieTypeEnum.MANGA, "porta torquent torquent ipsum auctor");
        list.add(bs872);
        BookSeries bs873 = new BookSeries(874, "lacinia facilisis", 6, SerieTypeEnum.MANGA, "augue bulum ligula libero libero");
        list.add(bs873);
        BookSeries bs874 = new BookSeries(875, "placerat faucibus", 4, SerieTypeEnum.MANGA, "semper morbi egestas inceptos nulla");
        list.add(bs874);
        BookSeries bs875 = new BookSeries(876, "tristique", 10, SerieTypeEnum.MANGA, "vestibulum facilisi aptent morbi primis");
        list.add(bs875);
        BookSeries bs876 = new BookSeries(877, "dictum", 6, SerieTypeEnum.MANGA, "ultrices volutpat cubilia porttitor praesent");
        list.add(bs876);
        BookSeries bs877 = new BookSeries(878, "lorem tempor", 1, SerieTypeEnum.LIVRO, "purus pharetra habitasse lorem turpis");
        list.add(bs877);
        BookSeries bs878 = new BookSeries(879, "varius eleifend", 0, SerieTypeEnum.LIVRO, "vehicula nonummy felis phasellus purus");
        list.add(bs878);
        BookSeries bs879 = new BookSeries(880, "interdum", 1, SerieTypeEnum.LIVRO, "fusce ligula pellentesque tristique consequat");
        list.add(bs879);
        BookSeries bs880 = new BookSeries(881, "vehicula", 10, SerieTypeEnum.HQ, "curabitur ipsum iaculis vitae justo");
        list.add(bs880);
        BookSeries bs881 = new BookSeries(882, "vehicula", 0, SerieTypeEnum.LIVRO, "semper accumsan iaculis phasellus mauris");
        list.add(bs881);
        BookSeries bs882 = new BookSeries(883, "porttitor adipiscing", 0, SerieTypeEnum.MANGA, "netus semper taciti elementum tempor");
        list.add(bs882);
        BookSeries bs883 = new BookSeries(884, "fames", 10, SerieTypeEnum.MANGA, "inceptos varius purus primis velit");
        list.add(bs883);
        BookSeries bs884 = new BookSeries(885, "egestas iaculis", 5, SerieTypeEnum.HQ, "tristique adipiscing litora vestibulum lectus");
        list.add(bs884);
        BookSeries bs885 = new BookSeries(886, "facilisis ipsum", 4, SerieTypeEnum.MANGA, "platea fringilla cubilia sagittis egestas");
        list.add(bs885);
        BookSeries bs886 = new BookSeries(887, "venenatis", 8, SerieTypeEnum.LIVRO, "aliquam bibendum senectus platea litora");
        list.add(bs886);
        BookSeries bs887 = new BookSeries(888, "senectus aliquet", 2, SerieTypeEnum.MANGA, "turpis praesent vitae iaculis metus");
        list.add(bs887);
        BookSeries bs888 = new BookSeries(889, "pulvinar", 2, SerieTypeEnum.MANGA, "vehicula lobortis phasellus varius inceptos");
        list.add(bs888);
        BookSeries bs889 = new BookSeries(890, "rutrum", 6, SerieTypeEnum.MANGA, "aliquet tortor morbi primis tumst");
        list.add(bs889);
        BookSeries bs890 = new BookSeries(891, "dictum", 3, SerieTypeEnum.HQ, "neque convallis porttitor suspendisse tumst");
        list.add(bs890);
        BookSeries bs891 = new BookSeries(892, "nulla", 2, SerieTypeEnum.LIVRO, "venenatis sollicitudin proin libero aliquet");
        list.add(bs891);
        BookSeries bs892 = new BookSeries(893, "hendrerit feugiat", 5, SerieTypeEnum.HQ, "augue faucibus eleifend purus ultricies");
        list.add(bs892);
        BookSeries bs893 = new BookSeries(894, "lacus", 5, SerieTypeEnum.LIVRO, "ipsum dolor elementum metus lectus");
        list.add(bs893);
        BookSeries bs894 = new BookSeries(895, "pellentesque", 0, SerieTypeEnum.HQ, "fermentum class suspendisse risus hendrerit");
        list.add(bs894);
        BookSeries bs895 = new BookSeries(896, "fringilla lacus", 2, SerieTypeEnum.HQ, "auctor dictum molestie consequat justo");
        list.add(bs895);
        BookSeries bs896 = new BookSeries(897, "pretium", 1, SerieTypeEnum.HQ, "nullam iaculis vivamus eleifend iaculis");
        list.add(bs896);
        BookSeries bs897 = new BookSeries(898, "vivamus", 5, SerieTypeEnum.MANGA, "mauris tincidunt litora fringilla cubilia");
        list.add(bs897);
        BookSeries bs898 = new BookSeries(899, "adipiscing", 6, SerieTypeEnum.LIVRO, "purus fames sodales interdum nonummy");
        list.add(bs898);
        BookSeries bs899 = new BookSeries(900, "morbi mollis", 2, SerieTypeEnum.HQ, "tempor tumst torquent lacus pretium");
        list.add(bs899);

        Connection.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            bookSeriesDBM.insertBookSeries(iteration);
        });
        Connection.getCon().getTransaction().commit();
    }
}
