package preInsertions;

import Conn.Connection;
import DBManager.WritersDBM;
import entities.Countries;
import entities.Writers;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertWriters2
{

    WritersDBM writersDBM = new WritersDBM();
    List<Writers> list = new ArrayList<>();
    Countries c = new Countries();

    public void insert() {

        c.setCountry_id(108);
        Writers wirters500 = new Writers(501, "risus consectetuer nostra bibendum", c, "justo metus porttitor curabitur placerat");
        list.add(wirters500);
        c.setCountry_id(136);
        Writers wirters501 = new Writers(502, "pulvinar aptent luctus", c, "accumsan conubia luctus mauris felis");
        list.add(wirters501);
        c.setCountry_id(90);
        Writers wirters502 = new Writers(503, "lectus vivamus fusce tincidunt", c, "imperdiet ligula velit viverra primis");
        list.add(wirters502);
        c.setCountry_id(119);
        Writers wirters503 = new Writers(504, "elementum ullamcorper sodales", c, "felis bibendum vestibulum viverra nonummy");
        list.add(wirters503);
        c.setCountry_id(70);
        Writers wirters504 = new Writers(505, "ultricies eleifend justo", c, "lorem facilisis fringilla cubilia habitant");
        list.add(wirters504);
        c.setCountry_id(19);
        Writers wirters505 = new Writers(506, "aliquam mattis", c, "taciti dolor faucibus pharetra metus");
        list.add(wirters505);
        c.setCountry_id(113);
        Writers wirters506 = new Writers(507, "fusce nonummy quisque", c, "convallis pulvinar maecenas vehicula tortor");
        list.add(wirters506);
        c.setCountry_id(16);
        Writers wirters507 = new Writers(508, "malesuada bibendum vitae", c, "taciti interdum primis aptent tortor");
        list.add(wirters507);
        c.setCountry_id(89);
        Writers wirters508 = new Writers(509, "pharetra consequat", c, "morbi fames tristique curae torquent");
        list.add(wirters508);
        c.setCountry_id(141);
        Writers wirters509 = new Writers(510, "sapien ultrices porta facilisisnunc", c, "tristique feugiat consequat fusce malesuada");
        list.add(wirters509);
        c.setCountry_id(42);
        Writers wirters510 = new Writers(511, "pharetra dignissim interdum senectus", c, "lorem porttitor aliquam wisiaenean lacus");
        list.add(wirters510);
        c.setCountry_id(119);
        Writers wirters511 = new Writers(512, "class molestie justo metus", c, "elementum nonummy integer consectetuer habitasse");
        list.add(wirters511);
        c.setCountry_id(73);
        Writers wirters512 = new Writers(513, "placerat fringilla", c, "litora augue nonummy litora porttitor");
        list.add(wirters512);
        c.setCountry_id(100);
        Writers wirters513 = new Writers(514, "consequat dictum tempus", c, "malesuada sollicitudin nullam porttitor volutpat");
        list.add(wirters513);
        c.setCountry_id(147);
        Writers wirters514 = new Writers(515, "dignissim vesti morbi nullam", c, "magna scelerisque curae sociosqu ultricies");
        list.add(wirters514);
        c.setCountry_id(20);
        Writers wirters515 = new Writers(516, "sodales velit", c, "habitant varius interdum dictumst conubia");
        list.add(wirters515);
        c.setCountry_id(77);
        Writers wirters516 = new Writers(517, "adipiscing congue", c, "ullamcorper lorem justo volutpat pharetra");
        list.add(wirters516);
        c.setCountry_id(26);
        Writers wirters517 = new Writers(518, "cursus mattis", c, "egestas lobortis tortor senectus tincidunt");
        list.add(wirters517);
        c.setCountry_id(146);
        Writers wirters518 = new Writers(519, "dictum nullam cursus", c, "fusce placerat cubilia elementum quisque");
        list.add(wirters518);
        c.setCountry_id(89);
        Writers wirters519 = new Writers(520, "curae habitasse", c, "curabitur wisiaenean lorem placerat quisque");
        list.add(wirters519);
        c.setCountry_id(44);
        Writers wirters520 = new Writers(521, "pharetra aliquam mollis", c, "lorem vesti habitant malesuada facilisi");
        list.add(wirters520);
        c.setCountry_id(10);
        Writers wirters521 = new Writers(522, "varius facilisisnunc", c, "rutrum lectus convallis primis inceptos");
        list.add(wirters521);
        c.setCountry_id(137);
        Writers wirters522 = new Writers(523, "consequat varius", c, "imperdiet tempus tempus nostra quisque");
        list.add(wirters522);
        c.setCountry_id(117);
        Writers wirters523 = new Writers(524, "velit ipsum mollis", c, "fames etiam imperdiet ultrices nonummy");
        list.add(wirters523);
        c.setCountry_id(101);
        Writers wirters524 = new Writers(525, "bibendum turpis pretium", c, "habitant tempus sapien semper integer");
        list.add(wirters524);
        c.setCountry_id(105);
        Writers wirters525 = new Writers(526, "fringilla vitae sodales velit", c, "tincidunt sagittis ultricies rutrum libero");
        list.add(wirters525);
        c.setCountry_id(42);
        Writers wirters526 = new Writers(527, "rutrum curabitur augue sollicitudin", c, "tristique sociosqu iaculis sodales mattis");
        list.add(wirters526);
        c.setCountry_id(89);
        Writers wirters527 = new Writers(528, "augue lacus felis porta", c, "venenatis eleifend nostra dictum mattis");
        list.add(wirters527);
        c.setCountry_id(41);
        Writers wirters528 = new Writers(529, "suspendisse bulum egestas", c, "dignissim metus vehicula eleifend aenean");
        list.add(wirters528);
        c.setCountry_id(132);
        Writers wirters529 = new Writers(530, "fermentum elementum elementum", c, "adipiscing purus pretium pretium sapien");
        list.add(wirters529);
        c.setCountry_id(83);
        Writers wirters530 = new Writers(531, "magna nonummy aptent", c, "semper eleifend lectus risus ornare");
        list.add(wirters530);
        c.setCountry_id(137);
        Writers wirters531 = new Writers(532, "imperdiet sagittis ornare dictumst", c, "porttitor aliquet vitae sodales netus");
        list.add(wirters531);
        c.setCountry_id(97);
        Writers wirters532 = new Writers(533, "nullam habitasse", c, "hendrerit lobortis tristique magna aliquet");
        list.add(wirters532);
        c.setCountry_id(134);
        Writers wirters533 = new Writers(534, "turpis volutpat sagittis facilisis", c, "donec porta velit luctus imperdiet");
        list.add(wirters533);
        c.setCountry_id(100);
        Writers wirters534 = new Writers(535, "justo nulla", c, "libero lobortis commodo ullamcorper conubia");
        list.add(wirters534);
        c.setCountry_id(25);
        Writers wirters535 = new Writers(536, "proin justo egestas fermentum", c, "quisque aenean laoreet lectus quisque");
        list.add(wirters535);
        c.setCountry_id(89);
        Writers wirters536 = new Writers(537, "euismod pharetra imperdiet hymenaeos", c, "volutpat vitae sociosqu ultricies lacus");
        list.add(wirters536);
        c.setCountry_id(134);
        Writers wirters537 = new Writers(538, "rutrum vestibulum vitae aptent", c, "ipsum morbi dolor nullam mattis");
        list.add(wirters537);
        c.setCountry_id(105);
        Writers wirters538 = new Writers(539, "tortor fames hendrerit nostra", c, "sociosqu dignissim quisque ultricies semper");
        list.add(wirters538);
        c.setCountry_id(19);
        Writers wirters539 = new Writers(540, "sollicitudin lacinia", c, "ligula curae vitae nulla primis");
        list.add(wirters539);
        c.setCountry_id(75);
        Writers wirters540 = new Writers(541, "laoreet congue ipsum taciti", c, "eleifend lacinia scelerisque varius ultrices");
        list.add(wirters540);
        c.setCountry_id(104);
        Writers wirters541 = new Writers(542, "vehicula placerat convallis", c, "habitant mattis vitae luctus accumsan");
        list.add(wirters541);
        c.setCountry_id(124);
        Writers wirters542 = new Writers(543, "mauris nostra aenean libero", c, "purus sociosqu placerat taciti primis");
        list.add(wirters542);
        c.setCountry_id(118);
        Writers wirters543 = new Writers(544, "commodo turpis vesti", c, "placerat facilisis ultrices nullam hendrerit");
        list.add(wirters543);
        c.setCountry_id(51);
        Writers wirters544 = new Writers(545, "justo curabitur suspendisse", c, "facilisisnunc imperdiet dignissim ligula maecenas");
        list.add(wirters544);
        c.setCountry_id(109);
        Writers wirters545 = new Writers(546, "tempor curae wisiaenean faucibus", c, "vivamus iaculis fames lectus class");
        list.add(wirters545);
        c.setCountry_id(76);
        Writers wirters546 = new Writers(547, "ullamcorper litora", c, "pulvinar laoreet malesuada proin lorem");
        list.add(wirters546);
        c.setCountry_id(147);
        Writers wirters547 = new Writers(548, "sollicitudin vitae nulla", c, "tempus neque senectus pharetra donec");
        list.add(wirters547);
        c.setCountry_id(125);
        Writers wirters548 = new Writers(549, "adipiscing vitae", c, "suspendisse hymenaeos augue pretium phasellus");
        list.add(wirters548);
        c.setCountry_id(13);
        Writers wirters549 = new Writers(550, "bulum torquent integer tellus", c, "neque suspendisse venenatis vitae dictum");
        list.add(wirters549);
        c.setCountry_id(59);
        Writers wirters550 = new Writers(551, "nostra cursus", c, "aptent curae bibendum tumst tellus");
        list.add(wirters550);
        c.setCountry_id(78);
        Writers wirters551 = new Writers(552, "turpis eleifend litora", c, "inceptos lorem ultricies hymenaeos tristique");
        list.add(wirters551);
        c.setCountry_id(118);
        Writers wirters552 = new Writers(553, "nullam turpis magna", c, "quisque feugiat vesti ultricies tellus");
        list.add(wirters552);
        c.setCountry_id(131);
        Writers wirters553 = new Writers(554, "eleifend suspendisse", c, "etiam mattis platea hymenaeos tristique");
        list.add(wirters553);
        c.setCountry_id(127);
        Writers wirters554 = new Writers(555, "inceptos aptent pretium", c, "porta vitae pharetra luctus laoreet");
        list.add(wirters554);
        c.setCountry_id(54);
        Writers wirters555 = new Writers(556, "habitasse conubia", c, "tincidunt cursus imperdiet fames praesent");
        list.add(wirters555);
        c.setCountry_id(121);
        Writers wirters556 = new Writers(557, "lectus sapien", c, "vehicula integer vesti rutrum magna");
        list.add(wirters556);
        c.setCountry_id(45);
        Writers wirters557 = new Writers(558, "libero tortor mauris fermentum", c, "platea nostra ullamcorper ornare pretium");
        list.add(wirters557);
        c.setCountry_id(147);
        Writers wirters558 = new Writers(559, "phasellus auctor convallis volutpat", c, "fusce hymenaeos convallis curae fringilla");
        list.add(wirters558);
        c.setCountry_id(80);
        Writers wirters559 = new Writers(560, "habitant morbi", c, "commodo faucibus posuere viverra imperdiet");
        list.add(wirters559);
        c.setCountry_id(3);
        Writers wirters560 = new Writers(561, "magna tincidunt", c, "ultrices fermentum tellus sapien nullam");
        list.add(wirters560);
        c.setCountry_id(36);
        Writers wirters561 = new Writers(562, "laoreet congue nullam", c, "mattis suspendisse vitae hendrerit nullam");
        list.add(wirters561);
        c.setCountry_id(107);
        Writers wirters562 = new Writers(563, "etiam integer", c, "commodo dictumst bibendum fermentum iaculis");
        list.add(wirters562);
        c.setCountry_id(37);
        Writers wirters563 = new Writers(564, "purus aliquam litora", c, "praesent sagittis nulla cursus lectus");
        list.add(wirters563);
        c.setCountry_id(21);
        Writers wirters564 = new Writers(565, "conubia platea", c, "vestibulum aptent aptent magna felis");
        list.add(wirters564);
        c.setCountry_id(22);
        Writers wirters565 = new Writers(566, "malesuada fusce", c, "pulvinar praesent habitant magna dignissim");
        list.add(wirters565);
        c.setCountry_id(29);
        Writers wirters566 = new Writers(567, "mattis taciti torquent pulvinar", c, "pharetra tempor eleifend habitasse commodo");
        list.add(wirters566);
        c.setCountry_id(89);
        Writers wirters567 = new Writers(568, "aenean elementum", c, "netus posuere eleifend auctor vivamus");
        list.add(wirters567);
        c.setCountry_id(38);
        Writers wirters568 = new Writers(569, "porttitor maecenas bulum", c, "lacinia curae hendrerit libero vivamus");
        list.add(wirters568);
        c.setCountry_id(109);
        Writers wirters569 = new Writers(570, "congue placerat", c, "sollicitudin lorem cubilia imperdiet sapien");
        list.add(wirters569);
        c.setCountry_id(74);
        Writers wirters570 = new Writers(571, "iaculis habitant", c, "facilisisnunc placerat commodo lorem vitae");
        list.add(wirters570);
        c.setCountry_id(15);
        Writers wirters571 = new Writers(572, "torquent iaculis etiam purus", c, "torquent ipsum bibendum consequat curabitur");
        list.add(wirters571);
        c.setCountry_id(2);
        Writers wirters572 = new Writers(573, "lorem tincidunt pharetra hendrerit", c, "consequat adipiscing iaculis bibendum volutpat");
        list.add(wirters572);
        c.setCountry_id(27);
        Writers wirters573 = new Writers(574, "consectetuer viverra lobortis habitasse", c, "wisiaenean metus bibendum dictum habitasse");
        list.add(wirters573);
        c.setCountry_id(98);
        Writers wirters574 = new Writers(575, "lorem litora", c, "interdum tempor pharetra vesti dignissim");
        list.add(wirters574);
        c.setCountry_id(25);
        Writers wirters575 = new Writers(576, "placerat vehicula", c, "habitasse sollicitudin interdum dictum proin");
        list.add(wirters575);
        c.setCountry_id(137);
        Writers wirters576 = new Writers(577, "pellentesque pharetra", c, "feugiat imperdiet lorem nulla inceptos");
        list.add(wirters576);
        c.setCountry_id(124);
        Writers wirters577 = new Writers(578, "placerat tristique ultrices", c, "volutpat consectetuer facilisisnunc torquent justo");
        list.add(wirters577);
        c.setCountry_id(145);
        Writers wirters578 = new Writers(579, "pretium imperdiet nullam", c, "conubia bulum dolor sociosqu posuere");
        list.add(wirters578);
        c.setCountry_id(64);
        Writers wirters579 = new Writers(580, "netus maecenas", c, "imperdiet mattis nulla facilisi hendrerit");
        list.add(wirters579);
        c.setCountry_id(30);
        Writers wirters580 = new Writers(581, "consequat inceptos vivamus", c, "neque taciti sodales pellentesque taciti");
        list.add(wirters580);
        c.setCountry_id(19);
        Writers wirters581 = new Writers(582, "facilisi volutpat aenean", c, "dolor aenean dolor primis scelerisque");
        list.add(wirters581);
        c.setCountry_id(133);
        Writers wirters582 = new Writers(583, "bibendum dolor", c, "tellus velit pharetra vesti iaculis");
        list.add(wirters582);
        c.setCountry_id(56);
        Writers wirters583 = new Writers(584, "ornare luctus consectetuer", c, "tortor libero vestibulum curae fringilla");
        list.add(wirters583);
        c.setCountry_id(53);
        Writers wirters584 = new Writers(585, "lacinia proin hymenaeos", c, "feugiat ligula neque cubilia vesti");
        list.add(wirters584);
        c.setCountry_id(81);
        Writers wirters585 = new Writers(586, "suspendisse mollis", c, "pellentesque risus dictum ultrices iaculis");
        list.add(wirters585);
        c.setCountry_id(98);
        Writers wirters586 = new Writers(587, "class elementum", c, "dolor tumst porttitor hymenaeos risus");
        list.add(wirters586);
        c.setCountry_id(5);
        Writers wirters587 = new Writers(588, "posuere nulla eleifend", c, "class dignissim tristique vesti donec");
        list.add(wirters587);
        c.setCountry_id(13);
        Writers wirters588 = new Writers(589, "lorem dignissim mollis morbi", c, "augue litora lacinia habitant habitasse");
        list.add(wirters588);
        c.setCountry_id(81);
        Writers wirters589 = new Writers(590, "vitae tempor", c, "elementum metus ullamcorper volutpat suspendisse");
        list.add(wirters589);
        c.setCountry_id(112);
        Writers wirters590 = new Writers(591, "hendrerit nostra", c, "tincidunt metus dictumst feugiat class");
        list.add(wirters590);
        c.setCountry_id(149);
        Writers wirters591 = new Writers(592, "hendrerit platea aptent morbi", c, "sagittis adipiscing libero placerat volutpat");
        list.add(wirters591);
        c.setCountry_id(93);
        Writers wirters592 = new Writers(593, "mauris mollis tortor semper", c, "pharetra quisque taciti mauris sollicitudin");
        list.add(wirters592);
        c.setCountry_id(8);
        Writers wirters593 = new Writers(594, "luctus luctus turpis justo", c, "vestibulum lorem ipsum vestibulum porta");
        list.add(wirters593);
        c.setCountry_id(101);
        Writers wirters594 = new Writers(595, "phasellus hendrerit", c, "egestas integer sapien accumsan fusce");
        list.add(wirters594);
        c.setCountry_id(34);
        Writers wirters595 = new Writers(596, "pharetra posuere bulum fames", c, "consequat consectetuer euismod sapien viverra");
        list.add(wirters595);
        c.setCountry_id(133);
        Writers wirters596 = new Writers(597, "vesti feugiat tempus volutpat", c, "neque lobortis purus luctus litora");
        list.add(wirters596);
        c.setCountry_id(66);
        Writers wirters597 = new Writers(598, "justo commodo ornare auctor", c, "nulla consectetuer inceptos facilisisnunc hymenaeos");
        list.add(wirters597);
        c.setCountry_id(120);
        Writers wirters598 = new Writers(599, "facilisi accumsan felis sodales", c, "laoreet pretium curabitur pellentesque metus");
        list.add(wirters598);
        c.setCountry_id(134);
        Writers wirters599 = new Writers(600, "netus aliquet curabitur", c, "ultrices justo facilisi convallis lacus");
        list.add(wirters599);
        c.setCountry_id(87);
        Writers wirters600 = new Writers(601, "litora hendrerit", c, "cursus dolor dictumst fusce ultricies");
        list.add(wirters600);
        c.setCountry_id(35);
        Writers wirters601 = new Writers(602, "ligula pellentesque congue iaculis", c, "mattis class ligula nostra vehicula");
        list.add(wirters601);
        c.setCountry_id(135);
        Writers wirters602 = new Writers(603, "feugiat primis", c, "porttitor class ipsum dignissim hymenaeos");
        list.add(wirters602);
        c.setCountry_id(25);
        Writers wirters603 = new Writers(604, "aliquam faucibus volutpat vitae", c, "sodales hendrerit praesent habitant tristique");
        list.add(wirters603);
        c.setCountry_id(84);
        Writers wirters604 = new Writers(605, "dictum facilisis aptent purus", c, "malesuada habitant aliquet curabitur justo");
        list.add(wirters604);
        c.setCountry_id(93);
        Writers wirters605 = new Writers(606, "elementum tempus turpis scelerisque", c, "nostra sagittis dictumst tempus consequat");
        list.add(wirters605);
        c.setCountry_id(69);
        Writers wirters606 = new Writers(607, "cursus inceptos morbi facilisis", c, "felis habitasse ligula varius fames");
        list.add(wirters606);
        c.setCountry_id(57);
        Writers wirters607 = new Writers(608, "rutrum tincidunt pellentesque", c, "quisque aptent ligula conubia quisque");
        list.add(wirters607);
        c.setCountry_id(101);
        Writers wirters608 = new Writers(609, "fringilla lorem", c, "lorem tempor auctor porttitor tincidunt");
        list.add(wirters608);
        c.setCountry_id(59);
        Writers wirters609 = new Writers(610, "eleifend hendrerit feugiat", c, "vesti torquent facilisisnunc torquent praesent");
        list.add(wirters609);
        c.setCountry_id(23);
        Writers wirters610 = new Writers(611, "justo dolor vestibulum proin", c, "lobortis velit molestie purus pellentesque");
        list.add(wirters610);
        c.setCountry_id(74);
        Writers wirters611 = new Writers(612, "tortor iaculis", c, "taciti egestas risus commodo pellentesque");
        list.add(wirters611);
        c.setCountry_id(13);
        Writers wirters612 = new Writers(613, "inceptos facilisis", c, "facilisisnunc congue primis donec volutpat");
        list.add(wirters612);
        c.setCountry_id(54);
        Writers wirters613 = new Writers(614, "rutrum curabitur hymenaeos feugiat", c, "pulvinar dictum proin mattis mattis");
        list.add(wirters613);
        c.setCountry_id(31);
        Writers wirters614 = new Writers(615, "phasellus inceptos ligula", c, "integer interdum auctor dictumst nullam");
        list.add(wirters614);
        c.setCountry_id(4);
        Writers wirters615 = new Writers(616, "tellus ipsum", c, "hymenaeos taciti ornare facilisisnunc posuere");
        list.add(wirters615);
        c.setCountry_id(85);
        Writers wirters616 = new Writers(617, "habitant imperdiet elementum", c, "cursus vesti pellentesque congue taciti");
        list.add(wirters616);
        c.setCountry_id(115);
        Writers wirters617 = new Writers(618, "conubia sollicitudin", c, "sociosqu tincidunt porta curabitur consectetuer");
        list.add(wirters617);
        c.setCountry_id(97);
        Writers wirters618 = new Writers(619, "vehicula litora pretium integer", c, "lectus aptent posuere integer sociosqu");
        list.add(wirters618);
        c.setCountry_id(54);
        Writers wirters619 = new Writers(620, "facilisis lacus wisiaenean", c, "cursus consequat sagittis tincidunt vehicula");
        list.add(wirters619);
        c.setCountry_id(87);
        Writers wirters620 = new Writers(621, "nostra tristique tumst", c, "accumsan pulvinar viverra porta torquent");
        list.add(wirters620);
        c.setCountry_id(31);
        Writers wirters621 = new Writers(622, "velit facilisisnunc", c, "viverra fusce integer malesuada suspendisse");
        list.add(wirters621);
        c.setCountry_id(2);
        Writers wirters622 = new Writers(623, "fusce magna", c, "faucibus risus semper tellus imperdiet");
        list.add(wirters622);
        c.setCountry_id(68);
        Writers wirters623 = new Writers(624, "fermentum augue pellentesque", c, "ultrices sodales luctus hendrerit conubia");
        list.add(wirters623);
        c.setCountry_id(54);
        Writers wirters624 = new Writers(625, "malesuada justo", c, "magna purus netus luctus habitasse");
        list.add(wirters624);
        c.setCountry_id(100);
        Writers wirters625 = new Writers(626, "habitasse rutrum quisque magna", c, "lobortis semper senectus eleifend metus");
        list.add(wirters625);
        c.setCountry_id(108);
        Writers wirters626 = new Writers(627, "congue sagittis", c, "magna molestie volutpat tristique ipsum");
        list.add(wirters626);
        c.setCountry_id(55);
        Writers wirters627 = new Writers(628, "congue ullamcorper", c, "tempus primis wisiaenean bulum rutrum");
        list.add(wirters627);
        c.setCountry_id(121);
        Writers wirters628 = new Writers(629, "turpis integer semper", c, "dictumst justo cursus habitant lobortis");
        list.add(wirters628);
        c.setCountry_id(126);
        Writers wirters629 = new Writers(630, "fringilla morbi", c, "senectus placerat viverra posuere facilisisnunc");
        list.add(wirters629);
        c.setCountry_id(123);
        Writers wirters630 = new Writers(631, "adipiscing convallis", c, "venenatis curae ornare wisiaenean platea");
        list.add(wirters630);
        c.setCountry_id(40);
        Writers wirters631 = new Writers(632, "laoreet facilisisnunc", c, "sollicitudin convallis imperdiet bulum augue");
        list.add(wirters631);
        c.setCountry_id(73);
        Writers wirters632 = new Writers(633, "tempor primis", c, "egestas tincidunt primis dictum placerat");
        list.add(wirters632);
        c.setCountry_id(79);
        Writers wirters633 = new Writers(634, "vivamus curabitur", c, "pretium consectetuer vesti neque venenatis");
        list.add(wirters633);
        c.setCountry_id(4);
        Writers wirters634 = new Writers(635, "aliquet vivamus felis", c, "rutrum dictumst dignissim proin iaculis");
        list.add(wirters634);
        c.setCountry_id(56);
        Writers wirters635 = new Writers(636, "pretium convallis facilisi", c, "tellus aliquet vehicula scelerisque convallis");
        list.add(wirters635);
        c.setCountry_id(49);
        Writers wirters636 = new Writers(637, "platea porta litora morbi", c, "semper tristique venenatis aliquet sagittis");
        list.add(wirters636);
        c.setCountry_id(102);
        Writers wirters637 = new Writers(638, "lobortis sollicitudin cubilia", c, "bulum risus laoreet bulum congue");
        list.add(wirters637);
        c.setCountry_id(124);
        Writers wirters638 = new Writers(639, "purus varius", c, "feugiat elementum netus lorem habitant");
        list.add(wirters638);
        c.setCountry_id(131);
        Writers wirters639 = new Writers(640, "fames platea", c, "curae bibendum litora molestie pulvinar");
        list.add(wirters639);
        c.setCountry_id(104);
        Writers wirters640 = new Writers(641, "feugiat nullam dictum", c, "conubia dignissim commodo sodales curae");
        list.add(wirters640);
        c.setCountry_id(143);
        Writers wirters641 = new Writers(642, "volutpat cursus", c, "lorem facilisisnunc tincidunt interdum euismod");
        list.add(wirters641);
        c.setCountry_id(33);
        Writers wirters642 = new Writers(643, "commodo imperdiet molestie", c, "sodales etiam senectus dictumst sagittis");
        list.add(wirters642);
        c.setCountry_id(55);
        Writers wirters643 = new Writers(644, "scelerisque molestie", c, "dignissim consectetuer class magna tellus");
        list.add(wirters643);
        c.setCountry_id(81);
        Writers wirters644 = new Writers(645, "lectus facilisisnunc tristique pharetra", c, "elementum faucibus porttitor vesti placerat");
        list.add(wirters644);
        c.setCountry_id(99);
        Writers wirters645 = new Writers(646, "ligula semper ultrices litora", c, "ipsum mollis vesti cursus suspendisse");
        list.add(wirters645);
        c.setCountry_id(34);
        Writers wirters646 = new Writers(647, "ultrices quisque hendrerit aliquet", c, "laoreet placerat cubilia egestas suspendisse");
        list.add(wirters646);
        c.setCountry_id(92);
        Writers wirters647 = new Writers(648, "accumsan dictum sodales", c, "hymenaeos pharetra accumsan ligula ultricies");
        list.add(wirters647);
        c.setCountry_id(141);
        Writers wirters648 = new Writers(649, "magna mauris pulvinar congue", c, "sollicitudin accumsan nonummy imperdiet pulvinar");
        list.add(wirters648);
        c.setCountry_id(22);
        Writers wirters649 = new Writers(650, "dictum metus cursus cubilia", c, "purus platea morbi placerat aenean");
        list.add(wirters649);
        c.setCountry_id(77);
        Writers wirters650 = new Writers(651, "elementum taciti", c, "pellentesque interdum fermentum interdum wisiaenean");
        list.add(wirters650);
        c.setCountry_id(134);
        Writers wirters651 = new Writers(652, "consequat ornare", c, "class consequat fusce purus phasellus");
        list.add(wirters651);
        c.setCountry_id(120);
        Writers wirters652 = new Writers(653, "facilisi hendrerit", c, "porta nullam lorem maecenas phasellus");
        list.add(wirters652);
        c.setCountry_id(38);
        Writers wirters653 = new Writers(654, "imperdiet velit cubilia bibendum", c, "malesuada euismod fames donec quisque");
        list.add(wirters653);
        c.setCountry_id(14);
        Writers wirters654 = new Writers(655, "conubia egestas", c, "conubia porttitor mollis sociosqu sollicitudin");
        list.add(wirters654);
        c.setCountry_id(100);
        Writers wirters655 = new Writers(656, "interdum consectetuer justo", c, "lacus lacus elementum neque curae");
        list.add(wirters655);
        c.setCountry_id(3);
        Writers wirters656 = new Writers(657, "cubilia varius", c, "lacus ullamcorper nostra interdum velit");
        list.add(wirters656);
        c.setCountry_id(36);
        Writers wirters657 = new Writers(658, "tumst senectus velit", c, "purus imperdiet scelerisque dignissim wisiaenean");
        list.add(wirters657);
        c.setCountry_id(115);
        Writers wirters658 = new Writers(659, "hendrerit metus mattis praesent", c, "neque facilisis porttitor fames semper");
        list.add(wirters658);
        c.setCountry_id(97);
        Writers wirters659 = new Writers(660, "torquent lacus semper", c, "molestie morbi integer pretium mauris");
        list.add(wirters659);
        c.setCountry_id(76);
        Writers wirters660 = new Writers(661, "malesuada ipsum elementum", c, "habitasse vesti faucibus integer convallis");
        list.add(wirters660);
        c.setCountry_id(52);
        Writers wirters661 = new Writers(662, "ultricies wisiaenean", c, "laoreet turpis molestie primis dolor");
        list.add(wirters661);
        c.setCountry_id(33);
        Writers wirters662 = new Writers(663, "vestibulum tortor", c, "etiam aptent pellentesque metus magna");
        list.add(wirters662);
        c.setCountry_id(53);
        Writers wirters663 = new Writers(664, "netus phasellus vesti", c, "sollicitudin mollis nulla curae porttitor");
        list.add(wirters663);
        c.setCountry_id(5);
        Writers wirters664 = new Writers(665, "volutpat conubia nulla vehicula", c, "mattis porttitor libero nonummy morbi");
        list.add(wirters664);
        c.setCountry_id(82);
        Writers wirters665 = new Writers(666, "hendrerit ipsum etiam cubilia", c, "dictumst facilisisnunc velit fringilla aliquet");
        list.add(wirters665);
        c.setCountry_id(110);
        Writers wirters666 = new Writers(667, "volutpat mattis tempor phasellus", c, "sodales mattis torquent faucibus taciti");
        list.add(wirters666);
        c.setCountry_id(67);
        Writers wirters667 = new Writers(668, "viverra eleifend nullam", c, "cubilia posuere mattis facilisisnunc porttitor");
        list.add(wirters667);
        c.setCountry_id(120);
        Writers wirters668 = new Writers(669, "fermentum facilisi elementum", c, "augue vehicula litora hymenaeos congue");
        list.add(wirters668);
        c.setCountry_id(70);
        Writers wirters669 = new Writers(670, "fusce dignissim congue hymenaeos", c, "velit maecenas vehicula etiam turpis");
        list.add(wirters669);
        c.setCountry_id(141);
        Writers wirters670 = new Writers(671, "ligula iaculis lacinia convallis", c, "placerat tellus habitant nullam placerat");
        list.add(wirters670);
        c.setCountry_id(78);
        Writers wirters671 = new Writers(672, "mattis donec", c, "convallis magna dictum tristique curabitur");
        list.add(wirters671);
        c.setCountry_id(63);
        Writers wirters672 = new Writers(673, "litora primis maecenas", c, "facilisisnunc vitae tortor iaculis commodo");
        list.add(wirters672);
        c.setCountry_id(1);
        Writers wirters673 = new Writers(674, "congue sagittis semper felis", c, "nullam wisiaenean neque risus suspendisse");
        list.add(wirters673);
        c.setCountry_id(83);
        Writers wirters674 = new Writers(675, "turpis auctor iaculis", c, "ligula lobortis morbi sociosqu maecenas");
        list.add(wirters674);
        c.setCountry_id(6);
        Writers wirters675 = new Writers(676, "consectetuer sagittis integer volutpat", c, "dignissim mattis viverra habitasse tempor");
        list.add(wirters675);
        c.setCountry_id(130);
        Writers wirters676 = new Writers(677, "lorem hendrerit consectetuer venenatis", c, "ultrices fames purus commodo morbi");
        list.add(wirters676);
        c.setCountry_id(36);
        Writers wirters677 = new Writers(678, "mattis eleifend faucibus interdum", c, "fringilla praesent sagittis porttitor ultricies");
        list.add(wirters677);
        c.setCountry_id(127);
        Writers wirters678 = new Writers(679, "maecenas pellentesque", c, "elementum varius pellentesque varius fermentum");
        list.add(wirters678);
        c.setCountry_id(9);
        Writers wirters679 = new Writers(680, "primis nostra taciti senectus", c, "tortor magna class suspendisse congue");
        list.add(wirters679);
        c.setCountry_id(21);
        Writers wirters680 = new Writers(681, "lobortis lacinia nulla pharetra", c, "pharetra scelerisque faucibus tumst aliquam");
        list.add(wirters680);
        c.setCountry_id(53);
        Writers wirters681 = new Writers(682, "faucibus habitant litora", c, "libero sagittis facilisi cursus etiam");
        list.add(wirters681);
        c.setCountry_id(28);
        Writers wirters682 = new Writers(683, "bibendum aptent taciti commodo", c, "platea lacus convallis facilisisnunc facilisisnunc");
        list.add(wirters682);
        c.setCountry_id(81);
        Writers wirters683 = new Writers(684, "pharetra etiam sodales habitasse", c, "platea lobortis libero posuere sodales");
        list.add(wirters683);
        c.setCountry_id(75);
        Writers wirters684 = new Writers(685, "donec mattis convallis", c, "rutrum lectus pulvinar platea vehicula");
        list.add(wirters684);
        c.setCountry_id(150);
        Writers wirters685 = new Writers(686, "lacus commodo", c, "molestie risus primis fermentum nostra");
        list.add(wirters685);
        c.setCountry_id(123);
        Writers wirters686 = new Writers(687, "bibendum nulla", c, "volutpat dictumst posuere malesuada dolor");
        list.add(wirters686);
        c.setCountry_id(106);
        Writers wirters687 = new Writers(688, "vehicula ullamcorper tellus", c, "sapien hendrerit lobortis senectus egestas");
        list.add(wirters687);
        c.setCountry_id(66);
        Writers wirters688 = new Writers(689, "donec augue", c, "class vehicula adipiscing pretium commodo");
        list.add(wirters688);
        c.setCountry_id(104);
        Writers wirters689 = new Writers(690, "sociosqu facilisi elementum volutpat", c, "felis class faucibus curae sagittis");
        list.add(wirters689);
        c.setCountry_id(95);
        Writers wirters690 = new Writers(691, "tempus platea ultricies convallis", c, "scelerisque aptent scelerisque faucibus aliquet");
        list.add(wirters690);
        c.setCountry_id(135);
        Writers wirters691 = new Writers(692, "euismod tortor", c, "class placerat donec ipsum ultrices");
        list.add(wirters691);
        c.setCountry_id(129);
        Writers wirters692 = new Writers(693, "aliquet tumst proin", c, "sociosqu dolor elementum vesti dictumst");
        list.add(wirters692);
        c.setCountry_id(50);
        Writers wirters693 = new Writers(694, "velit pharetra", c, "taciti litora senectus habitant vivamus");
        list.add(wirters693);
        c.setCountry_id(23);
        Writers wirters694 = new Writers(695, "senectus vivamus", c, "primis tempor conubia magna convallis");
        list.add(wirters694);
        c.setCountry_id(28);
        Writers wirters695 = new Writers(696, "bibendum justo", c, "proin egestas vitae ullamcorper turpis");
        list.add(wirters695);
        c.setCountry_id(135);
        Writers wirters696 = new Writers(697, "imperdiet metus eleifend venenatis", c, "lobortis sodales litora convallis lorem");
        list.add(wirters696);
        c.setCountry_id(78);
        Writers wirters697 = new Writers(698, "lectus rutrum risus bibendum", c, "vitae lectus facilisisnunc ullamcorper semper");
        list.add(wirters697);
        c.setCountry_id(124);
        Writers wirters698 = new Writers(699, "tempus tellus", c, "ultricies dictum netus lacinia velit");
        list.add(wirters698);
        c.setCountry_id(57);
        Writers wirters699 = new Writers(700, "facilisisnunc sodales quisque", c, "sociosqu facilisisnunc malesuada fusce cursus");
        list.add(wirters699);
        c.setCountry_id(61);
        Writers wirters700 = new Writers(701, "platea pellentesque", c, "habitant etiam fringilla tempor consequat");
        list.add(wirters700);
        c.setCountry_id(144);
        Writers wirters701 = new Writers(702, "class eleifend pulvinar bibendum", c, "dignissim torquent hendrerit lorem augue");
        list.add(wirters701);
        c.setCountry_id(33);
        Writers wirters702 = new Writers(703, "nulla maecenas praesent", c, "fringilla aliquam posuere facilisi suspendisse");
        list.add(wirters702);
        c.setCountry_id(26);
        Writers wirters703 = new Writers(704, "tristique ipsum mattis phasellus", c, "primis viverra feugiat ipsum luctus");
        list.add(wirters703);
        c.setCountry_id(133);
        Writers wirters704 = new Writers(705, "wisiaenean tempus molestie dolor", c, "felis aliquam fermentum hymenaeos litora");
        list.add(wirters704);
        c.setCountry_id(16);
        Writers wirters705 = new Writers(706, "dignissim nulla pretium", c, "luctus donec vitae praesent primis");
        list.add(wirters705);
        c.setCountry_id(104);
        Writers wirters706 = new Writers(707, "tristique volutpat curae libero", c, "torquent eleifend sociosqu varius habitant");
        list.add(wirters706);
        c.setCountry_id(82);
        Writers wirters707 = new Writers(708, "pretium porttitor ultrices class", c, "volutpat lobortis vehicula tellus magna");
        list.add(wirters707);
        c.setCountry_id(64);
        Writers wirters708 = new Writers(709, "bibendum tortor", c, "taciti vitae vivamus tumst libero");
        list.add(wirters708);
        c.setCountry_id(60);
        Writers wirters709 = new Writers(710, "rutrum auctor", c, "dignissim nonummy hymenaeos consequat nostra");
        list.add(wirters709);
        c.setCountry_id(52);
        Writers wirters710 = new Writers(711, "vivamus morbi felis", c, "pellentesque sagittis euismod hendrerit porta");
        list.add(wirters710);
        c.setCountry_id(6);
        Writers wirters711 = new Writers(712, "nullam egestas convallis aliquam", c, "pellentesque habitasse cubilia euismod lectus");
        list.add(wirters711);
        c.setCountry_id(42);
        Writers wirters712 = new Writers(713, "sociosqu tortor tincidunt sollicitudin", c, "tempor tincidunt integer mollis dolor");
        list.add(wirters712);
        c.setCountry_id(15);
        Writers wirters713 = new Writers(714, "porta dictumst", c, "nullam fringilla feugiat fames maecenas");
        list.add(wirters713);
        c.setCountry_id(97);
        Writers wirters714 = new Writers(715, "accumsan hymenaeos semper lectus", c, "lectus proin habitasse hymenaeos malesuada");
        list.add(wirters714);
        c.setCountry_id(86);
        Writers wirters715 = new Writers(716, "habitasse sollicitudin lacus sollicitudin", c, "euismod facilisisnunc nostra fames class");
        list.add(wirters715);
        c.setCountry_id(138);
        Writers wirters716 = new Writers(717, "eleifend mollis imperdiet", c, "rutrum dignissim praesent torquent bibendum");
        list.add(wirters716);
        c.setCountry_id(4);
        Writers wirters717 = new Writers(718, "dictum accumsan justo", c, "pulvinar ornare euismod vitae hymenaeos");
        list.add(wirters717);
        c.setCountry_id(150);
        Writers wirters718 = new Writers(719, "taciti proin", c, "mauris aliquet pulvinar tempor adipiscing");
        list.add(wirters718);
        c.setCountry_id(149);
        Writers wirters719 = new Writers(720, "nulla varius facilisisnunc", c, "neque laoreet euismod viverra cursus");
        list.add(wirters719);
        c.setCountry_id(4);
        Writers wirters720 = new Writers(721, "bulum wisiaenean pharetra", c, "aptent convallis bulum lorem ornare");
        list.add(wirters720);
        c.setCountry_id(141);
        Writers wirters721 = new Writers(722, "cursus dignissim", c, "mattis sociosqu malesuada facilisi sollicitudin");
        list.add(wirters721);
        c.setCountry_id(5);
        Writers wirters722 = new Writers(723, "eleifend fermentum laoreet", c, "scelerisque nullam malesuada lectus proin");
        list.add(wirters722);
        c.setCountry_id(12);
        Writers wirters723 = new Writers(724, "torquent torquent morbi porta", c, "luctus torquent platea viverra imperdiet");
        list.add(wirters723);
        c.setCountry_id(97);
        Writers wirters724 = new Writers(725, "justo sagittis", c, "sollicitudin facilisi porta habitasse suspendisse");
        list.add(wirters724);
        c.setCountry_id(72);
        Writers wirters725 = new Writers(726, "donec bibendum ultricies", c, "bibendum tellus ipsum viverra aenean");
        list.add(wirters725);
        c.setCountry_id(74);
        Writers wirters726 = new Writers(727, "lobortis sociosqu proin", c, "adipiscing varius porttitor convallis facilisis");
        list.add(wirters726);
        c.setCountry_id(19);
        Writers wirters727 = new Writers(728, "pretium lacus habitasse ligula", c, "tincidunt laoreet aliquam ullamcorper sagittis");
        list.add(wirters727);
        c.setCountry_id(78);
        Writers wirters728 = new Writers(729, "imperdiet porta bibendum", c, "consequat faucibus risus morbi risus");
        list.add(wirters728);
        c.setCountry_id(117);
        Writers wirters729 = new Writers(730, "tempor tincidunt pulvinar sodales", c, "cursus luctus imperdiet lectus phasellus");
        list.add(wirters729);
        c.setCountry_id(47);
        Writers wirters730 = new Writers(731, "sociosqu venenatis", c, "congue aptent curae imperdiet tellus");
        list.add(wirters730);
        c.setCountry_id(98);
        Writers wirters731 = new Writers(732, "fusce senectus velit", c, "bulum tempus neque hymenaeos feugiat");
        list.add(wirters731);
        c.setCountry_id(47);
        Writers wirters732 = new Writers(733, "turpis faucibus aptent", c, "tellus vitae mauris tortor elementum");
        list.add(wirters732);
        c.setCountry_id(120);
        Writers wirters733 = new Writers(734, "congue porta ornare luctus", c, "tempus inceptos inceptos velit tincidunt");
        list.add(wirters733);
        c.setCountry_id(91);
        Writers wirters734 = new Writers(735, "tortor aptent mattis accumsan", c, "vesti praesent cursus tellus varius");
        list.add(wirters734);
        c.setCountry_id(18);
        Writers wirters735 = new Writers(736, "fusce litora malesuada fringilla", c, "donec pretium tempor lectus sollicitudin");
        list.add(wirters735);
        c.setCountry_id(13);
        Writers wirters736 = new Writers(737, "ornare volutpat semper", c, "ligula sodales hendrerit euismod tellus");
        list.add(wirters736);
        c.setCountry_id(97);
        Writers wirters737 = new Writers(738, "habitant ultricies", c, "porta curae vivamus molestie quisque");
        list.add(wirters737);
        c.setCountry_id(11);
        Writers wirters738 = new Writers(739, "neque ultrices", c, "eleifend pulvinar dignissim platea sagittis");
        list.add(wirters738);
        c.setCountry_id(20);
        Writers wirters739 = new Writers(740, "dolor tumst libero", c, "fames luctus dictumst dolor malesuada");
        list.add(wirters739);
        c.setCountry_id(73);
        Writers wirters740 = new Writers(741, "lectus iaculis", c, "justo mollis pellentesque dictum ipsum");
        list.add(wirters740);
        c.setCountry_id(129);
        Writers wirters741 = new Writers(742, "aliquam conubia", c, "cursus bibendum venenatis torquent bulum");
        list.add(wirters741);
        c.setCountry_id(20);
        Writers wirters742 = new Writers(743, "platea viverra praesent", c, "nulla litora torquent ultricies hendrerit");
        list.add(wirters742);
        c.setCountry_id(41);
        Writers wirters743 = new Writers(744, "mollis accumsan", c, "justo fusce conubia morbi hendrerit");
        list.add(wirters743);
        c.setCountry_id(57);
        Writers wirters744 = new Writers(745, "inceptos congue convallis", c, "egestas felis molestie torquent mollis");
        list.add(wirters744);
        c.setCountry_id(134);
        Writers wirters745 = new Writers(746, "consectetuer torquent", c, "velit convallis rutrum posuere scelerisque");
        list.add(wirters745);
        c.setCountry_id(1);
        Writers wirters746 = new Writers(747, "egestas tincidunt fames feugiat", c, "taciti maecenas etiam faucibus neque");
        list.add(wirters746);
        c.setCountry_id(135);
        Writers wirters747 = new Writers(748, "porta ligula metus posuere", c, "faucibus suspendisse vitae scelerisque habitasse");
        list.add(wirters747);
        c.setCountry_id(6);
        Writers wirters748 = new Writers(749, "nonummy tincidunt", c, "dictum varius conubia class elementum");
        list.add(wirters748);
        c.setCountry_id(41);
        Writers wirters749 = new Writers(750, "habitasse turpis ullamcorper primis", c, "taciti tempus quisque laoreet luctus");
        list.add(wirters749);
        c.setCountry_id(47);
        Writers wirters750 = new Writers(751, "viverra sociosqu tincidunt facilisi", c, "pretium sociosqu augue sociosqu ultrices");
        list.add(wirters750);
        c.setCountry_id(113);
        Writers wirters751 = new Writers(752, "aliquet nonummy", c, "senectus habitasse augue malesuada rutrum");
        list.add(wirters751);
        c.setCountry_id(86);
        Writers wirters752 = new Writers(753, "aliquet euismod", c, "fringilla laoreet lacinia accumsan consequat");
        list.add(wirters752);
        c.setCountry_id(21);
        Writers wirters753 = new Writers(754, "neque nullam suspendisse inceptos", c, "tumst netus facilisi dictumst quisque");
        list.add(wirters753);
        c.setCountry_id(149);
        Writers wirters754 = new Writers(755, "ipsum consequat", c, "sodales habitant hendrerit elementum augue");
        list.add(wirters754);
        c.setCountry_id(106);
        Writers wirters755 = new Writers(756, "turpis habitant nullam cubilia", c, "wisiaenean risus habitant adipiscing vivamus");
        list.add(wirters755);
        c.setCountry_id(99);
        Writers wirters756 = new Writers(757, "habitant primis placerat", c, "fringilla vesti volutpat pretium vehicula");
        list.add(wirters756);
        c.setCountry_id(57);
        Writers wirters757 = new Writers(758, "felis aliquam metus", c, "dignissim fermentum velit platea rutrum");
        list.add(wirters757);
        c.setCountry_id(10);
        Writers wirters758 = new Writers(759, "molestie donec pretium", c, "ultricies proin nonummy habitant tellus");
        list.add(wirters758);
        c.setCountry_id(149);
        Writers wirters759 = new Writers(760, "hymenaeos laoreet wisiaenean platea", c, "senectus proin luctus justo conubia");
        list.add(wirters759);
        c.setCountry_id(63);
        Writers wirters760 = new Writers(761, "tristique vivamus sociosqu egestas", c, "tellus laoreet tumst sodales primis");
        list.add(wirters760);
        c.setCountry_id(50);
        Writers wirters761 = new Writers(762, "sodales egestas ullamcorper", c, "bulum senectus purus proin pellentesque");
        list.add(wirters761);
        c.setCountry_id(65);
        Writers wirters762 = new Writers(763, "molestie habitant", c, "dictum aliquet justo praesent pretium");
        list.add(wirters762);
        c.setCountry_id(54);
        Writers wirters763 = new Writers(764, "pellentesque fames fames rutrum", c, "justo ligula class lorem aliquet");
        list.add(wirters763);
        c.setCountry_id(139);
        Writers wirters764 = new Writers(765, "ultricies inceptos lorem congue", c, "imperdiet ornare augue dignissim porttitor");
        list.add(wirters764);
        c.setCountry_id(32);
        Writers wirters765 = new Writers(766, "nulla pellentesque viverra imperdiet", c, "aenean praesent netus molestie lectus");
        list.add(wirters765);
        c.setCountry_id(96);
        Writers wirters766 = new Writers(767, "integer dictum", c, "hendrerit dolor lacinia primis torquent");
        list.add(wirters766);
        c.setCountry_id(41);
        Writers wirters767 = new Writers(768, "ipsum platea", c, "venenatis facilisisnunc ligula nulla egestas");
        list.add(wirters767);
        c.setCountry_id(135);
        Writers wirters768 = new Writers(769, "integer faucibus aliquam platea", c, "pulvinar accumsan vehicula commodo fermentum");
        list.add(wirters768);
        c.setCountry_id(57);
        Writers wirters769 = new Writers(770, "mattis aenean litora velit", c, "curabitur donec posuere tellus curae");
        list.add(wirters769);
        c.setCountry_id(20);
        Writers wirters770 = new Writers(771, "auctor wisiaenean volutpat nulla", c, "sodales nonummy etiam aliquam vivamus");
        list.add(wirters770);
        c.setCountry_id(135);
        Writers wirters771 = new Writers(772, "interdum velit pellentesque", c, "vitae aenean facilisisnunc fringilla tincidunt");
        list.add(wirters771);
        c.setCountry_id(61);
        Writers wirters772 = new Writers(773, "inceptos auctor sapien congue", c, "ullamcorper aliquam malesuada convallis lectus");
        list.add(wirters772);
        c.setCountry_id(149);
        Writers wirters773 = new Writers(774, "curae vestibulum", c, "lectus dignissim tortor cursus sollicitudin");
        list.add(wirters773);
        c.setCountry_id(40);
        Writers wirters774 = new Writers(775, "justo metus phasellus scelerisque", c, "risus ultricies platea magna accumsan");
        list.add(wirters774);
        c.setCountry_id(106);
        Writers wirters775 = new Writers(776, "mattis facilisisnunc vitae", c, "turpis facilisi facilisi accumsan faucibus");
        list.add(wirters775);
        c.setCountry_id(122);
        Writers wirters776 = new Writers(777, "eleifend habitant commodo", c, "hendrerit dictum torquent sociosqu cursus");
        list.add(wirters776);
        c.setCountry_id(119);
        Writers wirters777 = new Writers(778, "pharetra aptent vehicula", c, "molestie phasellus vestibulum molestie ultrices");
        list.add(wirters777);
        c.setCountry_id(121);
        Writers wirters778 = new Writers(779, "proin bibendum", c, "praesent magna inceptos cubilia venenatis");
        list.add(wirters778);
        c.setCountry_id(81);
        Writers wirters779 = new Writers(780, "faucibus luctus", c, "cursus sollicitudin morbi dictum nulla");
        list.add(wirters779);
        c.setCountry_id(144);
        Writers wirters780 = new Writers(781, "euismod litora", c, "ultrices tortor sapien fermentum cursus");
        list.add(wirters780);
        c.setCountry_id(59);
        Writers wirters781 = new Writers(782, "venenatis ligula", c, "cubilia habitasse dictum luctus phasellus");
        list.add(wirters781);
        c.setCountry_id(79);
        Writers wirters782 = new Writers(783, "vivamus quisque", c, "cursus viverra pellentesque ornare tristique");
        list.add(wirters782);
        c.setCountry_id(29);
        Writers wirters783 = new Writers(784, "fusce malesuada primis", c, "lobortis lacinia wisiaenean inceptos consectetuer");
        list.add(wirters783);
        c.setCountry_id(120);
        Writers wirters784 = new Writers(785, "sapien metus venenatis", c, "aenean laoreet lacinia risus facilisis");
        list.add(wirters784);
        c.setCountry_id(128);
        Writers wirters785 = new Writers(786, "mauris curabitur", c, "ornare primis nullam mauris tortor");
        list.add(wirters785);
        c.setCountry_id(44);
        Writers wirters786 = new Writers(787, "lobortis inceptos aenean nonummy", c, "suspendisse suspendisse auctor augue posuere");
        list.add(wirters786);
        c.setCountry_id(61);
        Writers wirters787 = new Writers(788, "tempor dictum dolor iaculis", c, "tempor nostra risus eleifend hendrerit");
        list.add(wirters787);
        c.setCountry_id(15);
        Writers wirters788 = new Writers(789, "class pharetra curabitur", c, "ligula nulla sodales cubilia velit");
        list.add(wirters788);
        c.setCountry_id(135);
        Writers wirters789 = new Writers(790, "tristique justo euismod", c, "facilisis sociosqu posuere aliquam taciti");
        list.add(wirters789);
        c.setCountry_id(114);
        Writers wirters790 = new Writers(791, "semper eleifend hendrerit dignissim", c, "nostra sociosqu hendrerit hendrerit hymenaeos");
        list.add(wirters790);
        c.setCountry_id(22);
        Writers wirters791 = new Writers(792, "fringilla curae bulum", c, "pretium volutpat hymenaeos eleifend nostra");
        list.add(wirters791);
        c.setCountry_id(133);
        Writers wirters792 = new Writers(793, "adipiscing feugiat aliquet consequat", c, "egestas eleifend fusce tellus hymenaeos");
        list.add(wirters792);
        c.setCountry_id(43);
        Writers wirters793 = new Writers(794, "ipsum dignissim convallis maecenas", c, "mollis velit habitasse metus tortor");
        list.add(wirters793);
        c.setCountry_id(9);
        Writers wirters794 = new Writers(795, "tellus lorem", c, "tumst nullam bulum felis porttitor");
        list.add(wirters794);
        c.setCountry_id(85);
        Writers wirters795 = new Writers(796, "aliquet neque primis felis", c, "primis morbi phasellus cursus iaculis");
        list.add(wirters795);
        c.setCountry_id(115);
        Writers wirters796 = new Writers(797, "ipsum vestibulum magna", c, "elementum faucibus facilisi inceptos egestas");
        list.add(wirters796);
        c.setCountry_id(92);
        Writers wirters797 = new Writers(798, "primis vestibulum", c, "aliquam tumst curabitur lacinia rutrum");
        list.add(wirters797);
        c.setCountry_id(42);
        Writers wirters798 = new Writers(799, "bulum dictumst pretium", c, "aliquet fames mattis tristique tincidunt");
        list.add(wirters798);
        c.setCountry_id(111);
        Writers wirters799 = new Writers(800, "sapien mauris", c, "purus luctus sagittis hendrerit feugiat");
        list.add(wirters799);
        c.setCountry_id(52);
        Writers wirters800 = new Writers(801, "rutrum justo lorem faucibus", c, "aenean tumst morbi tempor vivamus");
        list.add(wirters800);
        c.setCountry_id(150);
        Writers wirters801 = new Writers(802, "volutpat porttitor tumst primis", c, "augue morbi consequat placerat elementum");
        list.add(wirters801);
        c.setCountry_id(124);
        Writers wirters802 = new Writers(803, "fermentum wisiaenean venenatis", c, "tellus curae mauris volutpat wisiaenean");
        list.add(wirters802);
        c.setCountry_id(35);
        Writers wirters803 = new Writers(804, "justo morbi aliquam", c, "bulum pharetra rutrum auctor tumst");
        list.add(wirters803);
        c.setCountry_id(20);
        Writers wirters804 = new Writers(805, "ultricies justo senectus", c, "magna vehicula laoreet ipsum lobortis");
        list.add(wirters804);
        c.setCountry_id(5);
        Writers wirters805 = new Writers(806, "class molestie", c, "primis fringilla sociosqu curae semper");
        list.add(wirters805);
        c.setCountry_id(100);
        Writers wirters806 = new Writers(807, "curabitur eleifend tellus nonummy", c, "varius vestibulum netus augue suspendisse");
        list.add(wirters806);
        c.setCountry_id(54);
        Writers wirters807 = new Writers(808, "lobortis vivamus porta", c, "ultrices neque neque consectetuer sagittis");
        list.add(wirters807);
        c.setCountry_id(34);
        Writers wirters808 = new Writers(809, "lacinia aptent", c, "mattis fringilla sapien lobortis cursus");
        list.add(wirters808);
        c.setCountry_id(51);
        Writers wirters809 = new Writers(810, "consectetuer luctus primis", c, "habitasse rutrum netus wisiaenean congue");
        list.add(wirters809);
        c.setCountry_id(36);
        Writers wirters810 = new Writers(811, "habitasse volutpat", c, "vitae mauris fringilla risus tumst");
        list.add(wirters810);
        c.setCountry_id(4);
        Writers wirters811 = new Writers(812, "ligula curabitur", c, "curae platea velit fermentum varius");
        list.add(wirters811);
        c.setCountry_id(5);
        Writers wirters812 = new Writers(813, "mattis ipsum", c, "sagittis curae ultricies porta aliquam");
        list.add(wirters812);
        c.setCountry_id(99);
        Writers wirters813 = new Writers(814, "donec quisque curae", c, "netus pulvinar dignissim malesuada lacinia");
        list.add(wirters813);
        c.setCountry_id(137);
        Writers wirters814 = new Writers(815, "cursus malesuada pulvinar lacinia", c, "pharetra tumst neque posuere etiam");
        list.add(wirters814);
        c.setCountry_id(142);
        Writers wirters815 = new Writers(816, "netus habitant", c, "sagittis augue pellentesque dictumst tempus");
        list.add(wirters815);
        c.setCountry_id(119);
        Writers wirters816 = new Writers(817, "facilisi posuere maecenas risus", c, "auctor aptent congue torquent euismod");
        list.add(wirters816);
        c.setCountry_id(19);
        Writers wirters817 = new Writers(818, "mattis integer", c, "rutrum fermentum augue consequat volutpat");
        list.add(wirters817);
        c.setCountry_id(125);
        Writers wirters818 = new Writers(819, "vehicula ultrices", c, "cursus sapien pharetra nullam habitasse");
        list.add(wirters818);
        c.setCountry_id(127);
        Writers wirters819 = new Writers(820, "malesuada rutrum molestie", c, "felis malesuada mattis aliquet auctor");
        list.add(wirters819);
        c.setCountry_id(26);
        Writers wirters820 = new Writers(821, "malesuada pulvinar", c, "lectus mattis malesuada interdum sodales");
        list.add(wirters820);
        c.setCountry_id(48);
        Writers wirters821 = new Writers(822, "litora nullam praesent", c, "congue donec consectetuer nulla aliquam");
        list.add(wirters821);
        c.setCountry_id(1);
        Writers wirters822 = new Writers(823, "interdum felis", c, "risus ligula bulum ipsum nostra");
        list.add(wirters822);
        c.setCountry_id(126);
        Writers wirters823 = new Writers(824, "donec hendrerit", c, "posuere neque suspendisse augue interdum");
        list.add(wirters823);
        c.setCountry_id(15);
        Writers wirters824 = new Writers(825, "luctus convallis dictumst", c, "pharetra class wisiaenean augue dictum");
        list.add(wirters824);
        c.setCountry_id(129);
        Writers wirters825 = new Writers(826, "fames ipsum ultricies sollicitudin", c, "ornare bulum class habitasse sociosqu");
        list.add(wirters825);
        c.setCountry_id(136);
        Writers wirters826 = new Writers(827, "ligula ultricies", c, "ullamcorper sociosqu congue fames lorem");
        list.add(wirters826);
        c.setCountry_id(92);
        Writers wirters827 = new Writers(828, "felis torquent", c, "litora tempor tumst fermentum integer");
        list.add(wirters827);
        c.setCountry_id(70);
        Writers wirters828 = new Writers(829, "mattis tumst aptent porttitor", c, "luctus tempor tortor feugiat laoreet");
        list.add(wirters828);
        c.setCountry_id(6);
        Writers wirters829 = new Writers(830, "cursus senectus taciti", c, "conubia hendrerit hymenaeos purus dolor");
        list.add(wirters829);
        c.setCountry_id(112);
        Writers wirters830 = new Writers(831, "commodo proin sollicitudin facilisis", c, "ultrices magna bibendum mollis conubia");
        list.add(wirters830);
        c.setCountry_id(77);
        Writers wirters831 = new Writers(832, "morbi elementum lacinia fringilla", c, "conubia lorem lorem sodales cursus");
        list.add(wirters831);
        c.setCountry_id(11);
        Writers wirters832 = new Writers(833, "wisiaenean imperdiet cubilia ultrices", c, "vehicula inceptos aliquam platea purus");
        list.add(wirters832);
        c.setCountry_id(88);
        Writers wirters833 = new Writers(834, "facilisi rutrum", c, "consectetuer facilisis imperdiet proin rutrum");
        list.add(wirters833);
        c.setCountry_id(89);
        Writers wirters834 = new Writers(835, "integer bibendum", c, "mauris bulum facilisis ultricies posuere");
        list.add(wirters834);
        c.setCountry_id(135);
        Writers wirters835 = new Writers(836, "lectus lorem aenean", c, "ipsum sapien volutpat augue venenatis");
        list.add(wirters835);
        c.setCountry_id(77);
        Writers wirters836 = new Writers(837, "semper maecenas libero", c, "scelerisque molestie bulum sollicitudin lacinia");
        list.add(wirters836);
        c.setCountry_id(62);
        Writers wirters837 = new Writers(838, "aptent euismod facilisisnunc", c, "hendrerit varius fusce neque torquent");
        list.add(wirters837);
        c.setCountry_id(27);
        Writers wirters838 = new Writers(839, "tristique facilisi congue molestie", c, "fames taciti lacinia tempus litora");
        list.add(wirters838);
        c.setCountry_id(139);
        Writers wirters839 = new Writers(840, "sollicitudin tempor", c, "imperdiet cursus luctus facilisisnunc pretium");
        list.add(wirters839);
        c.setCountry_id(30);
        Writers wirters840 = new Writers(841, "tempus cubilia ornare dolor", c, "aenean inceptos morbi magna risus");
        list.add(wirters840);
        c.setCountry_id(128);
        Writers wirters841 = new Writers(842, "euismod taciti", c, "phasellus interdum rutrum curae torquent");
        list.add(wirters841);
        c.setCountry_id(139);
        Writers wirters842 = new Writers(843, "maecenas senectus", c, "morbi facilisis cubilia ipsum hendrerit");
        list.add(wirters842);
        c.setCountry_id(16);
        Writers wirters843 = new Writers(844, "integer tumst", c, "adipiscing tellus sodales pellentesque magna");
        list.add(wirters843);
        c.setCountry_id(12);
        Writers wirters844 = new Writers(845, "neque varius", c, "lorem consequat libero viverra accumsan");
        list.add(wirters844);
        c.setCountry_id(138);
        Writers wirters845 = new Writers(846, "molestie purus", c, "aptent curabitur tempus justo iaculis");
        list.add(wirters845);
        c.setCountry_id(145);
        Writers wirters846 = new Writers(847, "tortor aenean pulvinar", c, "maecenas tincidunt viverra posuere purus");
        list.add(wirters846);
        c.setCountry_id(81);
        Writers wirters847 = new Writers(848, "imperdiet posuere sociosqu augue", c, "facilisisnunc posuere curae vestibulum consequat");
        list.add(wirters847);
        c.setCountry_id(4);
        Writers wirters848 = new Writers(849, "dictumst lectus aliquam", c, "tellus inceptos primis euismod tumst");
        list.add(wirters848);
        c.setCountry_id(21);
        Writers wirters849 = new Writers(850, "consectetuer justo", c, "bulum suspendisse luctus etiam tempor");
        list.add(wirters849);
        c.setCountry_id(16);
        Writers wirters850 = new Writers(851, "mauris imperdiet", c, "dictumst senectus taciti suspendisse aenean");
        list.add(wirters850);
        c.setCountry_id(107);
        Writers wirters851 = new Writers(852, "pretium quisque", c, "egestas class convallis congue metus");
        list.add(wirters851);
        c.setCountry_id(117);
        Writers wirters852 = new Writers(853, "vestibulum pharetra", c, "feugiat fames vesti proin bulum");
        list.add(wirters852);
        c.setCountry_id(27);
        Writers wirters853 = new Writers(854, "tempor pellentesque platea", c, "wisiaenean curabitur placerat aptent class");
        list.add(wirters853);
        c.setCountry_id(133);
        Writers wirters854 = new Writers(855, "molestie euismod congue", c, "adipiscing adipiscing dolor libero nostra");
        list.add(wirters854);
        c.setCountry_id(54);
        Writers wirters855 = new Writers(856, "neque metus tempus mattis", c, "porttitor habitant etiam cubilia fermentum");
        list.add(wirters855);
        c.setCountry_id(147);
        Writers wirters856 = new Writers(857, "varius dictumst", c, "porta pretium mauris ultrices nullam");
        list.add(wirters856);
        c.setCountry_id(92);
        Writers wirters857 = new Writers(858, "purus neque hendrerit tincidunt", c, "senectus nulla mollis libero feugiat");
        list.add(wirters857);
        c.setCountry_id(116);
        Writers wirters858 = new Writers(859, "facilisis tellus suspendisse luctus", c, "facilisisnunc sollicitudin sollicitudin dolor mattis");
        list.add(wirters858);
        c.setCountry_id(43);
        Writers wirters859 = new Writers(860, "sagittis aliquam integer", c, "sociosqu sapien tellus laoreet pretium");
        list.add(wirters859);
        c.setCountry_id(37);
        Writers wirters860 = new Writers(861, "suspendisse aptent quisque", c, "posuere nonummy lacinia bibendum tortor");
        list.add(wirters860);
        c.setCountry_id(93);
        Writers wirters861 = new Writers(862, "posuere posuere habitant malesuada", c, "velit fames posuere vehicula facilisi");
        list.add(wirters861);
        c.setCountry_id(147);
        Writers wirters862 = new Writers(863, "consequat tincidunt nulla", c, "taciti donec torquent consequat platea");
        list.add(wirters862);
        c.setCountry_id(84);
        Writers wirters863 = new Writers(864, "velit facilisis fusce", c, "nullam vitae turpis morbi tellus");
        list.add(wirters863);
        c.setCountry_id(102);
        Writers wirters864 = new Writers(865, "accumsan lacus sollicitudin pulvinar", c, "volutpat fermentum cursus hendrerit magna");
        list.add(wirters864);
        c.setCountry_id(96);
        Writers wirters865 = new Writers(866, "cubilia tempus auctor mattis", c, "conubia justo consectetuer nonummy lectus");
        list.add(wirters865);
        c.setCountry_id(13);
        Writers wirters866 = new Writers(867, "euismod cubilia ullamcorper morbi", c, "consectetuer integer bibendum mauris integer");
        list.add(wirters866);
        c.setCountry_id(98);
        Writers wirters867 = new Writers(868, "dictum porttitor fermentum neque", c, "pellentesque suspendisse dignissim libero etiam");
        list.add(wirters867);
        c.setCountry_id(32);
        Writers wirters868 = new Writers(869, "hymenaeos pulvinar commodo", c, "lectus mauris magna tortor curabitur");
        list.add(wirters868);
        c.setCountry_id(135);
        Writers wirters869 = new Writers(870, "tincidunt ipsum tincidunt", c, "habitasse wisiaenean laoreet eleifend inceptos");
        list.add(wirters869);
        c.setCountry_id(40);
        Writers wirters870 = new Writers(871, "semper commodo", c, "senectus fusce fringilla tortor consequat");
        list.add(wirters870);
        c.setCountry_id(115);
        Writers wirters871 = new Writers(872, "feugiat class inceptos laoreet", c, "tellus habitasse lorem eleifend neque");
        list.add(wirters871);
        c.setCountry_id(47);
        Writers wirters872 = new Writers(873, "facilisis placerat", c, "primis congue proin curae pellentesque");
        list.add(wirters872);
        c.setCountry_id(117);
        Writers wirters873 = new Writers(874, "laoreet auctor", c, "malesuada eleifend nullam scelerisque sapien");
        list.add(wirters873);
        c.setCountry_id(8);
        Writers wirters874 = new Writers(875, "aliquet auctor dictumst pretium", c, "mauris convallis malesuada ullamcorper senectus");
        list.add(wirters874);
        c.setCountry_id(143);
        Writers wirters875 = new Writers(876, "habitant semper tortor aliquet", c, "nonummy netus platea dictum tempus");
        list.add(wirters875);
        c.setCountry_id(47);
        Writers wirters876 = new Writers(877, "curabitur phasellus egestas platea", c, "nullam cursus laoreet class tempor");
        list.add(wirters876);
        c.setCountry_id(86);
        Writers wirters877 = new Writers(878, "sagittis porttitor ultrices accumsan", c, "porta libero pretium morbi adipiscing");
        list.add(wirters877);
        c.setCountry_id(146);
        Writers wirters878 = new Writers(879, "viverra elementum sodales", c, "molestie sollicitudin etiam quisque proin");
        list.add(wirters878);
        c.setCountry_id(74);
        Writers wirters879 = new Writers(880, "auctor nostra accumsan praesent", c, "placerat quisque cursus senectus turpis");
        list.add(wirters879);
        c.setCountry_id(84);
        Writers wirters880 = new Writers(881, "torquent posuere dignissim", c, "cubilia euismod congue nonummy vesti");
        list.add(wirters880);
        c.setCountry_id(119);
        Writers wirters881 = new Writers(882, "ipsum lacus donec pulvinar", c, "augue wisiaenean pharetra tristique hymenaeos");
        list.add(wirters881);
        c.setCountry_id(74);
        Writers wirters882 = new Writers(883, "donec volutpat conubia", c, "cursus class nulla euismod feugiat");
        list.add(wirters882);
        c.setCountry_id(81);
        Writers wirters883 = new Writers(884, "ligula sollicitudin", c, "posuere dictumst pretium nulla tristique");
        list.add(wirters883);
        c.setCountry_id(126);
        Writers wirters884 = new Writers(885, "adipiscing pellentesque taciti bulum", c, "conubia luctus integer ullamcorper lorem");
        list.add(wirters884);
        c.setCountry_id(96);
        Writers wirters885 = new Writers(886, "imperdiet etiam convallis venenatis", c, "quisque lacinia quisque vitae vivamus");
        list.add(wirters885);
        c.setCountry_id(132);
        Writers wirters886 = new Writers(887, "vesti euismod vehicula dolor", c, "class mattis elementum class volutpat");
        list.add(wirters886);
        c.setCountry_id(91);
        Writers wirters887 = new Writers(888, "sociosqu nulla lacinia ipsum", c, "habitasse ultrices proin imperdiet ullamcorper");
        list.add(wirters887);
        c.setCountry_id(70);
        Writers wirters888 = new Writers(889, "adipiscing facilisis", c, "fusce sapien tempor sociosqu auctor");
        list.add(wirters888);
        c.setCountry_id(108);
        Writers wirters889 = new Writers(890, "praesent facilisisnunc elementum", c, "pulvinar facilisisnunc phasellus venenatis dictumst");
        list.add(wirters889);
        c.setCountry_id(89);
        Writers wirters890 = new Writers(891, "curabitur tortor molestie inceptos", c, "laoreet ornare praesent mattis tincidunt");
        list.add(wirters890);
        c.setCountry_id(97);
        Writers wirters891 = new Writers(892, "sodales posuere proin nonummy", c, "ultrices turpis sagittis pulvinar curabitur");
        list.add(wirters891);
        c.setCountry_id(4);
        Writers wirters892 = new Writers(893, "proin tristique nostra", c, "semper rutrum quisque habitant varius");
        list.add(wirters892);
        c.setCountry_id(71);
        Writers wirters893 = new Writers(894, "auctor facilisis", c, "curabitur porttitor pulvinar mattis adipiscing");
        list.add(wirters893);
        c.setCountry_id(129);
        Writers wirters894 = new Writers(895, "mauris pellentesque pulvinar primis", c, "etiam nullam ultricies placerat nulla");
        list.add(wirters894);
        c.setCountry_id(47);
        Writers wirters895 = new Writers(896, "imperdiet ullamcorper", c, "volutpat sociosqu facilisi praesent neque");
        list.add(wirters895);
        c.setCountry_id(60);
        Writers wirters896 = new Writers(897, "luctus ornare aptent primis", c, "molestie feugiat vestibulum aliquam sapien");
        list.add(wirters896);
        c.setCountry_id(48);
        Writers wirters897 = new Writers(898, "praesent luctus sodales cursus", c, "dictum taciti dignissim mollis tristique");
        list.add(wirters897);
        c.setCountry_id(34);
        Writers wirters898 = new Writers(899, "hymenaeos curae commodo", c, "nonummy ornare tortor nonummy mauris");
        list.add(wirters898);
        c.setCountry_id(71);
        Writers wirters899 = new Writers(900, "tortor litora adipiscing neque", c, "placerat habitasse egestas pellentesque aliquet");
        list.add(wirters899);
        c.setCountry_id(45);
        Writers wirters900 = new Writers(901, "lorem aliquam curabitur", c, "rutrum dolor ultricies aptent maecenas");
        list.add(wirters900);
        c.setCountry_id(5);
        Writers wirters901 = new Writers(902, "pellentesque convallis", c, "iaculis euismod porttitor convallis ligula");
        list.add(wirters901);
        c.setCountry_id(84);
        Writers wirters902 = new Writers(903, "vesti donec tortor aliquet", c, "magna facilisisnunc sagittis aptent mauris");
        list.add(wirters902);
        c.setCountry_id(63);
        Writers wirters903 = new Writers(904, "porttitor lacus elementum curabitur", c, "cubilia vivamus primis laoreet nullam");
        list.add(wirters903);
        c.setCountry_id(97);
        Writers wirters904 = new Writers(905, "fermentum conubia platea", c, "semper lorem tempor sagittis aptent");
        list.add(wirters904);
        c.setCountry_id(83);
        Writers wirters905 = new Writers(906, "litora tristique bulum", c, "iaculis mollis nonummy inceptos ultrices");
        list.add(wirters905);
        c.setCountry_id(33);
        Writers wirters906 = new Writers(907, "vivamus euismod adipiscing neque", c, "mattis nonummy senectus lacus ligula");
        list.add(wirters906);
        c.setCountry_id(98);
        Writers wirters907 = new Writers(908, "consectetuer lacinia", c, "varius ornare facilisi mauris ultrices");
        list.add(wirters907);
        c.setCountry_id(13);
        Writers wirters908 = new Writers(909, "ipsum bibendum dictumst convallis", c, "sagittis auctor netus tempor bulum");
        list.add(wirters908);
        c.setCountry_id(102);
        Writers wirters909 = new Writers(910, "aliquam sociosqu", c, "vestibulum vivamus sociosqu bulum neque");
        list.add(wirters909);
        c.setCountry_id(43);
        Writers wirters910 = new Writers(911, "primis pellentesque porttitor", c, "facilisis turpis praesent conubia tempor");
        list.add(wirters910);
        c.setCountry_id(134);
        Writers wirters911 = new Writers(912, "morbi neque sociosqu", c, "netus fermentum felis viverra venenatis");
        list.add(wirters911);
        c.setCountry_id(140);
        Writers wirters912 = new Writers(913, "lorem iaculis", c, "augue interdum vesti felis proin");
        list.add(wirters912);
        c.setCountry_id(28);
        Writers wirters913 = new Writers(914, "malesuada platea", c, "nonummy viverra feugiat tortor eleifend");
        list.add(wirters913);
        c.setCountry_id(84);
        Writers wirters914 = new Writers(915, "tincidunt sociosqu", c, "ligula habitant fringilla curabitur sociosqu");
        list.add(wirters914);
        c.setCountry_id(124);
        Writers wirters915 = new Writers(916, "mattis iaculis vehicula", c, "luctus rutrum sociosqu vivamus rutrum");
        list.add(wirters915);
        c.setCountry_id(124);
        Writers wirters916 = new Writers(917, "dictumst ultrices nullam", c, "class lacinia accumsan sagittis curae");
        list.add(wirters916);
        c.setCountry_id(71);
        Writers wirters917 = new Writers(918, "vestibulum ultricies ligula tellus", c, "vitae pulvinar pharetra nostra sagittis");
        list.add(wirters917);
        c.setCountry_id(26);
        Writers wirters918 = new Writers(919, "torquent cubilia integer", c, "euismod justo ipsum mattis risus");
        list.add(wirters918);
        c.setCountry_id(70);
        Writers wirters919 = new Writers(920, "tortor velit", c, "justo aliquet mattis nullam convallis");
        list.add(wirters919);
        c.setCountry_id(35);
        Writers wirters920 = new Writers(921, "elementum feugiat", c, "lacus fringilla facilisi tincidunt luctus");
        list.add(wirters920);
        c.setCountry_id(84);
        Writers wirters921 = new Writers(922, "sociosqu venenatis consequat platea", c, "habitant faucibus lacinia accumsan neque");
        list.add(wirters921);
        c.setCountry_id(126);
        Writers wirters922 = new Writers(923, "senectus rutrum", c, "libero facilisis tortor platea justo");
        list.add(wirters922);
        c.setCountry_id(10);
        Writers wirters923 = new Writers(924, "hymenaeos praesent", c, "luctus mauris semper tempus aptent");
        list.add(wirters923);
        c.setCountry_id(2);
        Writers wirters924 = new Writers(925, "pulvinar varius torquent sagittis", c, "wisiaenean integer lectus morbi convallis");
        list.add(wirters924);
        c.setCountry_id(2);
        Writers wirters925 = new Writers(926, "lorem viverra", c, "maecenas iaculis fames vehicula varius");
        list.add(wirters925);
        c.setCountry_id(77);
        Writers wirters926 = new Writers(927, "hymenaeos lorem euismod hendrerit", c, "dictum pretium tellus volutpat feugiat");
        list.add(wirters926);
        c.setCountry_id(89);
        Writers wirters927 = new Writers(928, "nostra mauris tumst ligula", c, "lectus inceptos donec convallis tempor");
        list.add(wirters927);
        c.setCountry_id(44);
        Writers wirters928 = new Writers(929, "volutpat neque accumsan", c, "accumsan ultrices hendrerit euismod conubia");
        list.add(wirters928);
        c.setCountry_id(66);
        Writers wirters929 = new Writers(930, "habitant mattis tempor praesent", c, "elementum sodales pharetra sollicitudin semper");
        list.add(wirters929);
        c.setCountry_id(20);
        Writers wirters930 = new Writers(931, "tellus tristique laoreet", c, "fringilla tellus inceptos pretium augue");
        list.add(wirters930);
        c.setCountry_id(7);
        Writers wirters931 = new Writers(932, "neque turpis congue", c, "class commodo donec primis pulvinar");
        list.add(wirters931);
        c.setCountry_id(91);
        Writers wirters932 = new Writers(933, "magna lorem", c, "hymenaeos porttitor laoreet praesent pulvinar");
        list.add(wirters932);
        c.setCountry_id(112);
        Writers wirters933 = new Writers(934, "porta taciti", c, "lobortis tristique interdum maecenas ornare");
        list.add(wirters933);
        c.setCountry_id(18);
        Writers wirters934 = new Writers(935, "ultricies fames conubia etiam", c, "imperdiet pharetra sapien consectetuer tumst");
        list.add(wirters934);
        c.setCountry_id(111);
        Writers wirters935 = new Writers(936, "sagittis praesent", c, "inceptos iaculis dignissim vehicula donec");
        list.add(wirters935);
        c.setCountry_id(97);
        Writers wirters936 = new Writers(937, "dictum habitant tortor dolor", c, "tristique sapien semper viverra hendrerit");
        list.add(wirters936);
        c.setCountry_id(65);
        Writers wirters937 = new Writers(938, "sollicitudin aliquet", c, "proin molestie platea purus nonummy");
        list.add(wirters937);
        c.setCountry_id(69);
        Writers wirters938 = new Writers(939, "morbi iaculis", c, "mattis egestas dictumst bibendum platea");
        list.add(wirters938);
        c.setCountry_id(148);
        Writers wirters939 = new Writers(940, "dolor feugiat quisque mattis", c, "adipiscing habitasse risus aenean nostra");
        list.add(wirters939);
        c.setCountry_id(149);
        Writers wirters940 = new Writers(941, "molestie viverra", c, "accumsan fringilla luctus dictumst pellentesque");
        list.add(wirters940);
        c.setCountry_id(29);
        Writers wirters941 = new Writers(942, "augue molestie felis", c, "primis dictumst lobortis interdum dignissim");
        list.add(wirters941);
        c.setCountry_id(146);
        Writers wirters942 = new Writers(943, "tempus metus", c, "pulvinar varius placerat luctus sapien");
        list.add(wirters942);
        c.setCountry_id(146);
        Writers wirters943 = new Writers(944, "justo facilisisnunc habitasse", c, "donec aliquet pulvinar metus adipiscing");
        list.add(wirters943);
        c.setCountry_id(88);
        Writers wirters944 = new Writers(945, "conubia pellentesque aptent", c, "iaculis aliquam interdum imperdiet convallis");
        list.add(wirters944);
        c.setCountry_id(5);
        Writers wirters945 = new Writers(946, "proin dolor accumsan elementum", c, "magna habitasse rutrum senectus justo");
        list.add(wirters945);
        c.setCountry_id(17);
        Writers wirters946 = new Writers(947, "litora ligula", c, "lacinia iaculis torquent wisiaenean elementum");
        list.add(wirters946);
        c.setCountry_id(5);
        Writers wirters947 = new Writers(948, "euismod ultrices libero litora", c, "sagittis class lacus facilisisnunc nulla");
        list.add(wirters947);
        c.setCountry_id(144);
        Writers wirters948 = new Writers(949, "ultrices malesuada", c, "nostra tumst morbi dignissim dolor");
        list.add(wirters948);
        c.setCountry_id(128);
        Writers wirters949 = new Writers(950, "ligula habitant nullam", c, "tortor curabitur bibendum pulvinar mollis");
        list.add(wirters949);
        c.setCountry_id(23);
        Writers wirters950 = new Writers(951, "tincidunt metus", c, "bibendum integer vesti suspendisse tristique");
        list.add(wirters950);
        c.setCountry_id(16);
        Writers wirters951 = new Writers(952, "varius ligula iaculis", c, "vitae ullamcorper suspendisse dictum vitae");
        list.add(wirters951);
        c.setCountry_id(18);
        Writers wirters952 = new Writers(953, "mauris phasellus tellus", c, "proin morbi suspendisse sagittis molestie");
        list.add(wirters952);
        c.setCountry_id(91);
        Writers wirters953 = new Writers(954, "tempus vesti sodales", c, "primis aenean platea semper pellentesque");
        list.add(wirters953);
        c.setCountry_id(103);
        Writers wirters954 = new Writers(955, "eleifend imperdiet wisiaenean", c, "metus eleifend turpis malesuada libero");
        list.add(wirters954);
        c.setCountry_id(21);
        Writers wirters955 = new Writers(956, "habitant hymenaeos risus tempus", c, "euismod imperdiet mollis dignissim faucibus");
        list.add(wirters955);
        c.setCountry_id(62);
        Writers wirters956 = new Writers(957, "facilisis purus nostra ullamcorper", c, "lobortis elementum lorem conubia mattis");
        list.add(wirters956);
        c.setCountry_id(5);
        Writers wirters957 = new Writers(958, "vitae lectus", c, "dignissim aliquam bibendum cubilia fames");
        list.add(wirters957);
        c.setCountry_id(112);
        Writers wirters958 = new Writers(959, "senectus semper fames", c, "praesent adipiscing malesuada facilisi vitae");
        list.add(wirters958);
        c.setCountry_id(146);
        Writers wirters959 = new Writers(960, "tempus mollis phasellus", c, "lacus litora tellus morbi scelerisque");
        list.add(wirters959);
        c.setCountry_id(63);
        Writers wirters960 = new Writers(961, "dictum posuere", c, "semper lobortis sollicitudin proin lorem");
        list.add(wirters960);
        c.setCountry_id(59);
        Writers wirters961 = new Writers(962, "aliquet adipiscing", c, "cursus quisque fermentum nostra aenean");
        list.add(wirters961);
        c.setCountry_id(59);
        Writers wirters962 = new Writers(963, "magna taciti felis consequat", c, "mollis litora auctor ornare mollis");
        list.add(wirters962);
        c.setCountry_id(28);
        Writers wirters963 = new Writers(964, "consectetuer ultrices", c, "felis habitant elementum venenatis nonummy");
        list.add(wirters963);
        c.setCountry_id(74);
        Writers wirters964 = new Writers(965, "lacus aliquam aenean", c, "accumsan pharetra integer praesent vesti");
        list.add(wirters964);
        c.setCountry_id(5);
        Writers wirters965 = new Writers(966, "luctus laoreet", c, "mauris pharetra velit consequat taciti");
        list.add(wirters965);
        c.setCountry_id(54);
        Writers wirters966 = new Writers(967, "semper facilisisnunc proin vitae", c, "netus purus ornare aptent venenatis");
        list.add(wirters966);
        c.setCountry_id(37);
        Writers wirters967 = new Writers(968, "accumsan lacus tincidunt", c, "aenean donec ipsum sociosqu tempus");
        list.add(wirters967);
        c.setCountry_id(74);
        Writers wirters968 = new Writers(969, "pharetra platea velit integer", c, "taciti class rutrum conubia auctor");
        list.add(wirters968);
        c.setCountry_id(76);
        Writers wirters969 = new Writers(970, "facilisi egestas justo", c, "commodo luctus bulum fusce nulla");
        list.add(wirters969);
        c.setCountry_id(40);
        Writers wirters970 = new Writers(971, "sollicitudin nostra maecenas feugiat", c, "adipiscing facilisis aliquam proin bulum");
        list.add(wirters970);
        c.setCountry_id(68);
        Writers wirters971 = new Writers(972, "facilisi hendrerit dolor consectetuer", c, "pharetra fermentum molestie lorem semper");
        list.add(wirters971);
        c.setCountry_id(11);
        Writers wirters972 = new Writers(973, "tincidunt aenean lobortis consectetuer", c, "volutpat convallis fames pharetra imperdiet");
        list.add(wirters972);
        c.setCountry_id(130);
        Writers wirters973 = new Writers(974, "sociosqu primis faucibus curae", c, "cubilia senectus posuere senectus aenean");
        list.add(wirters973);
        c.setCountry_id(146);
        Writers wirters974 = new Writers(975, "netus adipiscing aenean", c, "aptent morbi phasellus iaculis libero");
        list.add(wirters974);
        c.setCountry_id(138);
        Writers wirters975 = new Writers(976, "ipsum tempor sapien phasellus", c, "dictumst congue integer neque velit");
        list.add(wirters975);
        c.setCountry_id(83);
        Writers wirters976 = new Writers(977, "tempus aliquam aptent", c, "fusce congue lobortis vestibulum vitae");
        list.add(wirters976);
        c.setCountry_id(48);
        Writers wirters977 = new Writers(978, "augue platea phasellus", c, "libero cubilia praesent feugiat maecenas");
        list.add(wirters977);
        c.setCountry_id(62);
        Writers wirters978 = new Writers(979, "sodales pretium", c, "interdum mollis molestie praesent sollicitudin");
        list.add(wirters978);
        c.setCountry_id(30);
        Writers wirters979 = new Writers(980, "vesti congue", c, "habitant conubia ipsum vivamus tincidunt");
        list.add(wirters979);
        c.setCountry_id(128);
        Writers wirters980 = new Writers(981, "pharetra consectetuer mollis", c, "morbi porttitor egestas sodales proin");
        list.add(wirters980);
        c.setCountry_id(37);
        Writers wirters981 = new Writers(982, "aliquet laoreet elementum", c, "aptent congue nostra ultricies vesti");
        list.add(wirters981);
        c.setCountry_id(41);
        Writers wirters982 = new Writers(983, "dignissim sagittis", c, "euismod bulum ultrices aliquet pulvinar");
        list.add(wirters982);
        c.setCountry_id(39);
        Writers wirters983 = new Writers(984, "lacinia bulum feugiat pulvinar", c, "consectetuer lorem elementum lorem fringilla");
        list.add(wirters983);
        c.setCountry_id(98);
        Writers wirters984 = new Writers(985, "convallis metus maecenas", c, "inceptos semper magna scelerisque commodo");
        list.add(wirters984);
        c.setCountry_id(124);
        Writers wirters985 = new Writers(986, "facilisis fringilla phasellus", c, "scelerisque fames iaculis aliquam lacus");
        list.add(wirters985);
        c.setCountry_id(50);
        Writers wirters986 = new Writers(987, "mauris varius molestie", c, "adipiscing lacus vivamus suspendisse consequat");
        list.add(wirters986);
        c.setCountry_id(140);
        Writers wirters987 = new Writers(988, "tincidunt consequat", c, "purus scelerisque fermentum pretium feugiat");
        list.add(wirters987);
        c.setCountry_id(13);
        Writers wirters988 = new Writers(989, "curabitur fusce ultricies fringilla", c, "sollicitudin sodales lobortis dictum velit");
        list.add(wirters988);
        c.setCountry_id(74);
        Writers wirters989 = new Writers(990, "auctor dolor nostra", c, "mollis turpis facilisi ligula risus");
        list.add(wirters989);
        c.setCountry_id(75);
        Writers wirters990 = new Writers(991, "venenatis aenean commodo", c, "metus viverra mattis dolor iaculis");
        list.add(wirters990);
        c.setCountry_id(29);
        Writers wirters991 = new Writers(992, "praesent ultricies lacinia", c, "morbi velit lacus ultricies fringilla");
        list.add(wirters991);
        c.setCountry_id(124);
        Writers wirters992 = new Writers(993, "magna dignissim ultrices", c, "nullam iaculis hendrerit tumst consequat");
        list.add(wirters992);
        c.setCountry_id(104);
        Writers wirters993 = new Writers(994, "risus tellus", c, "venenatis ipsum donec dictum integer");
        list.add(wirters993);
        c.setCountry_id(59);
        Writers wirters994 = new Writers(995, "viverra tellus laoreet conubia", c, "morbi congue fusce hymenaeos adipiscing");
        list.add(wirters994);
        c.setCountry_id(110);
        Writers wirters995 = new Writers(996, "proin magna", c, "mollis volutpat aliquam fringilla dignissim");
        list.add(wirters995);
        c.setCountry_id(54);
        Writers wirters996 = new Writers(997, "vesti accumsan litora", c, "cubilia volutpat bibendum nullam ipsum");
        list.add(wirters996);
        c.setCountry_id(1);
        Writers wirters997 = new Writers(998, "primis phasellus donec metus", c, "hymenaeos purus facilisi cursus torquent");
        list.add(wirters997);
        c.setCountry_id(137);
        Writers wirters998 = new Writers(999, "purus curabitur habitant sapien", c, "habitasse consectetuer vestibulum mollis venenatis");
        list.add(wirters998);
        c.setCountry_id(57);
        Writers wirters999 = new Writers(1000, "sollicitudin ligula commodo", c, "mollis auctor volutpat tempor semper");
        list.add(wirters999);

		
		Connection con = new Connection();
        con.setCon();
        con.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            writersDBM.insertWriters(iteration, con);
        });
        con.getCon().getTransaction().commit();
		con.closeCon();

    }
}
