package preInsertions;

import DBManager.BookSeriesDBM;
import Conn.Connection;
import entities.BookSeries;
import enums.SerieTypeEnum;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Jociane Franzoni de Lima
 * @author Lucas Penha de Moura
 */
public class InsertBookSeries2
{

    BookSeriesDBM bookSeriesDBM = new BookSeriesDBM();
    List<BookSeries> list = new ArrayList<>();

    public void insert() {

        BookSeries bs500 = new BookSeries("fames metus", 9, SerieTypeEnum.LIVRO, "pulvinar pellentesque sapien varius integer");
        list.add(bs500);
        BookSeries bs501 = new BookSeries("aenean integer", 5, SerieTypeEnum.LIVRO, "primis sapien facilisi pulvinar etiam");
        list.add(bs501);
        BookSeries bs502 = new BookSeries("tempor faucibus", 0, SerieTypeEnum.LIVRO, "commodo ornare facilisi pulvinar luctus");
        list.add(bs502);
        BookSeries bs503 = new BookSeries("neque", 7, SerieTypeEnum.HQ, "porta fringilla sapien dolor mauris");
        list.add(bs503);
        BookSeries bs504 = new BookSeries("scelerisque porttitor", 4, SerieTypeEnum.LIVRO, "facilisi consequat vivamus hymenaeos eleifend");
        list.add(bs504);
        BookSeries bs505 = new BookSeries("taciti", 4, SerieTypeEnum.HQ, "proin vesti consectetuer sollicitudin dolor");
        list.add(bs505);
        BookSeries bs506 = new BookSeries("nulla", 4, SerieTypeEnum.MANGA, "phasellus dictumst sollicitudin placerat quisque");
        list.add(bs506);
        BookSeries bs507 = new BookSeries("pretium", 5, SerieTypeEnum.MANGA, "laoreet nullam proin litora velit");
        list.add(bs507);
        BookSeries bs508 = new BookSeries("wisiaenean", 7, SerieTypeEnum.LIVRO, "consectetuer taciti conubia aenean tortor");
        list.add(bs508);
        BookSeries bs509 = new BookSeries("accumsan eleifend", 7, SerieTypeEnum.MANGA, "vestibulum risus accumsan pharetra libero");
        list.add(bs509);
        BookSeries bs510 = new BookSeries("curae etiam", 0, SerieTypeEnum.LIVRO, "hendrerit sagittis proin facilisisnunc fringilla");
        list.add(bs510);
        BookSeries bs511 = new BookSeries("phasellus litora", 4, SerieTypeEnum.LIVRO, "dictumst interdum congue habitasse pellentesque");
        list.add(bs511);
        BookSeries bs512 = new BookSeries("viverra", 2, SerieTypeEnum.LIVRO, "aenean primis pellentesque semper elementum");
        list.add(bs512);
        BookSeries bs513 = new BookSeries("tellus", 7, SerieTypeEnum.LIVRO, "fringilla pellentesque netus cursus platea");
        list.add(bs513);
        BookSeries bs514 = new BookSeries("mattis proin", 8, SerieTypeEnum.HQ, "proin euismod venenatis lacinia curabitur");
        list.add(bs514);
        BookSeries bs515 = new BookSeries("conubia", 4, SerieTypeEnum.HQ, "laoreet hymenaeos cursus vitae rutrum");
        list.add(bs515);
        BookSeries bs516 = new BookSeries("pellentesque", 9, SerieTypeEnum.MANGA, "sodales vehicula senectus scelerisque ornare");
        list.add(bs516);
        BookSeries bs517 = new BookSeries("libero", 2, SerieTypeEnum.LIVRO, "vehicula viverra convallis integer suspendisse");
        list.add(bs517);
        BookSeries bs518 = new BookSeries("porta", 3, SerieTypeEnum.MANGA, "posuere litora aliquam facilisisnunc pretium");
        list.add(bs518);
        BookSeries bs519 = new BookSeries("lacus", 1, SerieTypeEnum.LIVRO, "molestie litora dictum adipiscing porta");
        list.add(bs519);
        BookSeries bs520 = new BookSeries("convallis accumsan", 10, SerieTypeEnum.MANGA, "mauris congue lectus viverra volutpat");
        list.add(bs520);
        BookSeries bs521 = new BookSeries("egestas", 0, SerieTypeEnum.HQ, "convallis scelerisque taciti malesuada dictum");
        list.add(bs521);
        BookSeries bs522 = new BookSeries("lectus", 10, SerieTypeEnum.LIVRO, "aenean venenatis volutpat volutpat venenatis");
        list.add(bs522);
        BookSeries bs523 = new BookSeries("molestie", 1, SerieTypeEnum.HQ, "venenatis interdum pharetra libero facilisis");
        list.add(bs523);
        BookSeries bs524 = new BookSeries("pharetra augue", 6, SerieTypeEnum.MANGA, "mauris malesuada pulvinar adipiscing ullamcorper");
        list.add(bs524);
        BookSeries bs525 = new BookSeries("lobortis", 5, SerieTypeEnum.MANGA, "mattis sodales phasellus praesent taciti");
        list.add(bs525);
        BookSeries bs526 = new BookSeries("hymenaeos", 0, SerieTypeEnum.LIVRO, "torquent aliquam netus netus rutrum");
        list.add(bs526);
        BookSeries bs527 = new BookSeries("dignissim tellus", 6, SerieTypeEnum.LIVRO, "euismod tincidunt aptent phasellus purus");
        list.add(bs527);
        BookSeries bs528 = new BookSeries("praesent", 2, SerieTypeEnum.HQ, "vestibulum senectus libero cubilia pellentesque");
        list.add(bs528);
        BookSeries bs529 = new BookSeries("libero consequat", 7, SerieTypeEnum.LIVRO, "ligula porta mauris curae mattis");
        list.add(bs529);
        BookSeries bs530 = new BookSeries("ornare aliquam", 10, SerieTypeEnum.HQ, "vestibulum curabitur porttitor pulvinar tellus");
        list.add(bs530);
        BookSeries bs531 = new BookSeries("mollis", 7, SerieTypeEnum.MANGA, "bulum congue pellentesque aenean torquent");
        list.add(bs531);
        BookSeries bs532 = new BookSeries("posuere", 1, SerieTypeEnum.HQ, "platea velit mauris magna augue");
        list.add(bs532);
        BookSeries bs533 = new BookSeries("dolor", 10, SerieTypeEnum.HQ, "purus dictumst nonummy quisque augue");
        list.add(bs533);
        BookSeries bs534 = new BookSeries("porta", 9, SerieTypeEnum.HQ, "laoreet risus accumsan pretium dignissim");
        list.add(bs534);
        BookSeries bs535 = new BookSeries("curae metus", 4, SerieTypeEnum.MANGA, "libero commodo mauris aliquam elementum");
        list.add(bs535);
        BookSeries bs536 = new BookSeries("faucibus", 0, SerieTypeEnum.MANGA, "tempus suspendisse hendrerit nullam inceptos");
        list.add(bs536);
        BookSeries bs537 = new BookSeries("iaculis", 0, SerieTypeEnum.MANGA, "lectus iaculis molestie nulla cubilia");
        list.add(bs537);
        BookSeries bs538 = new BookSeries("netus laoreet", 2, SerieTypeEnum.HQ, "aliquam cursus dictumst pharetra fusce");
        list.add(bs538);
        BookSeries bs539 = new BookSeries("tempus", 2, SerieTypeEnum.HQ, "posuere pellentesque litora habitant venenatis");
        list.add(bs539);
        BookSeries bs540 = new BookSeries("tristique", 2, SerieTypeEnum.HQ, "fringilla luctus netus facilisis venenatis");
        list.add(bs540);
        BookSeries bs541 = new BookSeries("netus egestas", 9, SerieTypeEnum.HQ, "magna viverra dignissim lorem dictumst");
        list.add(bs541);
        BookSeries bs542 = new BookSeries("tempus ullamcorper", 9, SerieTypeEnum.LIVRO, "sapien consectetuer accumsan convallis fames");
        list.add(bs542);
        BookSeries bs543 = new BookSeries("ornare", 10, SerieTypeEnum.HQ, "proin vitae pharetra bibendum venenatis");
        list.add(bs543);
        BookSeries bs544 = new BookSeries("morbi", 2, SerieTypeEnum.LIVRO, "cubilia pulvinar wisiaenean primis fames");
        list.add(bs544);
        BookSeries bs545 = new BookSeries("torquent torquent", 0, SerieTypeEnum.HQ, "cursus tincidunt suspendisse lobortis nullam");
        list.add(bs545);
        BookSeries bs546 = new BookSeries("dictum", 5, SerieTypeEnum.HQ, "dictumst etiam maecenas libero tortor");
        list.add(bs546);
        BookSeries bs547 = new BookSeries("fermentum augue", 7, SerieTypeEnum.MANGA, "mollis sodales habitant vehicula mauris");
        list.add(bs547);
        BookSeries bs548 = new BookSeries("mollis", 1, SerieTypeEnum.MANGA, "varius curae dolor curae interdum");
        list.add(bs548);
        BookSeries bs549 = new BookSeries("ullamcorper", 9, SerieTypeEnum.LIVRO, "inceptos lacus accumsan facilisisnunc consectetuer");
        list.add(bs549);
        BookSeries bs550 = new BookSeries("porttitor", 8, SerieTypeEnum.LIVRO, "placerat lobortis mollis tristique placerat");
        list.add(bs550);
        BookSeries bs551 = new BookSeries("fames", 8, SerieTypeEnum.MANGA, "curabitur proin tempor aenean purus");
        list.add(bs551);
        BookSeries bs552 = new BookSeries("aptent", 0, SerieTypeEnum.MANGA, "wisiaenean interdum turpis consequat cursus");
        list.add(bs552);
        BookSeries bs553 = new BookSeries("sociosqu aliquam", 10, SerieTypeEnum.HQ, "lobortis curae mollis phasellus sociosqu");
        list.add(bs553);
        BookSeries bs554 = new BookSeries("fames", 2, SerieTypeEnum.LIVRO, "risus fringilla phasellus senectus feugiat");
        list.add(bs554);
        BookSeries bs555 = new BookSeries("nulla lacus", 9, SerieTypeEnum.HQ, "lectus eleifend facilisisnunc molestie adipiscing");
        list.add(bs555);
        BookSeries bs556 = new BookSeries("taciti", 6, SerieTypeEnum.HQ, "integer lacus habitasse quisque fermentum");
        list.add(bs556);
        BookSeries bs557 = new BookSeries("quisque", 2, SerieTypeEnum.HQ, "lobortis convallis curabitur cubilia fusce");
        list.add(bs557);
        BookSeries bs558 = new BookSeries("netus ipsum", 3, SerieTypeEnum.LIVRO, "scelerisque interdum nullam consequat luctus");
        list.add(bs558);
        BookSeries bs559 = new BookSeries("mollis", 0, SerieTypeEnum.LIVRO, "quisque pretium dictum proin nulla");
        list.add(bs559);
        BookSeries bs560 = new BookSeries("lectus", 6, SerieTypeEnum.MANGA, "dictum purus fusce vivamus consequat");
        list.add(bs560);
        BookSeries bs561 = new BookSeries("mauris", 2, SerieTypeEnum.HQ, "imperdiet adipiscing adipiscing tempor malesuada");
        list.add(bs561);
        BookSeries bs562 = new BookSeries("phasellus pulvinar", 6, SerieTypeEnum.MANGA, "augue tortor habitasse bibendum egestas");
        list.add(bs562);
        BookSeries bs563 = new BookSeries("ipsum integer", 7, SerieTypeEnum.MANGA, "etiam mollis hendrerit conubia cubilia");
        list.add(bs563);
        BookSeries bs564 = new BookSeries("varius", 4, SerieTypeEnum.LIVRO, "eleifend bulum bulum congue aptent");
        list.add(bs564);
        BookSeries bs565 = new BookSeries("taciti", 3, SerieTypeEnum.MANGA, "consequat lobortis ultricies venenatis rutrum");
        list.add(bs565);
        BookSeries bs566 = new BookSeries("ligula", 6, SerieTypeEnum.LIVRO, "lobortis sollicitudin iaculis nulla ligula");
        list.add(bs566);
        BookSeries bs567 = new BookSeries("tumst", 5, SerieTypeEnum.MANGA, "platea platea cubilia placerat habitant");
        list.add(bs567);
        BookSeries bs568 = new BookSeries("pretium", 7, SerieTypeEnum.HQ, "litora risus lobortis proin tumst");
        list.add(bs568);
        BookSeries bs569 = new BookSeries("fames", 7, SerieTypeEnum.MANGA, "torquent morbi bulum posuere purus");
        list.add(bs569);
        BookSeries bs570 = new BookSeries("hymenaeos", 4, SerieTypeEnum.HQ, "dignissim consequat adipiscing vitae neque");
        list.add(bs570);
        BookSeries bs571 = new BookSeries("facilisi", 7, SerieTypeEnum.MANGA, "integer habitant tellus vesti hymenaeos");
        list.add(bs571);
        BookSeries bs572 = new BookSeries("iaculis consequat", 2, SerieTypeEnum.LIVRO, "dictumst aptent mauris pharetra convallis");
        list.add(bs572);
        BookSeries bs573 = new BookSeries("velit", 3, SerieTypeEnum.MANGA, "volutpat quisque aptent conubia nullam");
        list.add(bs573);
        BookSeries bs574 = new BookSeries("inceptos lobortis", 1, SerieTypeEnum.HQ, "iaculis hendrerit purus turpis tincidunt");
        list.add(bs574);
        BookSeries bs575 = new BookSeries("egestas", 2, SerieTypeEnum.LIVRO, "litora taciti facilisisnunc senectus tumst");
        list.add(bs575);
        BookSeries bs576 = new BookSeries("primis", 8, SerieTypeEnum.LIVRO, "inceptos porttitor netus elementum aptent");
        list.add(bs576);
        BookSeries bs577 = new BookSeries("lacus", 6, SerieTypeEnum.MANGA, "tellus ullamcorper sodales nulla dignissim");
        list.add(bs577);
        BookSeries bs578 = new BookSeries("placerat lobortis", 5, SerieTypeEnum.HQ, "euismod tincidunt integer lobortis scelerisque");
        list.add(bs578);
        BookSeries bs579 = new BookSeries("ultricies", 9, SerieTypeEnum.LIVRO, "fermentum faucibus mauris cursus mauris");
        list.add(bs579);
        BookSeries bs580 = new BookSeries("cursus", 8, SerieTypeEnum.HQ, "nonummy aliquam integer nulla quisque");
        list.add(bs580);
        BookSeries bs581 = new BookSeries("posuere", 8, SerieTypeEnum.LIVRO, "tristique fringilla netus tortor lacus");
        list.add(bs581);
        BookSeries bs582 = new BookSeries("euismod mattis", 0, SerieTypeEnum.MANGA, "facilisis nonummy pretium tempus justo");
        list.add(bs582);
        BookSeries bs583 = new BookSeries("elementum mattis", 0, SerieTypeEnum.HQ, "porta tellus lectus morbi cubilia");
        list.add(bs583);
        BookSeries bs584 = new BookSeries("tempus", 9, SerieTypeEnum.LIVRO, "lectus consectetuer habitant fermentum posuere");
        list.add(bs584);
        BookSeries bs585 = new BookSeries("facilisi", 8, SerieTypeEnum.HQ, "turpis lorem sapien lobortis mollis");
        list.add(bs585);
        BookSeries bs586 = new BookSeries("feugiat", 2, SerieTypeEnum.HQ, "consequat risus hymenaeos sapien risus");
        list.add(bs586);
        BookSeries bs587 = new BookSeries("neque", 7, SerieTypeEnum.LIVRO, "posuere porta imperdiet morbi integer");
        list.add(bs587);
        BookSeries bs588 = new BookSeries("vehicula", 4, SerieTypeEnum.MANGA, "taciti adipiscing venenatis fringilla tristique");
        list.add(bs588);
        BookSeries bs589 = new BookSeries("tempus", 3, SerieTypeEnum.MANGA, "integer taciti metus netus bulum");
        list.add(bs589);
        BookSeries bs590 = new BookSeries("lacus", 6, SerieTypeEnum.MANGA, "nostra tempus habitant pharetra praesent");
        list.add(bs590);
        BookSeries bs591 = new BookSeries("sapien vivamus", 2, SerieTypeEnum.LIVRO, "tempus auctor mollis tempor risus");
        list.add(bs591);
        BookSeries bs592 = new BookSeries("libero libero", 8, SerieTypeEnum.HQ, "molestie euismod sociosqu habitasse lacus");
        list.add(bs592);
        BookSeries bs593 = new BookSeries("consectetuer aenean", 7, SerieTypeEnum.LIVRO, "dictumst curabitur placerat inceptos facilisis");
        list.add(bs593);
        BookSeries bs594 = new BookSeries("luctus", 5, SerieTypeEnum.HQ, "sollicitudin magna euismod semper platea");
        list.add(bs594);
        BookSeries bs595 = new BookSeries("hendrerit", 3, SerieTypeEnum.HQ, "hymenaeos senectus luctus elementum cursus");
        list.add(bs595);
        BookSeries bs596 = new BookSeries("cursus", 1, SerieTypeEnum.LIVRO, "curabitur quisque imperdiet luctus consequat");
        list.add(bs596);
        BookSeries bs597 = new BookSeries("fermentum", 5, SerieTypeEnum.LIVRO, "aenean faucibus aenean porta magna");
        list.add(bs597);
        BookSeries bs598 = new BookSeries("donec molestie", 4, SerieTypeEnum.MANGA, "praesent egestas facilisi metus facilisisnunc");
        list.add(bs598);
        BookSeries bs599 = new BookSeries("aenean", 1, SerieTypeEnum.HQ, "facilisi praesent nostra mollis class");
        list.add(bs599);
        BookSeries bs600 = new BookSeries("vitae", 8, SerieTypeEnum.HQ, "ultrices neque cursus litora ullamcorper");
        list.add(bs600);
        BookSeries bs601 = new BookSeries("ullamcorper eleifend", 5, SerieTypeEnum.MANGA, "vitae placerat maecenas sapien aliquet");
        list.add(bs601);
        BookSeries bs602 = new BookSeries("vestibulum", 9, SerieTypeEnum.LIVRO, "ipsum sagittis fringilla molestie ipsum");
        list.add(bs602);
        BookSeries bs603 = new BookSeries("curae tortor", 8, SerieTypeEnum.MANGA, "laoreet tempor nonummy volutpat curabitur");
        list.add(bs603);
        BookSeries bs604 = new BookSeries("venenatis", 8, SerieTypeEnum.LIVRO, "risus quisque risus lectus litora");
        list.add(bs604);
        BookSeries bs605 = new BookSeries("imperdiet feugiat", 7, SerieTypeEnum.HQ, "bulum nonummy sodales feugiat iaculis");
        list.add(bs605);
        BookSeries bs606 = new BookSeries("felis aliquam", 9, SerieTypeEnum.HQ, "facilisis purus vivamus placerat class");
        list.add(bs606);
        BookSeries bs607 = new BookSeries("ornare metus", 9, SerieTypeEnum.MANGA, "maecenas lobortis purus semper cursus");
        list.add(bs607);
        BookSeries bs608 = new BookSeries("faucibus purus", 5, SerieTypeEnum.LIVRO, "molestie pretium semper pellentesque sapien");
        list.add(bs608);
        BookSeries bs609 = new BookSeries("aliquet curae", 9, SerieTypeEnum.HQ, "purus lectus molestie fames egestas");
        list.add(bs609);
        BookSeries bs610 = new BookSeries("sagittis", 7, SerieTypeEnum.HQ, "inceptos senectus mattis vesti ligula");
        list.add(bs610);
        BookSeries bs611 = new BookSeries("ultricies", 5, SerieTypeEnum.LIVRO, "pharetra tortor adipiscing aptent vehicula");
        list.add(bs611);
        BookSeries bs612 = new BookSeries("malesuada eleifend", 1, SerieTypeEnum.LIVRO, "tempus volutpat semper conubia lectus");
        list.add(bs612);
        BookSeries bs613 = new BookSeries("euismod risus", 10, SerieTypeEnum.HQ, "fermentum tellus maecenas vitae sociosqu");
        list.add(bs613);
        BookSeries bs614 = new BookSeries("consequat", 0, SerieTypeEnum.LIVRO, "lobortis ipsum mattis turpis mattis");
        list.add(bs614);
        BookSeries bs615 = new BookSeries("imperdiet", 6, SerieTypeEnum.LIVRO, "commodo neque porta nostra habitasse");
        list.add(bs615);
        BookSeries bs616 = new BookSeries("nullam ultrices", 4, SerieTypeEnum.LIVRO, "felis ligula aenean sollicitudin metus");
        list.add(bs616);
        BookSeries bs617 = new BookSeries("integer", 7, SerieTypeEnum.LIVRO, "viverra inceptos tumst interdum posuere");
        list.add(bs617);
        BookSeries bs618 = new BookSeries("aliquam", 5, SerieTypeEnum.LIVRO, "faucibus imperdiet cubilia bulum fringilla");
        list.add(bs618);
        BookSeries bs619 = new BookSeries("rutrum", 6, SerieTypeEnum.MANGA, "curae vivamus sapien faucibus aliquam");
        list.add(bs619);
        BookSeries bs620 = new BookSeries("primis mauris", 10, SerieTypeEnum.MANGA, "neque curae curabitur lacus commodo");
        list.add(bs620);
        BookSeries bs621 = new BookSeries("litora metus", 6, SerieTypeEnum.MANGA, "volutpat ligula sodales phasellus facilisis");
        list.add(bs621);
        BookSeries bs622 = new BookSeries("neque", 6, SerieTypeEnum.HQ, "lobortis congue nonummy dignissim congue");
        list.add(bs622);
        BookSeries bs623 = new BookSeries("maecenas", 5, SerieTypeEnum.LIVRO, "faucibus sagittis hendrerit consequat porttitor");
        list.add(bs623);
        BookSeries bs624 = new BookSeries("facilisisnunc", 0, SerieTypeEnum.MANGA, "cubilia elementum turpis purus felis");
        list.add(bs624);
        BookSeries bs625 = new BookSeries("litora", 6, SerieTypeEnum.MANGA, "semper risus mattis pellentesque mauris");
        list.add(bs625);
        BookSeries bs626 = new BookSeries("habitasse", 5, SerieTypeEnum.LIVRO, "ultrices sagittis pulvinar libero porttitor");
        list.add(bs626);
        BookSeries bs627 = new BookSeries("vehicula", 7, SerieTypeEnum.MANGA, "mattis bulum semper lacus dictumst");
        list.add(bs627);
        BookSeries bs628 = new BookSeries("senectus", 7, SerieTypeEnum.MANGA, "praesent faucibus class nullam augue");
        list.add(bs628);
        BookSeries bs629 = new BookSeries("rutrum taciti", 1, SerieTypeEnum.HQ, "placerat netus hymenaeos vitae pulvinar");
        list.add(bs629);
        BookSeries bs630 = new BookSeries("nostra metus", 7, SerieTypeEnum.LIVRO, "felis feugiat pulvinar adipiscing pellentesque");
        list.add(bs630);
        BookSeries bs631 = new BookSeries("risus", 2, SerieTypeEnum.MANGA, "habitasse lacinia cubilia porttitor congue");
        list.add(bs631);
        BookSeries bs632 = new BookSeries("quisque", 6, SerieTypeEnum.MANGA, "pulvinar libero suspendisse aliquam cursus");
        list.add(bs632);
        BookSeries bs633 = new BookSeries("commodo", 9, SerieTypeEnum.MANGA, "senectus iaculis luctus ullamcorper tristique");
        list.add(bs633);
        BookSeries bs634 = new BookSeries("tortor metus", 7, SerieTypeEnum.MANGA, "netus semper nostra aliquet hymenaeos");
        list.add(bs634);
        BookSeries bs635 = new BookSeries("luctus elementum", 8, SerieTypeEnum.MANGA, "semper malesuada accumsan curabitur convallis");
        list.add(bs635);
        BookSeries bs636 = new BookSeries("nullam habitasse", 6, SerieTypeEnum.MANGA, "lorem platea nonummy velit interdum");
        list.add(bs636);
        BookSeries bs637 = new BookSeries("netus pulvinar", 9, SerieTypeEnum.HQ, "facilisisnunc venenatis risus viverra primis");
        list.add(bs637);
        BookSeries bs638 = new BookSeries("magna", 7, SerieTypeEnum.MANGA, "tincidunt magna nulla venenatis vesti");
        list.add(bs638);
        BookSeries bs639 = new BookSeries("mauris", 4, SerieTypeEnum.MANGA, "semper convallis auctor tincidunt cursus");
        list.add(bs639);
        BookSeries bs640 = new BookSeries("justo ligula", 3, SerieTypeEnum.HQ, "ornare fringilla inceptos tempor venenatis");
        list.add(bs640);
        BookSeries bs641 = new BookSeries("sociosqu", 9, SerieTypeEnum.MANGA, "velit varius sollicitudin aenean litora");
        list.add(bs641);
        BookSeries bs642 = new BookSeries("wisiaenean", 7, SerieTypeEnum.LIVRO, "scelerisque posuere neque primis convallis");
        list.add(bs642);
        BookSeries bs643 = new BookSeries("auctor", 3, SerieTypeEnum.HQ, "justo placerat convallis tumst cubilia");
        list.add(bs643);
        BookSeries bs644 = new BookSeries("congue", 5, SerieTypeEnum.HQ, "ullamcorper iaculis tellus porttitor velit");
        list.add(bs644);
        BookSeries bs645 = new BookSeries("conubia conubia", 2, SerieTypeEnum.LIVRO, "mauris hymenaeos phasellus tortor aliquam");
        list.add(bs645);
        BookSeries bs646 = new BookSeries("porttitor", 0, SerieTypeEnum.MANGA, "accumsan hendrerit tumst vestibulum imperdiet");
        list.add(bs646);
        BookSeries bs647 = new BookSeries("venenatis", 0, SerieTypeEnum.HQ, "metus luctus inceptos curabitur posuere");
        list.add(bs647);
        BookSeries bs648 = new BookSeries("scelerisque", 6, SerieTypeEnum.LIVRO, "lobortis vitae metus varius litora");
        list.add(bs648);
        BookSeries bs649 = new BookSeries("venenatis", 5, SerieTypeEnum.HQ, "volutpat fermentum suspendisse semper etiam");
        list.add(bs649);
        BookSeries bs650 = new BookSeries("curae", 10, SerieTypeEnum.MANGA, "mauris cubilia porttitor porta taciti");
        list.add(bs650);
        BookSeries bs651 = new BookSeries("interdum ornare", 2, SerieTypeEnum.MANGA, "justo lectus nulla tumst neque");
        list.add(bs651);
        BookSeries bs652 = new BookSeries("commodo tristique", 7, SerieTypeEnum.MANGA, "consectetuer conubia augue accumsan mollis");
        list.add(bs652);
        BookSeries bs653 = new BookSeries("suspendisse dignissim", 4, SerieTypeEnum.MANGA, "ligula accumsan hendrerit fusce facilisisnunc");
        list.add(bs653);
        BookSeries bs654 = new BookSeries("euismod fringilla", 10, SerieTypeEnum.LIVRO, "egestas semper bibendum habitasse aliquam");
        list.add(bs654);
        BookSeries bs655 = new BookSeries("molestie", 9, SerieTypeEnum.MANGA, "sodales convallis mollis habitant velit");
        list.add(bs655);
        BookSeries bs656 = new BookSeries("quisque", 0, SerieTypeEnum.HQ, "accumsan morbi torquent placerat dictumst");
        list.add(bs656);
        BookSeries bs657 = new BookSeries("curae proin", 5, SerieTypeEnum.MANGA, "faucibus bulum neque felis integer");
        list.add(bs657);
        BookSeries bs658 = new BookSeries("curae", 7, SerieTypeEnum.LIVRO, "placerat tellus phasellus rutrum facilisisnunc");
        list.add(bs658);
        BookSeries bs659 = new BookSeries("lobortis maecenas", 5, SerieTypeEnum.MANGA, "mollis sociosqu auctor platea cubilia");
        list.add(bs659);
        BookSeries bs660 = new BookSeries("aliquam volutpat", 10, SerieTypeEnum.MANGA, "taciti tempor metus cursus etiam");
        list.add(bs660);
        BookSeries bs661 = new BookSeries("metus elementum", 9, SerieTypeEnum.HQ, "molestie fermentum convallis facilisi hendrerit");
        list.add(bs661);
        BookSeries bs662 = new BookSeries("torquent", 4, SerieTypeEnum.MANGA, "etiam netus dictum dolor cubilia");
        list.add(bs662);
        BookSeries bs663 = new BookSeries("nulla tortor", 5, SerieTypeEnum.MANGA, "porta nostra venenatis eleifend bulum");
        list.add(bs663);
        BookSeries bs664 = new BookSeries("aenean", 0, SerieTypeEnum.MANGA, "phasellus nonummy torquent ornare fusce");
        list.add(bs664);
        BookSeries bs665 = new BookSeries("adipiscing", 1, SerieTypeEnum.HQ, "consectetuer tumst class porttitor dolor");
        list.add(bs665);
        BookSeries bs666 = new BookSeries("hendrerit", 5, SerieTypeEnum.HQ, "mattis vesti nostra velit lacinia");
        list.add(bs666);
        BookSeries bs667 = new BookSeries("libero", 9, SerieTypeEnum.MANGA, "eleifend consequat vehicula auctor semper");
        list.add(bs667);
        BookSeries bs668 = new BookSeries("nullam accumsan", 10, SerieTypeEnum.HQ, "bibendum ultricies proin commodo pharetra");
        list.add(bs668);
        BookSeries bs669 = new BookSeries("metus", 3, SerieTypeEnum.MANGA, "placerat conubia metus mollis neque");
        list.add(bs669);
        BookSeries bs670 = new BookSeries("vivamus congue", 0, SerieTypeEnum.LIVRO, "magna sodales etiam ullamcorper egestas");
        list.add(bs670);
        BookSeries bs671 = new BookSeries("feugiat", 7, SerieTypeEnum.MANGA, "placerat risus pretium pretium porta");
        list.add(bs671);
        BookSeries bs672 = new BookSeries("semper feugiat", 1, SerieTypeEnum.MANGA, "interdum sapien tortor quisque vivamus");
        list.add(bs672);
        BookSeries bs673 = new BookSeries("ullamcorper", 9, SerieTypeEnum.MANGA, "habitant lectus consequat tristique inceptos");
        list.add(bs673);
        BookSeries bs674 = new BookSeries("ultricies", 5, SerieTypeEnum.HQ, "fames fringilla phasellus facilisisnunc curabitur");
        list.add(bs674);
        BookSeries bs675 = new BookSeries("suspendisse malesuada", 2, SerieTypeEnum.LIVRO, "risus viverra torquent ultricies fermentum");
        list.add(bs675);
        BookSeries bs676 = new BookSeries("fermentum tempor", 2, SerieTypeEnum.LIVRO, "velit quisque varius rutrum hendrerit");
        list.add(bs676);
        BookSeries bs677 = new BookSeries("laoreet", 6, SerieTypeEnum.LIVRO, "integer consectetuer vivamus lacus tortor");
        list.add(bs677);
        BookSeries bs678 = new BookSeries("facilisis", 5, SerieTypeEnum.MANGA, "tortor vesti dictumst imperdiet vitae");
        list.add(bs678);
        BookSeries bs679 = new BookSeries("donec", 8, SerieTypeEnum.HQ, "cursus vesti inceptos dolor libero");
        list.add(bs679);
        BookSeries bs680 = new BookSeries("conubia", 6, SerieTypeEnum.MANGA, "interdum senectus lorem nostra taciti");
        list.add(bs680);
        BookSeries bs681 = new BookSeries("posuere pharetra", 4, SerieTypeEnum.LIVRO, "sapien convallis tincidunt ligula euismod");
        list.add(bs681);
        BookSeries bs682 = new BookSeries("egestas", 5, SerieTypeEnum.HQ, "integer malesuada nullam etiam metus");
        list.add(bs682);
        BookSeries bs683 = new BookSeries("turpis", 9, SerieTypeEnum.LIVRO, "donec curabitur proin conubia lacus");
        list.add(bs683);
        BookSeries bs684 = new BookSeries("donec", 6, SerieTypeEnum.HQ, "suspendisse vivamus lectus metus sollicitudin");
        list.add(bs684);
        BookSeries bs685 = new BookSeries("volutpat", 6, SerieTypeEnum.HQ, "tempor neque habitant pulvinar nonummy");
        list.add(bs685);
        BookSeries bs686 = new BookSeries("purus", 7, SerieTypeEnum.MANGA, "senectus conubia volutpat curae pellentesque");
        list.add(bs686);
        BookSeries bs687 = new BookSeries("habitant", 3, SerieTypeEnum.MANGA, "lacinia senectus facilisisnunc hendrerit lobortis");
        list.add(bs687);
        BookSeries bs688 = new BookSeries("vesti", 5, SerieTypeEnum.LIVRO, "aptent curabitur turpis quisque aliquet");
        list.add(bs688);
        BookSeries bs689 = new BookSeries("hendrerit", 7, SerieTypeEnum.HQ, "libero porta wisiaenean turpis proin");
        list.add(bs689);
        BookSeries bs690 = new BookSeries("lacinia", 3, SerieTypeEnum.MANGA, "commodo convallis habitasse nullam congue");
        list.add(bs690);
        BookSeries bs691 = new BookSeries("augue", 8, SerieTypeEnum.LIVRO, "scelerisque turpis euismod varius donec");
        list.add(bs691);
        BookSeries bs692 = new BookSeries("aliquam phasellus", 3, SerieTypeEnum.HQ, "congue ultricies rutrum suspendisse elementum");
        list.add(bs692);
        BookSeries bs693 = new BookSeries("dignissim sapien", 3, SerieTypeEnum.LIVRO, "adipiscing tellus eleifend donec hymenaeos");
        list.add(bs693);
        BookSeries bs694 = new BookSeries("facilisis", 0, SerieTypeEnum.HQ, "hymenaeos praesent libero rutrum pellentesque");
        list.add(bs694);
        BookSeries bs695 = new BookSeries("porta", 5, SerieTypeEnum.HQ, "quisque pretium auctor praesent lorem");
        list.add(bs695);
        BookSeries bs696 = new BookSeries("tempus", 7, SerieTypeEnum.LIVRO, "metus pellentesque euismod praesent malesuada");
        list.add(bs696);
        BookSeries bs697 = new BookSeries("vesti", 5, SerieTypeEnum.LIVRO, "tellus augue posuere aliquet habitasse");
        list.add(bs697);
        BookSeries bs698 = new BookSeries("sodales class", 10, SerieTypeEnum.MANGA, "bibendum cubilia aliquam malesuada mollis");
        list.add(bs698);
        BookSeries bs699 = new BookSeries("imperdiet", 4, SerieTypeEnum.LIVRO, "sagittis porttitor felis sollicitudin lacus");
        list.add(bs699);
        BookSeries bs700 = new BookSeries("fringilla dignissim", 5, SerieTypeEnum.MANGA, "donec mollis sollicitudin aenean platea");
        list.add(bs700);
        BookSeries bs701 = new BookSeries("morbi", 0, SerieTypeEnum.LIVRO, "ullamcorper porttitor mauris proin curabitur");
        list.add(bs701);
        BookSeries bs702 = new BookSeries("adipiscing", 3, SerieTypeEnum.HQ, "molestie dolor adipiscing turpis tellus");
        list.add(bs702);
        BookSeries bs703 = new BookSeries("lacus", 0, SerieTypeEnum.LIVRO, "donec phasellus lacinia facilisi sociosqu");
        list.add(bs703);
        BookSeries bs704 = new BookSeries("feugiat", 4, SerieTypeEnum.HQ, "placerat consequat vitae tristique tortor");
        list.add(bs704);
        BookSeries bs705 = new BookSeries("rutrum", 10, SerieTypeEnum.MANGA, "auctor auctor lectus ipsum posuere");
        list.add(bs705);
        BookSeries bs706 = new BookSeries("volutpat", 6, SerieTypeEnum.HQ, "posuere vehicula fusce facilisisnunc vehicula");
        list.add(bs706);
        BookSeries bs707 = new BookSeries("tristique", 10, SerieTypeEnum.HQ, "fermentum cubilia facilisis dictumst mollis");
        list.add(bs707);
        BookSeries bs708 = new BookSeries("nonummy inceptos", 9, SerieTypeEnum.MANGA, "facilisi augue tristique venenatis maecenas");
        list.add(bs708);
        BookSeries bs709 = new BookSeries("pellentesque", 4, SerieTypeEnum.HQ, "consequat justo proin magna habitant");
        list.add(bs709);
        BookSeries bs710 = new BookSeries("bibendum porta", 0, SerieTypeEnum.HQ, "lectus mollis bulum ultrices bulum");
        list.add(bs710);
        BookSeries bs711 = new BookSeries("lacus", 5, SerieTypeEnum.LIVRO, "tempus vestibulum praesent consectetuer nullam");
        list.add(bs711);
        BookSeries bs712 = new BookSeries("platea maecenas", 4, SerieTypeEnum.MANGA, "laoreet tellus praesent tristique vesti");
        list.add(bs712);
        BookSeries bs713 = new BookSeries("feugiat", 10, SerieTypeEnum.MANGA, "fames fusce phasellus rutrum fusce");
        list.add(bs713);
        BookSeries bs714 = new BookSeries("ullamcorper", 5, SerieTypeEnum.MANGA, "donec taciti vitae faucibus vivamus");
        list.add(bs714);
        BookSeries bs715 = new BookSeries("maecenas", 0, SerieTypeEnum.HQ, "integer venenatis adipiscing proin lobortis");
        list.add(bs715);
        BookSeries bs716 = new BookSeries("cubilia", 7, SerieTypeEnum.LIVRO, "habitasse ultricies lobortis malesuada cubilia");
        list.add(bs716);
        BookSeries bs717 = new BookSeries("dignissim", 10, SerieTypeEnum.MANGA, "torquent facilisi platea vehicula pulvinar");
        list.add(bs717);
        BookSeries bs718 = new BookSeries("felis ipsum", 5, SerieTypeEnum.LIVRO, "hendrerit ipsum justo curabitur turpis");
        list.add(bs718);
        BookSeries bs719 = new BookSeries("laoreet augue", 1, SerieTypeEnum.HQ, "tristique facilisi eleifend conubia morbi");
        list.add(bs719);
        BookSeries bs720 = new BookSeries("placerat", 7, SerieTypeEnum.MANGA, "netus tincidunt venenatis nullam accumsan");
        list.add(bs720);
        BookSeries bs721 = new BookSeries("egestas", 6, SerieTypeEnum.MANGA, "curae euismod scelerisque lorem porttitor");
        list.add(bs721);
        BookSeries bs722 = new BookSeries("nullam", 3, SerieTypeEnum.MANGA, "phasellus donec phasellus sociosqu iaculis");
        list.add(bs722);
        BookSeries bs723 = new BookSeries("proin", 3, SerieTypeEnum.LIVRO, "ultricies egestas pellentesque habitant lacus");
        list.add(bs723);
        BookSeries bs724 = new BookSeries("pretium libero", 8, SerieTypeEnum.MANGA, "justo neque hendrerit vitae sagittis");
        list.add(bs724);
        BookSeries bs725 = new BookSeries("nonummy imperdiet", 9, SerieTypeEnum.HQ, "ornare senectus dignissim adipiscing torquent");
        list.add(bs725);
        BookSeries bs726 = new BookSeries("dolor pulvinar", 10, SerieTypeEnum.HQ, "ullamcorper nullam hymenaeos ligula tincidunt");
        list.add(bs726);
        BookSeries bs727 = new BookSeries("auctor", 2, SerieTypeEnum.HQ, "faucibus ipsum tortor tempus nullam");
        list.add(bs727);
        BookSeries bs728 = new BookSeries("iaculis", 7, SerieTypeEnum.LIVRO, "proin curabitur purus etiam sociosqu");
        list.add(bs728);
        BookSeries bs729 = new BookSeries("bulum", 3, SerieTypeEnum.MANGA, "cubilia bibendum vitae cubilia hymenaeos");
        list.add(bs729);
        BookSeries bs730 = new BookSeries("nullam varius", 3, SerieTypeEnum.HQ, "tincidunt integer etiam conubia risus");
        list.add(bs730);
        BookSeries bs731 = new BookSeries("lacus ultricies", 2, SerieTypeEnum.LIVRO, "consectetuer dictumst venenatis sollicitudin lobortis");
        list.add(bs731);
        BookSeries bs732 = new BookSeries("curae", 7, SerieTypeEnum.MANGA, "donec curabitur vehicula luctus sollicitudin");
        list.add(bs732);
        BookSeries bs733 = new BookSeries("vitae inceptos", 8, SerieTypeEnum.LIVRO, "malesuada egestas wisiaenean tempor faucibus");
        list.add(bs733);
        BookSeries bs734 = new BookSeries("faucibus", 5, SerieTypeEnum.HQ, "dictum platea nostra vesti inceptos");
        list.add(bs734);
        BookSeries bs735 = new BookSeries("iaculis", 1, SerieTypeEnum.HQ, "tellus elementum vestibulum aenean wisiaenean");
        list.add(bs735);
        BookSeries bs736 = new BookSeries("aenean", 2, SerieTypeEnum.MANGA, "facilisi curabitur vestibulum vestibulum habitant");
        list.add(bs736);
        BookSeries bs737 = new BookSeries("tempor", 2, SerieTypeEnum.MANGA, "egestas cubilia nulla tempus mauris");
        list.add(bs737);
        BookSeries bs738 = new BookSeries("lacus", 0, SerieTypeEnum.HQ, "sagittis scelerisque fringilla mattis aliquet");
        list.add(bs738);
        BookSeries bs739 = new BookSeries("nulla", 10, SerieTypeEnum.LIVRO, "venenatis quisque iaculis faucibus mattis");
        list.add(bs739);
        BookSeries bs740 = new BookSeries("turpis", 10, SerieTypeEnum.MANGA, "bibendum facilisi pharetra dignissim elementum");
        list.add(bs740);
        BookSeries bs741 = new BookSeries("lacus", 3, SerieTypeEnum.LIVRO, "fames vivamus interdum dictumst morbi");
        list.add(bs741);
        BookSeries bs742 = new BookSeries("praesent", 1, SerieTypeEnum.MANGA, "habitasse phasellus semper fusce maecenas");
        list.add(bs742);
        BookSeries bs743 = new BookSeries("faucibus", 9, SerieTypeEnum.MANGA, "ornare placerat mauris bulum class");
        list.add(bs743);
        BookSeries bs744 = new BookSeries("sapien hymenaeos", 7, SerieTypeEnum.MANGA, "turpis nostra malesuada elementum pharetra");
        list.add(bs744);
        BookSeries bs745 = new BookSeries("pharetra eleifend", 1, SerieTypeEnum.MANGA, "risus mattis sodales donec fringilla");
        list.add(bs745);
        BookSeries bs746 = new BookSeries("mauris", 5, SerieTypeEnum.LIVRO, "convallis pretium platea mauris faucibus");
        list.add(bs746);
        BookSeries bs747 = new BookSeries("pulvinar", 3, SerieTypeEnum.HQ, "facilisi mauris egestas accumsan placerat");
        list.add(bs747);
        BookSeries bs748 = new BookSeries("tempor", 3, SerieTypeEnum.LIVRO, "consectetuer tristique pretium malesuada curabitur");
        list.add(bs748);
        BookSeries bs749 = new BookSeries("rutrum primis", 6, SerieTypeEnum.MANGA, "magna tristique pretium iaculis primis");
        list.add(bs749);
        BookSeries bs750 = new BookSeries("congue", 10, SerieTypeEnum.LIVRO, "risus platea metus justo ligula");
        list.add(bs750);
        BookSeries bs751 = new BookSeries("luctus", 3, SerieTypeEnum.LIVRO, "euismod vestibulum iaculis metus class");
        list.add(bs751);
        BookSeries bs752 = new BookSeries("vestibulum", 2, SerieTypeEnum.MANGA, "auctor lorem eleifend interdum vestibulum");
        list.add(bs752);
        BookSeries bs753 = new BookSeries("tumst", 10, SerieTypeEnum.LIVRO, "velit praesent tincidunt placerat venenatis");
        list.add(bs753);
        BookSeries bs754 = new BookSeries("pellentesque scelerisque", 10, SerieTypeEnum.LIVRO, "pellentesque ipsum laoreet turpis lacinia");
        list.add(bs754);
        BookSeries bs755 = new BookSeries("venenatis lorem", 4, SerieTypeEnum.LIVRO, "etiam consequat senectus hymenaeos scelerisque");
        list.add(bs755);
        BookSeries bs756 = new BookSeries("vesti", 9, SerieTypeEnum.HQ, "sollicitudin faucibus rutrum velit rutrum");
        list.add(bs756);
        BookSeries bs757 = new BookSeries("netus libero", 9, SerieTypeEnum.HQ, "fermentum porta tortor semper malesuada");
        list.add(bs757);
        BookSeries bs758 = new BookSeries("egestas", 4, SerieTypeEnum.LIVRO, "conubia wisiaenean aenean congue ultricies");
        list.add(bs758);
        BookSeries bs759 = new BookSeries("vestibulum semper", 4, SerieTypeEnum.HQ, "accumsan mattis fringilla porta facilisi");
        list.add(bs759);
        BookSeries bs760 = new BookSeries("pretium", 5, SerieTypeEnum.HQ, "litora interdum turpis facilisis scelerisque");
        list.add(bs760);
        BookSeries bs761 = new BookSeries("senectus", 8, SerieTypeEnum.HQ, "fusce neque viverra donec neque");
        list.add(bs761);
        BookSeries bs762 = new BookSeries("sapien", 4, SerieTypeEnum.HQ, "pulvinar tellus cursus praesent adipiscing");
        list.add(bs762);
        BookSeries bs763 = new BookSeries("semper", 3, SerieTypeEnum.LIVRO, "facilisisnunc auctor malesuada accumsan commodo");
        list.add(bs763);
        BookSeries bs764 = new BookSeries("interdum", 8, SerieTypeEnum.LIVRO, "semper semper laoreet habitasse sodales");
        list.add(bs764);
        BookSeries bs765 = new BookSeries("vehicula", 3, SerieTypeEnum.LIVRO, "molestie curae felis posuere auctor");
        list.add(bs765);
        BookSeries bs766 = new BookSeries("posuere", 0, SerieTypeEnum.HQ, "vitae ultrices nostra aptent viverra");
        list.add(bs766);
        BookSeries bs767 = new BookSeries("sodales mattis", 6, SerieTypeEnum.MANGA, "ornare molestie phasellus ipsum nulla");
        list.add(bs767);
        BookSeries bs768 = new BookSeries("commodo morbi", 8, SerieTypeEnum.MANGA, "phasellus dolor tumst lorem ipsum");
        list.add(bs768);
        BookSeries bs769 = new BookSeries("ipsum donec", 2, SerieTypeEnum.MANGA, "molestie egestas pharetra donec maecenas");
        list.add(bs769);
        BookSeries bs770 = new BookSeries("adipiscing libero", 9, SerieTypeEnum.MANGA, "tellus ultrices tellus ipsum mauris");
        list.add(bs770);
        BookSeries bs771 = new BookSeries("tumst", 4, SerieTypeEnum.MANGA, "turpis curae dolor ornare facilisi");
        list.add(bs771);
        BookSeries bs772 = new BookSeries("felis", 7, SerieTypeEnum.LIVRO, "viverra consectetuer lacinia maecenas hymenaeos");
        list.add(bs772);
        BookSeries bs773 = new BookSeries("taciti", 1, SerieTypeEnum.LIVRO, "dictumst ultricies lorem donec nostra");
        list.add(bs773);
        BookSeries bs774 = new BookSeries("bulum neque", 5, SerieTypeEnum.MANGA, "aliquet vehicula suspendisse tristique vesti");
        list.add(bs774);
        BookSeries bs775 = new BookSeries("cubilia", 0, SerieTypeEnum.HQ, "taciti ipsum inceptos mauris habitasse");
        list.add(bs775);
        BookSeries bs776 = new BookSeries("class pellentesque", 2, SerieTypeEnum.LIVRO, "lacus hendrerit venenatis vehicula varius");
        list.add(bs776);
        BookSeries bs777 = new BookSeries("tellus pulvinar", 0, SerieTypeEnum.MANGA, "feugiat dolor lobortis ultrices adipiscing");
        list.add(bs777);
        BookSeries bs778 = new BookSeries("purus", 3, SerieTypeEnum.LIVRO, "morbi venenatis fusce vitae felis");
        list.add(bs778);
        BookSeries bs779 = new BookSeries("venenatis", 2, SerieTypeEnum.LIVRO, "bulum dignissim mattis cursus interdum");
        list.add(bs779);
        BookSeries bs780 = new BookSeries("ultrices senectus", 4, SerieTypeEnum.LIVRO, "consequat tumst placerat elementum integer");
        list.add(bs780);
        BookSeries bs781 = new BookSeries("tempor ornare", 6, SerieTypeEnum.MANGA, "integer curae litora eleifend suspendisse");
        list.add(bs781);
        BookSeries bs782 = new BookSeries("class", 1, SerieTypeEnum.MANGA, "aliquet vehicula fringilla mattis inceptos");
        list.add(bs782);
        BookSeries bs783 = new BookSeries("netus", 4, SerieTypeEnum.MANGA, "justo ultrices molestie vesti inceptos");
        list.add(bs783);
        BookSeries bs784 = new BookSeries("volutpat", 8, SerieTypeEnum.LIVRO, "fusce auctor pretium felis integer");
        list.add(bs784);
        BookSeries bs785 = new BookSeries("fusce", 6, SerieTypeEnum.LIVRO, "magna libero aptent scelerisque molestie");
        list.add(bs785);
        BookSeries bs786 = new BookSeries("etiam", 9, SerieTypeEnum.MANGA, "iaculis morbi netus torquent sollicitudin");
        list.add(bs786);
        BookSeries bs787 = new BookSeries("ultrices", 6, SerieTypeEnum.MANGA, "vestibulum faucibus litora magna egestas");
        list.add(bs787);
        BookSeries bs788 = new BookSeries("aliquam", 9, SerieTypeEnum.HQ, "consequat facilisi placerat facilisi velit");
        list.add(bs788);
        BookSeries bs789 = new BookSeries("hymenaeos", 3, SerieTypeEnum.HQ, "posuere tincidunt taciti ligula justo");
        list.add(bs789);
        BookSeries bs790 = new BookSeries("rutrum rutrum", 8, SerieTypeEnum.LIVRO, "sodales tortor pharetra commodo porta");
        list.add(bs790);
        BookSeries bs791 = new BookSeries("elementum", 4, SerieTypeEnum.HQ, "facilisisnunc pretium lobortis commodo dictum");
        list.add(bs791);
        BookSeries bs792 = new BookSeries("tumst", 7, SerieTypeEnum.MANGA, "laoreet mattis eleifend tristique primis");
        list.add(bs792);
        BookSeries bs793 = new BookSeries("porta", 10, SerieTypeEnum.LIVRO, "nonummy adipiscing sodales ullamcorper risus");
        list.add(bs793);
        BookSeries bs794 = new BookSeries("tellus", 1, SerieTypeEnum.MANGA, "fermentum commodo aptent laoreet tempor");
        list.add(bs794);
        BookSeries bs795 = new BookSeries("integer", 1, SerieTypeEnum.MANGA, "faucibus morbi tempor turpis euismod");
        list.add(bs795);
        BookSeries bs796 = new BookSeries("bulum", 4, SerieTypeEnum.MANGA, "velit justo adipiscing convallis pellentesque");
        list.add(bs796);
        BookSeries bs797 = new BookSeries("lorem aliquam", 2, SerieTypeEnum.HQ, "integer elementum eleifend donec curae");
        list.add(bs797);
        BookSeries bs798 = new BookSeries("aliquet habitant", 6, SerieTypeEnum.MANGA, "wisiaenean tellus senectus elementum euismod");
        list.add(bs798);
        BookSeries bs799 = new BookSeries("risus pulvinar", 1, SerieTypeEnum.LIVRO, "porta dictumst quisque hymenaeos lobortis");
        list.add(bs799);
        BookSeries bs800 = new BookSeries("auctor", 9, SerieTypeEnum.MANGA, "rutrum tortor auctor pretium bibendum");
        list.add(bs800);
        BookSeries bs801 = new BookSeries("malesuada faucibus", 2, SerieTypeEnum.MANGA, "augue metus facilisi habitasse semper");
        list.add(bs801);
        BookSeries bs802 = new BookSeries("metus", 8, SerieTypeEnum.HQ, "accumsan laoreet fusce dictum luctus");
        list.add(bs802);
        BookSeries bs803 = new BookSeries("habitant tumst", 2, SerieTypeEnum.LIVRO, "fames accumsan dolor convallis habitant");
        list.add(bs803);
        BookSeries bs804 = new BookSeries("metus", 2, SerieTypeEnum.HQ, "suspendisse eleifend facilisisnunc justo netus");
        list.add(bs804);
        BookSeries bs805 = new BookSeries("taciti", 5, SerieTypeEnum.HQ, "fames pulvinar lorem pulvinar maecenas");
        list.add(bs805);
        BookSeries bs806 = new BookSeries("adipiscing", 2, SerieTypeEnum.LIVRO, "bibendum feugiat primis congue pretium");
        list.add(bs806);
        BookSeries bs807 = new BookSeries("etiam senectus", 5, SerieTypeEnum.HQ, "scelerisque tumst ultrices conubia euismod");
        list.add(bs807);
        BookSeries bs808 = new BookSeries("mollis", 5, SerieTypeEnum.MANGA, "consectetuer tempus volutpat primis accumsan");
        list.add(bs808);
        BookSeries bs809 = new BookSeries("iaculis", 9, SerieTypeEnum.HQ, "augue facilisi libero maecenas felis");
        list.add(bs809);
        BookSeries bs810 = new BookSeries("ipsum", 3, SerieTypeEnum.MANGA, "ipsum consequat eleifend ultrices facilisis");
        list.add(bs810);
        BookSeries bs811 = new BookSeries("posuere", 3, SerieTypeEnum.MANGA, "libero litora tempus risus vitae");
        list.add(bs811);
        BookSeries bs812 = new BookSeries("primis inceptos", 9, SerieTypeEnum.MANGA, "curabitur tempus sociosqu cursus ipsum");
        list.add(bs812);
        BookSeries bs813 = new BookSeries("eleifend", 2, SerieTypeEnum.HQ, "nonummy quisque feugiat class mauris");
        list.add(bs813);
        BookSeries bs814 = new BookSeries("adipiscing", 3, SerieTypeEnum.HQ, "sollicitudin senectus praesent ultrices tristique");
        list.add(bs814);
        BookSeries bs815 = new BookSeries("lacinia", 3, SerieTypeEnum.MANGA, "ultrices ipsum auctor molestie aptent");
        list.add(bs815);
        BookSeries bs816 = new BookSeries("tumst magna", 7, SerieTypeEnum.HQ, "bulum tempus eleifend lacus augue");
        list.add(bs816);
        BookSeries bs817 = new BookSeries("sapien", 2, SerieTypeEnum.MANGA, "aliquet class aliquam dictumst libero");
        list.add(bs817);
        BookSeries bs818 = new BookSeries("dictumst", 7, SerieTypeEnum.MANGA, "aliquam laoreet imperdiet imperdiet curae");
        list.add(bs818);
        BookSeries bs819 = new BookSeries("neque varius", 4, SerieTypeEnum.MANGA, "fringilla inceptos molestie lacus ligula");
        list.add(bs819);
        BookSeries bs820 = new BookSeries("maecenas tincidunt", 3, SerieTypeEnum.HQ, "bibendum scelerisque mattis facilisis facilisis");
        list.add(bs820);
        BookSeries bs821 = new BookSeries("porttitor tristique", 1, SerieTypeEnum.LIVRO, "integer tincidunt habitasse vehicula class");
        list.add(bs821);
        BookSeries bs822 = new BookSeries("pulvinar", 2, SerieTypeEnum.LIVRO, "facilisi sagittis imperdiet egestas bibendum");
        list.add(bs822);
        BookSeries bs823 = new BookSeries("litora", 8, SerieTypeEnum.HQ, "sodales mollis habitasse donec inceptos");
        list.add(bs823);
        BookSeries bs824 = new BookSeries("litora", 10, SerieTypeEnum.MANGA, "pretium dictum lorem volutpat vitae");
        list.add(bs824);
        BookSeries bs825 = new BookSeries("bulum euismod", 6, SerieTypeEnum.MANGA, "morbi sociosqu euismod luctus vitae");
        list.add(bs825);
        BookSeries bs826 = new BookSeries("torquent", 7, SerieTypeEnum.HQ, "quisque conubia pellentesque sagittis litora");
        list.add(bs826);
        BookSeries bs827 = new BookSeries("ornare", 6, SerieTypeEnum.MANGA, "curabitur taciti fusce metus lacus");
        list.add(bs827);
        BookSeries bs828 = new BookSeries("metus", 2, SerieTypeEnum.MANGA, "porta nulla ipsum rutrum commodo");
        list.add(bs828);
        BookSeries bs829 = new BookSeries("eleifend", 6, SerieTypeEnum.MANGA, "iaculis vivamus hendrerit facilisis aliquam");
        list.add(bs829);
        BookSeries bs830 = new BookSeries("nullam lorem", 2, SerieTypeEnum.MANGA, "integer vestibulum lorem tellus porta");
        list.add(bs830);
        BookSeries bs831 = new BookSeries("libero", 7, SerieTypeEnum.MANGA, "aliquet hymenaeos nullam interdum ligula");
        list.add(bs831);
        BookSeries bs832 = new BookSeries("lacinia", 6, SerieTypeEnum.MANGA, "congue porttitor nullam fames luctus");
        list.add(bs832);
        BookSeries bs833 = new BookSeries("torquent", 5, SerieTypeEnum.MANGA, "malesuada curabitur praesent mattis tristique");
        list.add(bs833);
        BookSeries bs834 = new BookSeries("egestas", 3, SerieTypeEnum.HQ, "tumst sodales viverra ligula iaculis");
        list.add(bs834);
        BookSeries bs835 = new BookSeries("aliquet ligula", 5, SerieTypeEnum.LIVRO, "imperdiet adipiscing congue etiam hymenaeos");
        list.add(bs835);
        BookSeries bs836 = new BookSeries("ornare", 5, SerieTypeEnum.MANGA, "dignissim tellus phasellus magna dictumst");
        list.add(bs836);
        BookSeries bs837 = new BookSeries("porta lectus", 3, SerieTypeEnum.LIVRO, "molestie maecenas faucibus dictumst quisque");
        list.add(bs837);
        BookSeries bs838 = new BookSeries("tempus", 2, SerieTypeEnum.HQ, "auctor litora curabitur praesent bulum");
        list.add(bs838);
        BookSeries bs839 = new BookSeries("consequat platea", 9, SerieTypeEnum.HQ, "lectus facilisisnunc porttitor interdum sociosqu");
        list.add(bs839);
        BookSeries bs840 = new BookSeries("integer", 7, SerieTypeEnum.HQ, "lacus praesent nullam ligula euismod");
        list.add(bs840);
        BookSeries bs841 = new BookSeries("curabitur mollis", 8, SerieTypeEnum.LIVRO, "suspendisse integer curae nostra taciti");
        list.add(bs841);
        BookSeries bs842 = new BookSeries("ornare", 4, SerieTypeEnum.MANGA, "rutrum dignissim cursus fringilla cursus");
        list.add(bs842);
        BookSeries bs843 = new BookSeries("fames", 6, SerieTypeEnum.MANGA, "vesti wisiaenean rutrum proin etiam");
        list.add(bs843);
        BookSeries bs844 = new BookSeries("pulvinar", 8, SerieTypeEnum.MANGA, "sodales consequat vivamus volutpat nullam");
        list.add(bs844);
        BookSeries bs845 = new BookSeries("eleifend", 8, SerieTypeEnum.LIVRO, "consequat facilisi euismod sagittis posuere");
        list.add(bs845);
        BookSeries bs846 = new BookSeries("fermentum libero", 3, SerieTypeEnum.MANGA, "donec magna bulum pulvinar facilisi");
        list.add(bs846);
        BookSeries bs847 = new BookSeries("iaculis aenean", 6, SerieTypeEnum.LIVRO, "primis dictumst mollis tempus cubilia");
        list.add(bs847);
        BookSeries bs848 = new BookSeries("tortor nulla", 0, SerieTypeEnum.HQ, "porta interdum curae curae curae");
        list.add(bs848);
        BookSeries bs849 = new BookSeries("bibendum", 10, SerieTypeEnum.MANGA, "metus imperdiet curabitur dignissim bibendum");
        list.add(bs849);
        BookSeries bs850 = new BookSeries("imperdiet velit", 9, SerieTypeEnum.LIVRO, "morbi curae turpis ultrices tempus");
        list.add(bs850);
        BookSeries bs851 = new BookSeries("curabitur", 3, SerieTypeEnum.LIVRO, "lectus fusce nonummy integer commodo");
        list.add(bs851);
        BookSeries bs852 = new BookSeries("lectus", 3, SerieTypeEnum.MANGA, "aliquam dolor tincidunt justo feugiat");
        list.add(bs852);
        BookSeries bs853 = new BookSeries("consequat", 8, SerieTypeEnum.LIVRO, "mollis aliquet vesti rutrum fusce");
        list.add(bs853);
        BookSeries bs854 = new BookSeries("lobortis", 0, SerieTypeEnum.MANGA, "fusce inceptos varius morbi scelerisque");
        list.add(bs854);
        BookSeries bs855 = new BookSeries("venenatis morbi", 4, SerieTypeEnum.MANGA, "lorem interdum metus laoreet purus");
        list.add(bs855);
        BookSeries bs856 = new BookSeries("viverra etiam", 8, SerieTypeEnum.LIVRO, "sodales taciti habitant lacinia mauris");
        list.add(bs856);
        BookSeries bs857 = new BookSeries("velit", 6, SerieTypeEnum.LIVRO, "netus habitant sollicitudin vehicula euismod");
        list.add(bs857);
        BookSeries bs858 = new BookSeries("rutrum", 5, SerieTypeEnum.HQ, "pulvinar eleifend tincidunt molestie proin");
        list.add(bs858);
        BookSeries bs859 = new BookSeries("placerat", 7, SerieTypeEnum.MANGA, "bulum sollicitudin sodales purus donec");
        list.add(bs859);
        BookSeries bs860 = new BookSeries("proin", 6, SerieTypeEnum.MANGA, "elementum cubilia interdum elementum pharetra");
        list.add(bs860);
        BookSeries bs861 = new BookSeries("consequat", 3, SerieTypeEnum.MANGA, "lectus pretium curae consectetuer mauris");
        list.add(bs861);
        BookSeries bs862 = new BookSeries("faucibus justo", 10, SerieTypeEnum.MANGA, "lobortis semper laoreet cursus vitae");
        list.add(bs862);
        BookSeries bs863 = new BookSeries("netus", 0, SerieTypeEnum.LIVRO, "fusce risus quisque sollicitudin ultrices");
        list.add(bs863);
        BookSeries bs864 = new BookSeries("etiam", 1, SerieTypeEnum.HQ, "lectus sapien vivamus posuere pulvinar");
        list.add(bs864);
        BookSeries bs865 = new BookSeries("pretium", 6, SerieTypeEnum.HQ, "molestie aenean fermentum velit primis");
        list.add(bs865);
        BookSeries bs866 = new BookSeries("nonummy", 6, SerieTypeEnum.LIVRO, "praesent ornare vivamus taciti facilisis");
        list.add(bs866);
        BookSeries bs867 = new BookSeries("auctor", 3, SerieTypeEnum.HQ, "cursus bibendum auctor augue platea");
        list.add(bs867);
        BookSeries bs868 = new BookSeries("hendrerit", 8, SerieTypeEnum.HQ, "taciti sociosqu sagittis semper interdum");
        list.add(bs868);
        BookSeries bs869 = new BookSeries("scelerisque pharetra", 7, SerieTypeEnum.HQ, "rutrum sagittis auctor hendrerit taciti");
        list.add(bs869);
        BookSeries bs870 = new BookSeries("sapien", 8, SerieTypeEnum.MANGA, "dictumst vesti porta euismod lectus");
        list.add(bs870);
        BookSeries bs871 = new BookSeries("metus", 9, SerieTypeEnum.LIVRO, "curabitur vesti mauris tempus pulvinar");
        list.add(bs871);
        BookSeries bs872 = new BookSeries("feugiat adipiscing", 2, SerieTypeEnum.MANGA, "commodo posuere facilisi viverra convallis");
        list.add(bs872);
        BookSeries bs873 = new BookSeries("scelerisque dignissim", 4, SerieTypeEnum.LIVRO, "lorem dignissim tortor sagittis porttitor");
        list.add(bs873);
        BookSeries bs874 = new BookSeries("taciti ornare", 5, SerieTypeEnum.LIVRO, "pharetra porta luctus congue velit");
        list.add(bs874);
        BookSeries bs875 = new BookSeries("nullam", 8, SerieTypeEnum.MANGA, "taciti venenatis volutpat scelerisque mollis");
        list.add(bs875);
        BookSeries bs876 = new BookSeries("inceptos placerat", 2, SerieTypeEnum.LIVRO, "netus dolor sapien egestas rutrum");
        list.add(bs876);
        BookSeries bs877 = new BookSeries("vesti", 2, SerieTypeEnum.LIVRO, "quisque nonummy sociosqu pellentesque lorem");
        list.add(bs877);
        BookSeries bs878 = new BookSeries("luctus rutrum", 2, SerieTypeEnum.MANGA, "nullam fusce fringilla turpis nostra");
        list.add(bs878);
        BookSeries bs879 = new BookSeries("vehicula", 7, SerieTypeEnum.HQ, "conubia turpis senectus suspendisse sociosqu");
        list.add(bs879);
        BookSeries bs880 = new BookSeries("mattis litora", 5, SerieTypeEnum.HQ, "feugiat quisque conubia varius faucibus");
        list.add(bs880);
        BookSeries bs881 = new BookSeries("magna", 1, SerieTypeEnum.LIVRO, "rutrum lobortis molestie ultrices interdum");
        list.add(bs881);
        BookSeries bs882 = new BookSeries("bulum", 9, SerieTypeEnum.MANGA, "litora vesti inceptos ullamcorper taciti");
        list.add(bs882);
        BookSeries bs883 = new BookSeries("ligula", 1, SerieTypeEnum.HQ, "nulla vesti mattis torquent ipsum");
        list.add(bs883);
        BookSeries bs884 = new BookSeries("felis", 1, SerieTypeEnum.LIVRO, "faucibus imperdiet tincidunt interdum metus");
        list.add(bs884);
        BookSeries bs885 = new BookSeries("hendrerit", 1, SerieTypeEnum.MANGA, "lobortis lectus praesent vestibulum morbi");
        list.add(bs885);
        BookSeries bs886 = new BookSeries("interdum", 9, SerieTypeEnum.HQ, "cursus euismod euismod vehicula curae");
        list.add(bs886);
        BookSeries bs887 = new BookSeries("consectetuer", 4, SerieTypeEnum.HQ, "sodales vestibulum morbi fusce purus");
        list.add(bs887);
        BookSeries bs888 = new BookSeries("consequat", 7, SerieTypeEnum.MANGA, "semper felis consequat velit suspendisse");
        list.add(bs888);
        BookSeries bs889 = new BookSeries("varius", 5, SerieTypeEnum.HQ, "facilisis auctor libero felis risus");
        list.add(bs889);
        BookSeries bs890 = new BookSeries("consectetuer", 1, SerieTypeEnum.MANGA, "elementum aliquam egestas curabitur vesti");
        list.add(bs890);
        BookSeries bs891 = new BookSeries("etiam", 0, SerieTypeEnum.LIVRO, "faucibus torquent platea varius cubilia");
        list.add(bs891);
        BookSeries bs892 = new BookSeries("convallis", 8, SerieTypeEnum.MANGA, "aenean magna phasellus dictum dolor");
        list.add(bs892);
        BookSeries bs893 = new BookSeries("primis phasellus", 8, SerieTypeEnum.HQ, "integer habitant sapien integer class");
        list.add(bs893);
        BookSeries bs894 = new BookSeries("fringilla", 6, SerieTypeEnum.HQ, "bibendum tumst porttitor accumsan metus");
        list.add(bs894);
        BookSeries bs895 = new BookSeries("ipsum", 5, SerieTypeEnum.HQ, "consectetuer hendrerit lectus ligula sodales");
        list.add(bs895);
        BookSeries bs896 = new BookSeries("vitae torquent", 7, SerieTypeEnum.HQ, "pellentesque eleifend congue rutrum facilisisnunc");
        list.add(bs896);
        BookSeries bs897 = new BookSeries("hymenaeos fusce", 9, SerieTypeEnum.LIVRO, "justo curabitur integer pretium nostra");
        list.add(bs897);
        BookSeries bs898 = new BookSeries("conubia", 3, SerieTypeEnum.HQ, "curae taciti tristique justo fusce");
        list.add(bs898);
        BookSeries bs899 = new BookSeries("lectus", 2, SerieTypeEnum.HQ, "vestibulum nulla pretium magna interdum");
        list.add(bs899);

        Connection.getCon().getTransaction().begin();
        list.forEach((iteration) -> {
            bookSeriesDBM.insertBookSeries(iteration);
        });
        Connection.getCon().getTransaction().commit();
    }
}
